return {
 ["check"]={
  ["1"]={
   ["cs"]="postradam '=' po '--' na radku --",
   ["de"]="Fehlendes '=' nach '--' in Zeile --",
   ["en"]="missing or ungrouped '=' after '--' in line --",
   ["fr"]="manquant ou dégroupé '=' après '--' à la ligne --",
   ["it"]="'=' mancante o non raggruppato dopo '--' alla riga --",
   ["nl"]="'=' ontbreekt of zonder {} na '--' in regel --",
   ["no"]="manglende '=' etter '--' i linje --",
   ["ro"]="lipseste '=' dupa '--' in linia --",
  },
  ["2"]={
   ["cs"]="ocekavam -- argument(y) na radku --",
   ["de"]="-- Argument(e) in Zeile -- erwartet",
   ["en"]="-- argument(s) expected in line --",
   ["fr"]="-- argument(s) attendu(s) à la ligne --",
   ["it"]="-- argomento/i attesi alla riga --",
   ["nl"]="-- argument(en) verwacht in regel --",
   ["no"]="-- argument forventet i linje --",
   ["ro"]="argumentul(ele) -- sunt asteptate in linia  --",
  },
  ["3"]={
   ["cs"]="-- -- nahrazuje makro, uzijte VERZALKY!",
   ["de"]="-- -- ersetzt ein Makro, verwende VERSALIEN!",
   ["en"]="-- -- replaces a macro, use CAPITALS!",
   ["fr"]="-- -- remplace une macro, utilisez des MAJUSCULES !",
   ["it"]="-- -- sostituisce una macro, usare le MAIUSCOLE!",
   ["nl"]="-- -- vervangt een macro, gebruik HOOFDLETTERS!",
   ["no"]="-- -- overskygger en makro, bruk STORE BOKSTAVER!",
   ["ro"]="-- -- inlocuieste un macro, folositi MAJUSCULE!",
  },
  ["files"]={ "mult-sys.tex" },
  ["title"]={
   ["cs"]="kontrola",
   ["de"]="check",
   ["en"]="check",
   ["fr"]="vérification",
   ["it"]="controllo",
   ["nl"]="controle",
   ["no"]="kontroll",
   ["ro"]="verificari",
  },
 },
 ["colors"]={
  ["1"]={
   ["cs"]="system -- je globalne aktivovana",
   ["de"]="system -- ist global aktiviert",
   ["en"]="system -- is global activated",
   ["fr"]="le système -- est globalement activé",
   ["it"]="sistema -- attivato globalmente",
   ["nl"]="systeem -- is globaal actief",
   ["no"]="system -- er aktivert globalt",
   ["ro"]="sistem -- este activata global",
  },
  ["10"]={
   ["cs"]="-- prostor barev je podporovan",
   ["de"]="-- Farbraum wird unterstuetzt",
   ["en"]="-- color space is supported",
   ["fr"]="-- l'espace de couleur est supporté",
   ["it"]="spazio dei colori -- supportato",
   ["nl"]="-- kleurruimte wordt ondersteund",
   ["no"]="-- fargerom er støttet",
   ["ro"]="spatiul de culoare -- este suportat",
  },
  ["11"]={
   ["cs"]="barva je prevedena na sed",
   ["de"]="Farbe wird in Grau umgewandelt",
   ["en"]="color is converted to gray",
   ["fr"]="la couleur est convertie en niveau de gris",
   ["it"]="il colore ø convertito in grigio",
   ["nl"]="kleur wordt vertaald in grijs",
   ["no"]="fargen vil bli vist som grø",
   ["ro"]="culoarea este convertita la gri",
  },
  ["12"]={
   ["cs"]="-- is registered",
   ["de"]="-- is registered",
   ["en"]="-- is registered",
   ["fr"]="-- est enregistré",
   ["it"]="-- is registered",
   ["nl"]="-- is geregistreerd",
   ["no"]="-- is registered",
   ["ro"]="-- is registered",
  },
  ["2"]={
   ["cs"]="system -- je lokalne activovana",
   ["de"]="system -- ist lokal aktiviert",
   ["en"]="system -- is local activated",
   ["fr"]="le système -- est localement activé",
   ["it"]="sistema -- attivato localmente",
   ["nl"]="systeem -- is lokaal actief",
   ["no"]="system -- er aktivert lokalt",
   ["ro"]="sistem -- este activata local",
  },
  ["3"]={
   ["cs"]="-- neni definovana --",
   ["de"]="-- ist undefiniert --",
   ["en"]="-- is not defined --",
   ["fr"]="-- n'est pas défini --",
   ["it"]="-- non definito --",
   ["nl"]="-- is niet gedefinieerd --",
   ["no"]="-- er udefinert --",
   ["ro"]="-- nu este definita --",
  },
  ["4"]={
   ["cs"]="system -- je nacten",
   ["de"]="system -- ist geladen",
   ["en"]="system -- is loaded",
   ["fr"]="le système -- est chargé",
   ["it"]="sistema -- caricato",
   ["nl"]="systeem -- wordt geladen",
   ["no"]="system -- er lest inn",
   ["ro"]="sistem -- este incarcata",
  },
  ["5"]={
   ["cs"]="neznamy system --",
   ["de"]="unbekanntes System --",
   ["en"]="unknown system --",
   ["fr"]="système -- inconnu",
   ["it"]="sistema -- sconosciuto",
   ["nl"]="onbekend systeem --",
   ["no"]="ukjent system --",
   ["ro"]="sistem -- necunoscuta",
  },
  ["6"]={
   ["cs"]="palette -- je k dispozici",
   ["de"]="palette -- ist verfuegbar",
   ["en"]="palette -- is available",
   ["fr"]="la palette -- est disponible",
   ["it"]="tavolozza -- resa disponibile",
   ["nl"]="palet -- is beschikbaar",
   ["no"]="palett -- er tilgjengelig",
   ["ro"]="paleta -- este disponibila",
  },
  ["7"]={
   ["cs"]="palette -- neni k dispozici",
   ["de"]="palette -- ist nicht verfuegbar",
   ["en"]="palette -- is not available",
   ["fr"]="le palette -- n'est pas disponible",
   ["it"]="tavolozza -- non disponibile",
   ["nl"]="palet -- is niet beschikbaar",
   ["no"]="palett -- er ikke tilgjengelig",
   ["ro"]="palette -- nu este disponibila",
  },
  ["8"]={
   ["cs"]="specifikace -- v barve -- bude cerna",
   ["de"]="Spezifikation -- bei Farbe -- wird schwarz",
   ["en"]="specification -- at color -- becomes black",
   ["fr"]="la spécification -- de la couleur -- devient noire",
   ["it"]="specifica -- del colore -- convertita in nero",
   ["nl"]="specificatie -- bij -- wordt zwart",
   ["no"]="spesifikasjon -- for farge -- gir kun svart",
   ["ro"]="specificatia -- la culoarea -- devine neagra",
  },
  ["9"]={
   ["cs"]="-- prostor barev neni podporovan",
   ["de"]="-- Farbraum wird nicht unterstuetzt",
   ["en"]="-- color space is not supported",
   ["fr"]="l'espace de couleur -- n'est pas supporté",
   ["it"]="spazio dei colori -- non supportato",
   ["nl"]="-- kleurruimte wordt niet ondersteund",
   ["no"]="-- fargerom er ikke støttet",
   ["ro"]="spatiul de culoare -- nu este suportat",
  },
  ["files"]={ "colo-ini.tex" },
  ["title"]={
   ["cs"]="barva",
   ["de"]="farbe",
   ["en"]="color",
   ["fr"]="couleurs",
   ["it"]="colore",
   ["nl"]="kleur",
   ["no"]="farge",
   ["ro"]="culori",
  },
 },
 ["columns"]={
  ["1"]={
   ["cs"]="je mozno pouze -- sloupcu",
   ["de"]="nur -- Spalten moeglich",
   ["en"]="only -- columns possible",
   ["fr"]="seules -- colonnes possibles",
   ["it"]="solo -- colonne possibili",
   ["nl"]="maximaal -- kolommen",
   ["no"]="maksimalt -- kolonner",
   ["ro"]="este posibil numai -- coloane",
  },
  ["10"]={
   ["cs"]="zbyl (mene nez) 1 radek",
   ["de"]="(weniger als) 1 Zeile uebrig",
   ["en"]="(less than) 1 line left",
   ["fr"]="(moins de) 1 ligne restante",
   ["it"]="(meno di) una riga rimasta",
   ["nl"]="(minder dan) 1 regel over",
   ["no"]="(mindre enn) 1 linje igjen",
   ["ro"]="a mai ramas (mai putin de) 1 linie",
  },
  ["11"]={
   ["cs"]="plovouci objekt je pro sloupec prilis siroky",
   ["de"]="Gleitobjekt zu breit fuer Spalte",
   ["en"]="float too wide for column",
   ["fr"]="flottant mis à la largeur de la colonne",
   ["it"]="oggetto mobile troppo ampio per la colonna",
   ["nl"]="plaatsblok te breed voor kolom",
   ["no"]="flytblokk for bredt for kolonna",
   ["ro"]="blocul este prea lat pentru coloana",
  },
  ["12"]={
   ["cs"]="plovouci objekt je presunut do nasledujiciho sloupce / --",
   ["de"]="Gleitobjekt in naechste Zeile verschoben / --",
   ["en"]="float moved to next column / --",
   ["fr"]="flottant déplacé à la colonne suivante / --",
   ["it"]="oggetto mobile spostata alla colonna successiva / --",
   ["nl"]="plaatsblok verplaatst naar volgende kolom / --",
   ["no"]="flytblokk forskjøvet til neste kolonne / --",
   ["ro"]="blocul este mutat pe urmatoarea coloana / --",
  },
  ["13"]={
   ["cs"]="siroky plovouci objekt je presunut nad sloupce",
   ["de"]="breites Gleitobjekt an den Anfang der Spalten verschoben",
   ["en"]="wide float moved to top of columns",
   ["fr"]="flottant large déplacé dans la partie supérieure de la colonne",
   ["it"]="oggetto mobile ampio spostato sopra le colonne",
   ["nl"]="breed figuur geplaatst boven kolommen",
   ["no"]="bred flytblokk forksjøvet til toppen av kolonnene",
   ["ro"]="blocul lat este mutat in partea de sus a coloanelor",
  },
  ["2"]={
   ["cs"]="pouzijte \\string\\filbreak\\space jako alternativu",
   ["de"]="benutzte \\string\\filbreak\\space als Alternative",
   ["en"]="use \\string\\filbreak\\space as alternative",
   ["fr"]="utilisez \\string\\filbreak\\space en tant qu'alternative",
   ["it"]="in alternativa, usare \\string\\filbreak",
   ["nl"]="gebruik eventueel \\string\\filbreak",
   ["no"]="bruk \\string\\filbreak\\space som et alternativ",
   ["ro"]="folositi \\string\\filbreak\\space ca alternativa",
  },
  ["3"]={
   ["cs"]="problem, vypina se vyvazovani",
   ["de"]="Problem, verwende [ausgleich=nein]",
   ["en"]="problems, disable balancing",
   ["fr"]="problèmes, désactive l'équilibrage",
   ["it"]="problemi, disabilitare il bilanciamento",
   ["nl"]="probleempje, probeer [balanceren=nee]",
   ["no"]="problemer, slår av balansering",
   ["ro"]="probleme, se dezactiveaza alinierea",
  },
  ["4"]={
   ["cs"]="horni plovouci objekt jeste neni podporovan",
   ["de"]="Gleitobjekt oben ncoh nicht unterstuetzt",
   ["en"]="top float not yet supported",
   ["fr"]="flottant en partie supérieure pas encore supporté",
   ["it"]="float in cima non ancora supportato",
   ["nl"]="plaatsblok boven nog niet mogelijk",
   ["no"]="flytblokker øverst er ikke støttet enda",
   ["ro"]="cadrele top (top float) nu sunt inca suportate",
  },
  ["5"]={
   ["cs"]="spodni plovouci objekt jeste neni podporovan",
   ["de"]="Gleitobjekt unten ncoh nicht unterstuetzt",
   ["en"]="bottom float not yet supported",
   ["fr"]="flottant en partie inférieure pas encore supporté",
   ["it"]="float in fondo non ancora supportato",
   ["nl"]="plaatsblok onder nog niet mogelijk",
   ["no"]="flytblokker nedert er ikke støttet enda",
   ["ro"]="cadrele bottom (bottom float) nu sunt inca suportate",
  },
  ["6"]={
   ["cs"]="-- plovouci objekt(y) odlozeny",
   ["de"]="-- Gleitobjekt(e) verschoben",
   ["en"]="-- float(s) postponed",
   ["fr"]="-- flottant(s) reporté(s)",
   ["it"]="-- float(s) posticipate",
   ["nl"]="-- plaatsblok(en) opgeschort",
   ["no"]="-- flytblokk forskjøvet",
   ["ro"]="-- blocurile sunt amanate",
  },
  ["7"]={
   ["cs"]="vyvazovani ukonceno po 100 krocich",
   ["de"]="ausgleich nach 100 Schritten abgebrocheb",
   ["en"]="balancing aborted after 100 steps",
   ["fr"]="équilibrage abandonné après 100 pas",
   ["it"]="bilanciamento annullato dopo 100 passi",
   ["nl"]="balanceren afgebroken na 100 stappen",
   ["no"]="balansering avbrutt etter 100 iterasjoner",
   ["ro"]="alinierea este oprita dupa 100 de incercari",
  },
  ["8"]={
   ["cs"]="vyvazeno v -- krocich",
   ["de"]="ausgeglichen nach  -- Schritt(en)",
   ["en"]="balanced in -- step(s)",
   ["fr"]="équilibré en -- pas",
   ["it"]="bilanciamento in -- passo/i",
   ["nl"]="gebalanceerd in -- stap(pen)",
   ["no"]="balansert etter -- iterasjoner",
   ["ro"]="aliniat in  -- pas(i)",
  },
  ["9"]={
   ["cs"]="kontrola nerovnost",
   ["de"]="Ausrichtung ueberpruefen",
   ["en"]="check raggedness",
   ["fr"]="vérification des irrégularités",
   ["it"]="controllare seghettamento",
   ["nl"]="uitlijnen controleren!",
   ["no"]="kontroller tekstlayout!",
   ["ro"]="verificat alinierea",
  },
  ["files"]={ "page-ini.tex" },
  ["title"]={
   ["cs"]="sloupce",
   ["de"]="Spalten",
   ["en"]="columns",
   ["fr"]="colonnes",
   ["it"]="colonne",
   ["nl"]="kolommen",
   ["no"]="kolonner",
   ["ro"]="coloane",
  },
 },
 ["databases"]={
  ["1"]={
   ["cs"]="--",
   ["de"]="--",
   ["en"]="--",
   ["fr"]="--",
   ["it"]="--",
   ["nl"]="--",
   ["no"]="--",
   ["ro"]="--",
  },
  ["2"]={
   ["cs"]="local file --",
   ["de"]="lokale Datei --",
   ["en"]="local file --",
   ["fr"]="fichier local --",
   ["it"]="file locale --",
   ["nl"]="lokaal bestand --",
   ["no"]="lokal fil --",
   ["ro"]="fisier local --",
  },
  ["3"]={
   ["cs"]="global file --",
   ["de"]="globale Datei --",
   ["en"]="global file --",
   ["fr"]="fichier global --",
   ["it"]="file globale --",
   ["nl"]="globaal bestand --",
   ["no"]="global fil --",
   ["ro"]="fisier global --",
  },
  ["4"]={
   ["cs"]="unknown file --",
   ["de"]="unbekannte Datei --",
   ["en"]="unknown file --",
   ["fr"]="fichier inconnu --",
   ["it"]="file sconosciuto --",
   ["nl"]="onbekend bestand --",
   ["no"]="ukjent fil --",
   ["ro"]="fisier necunoscut --",
  },
  ["files"]={ "core-dat.tex" },
  ["title"]={
   ["cs"]="databases",
   ["de"]="Datenbank",
   ["en"]="databases",
   ["fr"]="bases de données",
   ["it"]="database",
   ["nl"]="database",
   ["no"]="databaser",
   ["ro"]="baze de date",
  },
 },
 ["documents"]={
  ["1"]={
   ["de"]="Blatt --",
   ["en"]="sheet --",
   ["nl"]="sheet --",
  },
  ["2"]={
   ["de"]="Nummer --",
   ["en"]="number --",
   ["nl"]="nummer --",
  },
  ["files"]={ "docs-bri.tex", "docs-she.tex" },
  ["title"]={
   ["de"]="Blaetter",
   ["en"]="sheets",
   ["nl"]="sheets",
  },
 },
 ["encodings"]={
  ["1"]={
   ["cs"]="kodovani --",
   ["de"]="Kodierung --",
   ["en"]="coding --",
   ["fr"]="encodage --",
   ["it"]="codifica --",
   ["nl"]="codering --",
   ["no"]="koding --",
   ["ro"]="codificarea --",
  },
  ["2"]={
   ["cs"]="je nacteno kodovani --",
   ["de"]="Kodierung -- ist geladen",
   ["en"]="coding -- is loaded",
   ["fr"]="l'encodage -- est chargé",
   ["it"]="codifica -- caricata",
   ["nl"]="codering -- wordt geladen",
   ["no"]="koding -- er lest inn",
   ["ro"]="codificarea -- este Encarcata",
  },
  ["3"]={
   ["cs"]="nezname kodovani --",
   ["de"]="Unbekannte Kodierung --",
   ["en"]="unknown coding --",
   ["fr"]="encodage -- inconnu",
   ["it"]="codifica sconosciuta --",
   ["nl"]="onbekende codering --",
   ["no"]="ukjent koding --",
   ["ro"]="codificarea -- este necunoscuta",
  },
  ["files"]={ "enco-ini.mkii" },
  ["title"]={
   ["cs"]="kodovani",
   ["de"]="Kodierung",
   ["en"]="encoding",
   ["fr"]="encodage",
   ["it"]="codifica",
   ["nl"]="encoding",
   ["no"]="koding",
   ["ro"]="codificari",
  },
 },
 ["figures"]={
  ["1"]={
   ["cs"]="obraz -- nelze nalezt",
   ["de"]="Abbildung -- kann nicht gefunden werden",
   ["en"]="figure -- can not be found",
   ["fr"]="la figure -- ne peut être trouvée",
   ["it"]="figura -- non trovata",
   ["nl"]="figuur -- is niet te vinden",
   ["ro"]="figura -- nu poate fi gasita",
  },
  ["2"]={
   ["cs"]="obraz -- nepritomen",
   ["de"]="Abbildung -- wird nicht erstellt",
   ["en"]="figure -- is not preset",
   ["fr"]="la figure -- n'est pas pré-sélectionnée",
   ["it"]="la figura -- non è preimpostata",
   ["nl"]="figuur -- wordt niet preset",
   ["ro"]="figura -- nu este presetata",
  },
  ["3"]={
   ["cs"]="dimensions of -- are determined externally",
   ["de"]="dimensions of -- are determined externally",
   ["en"]="dimensions of -- are determined externally",
   ["fr"]="dimensions of -- are determined externally",
   ["it"]="dimensions of -- are determined externally",
   ["nl"]="maten van -- worden extern vastgesteld",
   ["ro"]="dimensions of -- are determined externally",
  },
  ["4"]={
   ["cs"]="dimenze obrazu -- nacteny primo z jeho souboru",
   ["de"]="Dimensionen von -- geladen aus der Abbildungsdatei selbst",
   ["en"]="dimensions of -- loaded from figurefile itself",
   ["fr"]="les dimensions de -- chargées implicitement à partir du fichier de figure",
   ["it"]="dimensioni di -- caricate dal file di immagini stesso",
   ["nl"]="maten van -- geladen uit figuurfile zelf",
   ["ro"]="dimensiunea figurii -- se incarca din fisierul insusi",
  },
  ["5"]={
   ["cs"]="dimensions of -- are unknown",
   ["de"]="Dimensions of -- are unknown",
   ["en"]="dimensions of -- are unknown",
   ["fr"]="dimensions of -- are unknown",
   ["it"]="dimensions of -- are unknown",
   ["nl"]="maten van -- zijn onbekend",
   ["ro"]="dimensions of -- are unknown",
  },
  ["6"]={
   ["cs"]="dimenze obrazu -- spocteny programem rlxtools",
   ["de"]="Dimensionen von -- ausgerechnet durch rlxtools",
   ["en"]="dimensions of -- calculated by rlxtools",
   ["fr"]="les dimensions de -- calculées par rlxtools",
   ["it"]="dimensioni di -- calcolate da rlxtools",
   ["nl"]="maten van -- berekend door rlxtools",
   ["ro"]="dimensiunea figurii -- este calculata de rlxtools",
  },
  ["8"]={
   ["cs"]="obrazovy objekt -- je znovu pouzit",
   ["de"]="Abbildungobjekt -- wurde wiederverwandt",
   ["en"]="figureobject -- is reused",
   ["fr"]="figureobject -- est réutilisé",
   ["it"]="oggetto-figura -- riutilizzato",
   ["nl"]="figuurobject -- wordt opnieuw gebruikt",
   ["ro"]="obiectul figura -- este refolosit",
  },
  ["files"]={ "core-inc.mkii" },
  ["title"]={
   ["cs"]="obrazy",
   ["de"]="Abbildungen",
   ["en"]="figures",
   ["fr"]="figures",
   ["it"]="figure",
   ["nl"]="figuren",
   ["ro"]="figuri",
  },
 },
 ["files"]={
  ["1"]={
   ["cs"]="synonymum souboru -- je jiz pouzito pro --",
   ["de"]="Dateisynonym -- wird bereits fuer -- benutzt",
   ["en"]="file synonym -- is already used for --",
   ["fr"]="le synonyme de fichier -- est déjà utilisé pour --",
   ["it"]="sinonimo file -- già in uso per --",
   ["nl"]="file synoniem -- is al in gebruik voor --",
   ["no"]="filesynonym -- er allerede brukt for --",
   ["ro"]="sinonimul fisierelor -- este folosit deja pentru --",
  },
  ["files"]={ "core-fil.tex" },
  ["title"]={
   ["cs"]="soubory",
   ["de"]="files",
   ["en"]="files",
   ["fr"]="fichiers",
   ["it"]="file",
   ["nl"]="files",
   ["no"]="filer",
   ["ro"]="fisiere",
  },
 },
 ["filters"]={
  ["1"]={
   ["cs"]="filter -- is loaded",
   ["de"]="filter -- ist geladen",
   ["en"]="filter -- is loaded",
   ["fr"]="le filtre -- est chargé",
   ["it"]="filtro -- caricato",
   ["nl"]="filter -- wordt geladen",
  },
  ["2"]={
   ["cs"]="unknown filter --",
   ["de"]="unknown filter --",
   ["en"]="unknown filter --",
   ["fr"]="filtre -- inconnu",
   ["it"]="filtro sconosciuto --",
   ["nl"]="onbekend filter --",
  },
  ["files"]={ "filt-ini.tex" },
  ["title"]={
   ["cs"]="filter",
   ["de"]="filter",
   ["en"]="filter",
   ["fr"]="filtre",
   ["it"]="filtri",
   ["nl"]="filter",
  },
 },
 ["floatblocks"]={
  ["1"]={
   ["cs"]="-- precislovano / -- => --",
   ["de"]="-- neu nummeriert / -- => --",
   ["en"]="-- renumbered / -- => --",
   ["fr"]="-- renuméroté / -- => --",
   ["it"]="-- rinumerato / -- => --",
   ["nl"]="-- hernummerd / -- => --",
   ["no"]="-- renummerert / -- => --",
   ["ro"]="-- renumerotat / -- => --",
  },
  ["10"]={
   ["cs"]="-- omezeno",
   ["de"]="-- begrenzt",
   ["en"]="-- limited",
   ["fr"]="-- limité",
   ["it"]="-- limitato",
   ["nl"]="-- begrensd",
   ["no"]="-- begrenset",
   ["ro"]="-- limitat",
  },
  ["11"]={
   ["cs"]="nedan zadny blok",
   ["de"]="kein Block gegeben",
   ["en"]="no block given",
   ["fr"]="pas de bloc donné",
   ["it"]="nessun oggetto specificato",
   ["nl"]="geen blok opgegeven",
   ["no"]="ingen blokk oppgitt",
   ["ro"]="nu este dat nici un bloc",
  },
  ["12"]={
   ["cs"]="nedefinovano",
   ["de"]="undefiniert",
   ["en"]="undefined",
   ["fr"]="indéfini",
   ["it"]="non definito",
   ["nl"]="niet gedefinieerd",
   ["no"]="udefinert",
   ["ro"]="nedefinit",
  },
  ["13"]={
   ["cs"]="there is nothing to split",
   ["de"]="there is nothing to split",
   ["en"]="there is nothing to split",
   ["fr"]="there is nothing to split",
   ["it"]="there is nothing to split",
   ["nl"]="er is niets te splitsen",
   ["no"]="there is nothing to split",
   ["ro"]="there is nothing to split",
  },
  ["2"]={
   ["cs"]="-- ulozeno",
   ["de"]="-- gespeichert",
   ["en"]="-- saved",
   ["fr"]="-- sauvegardé",
   ["it"]="-- salvato",
   ["nl"]="-- bewaard",
   ["no"]="-- lagret",
   ["ro"]="-- salvat",
  },
  ["3"]={
   ["cs"]="-- presunuto",
   ["de"]="-- verschoben",
   ["en"]="-- moved",
   ["fr"]="-- déplacé",
   ["it"]="-- mosso",
   ["nl"]="-- verplaatst",
   ["no"]="-- flyttet",
   ["ro"]="-- mutat",
  },
  ["4"]={
   ["cs"]="-- umisteno",
   ["de"]="-- plaziert",
   ["en"]="-- placed",
   ["fr"]="-- placé",
   ["it"]="-- sistemato",
   ["nl"]="-- geplaatst",
   ["no"]="-- plassert",
   ["ro"]="-- plasat",
  },
  ["5"]={
   ["cs"]="poradi prizpusobeno",
   ["de"]="Reihenfolge angepasst",
   ["en"]="order adapted",
   ["fr"]="ordre adapté",
   ["it"]="ordine aggiustato",
   ["nl"]="volgorde aangepast",
   ["no"]="rekkefølge tilpasset",
   ["ro"]="ordinea adaptata",
  },
  ["6"]={
   ["cs"]="pocet hornich plovoucich objektu je omezen na --",
   ["de"]="Anz. der oberen Gleitobjekte beschraengt auf --",
   ["en"]="n of top floats limited to --",
   ["fr"]="n flottants de haut de page limité à --",
   ["it"]="n di top floats limitato a --",
   ["nl"]="maximaal -- boven",
   ["no"]="maksimalt -- flytblokker øverst",
   ["ro"]="nr. cadrelor de sus limitat la  --",
  },
  ["7"]={
   ["cs"]="pocet spodnich plovoucich objektu je omezen na --",
   ["de"]="Anz. der unteren Gleitobjekte beschraengt auf  --",
   ["en"]="n of bottom floats limited to --",
   ["fr"]="n flottants de bas de page limité à --",
   ["it"]="n di bottom floats limitato a --",
   ["nl"]="maximaal -- onder",
   ["no"]="maksimalt -- flytblokker nederst",
   ["ro"]="nr. blocurilor de jos limitat la --",
  },
  ["8"]={
   ["cs"]="radku je mene nez --",
   ["de"]="weniger als -- zeilen",
   ["en"]="less than -- lines",
   ["fr"]="moins de -- lignes",
   ["it"]="meno di -- righe",
   ["nl"]="minder dan -- regels",
   ["no"]="mindre enn -- linjer",
   ["ro"]="mai putin de -- linii",
  },
  ["9"]={
   ["cs"]="poradi naruseno",
   ["de"]="Reigenfolge gestoert",
   ["en"]="order disturbed",
   ["fr"]="ordre perturbé",
   ["it"]="ordine disturbato",
   ["nl"]="volgorde verstoord",
   ["no"]="rekkefølge endret",
   ["ro"]="ordinea deranjata",
  },
  ["files"]={ "page-flt.tex", "strc-flt.tex" },
  ["title"]={
   ["cs"]="plovouciobjekty",
   ["de"]="Gleitobjektbloecke",
   ["en"]="floatblocks",
   ["fr"]="blocs de flottants",
   ["it"]="oggetti mobili",
   ["nl"]="plaatsblokken",
   ["no"]="flytblokker",
   ["ro"]="Blocuri",
  },
 },
 ["fonts"]={
  ["1"]={
   ["cs"]="kodovani --",
   ["de"]="Kodierung --",
   ["en"]="coding --",
   ["fr"]="encodage --",
   ["it"]="codifica --",
   ["nl"]="codering --",
   ["no"]="koding --",
   ["ro"]="codificarea --",
  },
  ["10"]={
   ["cs"]="neznamy font --",
   ["de"]="unbekanntes Font --",
   ["en"]="unknown font file --",
   ["fr"]="fichier de police -- inconnu",
   ["it"]="file di font sconosciuto --",
   ["nl"]="onbekende font file --",
   ["no"]="ukjent fontfil --",
   ["ro"]="fisier font necunoscut --",
  },
  ["14"]={
   ["cs"]="bodyfont -- is defined (can better be done global)",
   ["de"]="Fliesstext -- wurde definiert (besser waere globale Definition)",
   ["en"]="bodyfont -- is defined (can better be done global)",
   ["fr"]="policecorps -- est défini (une définition globale pourrait être plus adéquat)",
   ["it"]="corpo del testo -- definito (sarebbe meglio globale)",
   ["nl"]="korps -- is gedefinieerd (kan beter globaal plaatsvinden)",
   ["no"]="bodyfont -- is defined (can better be done global)",
   ["ro"]="bodyfont -- is defined (can better be done global)",
  },
  ["2"]={
   ["cs"]="varianta -- je nactena",
   ["de"]="Variante -- ist geladen",
   ["en"]="variant -- is loaded",
   ["fr"]="la variante -- est chargée",
   ["it"]="variante -- caricata",
   ["nl"]="variant -- wordt geladen",
   ["no"]="variant -- er lest inn",
   ["ro"]="varianta -- este incarcata",
  },
  ["3"]={
   ["cs"]="neznama varianta --",
   ["de"]="Unbekannte Variante --",
   ["en"]="unknown variant --",
   ["fr"]="variante -- inconnue",
   ["it"]="variante sconosciuta --",
   ["nl"]="onbekende variant --",
   ["no"]="ukjent variant --",
   ["ro"]="varianta necunoscuta --",
  },
  ["4"]={
   ["cs"]="zakladni font -- neni definovan",
   ["de"]="Fliesstext -- ist nicht definiert",
   ["en"]="bodyfont -- is not defined",
   ["fr"]="policecorps -- n'est pas définie",
   ["it"]="corpo del testo -- non definito",
   ["nl"]="korps -- is niet gedefinieerd",
   ["no"]="hovedfont -- er ikke definert",
   ["ro"]="corpul de litere -- nu este definit",
  },
  ["5"]={
   ["cs"]="styl -- neni definovan",
   ["de"]="Stil -- ist nicht definiert",
   ["en"]="style -- is not defined",
   ["fr"]="le style -- n'est pas défini",
   ["it"]="stile -- non definito",
   ["nl"]="stijl -- is niet gedefinieerd",
   ["no"]="stil -- er ikke definert",
   ["ro"]="stilul -- nu este definit",
  },
  ["6"]={
   ["cs"]="-- je nacten",
   ["de"]="-- ist geladen",
   ["en"]="-- is loaded",
   ["fr"]="-- est chargé",
   ["it"]="-- caricato",
   ["nl"]="-- wordt geladen",
   ["no"]="-- er lest inn",
   ["ro"]="-- este incarcat",
  },
  ["7"]={
   ["cs"]="neznamy format --",
   ["de"]="unbekanntes Format --",
   ["en"]="unknown format --",
   ["fr"]="format -- inconnu",
   ["it"]="formato sconosciuto --",
   ["nl"]="onbekend formaat --",
   ["no"]="ukjent format --",
   ["ro"]="format necunoscut --",
  },
  ["8"]={
   ["cs"]="styl -- definovan",
   ["de"]="Stil -- definiert",
   ["en"]="style -- defined",
   ["fr"]="style -- défini",
   ["it"]="stile -- definito",
   ["nl"]="stijl -- gedefinieerd",
   ["no"]="stil -- definert",
   ["ro"]="stilul -- definit",
  },
  ["files"]={ "font-ini.mkii", "font-ini.mkiv" },
  ["title"]={
   ["cs"]="zakladnifont",
   ["de"]="Fliesstext",
   ["en"]="bodyfont",
   ["fr"]="corps de texte",
   ["it"]="font del corpo",
   ["nl"]="korps",
   ["no"]="hovedfont",
   ["ro"]="corp de litere",
  },
 },
 ["handlings"]={
  ["1"]={
   ["cs"]="font handling --",
   ["de"]="Font Verarbeitung --",
   ["en"]="font handling --",
   ["fr"]="manipulation -- de police",
   ["it"]="font handling --",
   ["nl"]="font afhandeling --",
   ["no"]="font handling --",
   ["ro"]="font handling --",
  },
  ["2"]={
   ["cs"]="font handling -- is loaded",
   ["de"]="Font Verarbeitung -- ist geladen",
   ["en"]="font handling -- is loaded",
   ["fr"]="la manipulation -- de police est chargée",
   ["it"]="font handling -- is loaded",
   ["nl"]="font afhandeling -- wordt geladen",
   ["no"]="font handling -- is loaded",
   ["ro"]="font handling -- is loaded",
  },
  ["3"]={
   ["cs"]="unknown font handling --",
   ["de"]="unknown font handling --",
   ["en"]="unknown font handling --",
   ["fr"]="manipulation -- inconnue de police",
   ["it"]="unknown font handling --",
   ["nl"]="onbekende font afhandeling --",
   ["no"]="unknown font handling --",
   ["ro"]="unknown font handling --",
  },
  ["files"]={ "hand-ini.mkii" },
  ["title"]={
   ["cs"]="handling",
   ["de"]="handling",
   ["en"]="handling",
   ["fr"]="manipulation",
   ["it"]="handling",
   ["nl"]="handling",
   ["no"]="handling",
   ["ro"]="handling",
  },
 },
 ["interactions"]={
  ["1"]={
   ["cs"]="pomer -- x -- (s x v)",
   ["de"]="Seitenverhaeltnis -- x -- (B x H)",
   ["en"]="aspect ratio -- x -- (b x h)",
   ["fr"]="ratio d'aspect -- x -- (b x h)",
   ["it"]="rapporto -- x -- (b x a)",
   ["nl"]="aspect ratio -- x -- (b x h)",
   ["no"]="forholdstall -- x -- (b x h)",
   ["ro"]="aspectul -- x -- (b x h)",
  },
  ["2"]={
   ["cs"]="aktivni",
   ["de"]="aktiv",
   ["en"]="active",
   ["fr"]="actif",
   ["it"]="attiva",
   ["nl"]="actief",
   ["no"]="aktiv",
   ["ro"]="activ",
  },
  ["21"]={
   ["cs"]="-- kod vlozen",
   ["de"]="-- Code eingefuegt",
   ["en"]="-- code inserted",
   ["fr"]="-- code inseré",
   ["it"]="codice -- inserito",
   ["nl"]="-- code tussengevoegd",
   ["no"]="-- kode satt inn / tilføyd",
   ["ro"]="-- cod inserat",
  },
  ["3"]={
   ["cs"]="neaktivni",
   ["de"]="inaktiv",
   ["en"]="inactive",
   ["fr"]="inactif",
   ["it"]="inattiva",
   ["nl"]="niet actief",
   ["no"]="inaktiv",
   ["ro"]="inactiv",
  },
  ["4"]={
   ["cs"]="zadna strankova synchronizace (--) v hmode",
   ["de"]="keine Seitensynchronisation (--) im hmode",
   ["en"]="no pagesynchronisation (--) in hmode",
   ["fr"]="pas de synchronisation de page (--) dans le hmode",
   ["it"]="sincronizzazione di pagina (--) non disponibile in hmode",
   ["nl"]="geen paginasynchronisatie (--) in hmode",
   ["no"]="ingen sidesynkronisering (--) i hmode",
   ["ro"]="nu exista sincronizare pt. pagini (--) in hmode",
  },
  ["5"]={
   ["cs"]="unknown attachment --",
   ["de"]="unknown attachment --",
   ["en"]="unknown attachment --",
   ["fr"]="le fichier joint -- est inconnu",
   ["it"]="unknown attachment --",
   ["nl"]="onbekend attachment --",
   ["no"]="unknown attachment --",
   ["ro"]="unknown attachment --",
  },
  ["6"]={
   ["cs"]="attachment file -- does not exist",
   ["de"]="attachment file -- does not exist",
   ["en"]="attachment file -- does not exist",
   ["fr"]="le fichier joint -- n'existe pas",
   ["it"]="attachment file -- does not exist",
   ["nl"]="attachment file -- bestaat niet",
   ["no"]="attachment file -- does not exist",
   ["ro"]="attachment file -- does not exist",
  },
  ["files"]={ "core-int.tex", "spec-ini.tex" },
  ["title"]={
   ["cs"]="interakce",
   ["de"]="Interaktion",
   ["en"]="interaction",
   ["fr"]="interaction",
   ["it"]="interazione",
   ["nl"]="interactie",
   ["no"]="interaksjon",
   ["ro"]="interactiuni",
  },
 },
 ["javascript"]={
  ["1"]={
   ["cs"]="nacita se soubor skriptu --",
   ["de"]="Lade Scriptdatei --",
   ["en"]="loading script set --",
   ["fr"]="chargement du jeu de script --",
   ["it"]="caricamento dello script set --",
   ["nl"]="script set -- wordt geladen",
   ["no"]="leser inn scriptsett --",
   ["ro"]="se incarca scriptul --",
  },
  ["2"]={
   ["cs"]="neznama preambule --",
   ["de"]="unbekannte Preamble --",
   ["en"]="unknown preamble --",
   ["fr"]="préambule -- inconnu",
   ["it"]="preambolo sconosciuto --",
   ["nl"]="onbekende preamble --",
   ["no"]="ukjent 'preamble' --",
   ["ro"]="preambul necunoscut --",
  },
  ["files"]={ "java-ini.tex" },
  ["title"]={
   ["cs"]="javascript",
   ["de"]="javascript",
   ["en"]="javascript",
   ["fr"]="javascript",
   ["it"]="javascript",
   ["nl"]="javascript",
   ["no"]="javascript",
   ["ro"]="javascript",
  },
 },
 ["layouts"]={
  ["1"]={
   ["cs"]="vyska textu prizpusobena s -- na strane --",
   ["de"]="Texthoehe angepasst mit -- auf Seite --",
   ["en"]="textheight adapted with -- at page --",
   ["fr"]="hauteurtexte adaptée avec -- à la page --",
   ["it"]="altezza del testo adattata con -- a pagina --",
   ["nl"]="teksthoogte aangepast met -- op pagina --",
   ["no"]="teksthøyde tilpasset med -- på side --",
   ["ro"]="textheight adaptat cu -- la pagina --",
  },
  ["10"]={
   ["cs"]="-- a -- nedava dohromady 1.0",
   ["de"]="-- und -- ergeben zusammen nicht 1.0",
   ["en"]="-- and -- don't add up to 1.0",
   ["fr"]="-- et -- ne sont pas ajoutés à 1.0",
   ["it"]="-- e -- non sommano a 1.0",
   ["nl"]="-- en -- tellen niet op tot 1.0",
   ["no"]="-- og -- er ikke 1.0 til sammen",
   ["ro"]="-- si -- nu se adauga pana la 1.0",
  },
  ["11"]={
   ["cs"]="svisla mezera -- neni povolena v pevnem radkovem rejstriku",
   ["de"]="Zwischenraum -- nicht im Grittermoduserlau",
   ["en"]="spacing -- not permitted in gridmode",
   ["fr"]="espacement -- non permis en modegrille",
   ["it"]="spaziatura -- non permessa in modo griglia",
   ["nl"]="interlinie -- niet toegestaan in gridmode",
   ["no"]="mellomrom -- ikke tillatt i gridmodus",
   ["ro"]="spatierea -- nu este permisa in gridmode",
  },
  ["2"]={
   ["cs"]="-- krat odlozeny text umisten",
   ["de"]="-- mal verschobener Text plaziert",
   ["en"]="-- times postponed text placed",
   ["fr"]="-- times postponed text placed",
   ["it"]="posizionato testo posticipato -- volte",
   ["nl"]="-- maal uitgestelde tekst tussengevoegd",
   ["no"]="-- ganger forskjøvet tekst plassert",
   ["ro"]="textul amanat de -- ori a fost plasat",
  },
  ["3"]={
   ["cs"]="-- krat text odlozen",
   ["de"]="-- mal Text verschoben",
   ["en"]="-- times text postponed",
   ["fr"]="-- times text postponed",
   ["it"]="testo posticipato -- volte",
   ["nl"]="-- maal tekst plaatsen uitstellen",
   ["no"]="-- ganger tekst forskjøvet",
   ["ro"]="textul amanat de -- ori",
  },
  ["4"]={
   ["cs"]="okrajove bloky aktivni",
   ["de"]="marginalbloecke aktiv",
   ["en"]="marginblocks active",
   ["fr"]="blocsmarge actifs",
   ["it"]="blocchi in margine attivi",
   ["nl"]="margeblokken actief",
   ["no"]="margblokker aktive",
   ["ro"]="blocuri marginale active",
  },
  ["5"]={
   ["cs"]="okrajove bloky neaktivni",
   ["de"]="marginalbloecke inaktiv",
   ["en"]="marginblocks inactive",
   ["fr"]="blocsmarge inactifs",
   ["it"]="blocchi in margine inattivi",
   ["nl"]="margeblokken inactief",
   ["no"]="margblokker inaktive",
   ["ro"]="blocuri marginale inactive",
  },
  ["6"]={
   ["cs"]="sada stran -- zpracovana (velikost --)",
   ["de"]="Unterseitenfolge -- verarbeitet (Groesse --)",
   ["en"]="subpage set -- processed (size --)",
   ["fr"]="jeu de souspage -- traité (taille --)",
   ["it"]="gruppo di sottopagine -- elaborato (dimensione --)",
   ["nl"]="subpagina reeks -- verwerkt (aantal --)",
   ["no"]="delside sett -- behandlet (størrelse --)",
   ["ro"]="setul -- de subpagini procesat (dimensiunea --)",
  },
  ["7"]={
   ["cs"]="pocita se misto pro logo",
   ["de"]="berechne Platzbedarf des Logos",
   ["en"]="calculating logospace",
   ["fr"]="calcul de l'espace pour le logo",
   ["it"]="calcolo dello spazio per logo",
   ["nl"]="beeldmerken berekenen",
   ["no"]="beregner plass for logo",
   ["ro"]="se calculeaza spatiul pentru logo",
  },
  ["8"]={
   ["cs"]="pocita se pozadi",
   ["de"]="berechne Hintergrund",
   ["en"]="calculating backgrounds",
   ["fr"]="calcul des arrières-plans",
   ["it"]="calcolo dello sfondo",
   ["nl"]="achtergronden berekenen",
   ["no"]="beregner bakgrunn",
   ["ro"]="se calculeaza fundalurile",
  },
  ["9"]={
   ["cs"]="aktualne ne vice nez -- urovne/urovni vyctu",
   ["de"]="z.Z. nicht mehr als -- Ebenen in Aufzaehlungen",
   ["en"]="currently no more than -- levels in itemizations",
   ["fr"]="pas plus de -- niveaux pour l'instant dans les élémentarisations",
   ["it"]="attualmente non più di -- livelli di elencazione",
   ["nl"]="momenteel maximaal -- niveaus in opsommingen",
   ["no"]="for øyeblikket maksimalt -- nivåer i opplisting",
   ["ro"]="acum nu se supota mai mult de -- nivele de adancime la iteratii",
  },
  ["files"]={ "core-itm.tex", "page-bck.mkii", "page-bck.mkiv", "page-ini.tex", "page-log.tex", "strc-itm.tex" },
  ["title"]={
   ["cs"]="layout",
   ["de"]="Layout",
   ["en"]="layout",
   ["fr"]="calque",
   ["it"]="layout",
   ["nl"]="layout",
   ["no"]="layout",
   ["ro"]="aranjamente",
  },
 },
 ["linguals"]={
  ["1"]={
   ["cs"]="vzory -- pro -- nacteny (n=--,e=--,m=--)",
   ["de"]="Trennmuster -- fuer -- geladen (n=--,e=--,m=--)",
   ["en"]="patterns -- for -- loaded (n=--,e=--,m=--)",
   ["fr"]="les motifs -- pour -- sont chargés (n=--,e=--,m=--)",
   ["it"]="schemi -- per -- caricati (n=--,e=--,m=--)",
   ["nl"]="afbreekpatronen -- voor -- geladen (n=--,e=--,m=--)",
   ["no"]="orddelingsmønster -- for -- er lest inn (n=--,e=--,m=--)",
   ["ro"]="sablonul -- pentru -- s-a incarcat (n=--,e=--,m=--)",
  },
  ["10"]={
   ["cs"]="vzory --nacteny",
   ["de"]="Trennmuster --geladen",
   ["en"]="patterns --loaded",
   ["fr"]="motifs -- chargés",
   ["it"]="schemi -- caricati",
   ["nl"]="patronen --geladen",
   ["no"]="orddelingsmønster -- er lest inn",
   ["ro"]="sabloanele -- incarcate",
  },
  ["2"]={
   ["cs"]="zadne vzory -- pro -- (n=--,e=--,m=--) (--,--)",
   ["de"]="Keine Trennmuster -- fuer -- (n=--,e=--,m=--) (--,--)",
   ["en"]="no patterns -- for -- (n=--,e=--,m=--) (--,--)",
   ["fr"]="pas de motifs -- pour -- (n=--,e=--,m=--) (--,--)",
   ["it"]="niente schemi -- per -- (n=--,e=--,m=--) (--,--)",
   ["nl"]="geen afbreekpatronen -- voor -- (n=--,e=--,m=--) (--,--)",
   ["no"]="ingen orddelingsmønster -- for -- (n=--,e=--,m=--) (--,--)",
   ["ro"]="nu exista sabloane -- pentru -- (n=--,e=--,m=--) (--,--)",
  },
  ["3"]={
   ["cs"]="deleni slov -- pro -- nacteno (n=--,e=--,m=--)",
   ["de"]="Trenndefinitionen -- fuer -- geladen (n=--,e=--,m=--)",
   ["en"]="hyphenations -- for -- loaded (n=--,e=--,m=--)",
   ["fr"]="hyphenations -- pour -- chargés (n=--,e=--,m=--)",
   ["it"]="sillabazione -- per -- caricata (n=--,e=--,m=--)",
   ["nl"]="afbreekdefinities -- voor -- geladen (n=--,e=--,m=--)",
   ["no"]="orddelingsdefinisjon -- for -- er lest inn (n=--,e=--,m=--)",
   ["ro"]="despartirea in silabe -- pentru -- s-a incarcat (n=--,e=--,m=--)",
  },
  ["4"]={
   ["cs"]="zadne deleni slov -- pro -- (n=--,e=--,m=--)",
   ["de"]="Keine Trenndefinitionen -- fuer -- (n=--,e=--,m=--)",
   ["en"]="no hyphenations -- for -- (n=--,e=--,m=--)",
   ["fr"]="pas d'hyphenations -- pour -- (n=--,e=--,m=--)",
   ["it"]="niente sillabazione -- per -- (n=--,e=--,m=--)",
   ["nl"]="geen afbreekdefinities -- voor -- (n=--,e=--,m=--)",
   ["no"]="ingen orddelingsdefinisjon -- for -- (n=--,e=--,m=--)",
   ["ro"]="nu exista despartire in silabe -- pentru -- (n=--,e=--,m=--)",
  },
  ["5"]={
   ["cs"]="vzory pro -- nenacteny",
   ["de"]="Trennmuster fuer -- nicht geladen",
   ["en"]="patterns for -- not loaded",
   ["fr"]="les motifs pour -- ne sont pas chargés",
   ["it"]="schemi per -- non caricati",
   ["nl"]="afbreekpatronen voor -- niet geladen",
   ["no"]="orddelingsmønster for -- er ikke lest inn",
   ["ro"]="sabloanele pentru -- nu sunt incarcate",
  },
  ["6"]={
   ["cs"]="jazyk -- neni definovan",
   ["de"]="Sprache -- ist undefiniert",
   ["en"]="language -- is undefined",
   ["fr"]="langue -- non définie",
   ["it"]="lingua -- non definita",
   ["nl"]="taal -- is niet gedefinieerd",
   ["no"]="spràk -- er udefinert",
   ["ro"]="limba -- nu este definita",
  },
  ["7"]={
   ["cs"]="specificke volby jazyka [--] zavadeji -- (zavlecenou) mezeru",
   ["de"]="Sprachenspezifische Option [--] fuegt eine Luecke von -- ein",
   ["en"]="language specific options [--] introduce a -- skip",
   ["fr"]="les options spécifiques de langue [--] introduisent un -- saut",
   ["it"]="opzioni specifiche per la lingua [--] introducono un salto --",
   ["nl"]="taal specifieke opties [--] introduceren een skip van --",
   ["no"]="spràk spesifikk opsjon [--] introduserer et -- hopp",
   ["ro"]="optiunile specifice ale limbii [--] introduc un spatiu --",
  },
  ["8"]={
   ["cs"]="specificke volby jazyka [--] bez mezer pripojeny",
   ["de"]="Sprachenspezifische Option [--] nahtlos hinzugefuegt",
   ["en"]="language specific options [--] seamless appended",
   ["fr"]="les options spécifiques de langue [--] sont ajoutés en douceur",
   ["it"]="opzioni specifiche per la lingua [--] aggiunte trasparentemente",
   ["nl"]="taal specifieke opties [--] naadloos toegevoegd",
   ["no"]="spràk spesifikk opsjon [--] problemfritt tilføyd",
   ["ro"]="optiunile specifice ale limbii [--] adaugate",
  },
  ["9"]={
   ["cs"]="language -- is active",
   ["de"]="Sprache -- ist aktiv",
   ["en"]="language -- is active",
   ["fr"]="la langue -- est active",
   ["it"]="lingua -- attiva",
   ["nl"]="taal -- is actief",
   ["no"]="spràk -- er aktivt",
   ["ro"]="limba -- este activa",
  },
  ["files"]={ "lang-ini.mkii", "lang-ini.mkiv" },
  ["title"]={
   ["cs"]="jazyky",
   ["de"]="Sprache",
   ["en"]="language",
   ["fr"]="langue",
   ["it"]="lingua",
   ["nl"]="taal",
   ["no"]="sprøk",
   ["ro"]="limbi",
  },
 },
 ["metapost"]={
  ["1"]={
   ["cs"]="loading metapost library --",
   ["de"]="Lade metapost Bibliothek --",
   ["en"]="loading metapost library --",
   ["fr"]="chargement de la bibliothèque metapost --",
   ["it"]="caricamento della libreria metapost --",
   ["nl"]="metapost bibliotheek -- wordt geladen",
   ["no"]="metapost bibliotek -- blir lest inn",
   ["ro"]="se incarca biblioteca metapost --",
  },
  ["files"]={ "meta-ini.mkii", "meta-ini.mkiv" },
  ["title"]={
   ["cs"]="metapost",
   ["de"]="metapost",
   ["en"]="metapost",
   ["fr"]="metapost",
   ["it"]="metapost",
   ["nl"]="metapost",
   ["no"]="metapost",
   ["ro"]="metapost",
  },
 },
 ["references"]={
  ["1"]={
   ["cs"]="neznama reference --",
   ["de"]="unbekannte Referenz --",
   ["en"]="unknown reference --",
   ["fr"]="réference -- inconnue",
   ["it"]="riferimento sconosciuto --",
   ["nl"]="onbekende verwijzing --",
   ["no"]="ukjent referanse --",
   ["ro"]="referinta necunoscuta --",
  },
  ["2"]={
   ["cs"]="duplicitni reference -- na strane --",
   ["de"]="doppelte Referenz -- auf Seite --",
   ["en"]="duplicate reference -- on page --",
   ["fr"]="réference -- dupliquée à la page --",
   ["it"]="riferimento duplicato -- a pagina --",
   ["nl"]="dubbele verwijzing -- op pagina --",
   ["no"]="duplikat referanse -- pø side --",
   ["ro"]="referinta duplicat -- la pagina --",
  },
  ["21"]={
   ["cs"]="dokument -- nacten",
   ["de"]="Dokument -- geladen",
   ["en"]="document -- loaded",
   ["fr"]="document -- chargé",
   ["it"]="documento -- caricato",
   ["nl"]="document -- geladen",
   ["no"]="dokument -- er lest inn",
   ["ro"]="documentul -- este incarcat",
  },
  ["22"]={
   ["cs"]="dokument -- neni interaktivni",
   ["de"]="Dokument -- ist nicht aktiv",
   ["en"]="document -- is not interactive",
   ["fr"]="le document -- n'est pas interactif",
   ["it"]="il documento -- non ø interattivo",
   ["nl"]="document -- is niet interactief",
   ["no"]="dokument -- er ikke interaktivt",
   ["ro"]="documentul -- nu este interactiv",
  },
  ["23"]={
   ["cs"]="obskurni (nejasna) reference -- (prefix=--)",
   ["de"]="Obskure Referenz -- (Prefix=--)",
   ["en"]="obscure reference -- (prefix=--)",
   ["fr"]="reference -- indéterminé (préfixe=--)",
   ["it"]="riferimento ambiguo -- (prefisso=--)",
   ["nl"]="onduidelijke verwijzing -- (prefix=--)",
   ["no"]="obskur referanse -- (Prefix=--)",
   ["ro"]="referinta obscura -- (prefix=--)",
  },
  ["3"]={
   ["cs"]="neznamy typ reference --",
   ["de"]="unbekannte Referenz Typ --",
   ["en"]="unknown reference type --",
   ["fr"]="type -- de réference inconnu",
   ["it"]="riferimento di tipo sconosciuto --",
   ["nl"]="type verwijzing -- onbekend",
   ["no"]="ukjent referansetype --",
   ["ro"]="tip necunoscut de referinta --",
  },
  ["30"]={
   ["cs"]="neznamy objekt --",
   ["de"]="unbekanntes Object --",
   ["en"]="unknown object --",
   ["fr"]="objet -- inconnu",
   ["it"]="oggetto sconosciuto --",
   ["nl"]="onbekend object --",
   ["no"]="ukjent objekt --",
   ["ro"]="obiect necunoscut --",
  },
  ["31"]={
   ["cs"]="duplicitni object --",
   ["de"]="doppeltes Object --",
   ["en"]="duplicate object --",
   ["fr"]="objet -- dupliqué",
   ["it"]="oggetto duplicato --",
   ["nl"]="dubbel object --",
   ["no"]="duplikat objekt --",
   ["ro"]="obiect duplicat --",
  },
  ["4"]={
   ["cs"]="nedovolena reference --",
   ["de"]="illegale Referenz --",
   ["en"]="illegal reference --",
   ["fr"]="réference -- inconnue",
   ["it"]="riferimento illecito --",
   ["nl"]="verboden verwijzing --",
   ["no"]="ulovlig referanse --",
   ["ro"]="referinta eronata --",
  },
  ["files"]={ "core-obj.tex", "core-ref.tex", "strc-ref.tex" },
  ["title"]={
   ["cs"]="reference",
   ["de"]="referenzen",
   ["en"]="references",
   ["fr"]="réferences",
   ["it"]="riferimenti",
   ["nl"]="verwijzingen",
   ["no"]="referanser",
   ["ro"]="referinte",
  },
 },
 ["regimes"]={
  ["1"]={
   ["cs"]="kodovani --",
   ["de"]="Kodierung --",
   ["en"]="regime --",
   ["fr"]="encodage --",
   ["it"]="codifica --",
   ["nl"]="regime --",
   ["no"]="koding --",
   ["ro"]="codificarea --",
  },
  ["2"]={
   ["cs"]="je nacteno kodovani --",
   ["de"]="Kodierung -- ist geladen",
   ["en"]="regime -- is loaded",
   ["fr"]="l'encodage -- est chargé",
   ["it"]="codifica -- caricata",
   ["nl"]="regime -- wordt geladen",
   ["no"]="koding -- er lest inn",
   ["ro"]="codificarea -- este Encarcata",
  },
  ["3"]={
   ["cs"]="nezname kodovani --",
   ["de"]="Unbekannte Kodierung --",
   ["en"]="unknown regime --",
   ["fr"]="encodage -- inconnu",
   ["it"]="codifica sconosciuta --",
   ["nl"]="onbekend regime --",
   ["no"]="ukjent koding --",
   ["ro"]="codificarea -- este necunoscuta",
  },
  ["files"]={ "regi-ini.mkii" },
  ["title"]={
   ["cs"]="kodovani",
   ["de"]="Kodierung",
   ["en"]="regime",
   ["fr"]="encodage",
   ["it"]="codifica",
   ["nl"]="regime",
   ["no"]="koding",
   ["ro"]="codificari",
  },
 },
 ["specials"]={
  ["1"]={
   ["cs"]="-- nacteno",
   ["de"]="-- geladen",
   ["en"]="-- loaded",
   ["fr"]="-- chargé",
   ["it"]="-- caricato",
   ["nl"]="-- geladen",
   ["no"]="-- er lest inn",
   ["ro"]="-- incarcat",
  },
  ["2"]={
   ["cs"]="neni dovoleno hlubsi zanoreni --",
   ["de"]="keine tiefere Verschachtelung erlaubt --",
   ["en"]="no deeper nesting is permitted --",
   ["fr"]="pas d'imbracations plus profondes ne sont permises --",
   ["it"]="non ø permesso un annidamento maggiore --",
   ["nl"]="verdere nesting is niet toegestaan --",
   ["no"]="dypere 'nesting' er ikke tillatt --",
   ["ro"]="nu este permis un nivel de imbricare mai mare --",
  },
  ["3"]={
   ["cs"]="-- je resetovano",
   ["de"]="-- ist zurueckgesetzt",
   ["en"]="-- is reset",
   ["fr"]="-- est remis à zéro",
   ["it"]="-- reimpostato",
   ["nl"]="-- gereset",
   ["no"]="-- er tilbakestilt",
   ["ro"]="-- s-a resetat",
  },
  ["4"]={
   ["cs"]="prikaz -- neexistuje",
   ["de"]="Befehl -- existiert nicht",
   ["en"]="command -- does not exist",
   ["fr"]="la commande -- n'existe pas",
   ["it"]="il comando -- non esiste",
   ["nl"]="commando -- bestaat niet",
   ["no"]="kommando -- eksisterer ikke",
   ["ro"]="comanda -- nu exista",
  },
  ["5"]={
   ["cs"]="nacita se definicni soubor --",
   ["de"]="lade Definitionsdatei --",
   ["en"]="loading definition file --",
   ["fr"]="chargement du fichier de définition --",
   ["it"]="caricamento del file di definizione --",
   ["nl"]="definitiefile -- wordt geladen",
   ["no"]="leser inn definisjonsfil for --",
   ["ro"]="se incarca fisierul de definitii --",
  },
  ["6"]={
   ["cs"]="zanoreni neni dovoleno",
   ["de"]="Verschachtelung nicht erlaubt",
   ["en"]="nesting is not permitted",
   ["fr"]="l'imbrication n'est pas permise",
   ["it"]="annidamento non permesso",
   ["nl"]="nesting is niet toegestaan",
   ["no"]="'nesting' er ikke tillatt",
   ["ro"]="imbricarea nu este permisa",
  },
  ["7"]={
   ["cs"]="neznamy ovladac (driver) --",
   ["de"]="unbekante Driver --",
   ["en"]="unknown driver --",
   ["fr"]="pilote -- inconnu",
   ["it"]="driver sconosciuto --",
   ["nl"]="onbekende driver --",
   ["no"]="ukjent driver --",
   ["ro"]="driver necunoscut --",
  },
  ["files"]={ "spec-ini.tex" },
  ["title"]={
   ["cs"]="speciality",
   ["de"]="spezielles",
   ["en"]="specials",
   ["fr"]="specials",
   ["it"]="specialitø",
   ["nl"]="specials",
   ["no"]="specials",
   ["ro"]="specials",
  },
 },
 ["structures"]={
  ["1"]={
   ["cs"]="zacatek oddilu (sekce) --",
   ["de"]="Begin des Abschnittsblocks --",
   ["en"]="begin of sectionblock --",
   ["fr"]="début de blocsection --",
   ["it"]="inizio del blocco (sezione) --",
   ["nl"]="begin van sectieblok --",
   ["no"]="starten av blokk -- (seksjon)",
   ["ro"]="inceput de bloc sectiune --",
  },
  ["2"]={
   ["cs"]="konec oddilu (sekce) --",
   ["de"]="Ende des Abschnittsblocks --",
   ["en"]="end of sectionblock --",
   ["fr"]="fin de blocsection --",
   ["it"]="fine del blocco (sezione) --",
   ["nl"]="eind van sectieblok --",
   ["no"]="slutten av blokk -- (seksjon)",
   ["ro"]="sfarsit de bloc sectiune --",
  },
  ["files"]={ "core-sec.mkii", "core-sec.mkiv", "strc-sbe.tex" },
  ["title"]={
   ["cs"]="struktury",
   ["de"]="struktur",
   ["en"]="structure",
   ["fr"]="structure",
   ["it"]="struttura",
   ["nl"]="structuur",
   ["no"]="struktur",
   ["ro"]="structuri",
  },
 },
 ["symbols"]={
  ["1"]={
   ["cs"]="nacita se soubor symbolu --",
   ["de"]="Lade Symboldatei --",
   ["en"]="loading symbolset --",
   ["fr"]="chargement du jeu de symbole --",
   ["it"]="caricamento gruppo di simboli --",
   ["nl"]="symboolset -- wordt geladen",
   ["no"]="leser inn symbolsett --",
   ["ro"]="se incarca setul de simboluri --",
  },
  ["files"]={ "symb-ini.tex" },
  ["title"]={
   ["cs"]="symboly",
   ["de"]="Symbole",
   ["en"]="symbols",
   ["fr"]="symboles",
   ["it"]="simboli",
   ["nl"]="symbolen",
   ["no"]="symboler",
   ["ro"]="simboluri",
  },
 },
 ["systems"]={
  ["1"]={
   ["cs"]="nacteni pomocneho souboru odlozeno (typemode)",
   ["de"]="Laden der Hilfsdatei aufgeschoben (Eingabe-Modus)",
   ["en"]="loading utility-file postponed (typemode)",
   ["fr"]="chargement de fichier utilitaire reporté (typemode)",
   ["it"]="caricamento dei file supplementari posticipato (typemode)",
   ["nl"]="laden hulpfile uitgesteld (typemode)",
   ["no"]="innlesning av hjelpefila utsatt (typemode)",
   ["ro"]="se incarca utilitarul-fisierul este amanat (typemode)",
  },
  ["10"]={
   ["cs"]="nepouzivejte em v --",
   ["de"]="Benutzte kein em in --",
   ["en"]="don't use em in --",
   ["fr"]="n'utilisez pas em dans --",
   ["it"]="non usare em in --",
   ["nl"]="gebruik geen em in --",
   ["no"]="ikke bruk em i --",
   ["ro"]="nu folositi em in --",
  },
  ["11"]={
   ["cs"]="vytvarim jednoduchy pomocny soubor",
   ["de"]="Erstelle einfache Hilfdatei",
   ["en"]="building simple util",
   ["fr"]="construction util simple",
   ["it"]="costruzione di un semplice supplemento",
   ["nl"]="aanmaken basale hulpfile",
   ["no"]="lager enkel hjelpefil",
   ["ro"]="se creeaza un utilitar simplu",
  },
  ["12"]={
   ["cs"]="pomosny soubor neni setriden, pouzijte texutil",
   ["de"]="Die Hilfdatei ist nicht sortiert, verwende texutil",
   ["en"]="the utility-file is not sorted, use texutil",
   ["fr"]="le fichier utilitaire n'est pas trié, utilise texutil",
   ["it"]="file di supplemento non ordinato, usare texutil",
   ["nl"]="de hulpfile is niet gesorteerd, gebruik texutil",
   ["no"]="hjelpefila er ikke sortert, bruk texutil",
   ["ro"]="fisierul utilitar nu este sortat, folositi texutil",
  },
  ["13"]={
   ["cs"]="znacka -- definovana --",
   ["de"]="Beschriftung -- definiert --",
   ["en"]="mark -- defined --",
   ["fr"]="marquage -- defini --",
   ["it"]="marcatura -- definita --",
   ["nl"]="markering -- gedefinieerd --",
   ["no"]="markering -- definert --",
   ["ro"]="marcajul -- definit --",
  },
  ["14"]={
   ["cs"]="vynucena nova stranka v seznamu na --",
   ["de"]="Erzwungendes Seitenumbruch in Liste bei --",
   ["en"]="forced newpage in list at --",
   ["fr"]="nouvellepage forcée dans la liste à --",
   ["it"]="nuova pagina obbligata in lista a --",
   ["nl"]="geforceerde paginaovergang in lijst voor --",
   ["no"]="tvunget sideskift i liste ved --",
   ["ro"]="s-a fortat trecere pa pagina noua in lista la --",
  },
  ["15"]={
   ["cs"]="uklada se buffer --",
   ["de"]="Speichere Buffer --",
   ["en"]="saving buffer --",
   ["fr"]="sauvegarde du tampon (buffer) --",
   ["it"]="salvataggio del buffer --",
   ["nl"]="wegschrijven buffer --",
   ["no"]="lagrer Buffer --",
   ["ro"]="buffer salvat --",
  },
  ["16"]={
   ["cs"]="sazi se buffer --",
   ["de"]="Setzte Buffer --",
   ["en"]="typesetting buffer --",
   ["fr"]="composition du tampon (buffer) --",
   ["it"]="composizione del buffer --",
   ["nl"]="inlezen buffer --",
   ["no"]="tegnsetter buffer --",
   ["ro"]="buffer-ul -- s-a cules",
  },
  ["17"]={
   ["cs"]="sazi se doslovny (verbatim) buffer --",
   ["de"]="Setzte tippen-Buffer --",
   ["en"]="typesetting verbatim buffer --",
   ["fr"]="composition textuelle du tampon (buffer) --",
   ["it"]="composizione verbatim del buffer --",
   ["nl"]="verbatim inlezen buffer --",
   ["no"]="tegnsetter verbatim-buffer --",
   ["ro"]="se culege buffer-ul verbatim --",
  },
  ["18"]={
   ["cs"]="synonymum -- -- neexistuje",
   ["de"]="Synonym -- -- existiert nicht",
   ["en"]="synonym -- -- does not exist",
   ["fr"]="le synonyme -- -- n'existe pas",
   ["it"]="sinonimo -- -- non esistente",
   ["nl"]="synoniem -- -- bestaat niet",
   ["no"]="synonym -- -- eksisterer ikke",
   ["ro"]="sinonimul -- -- nu exista",
  },
  ["19"]={
   ["cs"]="vyznam (synonyma) -- nacten",
   ["de"]="Bedeutung (synonyme) von -- geladen",
   ["en"]="meaning (synonyms) of -- loaded",
   ["fr"]="signification (synonymes) de -- chargée",
   ["it"]="significato (sinonimi) di -- caricato",
   ["nl"]="betekenissen (synoniemen) van -- geladen",
   ["no"]="betydning (synonymer) av -- er lest inn",
   ["ro"]="intelesul (sinonimele) pentru -- incarcat",
  },
  ["2"]={
   ["cs"]="-- nacteno",
   ["de"]="-- geladen",
   ["en"]="-- loaded",
   ["fr"]="-- chargé",
   ["it"]="-- caricato",
   ["nl"]="-- geladen",
   ["no"]="-- er lest inn",
   ["ro"]="-- s-a incarcat",
  },
  ["20"]={
   ["cs"]="vyznam (trideni) -- nacten",
   ["de"]="Bedeutung (sortieren) von -- geladen",
   ["en"]="meaning (sorts) of -- loaded",
   ["fr"]="signification (tris) de -- chargée",
   ["it"]="significato (specie) di -- caricato",
   ["nl"]="betekenissen (sorteren) van -- geladen",
   ["no"]="betydning (sorterer) av -- er lest inn",
   ["ro"]="intelesul (ordinea) pentru -- incarcat",
  },
  ["21"]={
   ["cs"]="pomocny soubor necten",
   ["de"]="Die Hilfsdatei ist nicht geladen",
   ["en"]="no utility data is loaded",
   ["fr"]="pas de données utilitaires chargées",
   ["it"]="nessuna informazione supplementare caricata",
   ["nl"]="de hulpfile is niet geladen",
   ["no"]="hjelpefila er ikke lest inn",
   ["ro"]="nici o data utilitara nu este incarcata",
  },
  ["22"]={
   ["cs"]="pouzijte platny pomocny soubor",
   ["de"]="Benoetige gueltige Hilfsdateie",
   ["en"]="use a valid utilityfile",
   ["fr"]="utilise un fichier utilitaire valide",
   ["it"]="usare un file supplementare valido",
   ["nl"]="gebruik een goede hulpfile",
   ["no"]="bruk en gyldig hjelpefil",
   ["ro"]="folositi un fisier utilitar valid",
  },
  ["23"]={
   ["cs"]="-- upraveno na --",
   ["de"]="-- angeordnet auf --",
   ["en"]="-- arranged at --",
   ["fr"]="-- arrangé à --",
   ["it"]="-- sistemato a --",
   ["nl"]="-- gearrangeerd op --",
   ["no"]="-- arrangert på --",
   ["ro"]="-- aranjat la --",
  },
  ["24"]={
   ["cs"]="plovouci bloky",
   ["de"]="Fliessbloecke",
   ["en"]="Floatblocks",
   ["fr"]="blocsflottants",
   ["it"]="Oggetti mobili",
   ["nl"]="Plaatsblokken",
   ["no"]="Flytblokker",
   ["ro"]="Blocuri",
  },
  ["25"]={
   ["cs"]="reference",
   ["de"]="Referenzen",
   ["en"]="References",
   ["fr"]="Réferences",
   ["it"]="Riferimenti",
   ["nl"]="Verwijzingen",
   ["no"]="Referanser",
   ["ro"]="Referinte",
  },
  ["26"]={
   ["cs"]="registry",
   ["de"]="Register",
   ["en"]="Registers",
   ["fr"]="Registres",
   ["it"]="Registri",
   ["nl"]="Registers",
   ["no"]="Registere",
   ["ro"]="Registri",
  },
  ["27"]={
   ["cs"]="verze",
   ["de"]="Version",
   ["en"]="Version",
   ["fr"]="Version",
   ["it"]="Versione",
   ["nl"]="Versie",
   ["no"]="Versjon",
   ["ro"]="Versiune",
  },
  ["4"]={
   ["cs"]="prikaz -- je jiz definovan",
   ["de"]="Befehl -- ist bereits definiert",
   ["en"]="command -- is already defined",
   ["fr"]="la commande -- est déjà définie",
   ["it"]="comando -- già definito",
   ["nl"]="commando -- is al gedefinieerd",
   ["no"]="kommando -- er allerede definert",
   ["ro"]="comanda -- este deja definita",
  },
  ["41"]={
   ["cs"]="externi soubor -- ve skupine -- neexistuje",
   ["de"]="Externe Datei -- in Gruppe -- existiert nicht",
   ["en"]="external file -- in group -- does not exist",
   ["fr"]="le fichier externe -- du groupe -- n'existe pas",
   ["it"]="il file esterno -- del gruppo -- non esiste",
   ["nl"]="externe file -- in groep -- bestaat niet",
   ["no"]="ekstern fil -- i gruppe -- eksisterer ikke",
   ["ro"]="fisierul extern -- din grupul -- nu exista",
  },
  ["5"]={
   ["cs"]="makra z -- nactena",
   ["de"]="Modul -- geladen",
   ["en"]="module -- loaded",
   ["fr"]="module -- chargé",
   ["it"]="macro del modulo -- caricate",
   ["nl"]="module -- geladen",
   ["no"]="makroene i modul  -- er lest inn",
   ["ro"]="macro-urile din modulul -- s-au incarcat",
  },
  ["6"]={
   ["cs"]="zadna makra v -- nenalezena",
   ["de"]="Modul -- gefunden",
   ["en"]="module -- not found",
   ["fr"]="module -- non trouvé",
   ["it"]="nessuna macro trovata nel modulo --",
   ["nl"]="geen module -- gevonden",
   ["no"]="ingen makroer funnet i modul ---",
   ["ro"]="nu s-au gasit macro-uri in modulul --",
  },
  ["7"]={
   ["cs"]="makra z -- jsou jiz nactena",
   ["de"]="Modul -- bereits geladen",
   ["en"]="module -- already loaded",
   ["fr"]="module -- déjà chargé",
   ["it"]="macro del modulo -- già caricate",
   ["nl"]="module -- reeds geladen",
   ["no"]="makroene i modul -- er allerede lest inn",
   ["ro"]="macro-urile din modulul -- s-au incarcat deja",
  },
  ["8"]={
   ["cs"]="nova verze pomocneho souboru, je treba druheho behu",
   ["de"]="Neue Version der Hilfsdatei, zweiter Durchlauf benoetigt",
   ["en"]="new version of utility file, second pass needed",
   ["fr"]="nouvelle version de fichier utilitaire, seconde passe nécessaire",
   ["it"]="nuova versione del file supplementare, seconda passata necessaria",
   ["nl"]="nieuwe versie hulpfile, tweede run nodig",
   ["no"]="ny versjon av hjelpefil, andre gjennomkjøring nødvendig",
   ["ro"]="o noua versiune de fisier utilitar, este necesara o noua trecere",
  },
  ["9"]={
   ["cs"]="-- nenalezeno/nezpracovano",
   ["de"]="-- nicht gefunden/verarbeitet",
   ["en"]="-- not found/processed",
   ["fr"]="-- non trouvé/traité",
   ["it"]="-- non trovato/elaborato",
   ["nl"]="-- niet gevonden/geplaatst",
   ["no"]="-- ikke funnet/behandlet",
   ["ro"]="-- nu este gasit/procesat",
  },
  ["91"]={
   ["en"]="papertray --",
   ["nl"]="papierlade --",
  },
  ["files"]={ "core-mis.tex", "page-ini.tex", "prag-gen.tex", "strc-mar.tex" },
  ["title"]={
   ["cs"]="system",
   ["de"]="system",
   ["en"]="system",
   ["fr"]="système",
   ["it"]="sistema",
   ["nl"]="systeem",
   ["no"]="system",
   ["ro"]="sistem",
  },
 },
 ["textblocks"]={
  ["1"]={
   ["cs"]="nova verze, je treba druhy beh",
   ["de"]="neue Version, zweiter Durchlauf benoetigt",
   ["en"]="new version, second pass needed",
   ["fr"]="nouvelle version, une seconde passe est nécessaire",
   ["it"]="nuova versione, seconda passata necessaria",
   ["nl"]="nieuwe versie, tweede run nodig",
   ["no"]="ny versjon, andre gjennomkjøring nødvendig",
   ["ro"]="o noua versiune, este nevoie de inca o trecere",
  },
  ["10"]={
   ["cs"]="-- nacteno a zpracovano",
   ["de"]="-- geladen und verarbeitet",
   ["en"]="-- loaded and processed",
   ["fr"]="-- chargé et traité",
   ["it"]="-- caricato ed elaborato",
   ["nl"]="-- geladen en verwerkt",
   ["no"]="-- lest inn og behandlet",
   ["ro"]="-- incarcat si procesat",
  },
  ["11"]={
   ["cs"]="-- nacteno a vysazeno",
   ["de"]="-- geladen und gesetzt",
   ["en"]="-- loaded and typeset",
   ["fr"]="-- chargé et composé",
   ["it"]="-- caricato e composto",
   ["nl"]="-- geladen en geplaatst",
   ["no"]="-- lest inn og tegnsatt",
   ["ro"]="-- incarcat si cules",
  },
  ["12"]={
   ["cs"]="-- preskoceno",
   ["de"]="-- ausgelassen",
   ["en"]="-- skipped",
   ["fr"]="-- sauté",
   ["it"]="-- saltato",
   ["nl"]="-- overgeslagen",
   ["no"]="-- utelatt",
   ["ro"]="-- sarit peste",
  },
  ["2"]={
   ["cs"]="zapisuji bloky do --",
   ["de"]="schreibe Bloecke zu --",
   ["en"]="writing blocks to --",
   ["fr"]="ecriture des blocs vers --",
   ["it"]="scrittura dei blocchi su --",
   ["nl"]="wegschrijven blokken naar --",
   ["no"]="skriver blokker til --",
   ["ro"]="se scriu blocurile in --",
  },
  ["3"]={
   ["cs"]="ctu bloky z --",
   ["de"]="lese Bloecke von --",
   ["en"]="reading blocks from --",
   ["fr"]="lecture des blocs en provenance de --",
   ["it"]="lettura dei blocchi da --",
   ["nl"]="inlezen blokken uit --",
   ["no"]="leser blokker fra --",
   ["ro"]="se citesc blocurile din --",
  },
  ["4"]={
   ["cs"]="je treba druhy beh",
   ["de"]="zweiter Durchlauf benoetigt",
   ["en"]="second pass needed",
   ["fr"]="seconde passe nécessaire",
   ["it"]="seconda passata necessaria",
   ["nl"]="er is een tweede run nodig",
   ["no"]="andre gjennomkjøring nødvendig",
   ["ro"]="este nevoie de inca o trecere",
  },
  ["5"]={
   ["cs"]="-- neni skryto",
   ["de"]="-- nicht verborgen",
   ["en"]="-- not hidden",
   ["fr"]="-- non caché",
   ["it"]="-- non nascosto",
   ["nl"]="-- niet verborgen",
   ["no"]="-- ikke skjult",
   ["ro"]="-- nu este ascuns",
  },
  ["6"]={
   ["cs"]="-- skryto a zpracovano",
   ["de"]="-- verborgen und verarbeitet",
   ["en"]="-- hidden and processed",
   ["fr"]="-- caché et traité",
   ["it"]="-- nascosto ed elaborato",
   ["nl"]="-- verborgen en verwerkt",
   ["no"]="-- skjult og behandlet",
   ["ro"]="-- ascuns si procesat",
  },
  ["7"]={
   ["cs"]="-- skryto",
   ["de"]="-- verborgen",
   ["en"]="-- hidden",
   ["fr"]="-- caché",
   ["it"]="-- nascosto",
   ["nl"]="-- verborgen",
   ["no"]="-- skjult",
   ["ro"]="-- ascuns",
  },
  ["8"]={
   ["cs"]="-- vysazeno",
   ["de"]="-- gesetzt",
   ["en"]="-- typeset",
   ["fr"]="-- composé",
   ["it"]="-- composto",
   ["nl"]="-- gehandhaafd",
   ["no"]="-- tegnsatt",
   ["ro"]="-- cules",
  },
  ["9"]={
   ["cs"]="-- nevysazeno",
   ["de"]="-- nicht gesetzt",
   ["en"]="-- not typeset",
   ["fr"]="-- non composé",
   ["it"]="-- non composto",
   ["nl"]="-- niet gehandhaafd",
   ["no"]="-- ikke tegnsatt",
   ["ro"]="-- nu este cules",
  },
  ["files"]={ "core-blk.tex" },
  ["title"]={
   ["cs"]="textovyblok",
   ["de"]="textblock",
   ["en"]="textblocks",
   ["fr"]="blocs de texte",
   ["it"]="blocchi di testo",
   ["nl"]="tekstblokken",
   ["no"]="tekstblokker",
   ["ro"]="blocuri de text",
  },
 },
 ["verbatims"]={
  ["1"]={
   ["cs"]="soubor -- neexistuje",
   ["de"]="Datei -- existiert nicht",
   ["en"]="file -- does not exist",
   ["fr"]="le fichier -- n'existe pas",
   ["it"]="il file -- non esiste",
   ["nl"]="file -- bestaat niet",
   ["no"]="fil -- eksisterer ikke",
   ["ro"]="fisierul -- nu exista",
  },
  ["files"]={ "core-ver.tex" },
  ["title"]={
   ["cs"]="verbatim",
   ["de"]="verbatim",
   ["en"]="verbatim",
   ["fr"]="verbatim",
   ["it"]="verbatim",
   ["nl"]="typen",
   ["no"]="verbatim",
   ["ro"]="verbatim",
  },
 },
 ["versions"]={
  ["1"]={
   ["cs"]="postradam @+",
   ["de"]="fehlendes @+",
   ["en"]="missing @+",
   ["fr"]="@+ manquant",
   ["it"]="@+ mancante",
   ["nl"]="er mankeert een @+",
   ["no"]="manglende @+",
   ["ro"]="lipseste @+",
  },
  ["2"]={
   ["cs"]="oznacuji se strany",
   ["de"]="Erstelle Seiten",
   ["en"]="marking pages",
   ["fr"]="marquage des pages",
   ["it"]="marcatura pagine",
   ["nl"]="markeren pagina's",
   ["no"]="markerer sider",
   ["ro"]="pagini marcate",
  },
  ["3"]={
   ["cs"]="oznacene strany: --",
   ["de"]="Ausgewaehlte Seiten: --",
   ["en"]="selected pages: --",
   ["fr"]="pages sélectionnées : --",
   ["it"]="pagine selezionate: --",
   ["nl"]="geselecteerde pagina's: --",
   ["no"]="valgte sider: --",
   ["ro"]="pagini selectate: --",
  },
  ["files"]={ "core-int.tex" },
  ["title"]={
   ["cs"]="verze",
   ["de"]="Version",
   ["en"]="version",
   ["fr"]="version",
   ["it"]="version",
   ["nl"]="versie",
   ["no"]="versjon",
   ["ro"]="versiuni",
  },
 },
}