% This is placeholder for Bogluslaw Jackowski's hatching.mp file which can be found in
% the public domain and dates from 2000. It provides:
%
% draw hatched (fullcircle scaled 10cm) (45, 4, 1) withcolor "red" ;
%
% interim hatch_match := 1;
%
% This macro is not in mp-tool so this is a placeholder. The hatching macro doesn't fit
% into metafun because it assume withcolor to behave in a certain way. Also, we use more
% efficient path constructor.
