.TH "pstopdf" "1" "01-01-2020" "version 2.0.1" "PStoPDF"
.SH NAME
 pstopdf - PStoPDF
.SH SYNOPSIS
.B pstopdf [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B PStoPDF
.SH OPTIONS
.TP
.B --request
handles exa request file
.TP
.B --watch
watch folders for conversions (untested)
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
