.TH "textools" "1" "01-01-2020" "version 1.3.1" "TeXTools"
.SH NAME
 textools - TeXTools
.SH SYNOPSIS
.B textools [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B TeXTools
.SH OPTIONS
.TP
.B --removemapnames
[pattern]   [--recurse]
.TP
.B --restoremapnames
[pattern]   [--recurse]
.TP
.B --hidemapnames
[pattern]   [--recurse]
.TP
.B --videmapnames
[pattern]   [--recurse]
.TP
.B --findfile
filename    [--recurse]
.TP
.B --unzipfiles
[pattern]   [--recurse]
.TP
.B --fixafmfiles
[pattern]   [--recurse]
.TP
.B --mactodos
[pattern]   [--recurse]
.TP
.B --fixtexmftrees
[texmfroot] [--force]
.TP
.B --replacefile
filename    [--force]
.TP
.B --updatetree
fromroot toroot [--force --nocheck --merge --delete]
.TP
.B --downcasefilenames
[--recurse] [--force]
.TP
.B --stripformfeeds
[--recurse] [--force]
.TP
.B --showfont
filename
.TP
.B --encmake
afmfile encodingname
.TP
.B --tpmmake
tpm file (run in texmf root)
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
