.TH "texutil" "1" "01-01-2020" "version 9.1.0" "TeXUtil"
.SH NAME
 texutil - TeXUtil
.SH SYNOPSIS
.B texutil [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B TeXUtil
.SH OPTIONS
.TP
.B --references
convert tui file into tuo file
.TP
.B --figures
generate figure dimensions file
.TP
.B --logfile
filter essential log messages
.TP
.B --purgefiles
remove most temporary files
.TP
.B --purgeallfiles
remove all temporary files
.TP
.B --documentation
generate documentation file from source
.TP
.B --analyzefile
analyze pdf file
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
