.TH "tmftools" "1" "01-01-2013" "version 1.1.0" "TMFTools" 
.PP
.SH "NAME" 
.PP
.SH "SYNOPSIS" 
.PP
.SH \fBtmftools\fP [ \fIOPTIONS\fP ... ] [ \fIFILENAMES\fP ] 
.PP
.SH "DESCRIPTION"\nTMFTools\n 
.SH "OPTIONS"
.TP
.B --analyze
[--strict --sort --rootpath --treepath --delete --force] [pattern]
.TP
.B --serve
act as kpse server
.SH "AUTHOR"
More information about ConTeXt and the tools that come with it can be found at:

maillist : ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context
webpage  : http://www.pragma-ade.nl / http://tex.aanhet.net
wiki     : http://contextgarden.net
