.TH "xmltools" "1" "01-01-2013" "version 1.2.2" "XMLTools" 
.PP
.SH "NAME" 
.PP
.SH "SYNOPSIS" 
.PP
.SH \fBxmltools\fP [ \fIOPTIONS\fP ... ] [ \fIFILENAMES\fP ] 
.PP
.SH "DESCRIPTION"\nXMLTools\n 
.SH "OPTIONS"
.TP
.B --dir
generate directory listing
.TP
.B --mmlpages
generate graphic from mathml
.TP
.B --analyze
report entities and elements [--utf --process]
.TP
.B --cleanup
cleanup xml file [--force]
.TP
.B --enhance
enhance xml file (partial)
.TP
.B --filter
filter elements from xml file [--element]
.TP
.B --dir
generate ddirectory listing
.SH "AUTHOR"
More information about ConTeXt and the tools that come with it can be found at:

maillist : ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context
webpage  : http://www.pragma-ade.nl / http://tex.aanhet.net
wiki     : http://contextgarden.net
