.TH "xmltools" "1" "01-01-2020" "version 1.2.2" "XMLTools"
.SH NAME
 xmltools - XMLTools
.SH SYNOPSIS
.B xmltools [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B XMLTools
.SH OPTIONS
.TP
.B --dir
generate directory listing
.TP
.B --mmlpages
generate graphic from mathml
.TP
.B --analyze
report entities and elements [--utf --process]
.TP
.B --cleanup
cleanup xml file [--force]
.TP
.B --enhance
enhance xml file (partial)
.TP
.B --filter
filter elements from xml file [--element]
.TP
.B --dir
generate ddirectory listing
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
