return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="tr",
  ["source"]="hyph-tr",
  ["texcomment"]="% Turkish hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% hyph-tr.tex\
%\
% Turkish hyphenation patterns\
%\
% This file is auto-generated from source/generic/hyph-utf8/languages/tr/generate_patterns_tr.rb that is part of hyph-utf8.\
% Please don't modify this file; modify the generating script instead.\
%\
% Copyright (C) 1987 Pierre A. MacKay\
%               2008, 2011 TUG\
%\
% This program can redistributed and/or modified under the terms\
% of the LaTeX Project Public License Distributed from CTAN\
% archives in directory macros/latex/base/lppl.txt; either\
% version 1 of the License, or (at your option) any later version.\
%\
% Credits:\
% - algorithm developed by P. A. MacKay for the Ottoman Texts Project in 1987\
% - rules adapted for modern Turkish by H. Turgut Uyar <uyar at itu.edu.tr>\
% - initiative to improve Turkish patterns by S. Ekin Kocabas <kocabas at stanford.edu>\
% - script written by Mojca Miklavec <mojca.miklavec.lists at gmail.com> in June 2008\
%\
% See also:\
% - http://www.ctan.org/tex-archive/language/turkish/hyphen/turk_hyf.c\
% - http://www.tug.org/TUGboat/Articles/tb09-1/tb20mackay.pdf\
%\
% Differences with Ottoman patterns:\
% - adapted for the use on modern TeX engines, using UTF-8 charactes\
% - only letters for Modern Turkish + Ã¢Ã®Ã» (the first one often needed, the other two don't hurt)\
% - (if needed, support for Ottoman Turkish might be provided separately under language code 'ota')\
%\
% Changes:\
% - 2008-06-25/27/28 - create this file by adapting Ottoman rules for modern Turkish\
% - 2011-08-10 - add LPPL licence with permission of Pierre A. MacKay\
% \
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnoprstuvyzÃ¢Ã§Ã®Ã¶Ã»Ã¼ÄŸÄ±ÅŸ",
  ["compression"]="zlib",
  ["data"]="xÚ%ÓKnã:\16…á­x\5\23ˆoo(¡ŞÔ\11\20%@ÚL€d& \19M¤™­}õ\127Šƒ:´\19ó«\2z~~<¯¿DN½\127‰Z\127Ù‰A\31\14bÖ‡Kq~<>¾(G½~ˆŒ*¨’z\127\19\21ÕPj©ê©‘\
ÔDİúa¤\22j¥6õ\127ºÜÿ÷x~}Qzı\16\25UP%õş&*ª¡<ÕR\29ÕS#\21¨‰ºõÃH-ÔJm§ƒu°N¬ƒu°\14Ö‰u°\14ÖÁ:X\7ë`\29¬ƒu°N¬ƒu°\14ÖÁ¾~¾\20N!ùõ“)\
E©şú©\20Â+ZE§è\21£\"(&ÅmW¢bQ¬\
ze´Êè”©QFŸŒ6\25]25Éè‘Ñ\"£CFƒ\12?ƒÏĞ3ğ\12;\19!gÀ\25n\6[À\22°…Ø\2¶€-`\11±\5l\1[À\22°\5l\1[À\22°\5l!¶€-`\11Ø\2¶„-aK±%l\9[Â–bKØ\18¶„-aKØ\18¶„-aKØRl\9[Â–°%ìûûKá\20’ßß™¢P”\
éïïJÑ(¼¢UtŠ^1*‚bRÜv%*\22Åª WE«ŠN•\26Uô©hSÑ¥R“Š\30\21-*:T4¨ğ+ø\
½\2¯°+Ñ\21r\5\\áV°\13l\3Ûˆm`\27Ø\6¶\17ÛÀ6°\13l\3ÛÀ6°\13l\3ÛÀ6b\27Ø\6¶m`=¬‡õb=¬‡õ°^¬‡õ°\30ÖÃzX\15ëa=¬‡õb=¬‡õ°\30¶…ma[±-l\11ÛÂ¶b[Ø\22¶…ma[Ø\22¶…ma[ØVl\11ÛÂ¶°-l\7ÛÁvb;Ø\14¶ƒíÄv°\29l\7ÛÁv°\29l\7ÛÁv°Ø\14¶ƒí`;Ø\30¶‡íÅö°=l\15Û‹ía{Ø\30¶‡ía{Ø\30¶‡ía{±=l\15ÛÃö°#ì\8;Š\29aGØ\17v\20;Â°#ì\8;Â°#ì\8;ÂbGØ\17v„\29a\3l€\13b\3l€\13°Al€\13°\0016À\6Ø\0\27`\3l€\13b\3l€\13°\1v‚`'±\19ì\4;ÁNb'Ø\9v‚`'Ø\9v‚`'ØIì\4;ÁN°\19ì­Õ»µz·­Ş­Õ»µz·Vï¶Õ»µz·VïÖêİZ½[«wkõn­Ş­Õ»µz·­Ş­Õ»µz·VïÖêEZE:E5Šô‰´‰t‰j\18é\17i\17é\16i\16ñ#|Dà\17;ŠÈ\0178âFØ\5v]Ä.°\11ì\2»ˆ]`\23Ø\5v]`\23Ø\5v]`\23±\11ì\2»À.°+ì\
»Š]aWØ\21v\21»Â®°+ì\
»Â®°+ì\
»Â®bWØ\21v…]a7Ø\13v\19»Án°\27ì&vƒİ`7Ø\13vƒİ`7Ø\13vƒİÄn°\27ì\6»mÏÿ?ŸÄë¯2W¼\127•µıuW\14öñPÎöñ²<Ÿ×_İ&u#·\20ÀQ§ÿìv\12éËaÇœ¾\\éÀÉÅä¦äBr3r\17¹\9¹€ÜîçºÛíÜ.¿\127u›ÔuÜR\0Gş³Û1¤/‡\29súr¥\3§\22S›R\11©Í¨EÔ&Ô\2j»_ëzm·ëô\18»½Ä^b·—ØÓKìö\18{z‰İ^bO/±ÛKìé%vs\0061ƒ)ƒÁŒAÄ`Â `°ûƒ®\15v{HC\0286Ä‘†8lˆ#\13qØ\16G\26â°!4ÄaC\28iˆÃœYÌlÊ,d6c\0221›0\11˜íş¬ë³İÓ\16—\13q¥!.\27âJC\\6Ä•†¸lˆ+\13qÙ\16W\26âJÎiÎ™œÓœ39§9grNsÎäœæœÉ9Í‰óŸğÇ?ºø'|ú\127Ò¿Úß",
  ["length"]=2786,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=597,
 },
 ["version"]="1.001",
}