return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["characters"]="acefhijklnoprtyÃ­ÃºÄÅ™",
  ["compression"]="zlib",
  ["data"]="xÚËÎOÕMËÔMÎÔMÍ+QÈFâé–T*\20\20åëf¥fë\30éÍ;¼Váğ®Œœ|İ‚£3\15¯=Ò«›ˆ.P\9\0¡ï!",
  ["length"]=77,
  ["n"]=5,
 },
 ["metadata"]={
  ["mnemonic"]="cs",
  ["source"]="hyph-cs",
  ["texcomment"]="% Czech hyphenation patterns (Pavel Sevecek, v3, 1995)\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: czhyphen.tex (), czhyphen.ex ()\
% Author: Pavel Å eveÄek <pavel at lingea.cz>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
%%% ====================================================================\
% This is CZHYPHEN.TEX, containing czech hyphenation patterns.\
% Prepared by:\
%   Pavel Å eveÄek\
%   Lingea s.r.o., Brno, Czech Republic\
%   E-mail: pavel@lingea.cz\
%\
% This is free software; you can redistribute it and/or modify\
% it under the terms of the GNU General Public License as published by\
% the Free Software Foundation; either version 2 of the License, or\
% (at your option) any later version.\
%\
% This file is distributed in the hope that it will be useful,\
% but WITHOUT ANY WARRANTY; without even the implied warranty of\
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\
% GNU General Public License for more details.\
%\
% You should have received a copy of the GNU General Public License\
% along with this program; if not, write to the Free Software\
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA\
%%% --------------------------------------------------------------------\
% \\message {Czech Hyphenation Patterns (Pavel Sevecek, v3, 1995)}\
%\\lefthyphenmin=2\\righthyphenmin=2\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnopqrstuvwxyzÃ¡Ã©Ã­Ã³ÃºÃ½ÄÄÄ›ÅˆÅ™Å¡Å¥Å¯Å¾",
  ["compression"]="zlib",
  ["data"]="xÚ5œ;’ã¸Ò…·Â\21T„@nˆ\18Y\18Å\7xI·É\21\\gbì¶Êh£Š1Æëˆ*G¥}ıç;ìßĞI¼ßHd&@½”!{)‹ª4ÖÆÆ\24_¶3:¨Œ‹°«óox&çœ{rîÉI§ÍøxƒÌN4;ÑLôœ§Ü\30§JND§ÜÕ%—‘\\]ršU±gµ÷Âï\6l­Š¨äªê\29W1¨˜j¨\11ãó­h\29¨ÜUœ\9t\25Â¯\31&÷ì¥Vöº¸Ü@ºXÏykL„şÕ½º*\29•ŞŠ®\6\7a#\127ãJ…Q%43=¸+î^”*ë^\23\21\1îı½Ø+áã­R{Z¥i‹®1ª•íóûã=W|§ˆ®.®ê}×äíš½ô\
é›|NÊÖÇ¥Rw‡2ÿúKŞ¡Î/àÿ{\26ğ¡\9jÿ\16\11÷c(ÖQøx;\25Ÿß\25˜¨\18cqfŠcUç í\22zÊbÑ–Æ\8\14vÓçèF÷T¸\0247#£*Â¨ÆbtÚÑ©f»gJŸ=±‘ÙŸ\14¯s¥?•¦|%i:ÊHÏï\"š­\"áİiÄW.sw+öÃíV<ßÚƒt&ŸJ0ªã±6Ç2wqcì4ØĞcôF¯Váã\3BSÇ%?g/“òNõ½\0óY\24\25µ)îŒ•\8íŸ\22Oí¬¤³×PÕÎu_€ù8\16ÔªÌÙ•ÊM7g¯¡Ù£:{ôf×ìñš“‹KGJ÷ƒ…_q.µ±1F°rHåê\8YŒŒä¢å*¼\23=A­£ÙÂKWÜp÷.´w\17½‹èypÈàÑiF‡Œ„Œ.Ó-\22:ıH“E˜R|Tmö°x—ƒ\25,³{2;dNÆÍè\12îk±ºÒİÕ}ıõ‡4\0079Ê}¾Õ\7i\14¢ÉY´åÓáû“†Á[ŸGSŸŸñ D®ªf-=}«;±n9Î&®\19\30çßŠ8ğ‚]¹ö2\7\"‹b/'‡|ı\5\21í\4á\4¶\27Ø\15 ;f÷Ù½²\31{e÷¨înÄ~¬ùı¨Ì£à¢µTa_r?Ş\127\5Ï7CÍ\30‡Û•\7©\15²™<\127Æ?”=~“÷wQ=ÿQègÈÊS\22Ê—¬Ôîçœwq\16):í\6ùÄøä™ÏÂ ™*/,ï2TY™ëÌ\16Ô€‚ªĞÉ¯ÑlŒªÊä—bXWàBÒ(§8\1Î\\\11£¬\\E^MÏOÈB6ÍW–Ë³:~Dl\0¥æœIB\31îwŠ~üŞ\15¢¡S ºF”:P3€åk\19TR¸*ô*Çµx¥éW•{Í'J¿Ò´+¥ß`ÆåML¨\12´«Ñ`4°\0159\9»W@Ÿ•w÷ê\30”=´ŠmIÒ’E‡eÙ²gä¤p\29˜\2jhéDëN´îDûø\23t{[ÚÛ\21¯g2º\"©W]îÕZöÅ¹\2‰éYCeÏú“›%ZŠ“ÔFZ5\20•¦J§àÜB–‚ ùb¼\26;£º1„y´{\5Ó×_çç-+cQWà­\7gV¥¨SˆWjÁ\20£6p9jéÉùü®@O™Ô©¨ş‹“&MõDÀµ# ÁÙŞpFââ7\5ä,¬|R—¦À”ç\19ã4yœ&FhÊYçÊù|s\13Œ—`Î@Ã\22XO3Yg¦a¦‚™©›óÁÅĞÒ9\23×*ÅVKZ<§ÖŞîiy!AZIËTÍvÑù(Àó\5\127\18R\127 Í\18ZÊ\4Û—“Š\0193‘šH(\19%I†\21\12\19~†DÈ\30ƒ¬¤§çÉœQ$¹0šàÆ$šÜ„ä&$¯ûä†$\6'˜\25¸Æãı…@¯¦äaQ1Kqep–»œ°ÿrA P€&2”ªb•¸Q®Eõ‚“æ\22k·\24©c%ñª>)±š\"N¨–ï\18\4lø½ğ\30ßs¯÷]k)°Bt²–ÆÚØ\0245 âb½;óõW4.Æ?AîÔ×_\30Şçÿä~ş/\26•êù]Ò\25ï¤ÒJ\24»ƒl$ş™•ßjj8¿dùYìì\\\22ç\9¼Ü ¹8ãÙÒg8Ÿ.ÙùTeçº¨_IÈĞœu\\\11tH\9ƒäÉsÍQ\127>İ²“NÚs\19ÎòI¸\3$†\27¤Óóé®B[UÛ©Ú®8wÙ9tuoœ\9n3ØéÛ@Èã—\"N½r\12*4fçèúc!\"Œ-H©qÑî>\0312Í9Leg\28”Q›è¬S5ÉtÉÎ’E\
¢åÌYÉà™\0*U‡uÜg\22 ÜÊ¤åtSú%h –¢\30ÔÆM™6:¶Á\21„ìs‘Fïj©fH™\9|ü*¦‹B¾~(Ï×\15ö€¢ßUÈã]©\31ïD‡³æï¬É*µ’2êÑÉ\19¨xíèpyÉN—2»ˆwwÂBã\21.*üRg—ú¢F^jÇÔ]Ì…Å0ƒÚ5Â\17÷TàÖ:\15—\27eİÊL3^v×,¿ÜjÜªZq*ã†€-ìÏ\4ä\3˜H¡«Œ\11q‹ËØ\0:|¹iktà]šz(.\"Èpá\"©ı¢C6e—6Õ–\27ÃE5°!\4Ú\15á¢Ù½Äì\18\0111\27aßƒÏÏ1»„QÑ\
\12ÚS—ÔH+¹¤‚œ)\12Ê®]¯(mòËÒTH\127\11r¨A‚÷L¿b¤\21\26áÓE{%hët\24W:ó\4Å]â\127e­²úTÎY\21$6\22Õ¹L/¸é\\¥}P1*Y\14\25”NÙ«BCxÒ©^ÕÚ@ü6€:ø*vIÄCÙ5ZIU\7‰°Â¸\0192\19Î\
\2IÉéRÕb³¥1õé\27±ß\8\9Î´Sş»à¯¿\8÷@©Úw\18-ª¦¸^ÕøfP\19\26”3…Pº6^u/\22­™Ja4'¯´\7«“FSË¦<\27‰Ò™~ª:Õ\19:í\23ùãÂ8tvÃ\9+6¨¤\14åeú ï$ĞğVÚ­§ªWİıãCb”b5¹’c$ek¯ƒQ\13‰Ú‹šë*j3\0255…\16-*jd•®¨ş\16’WŒxÌo\2xÂÛ\1ìœ»'²Ú\1òh\8¥Gi¶âèL:%)sÎĞiGcj\8Ê]ÿÒ\26éUÌ%®Vâ\14®K!Tÿõ\23>äIÊe¨%ªŠ³Tê€J;1ë:µÅ\22ª)ŠMIB‹³q1²¼&Ä\9y\22<:ƒ\127\25?ÈøøX\25@ñœJÊ\14\3h¥¦\18ç©òÔ\1ì*IzÕÒ‹7ˆä¬¡…~JgĞÆ¬–\9ÿÜ\16À©VÑãb-©Sr±€rÖ\9Ø€\7Í@©Çı®Ò\21*VFƒ÷3P\1ÌÛ±ô5\20'äÈ\19b$²ä\29¿øR¥]Uà[ÕqâT…èxøÆáğ®Nâ\21\2Id\19;«r˜5˜Tšz$ªÆ?ÿ\17+?!*½$î TŸÊ¬FìÍêP\
´Gës!Q©Ö¡\19pkÍÖb“ß3l\19Ê †¦Å§·'*šÃ\13÷êp‚b—Ò\12…Ú\12µV± H·«óJ+ªÖà\16ç¦×'¥«\0177ê:ÿ¦º®ÅUxÒö\23(î6ÄBhEE!\17 ¡â”‚\13ĞX‚\31Bem:‰\22Y}ÏË«*¼—³‚ï5N\9’\
®»Ã³ã‘p&w£4wí/\5ˆ±(@:‚\2\"€kA4T¤š-!»æ\20¯‘´51Ú'5òu|]#_×È×µåëÚòumùZÈ ZÊ®a\13µ˜‚RwEµ\18P\3ô®£c\20Û¡uÊéîÁ\15j³ƒúÔk<‹Şn\9ß-!ŒHOµ½S÷\30¬\20yïj{WÛ3HZíŸ*xpÅC“°HÕ\22ÌAà€I¤¦ûæ\"uÔ9¥\0›eêˆ>¯Ã\6³ùëˆBV\0316\18eØqk±ƒ\26ïˆV˜Õ\24=4x#-\31%£Õc\22Š›\22b\3Ä“2QÌXh‡‚½q ¥„Ñz”j\28X'‰÷:uKVğÄ(M,\26\9óµÄxbæ\23ã@(\3:±R&\15Îä¡œ< “Wr\0203Ë%Ì\23f\21™½Åİ\9ÑøŠ°äE\8×$¿˜lFJ\0113\29›ağ\"LŞ\28zœ#)Q«k’D|\23¤³\30Ã^#VÏ©\20;ÁÙ\8F\\ªO$Omcœ@\23(<¡Á€ÑHO,~×Iº'yU\14¦#xa\5´€Zµ\20ı\11Î\1\24‰À‰–-Œ+¦’ÙäJ¬X¨æ,\5Í\23\30©\18‰Ø\20\11³¾äô&_U×ª£“Õ¿²[Š•!Ä¨!¸KÄ‚\15\12$rè\24 \22ËšZñ\13û«ø€Úoc\7¨ò÷2²¥÷B\7ƒPòª\14j\9\7 ãQØ\21\1\23ÕAN„´Æ`r7vÆÉ8\27w#ÍÜ\17~ä‘ +ìœ\27u­>¬#\"\18îÅ\13\29ıx»\28ä\6A±P…Şg^¸;|Y\19@v\29m­âú„4Q\31†“ZYRs\16r¡_ÔÖ/jë\23 \25Çã_æ‘\"\15ş_c+uü÷#\31‰°<\20(_Ú£®J<0×/Ú—LT£NrB)âñû\4ô[\1a5\8Gc2êpªQú\0176N¯Yx}É^ëB[ãµÆ²-÷Rg¯M!\29CøÚe¯A¿\28¾ôÚ=ş•úòÚck\
¯:K_å+8Ş_½¸ò×©n³W¶mx³×™Á\9¯){]ĞcÃ«vÕkxüÎN×,\\_²kY I\\µ²ë-.E–_›\0110d×F‡sŸ]‹.J¡¹¢Õ\\\21ªª\27£rÄ“~˜\16òëT¾f×…\21!Ô”_Ù\19Wï‰ë‚„xeI\7\29u·²\16O\0'PBÖÍÚÜMç¥İ•¸¸ˆ\14‚\27J»Ğ¼TA[•İÂY?© 7¹kçÓàá¾‹¯ÜèÈ\13áÆåÅ­)44·&×\18•ûz\3Å×Â­ÍŠ['6‡µ_™óN\2Q¸‰\21\20rÇ\23BâÙ8\26WPZv¸q†(ïãÍ™\31o31H1\4¾·”\"æw\19Ÿ\
7‰üREÔbp-ƒä8¹%PJìşúQ‰HÑS¢héùöÇ\\^Ü¢Ä P’“Év\16->S¥¹\5¥ŸJ\9ˆj’ÆH2¢Ê±jqÃ¼® Oùmáì•;iK¨EjÀV\4X‘…Ò³n¨†·-p<)DÇË\13\9*Ü”C*R\0\
\29X\18\5<[’r²Ğ¼d„œ\6­Dp\13™ÆZ\18LƒÕE\8ßi$ö4ÒŠ3©Ö'¼jOƒ$ó)·²UÅµ\22’@\18ºF½Á¦ø¡H­}Á\0¨°W2_±V7R\26\26pÖäˆKMÁ”5¨{Í\13k{“7ä¼g¤’Bˆ\25\15Tª µ¦i5ÓFjkµD¥óé\12k$Q\17~Ø\24\27IVM‡)¾é\0261\24•^tÃ\"ß’+R™$&”F²ö‹\18hª\27\4İfğˆHŸìÁŠ¦ªá’ˆ^k\2´\6ÁÑ8\27\19I\26 \2\11°\1šnğ\23¨yÅıNçÛˆGç\19AŒ—2FÌMĞ|6\12×„\21¶9ÍjÑœ_\4,†Æ'.J–ƒµÃÀx\4MÆÅ¸\26iÄÜ•öH†\2iÌœKŞ\0\9ÒÚk0ºu\0079|ÔÄMO3Û”¥f¸(úCúD\3S1İŒ#8×FÕ\30¤\"7§E£‡éª‘>Ùèø’\11óS³{\29¹ ,N\5\28æ(u\7Q›Â×ß¤QK1fÔ,ÔÇûÅÈâĞØp\0024°şÎ„ó¦÷7æıy\127ó|ÓÙŞ`iŸ\14²:&ÚCEò,ÆÇ‘“®²9äş,.ë³1:Ã§3|¢¦Ü_²{\25ÎAxÑIt/‹Ë\127„ê´àšIĞnSv?‘à¼i8•C:ı=(^ÇóÙØ\26gp\2Tîı\6p·¡ün;‹¤óWà›ü»­ê÷+÷6*QJø½ÉîlK¡X\25î^¸ëH*åA#¿3OQ$ì«š$6x§f\13ˆJP\0141;‰ø% ²úˆd\20îÈÉá>d÷A¢ªÄş3 ÖGô*Ü7`TMQm‘Sıˆ˜fïAüöG©\
EÉ\13w%\27ãT€\5\24éä^Ğ€\94Å\5l\15Š7\9µÒï3—a÷ãVî^\28\
+T\\áKŠ•\27[É…„ZÓÄsjŞµTï¨´÷…Sän=öh'íeÆ5`\"\4¸;\7œœß\8ä¦T\12ãâ\5\16î«\26ˆ\20'ĞQsW<ºë\29İUÀpJ½³È¹<\14î\20\\ø®Õ|º{BÑ<ï¬½Æ\30)„á¸q·œq?d\11\8\12ú.8é8Ò0´>e[¬¥BNY1€;Nñ\1ı4iBXL[†1ï\0142™Ìä\27W»5k­Od!‡E\28Ö\30\"„Ü+p8RûÇµÂ®B«µÛjí¶¡ÎÚÚí‘B\24q“QÒ\11F·ĞJ&j[%¤™bò…¸µNj8÷İ\30M/—êg‚$¬h\19kç«'rD§ÓB\
\"\27nÎéÖ|\11ü×ø¡h-Y±\127u9Hùh‡RÜ²µZ&~ø*'\22Û6\30}6k•\7–ÖÆ…\29¡T¸sn\19Å\31b©Ò¦x6*û$1¤tš¼¨|Z£µÔ&Mj»°\31Û¥x¥à¥¸1Š’+Ú…»ÖV\17p!R|´µÔÔêØn‹uÒ,®¬önAÛF\12,­í¸(Æ\26aÉÿcgÏdT|h5'-\18±@§y‹ÅV5\30\11\9ÅYÔ8Ÿ\24åÎ¢XÇ¥ õ¡á? &Hª5\13”g\21³\20ÙÈ\17vÉ:ÎzÁ\5¨²®â´îê¢¬Œ‹PÚn\18á°îêĞ¨>µ¢ó\"\16vÇ¸¢ \14Ï …Ú¡Ü’{ä$ë¼L:/\19¡”êÎ–Hp\21&\12*\"9A!9)Fn‘¥\5×›\0177öN|PÛ°ÓZë$\
w·,ïnÚå'Š‘$³ƒZ¤à\
V*¸\25$ShÍE\2§DVmÔ\14…3tb‹Ê·vÒ!mt-7y¡ë\24\20ÆH=Wˆ\"´ÒÔÄˆà\
ÎªW‹VÁb) J\127g^ØE÷æ°\3ˆˆ[uX\3º(½Œ\0Æ-tÊ\22¸–WEâ„”eÍÜÌPÏ© Ú™ƒX±jZ‚õƒ‹qËºÅ\13Y\
\29IÂÖHW,¾ƒ*AŒo\2×ÒØ\0257£KÖ2íöìä\13'°\26ÊJQ½˜ä´\11YfHÉİaæ†`·\19e¥vÈ¨\29Æ¶ÎÌ®+Ğ®>\20/¾}bãê'…1t–AÕ¸“N¾Dôïm\19ïı‚©èË®’›Ús\19G8Úu\127¬Üë-ågÍö¬Ùş$µ¶\15âŒ'\29\13y/¡¡¯‹k\0045;}í«½\30¢—b›kK÷¯Yï·B'±Ï¾ÁˆÓK¢TU\13G@èÛ ‚X\6}Ë\5@ï‡@½¸\26Â£¶\\¯¼}—ß\4ÅÍş\6§–6Ø’l!xÈzNŞ<\
ÍïF@<Ü»ê\24¢\6£·¸Ø[\\TÄã×\7Ëgo\25ñ$- çí\16\1ZØ\2*&bÕéc‚™\20:¼“<{Y\8­|÷Q'ŠÚ1ªÜQb`ï\13Ùs4ô~OÓš’\30–§qÔêëµØ<ºIµ.Y¿ Äö\24Fä\28^Œ•ñ\8™,“~1®Y¿Yâ”\18íåİÓM\22–€»\"\17×¦EÕ\7„7‰\26šÆÛ)–P,×‹Áq7)šë¨ìıF¢Tı\24íÀÇ‡\
d!Ä\9\8\0314-\18ßÅ|\6¿\19J Pˆ\3n¼W øâÀ=}g\12à\0122’C™\28 1\247I\"»`—”§$»Ú&òõ—Ë³Ç\15XÂ Õ8¨\27Ò\29n\23œªª*nPÛ_\24´\6\0212\17r\8yCM¢šëw9ÕÌ:ç®g¨Ã] éÅ¸\16Ş’„£Ê\21öÏÀ¥¨€Ö×n}íÇKxÄïåÓ\25¡x:#&;á^¨2_cu\17ê\29VÌÓÚƒ \12¯Ù¿ŠC\14×l¸JR\28®l\5°6Ò…âJ›®<å\24¤©É\18@'#\15E\6±[6D\24\26&òç€W\5\6­¡AÜT‰ÅyÆ}#¤¸á.š\9¤\28ÊI¡Q¼NáĞ·‡è\30ÁN\7›U‡?ìÔ;Jå3*A*Ô0K\24\23\"M\14’\21/„HT\28fóR¥T«¹+Ì•VG\17«&aùÃä»\24‘ø‡åœ\13\11×]Rğ´µ\7-kíZ•üxó\12ˆ]Î„[ğ\27$ø\5i|«Ñ\13’ü\18\6Øã`ö8üyş#M0\16¡$\18€¢ÔòXj@å’\
+¨³xÖ9kœ»P£\23QË¹ÚÒ¦QºEîmV¾3\9r\14FßïÊ§u\25\11nZ£¯%\"7¤ÆH¸ÄßxIÚáñ²å\4c/\21·9\11|ùÎ\11ÄÑ¨\6ps\17µÁT¤ßmFÖwKz\13f¬lÏÂ#¦\31§C‘»ÈµŒZR‡,ÖÒ\4Zœ1ˆ»Dì^*èª¨üªÜÚ\11Ño8ãII¤İÈ%…&É¯q(î¥ºp¼ÛDÒkŒ’è ‹‘ºyş#÷²k\\µãc\27\18\5*OÇ\19J\11Œ:Ù£\31îÄ>¨f~ğëh~\29Qş#ê}D½ƒ\23LDËhùÑl;şy´é\24âÑš~´Š\31Í¾£Tü¨UÍ\0ÄÄ\8ü1îÇÑš~„\29G[óãa\4Ç«8\"í\21\7E¨Øø£Z¡vMˆ5\17K\127Äd\24±ôG?Ø‰˜÷\21ÏÕ[ÄÊ\31må¾\12Œ¶òÇãNôÍ`ÄÒ †”*eæ%@œ%3\17Ü\18Œ©\13¨2ç–©”›â Î¬Ñ›a\13`c$|Æv%ç\4\27?x5ö™ŸšN$Jn\14\"Î/“çÛásÉ4]ıñ‹\29-3—›x[\21mèçEªÇ:\29È\0s\18²°Tëâ›^\20Z\19N2asà\12JZR4S'I³³{2Ò?Œ q\25Ù\24‹MÒÏNÏhYä'¤µ›”EZq\3ÅêJV²Jg§xlúñĞ'ãÚØN\26}\13\16W)\4jğ\
Wˆ§or²wÅï’q\16\21Uënû\0„¾\28v€ˆYŸ'¯’\127D¤`+Çà†$w ¥\0öùÎÒßé’„¶\23\18\17È¾¶-\31tÉ~\25Ê\3ZG³öc3ï,Ø|g6w‰\25òK|\6½´ö£=Nøü‡5\4\31Ô2—¤\18mõW¿àTùó\127¥‘İÇ„iº\2{\13æm\22¾\28ds˜\26ıÇr\15eE\29ªO4ûd#>?IóIÜIºêø’%ïãF¿Y\25-YV}äNÄ&Ná0Š+Ro\20[Wu»¹‚Ã(œš\\èwğ\
BüÌÇZ=\26\27dT!ï<Æ6\27\17\18GÔİ\17uw´º;\"\25–\12\9i ¨·a\28”VìcŒ˜†Æ˜_$gQ•ÖjqÃÁÁM\\5-\7QçG#Œ±\19ƒ–³'o!¡N\24;Bì¤ëÂâg’ğ\4AÈA©4É¹’\19¥\16iWãñ\28\1Â-ºâÙv§a<qõ{ì6;ØV×\18ÌÈDéˆ\27Gup¢ãS\9\3\26§ ±â\9 £“[(L…ÉN’™LÜëZ_ê—Y¦E{B¢©–X\24UT‘¤i‚“Q­óô<Ä\27y‡­ZıĞ{ä\14.\0277>Q\24yM/ \25·ê\8)†Õdfæè3\22Æ[\22Ìjá°\0121ä~\16Ú\
İ\15âqĞbÍ·‚Œš˜c9Êı3ûÏ¢“\\‚Ã‰¡˜¬ŒO–B'/Eáë+¨ƒ\24tøıjDt$¦È=Ü²ÉËu*=s\
ZWğ¿Î¶¹è-‚_\127÷™\14\3xÊ$V1\5)½“–õt)ólÊyr5ù9Â¤³4U6™óL\21ÊÃd\21\127²Š?Õ\21uùÉİd\19”X§ ˆ0«‚š¯'¦ÚO£&‹”Š^Ô‘“«Â¬?a#˜x” ÿ‚KËw’&~Ö¸4j[sáÒN!ÕÕ8bÍ“ïx„X$&\13\5;kBLœtJOE/Y2L*{8ôÀipŞè>Øú3E®#ä¦+Ør\8Ò¤*v¢ğ~\6[2ÇfF))\26\7N]Íö\20İI\14¶õ .`Æƒ´\2R¾\19ò¬T||\0Á{Q\29N|yP\25)œ\15 p;?Æ¦‰\23>c6Ù8\18&µ~âM\23HßNj\
Wâ“Î?\16o^Å’M1{M:\
§Ô\31-tJK\24Q¦´ä\4SKâc‹\19Ï\12'ŸO“MR“^ÓqöäÓZ\"ŸL:h$\26(åv¹©€MgÈ´ùŞ\0¢š¶bo\3È%ÙôG£›ölr?QÄ'¾–1)*Ô±\9™XÀu<\30±ø‰£ ˜¤Ï%Ô¶É²\15Âˆ8\"ˆÃÄŒh#¹a:=¤ÛX>I¥½ÒSS\20øø 9AÇğ\\\22ã«q\18ÒÁ\25sü¬\29?ç—\18¨•ŠO‘f¿¤›ı.\23‰#±Bš¢Æ©ZçPe'ØìÍ0Ã\
fŸ\7 2[\14–[+W\3K@Ù\9›õÌKÇ’\16ñÜ™w\17$”\0026ûıBù‡.\7ÕpÌu\"aZ£CŠeÂ³\3\\‡YË_¥=Í\\ûÊÉ½¯&S\19z\1\20í]3s·F²F¥ñ\9R;©Cwåº«V\29ÀZÉ¥ÆE‡ğáîqGÍäÜÆ!\19h;+<*[‹ˆ\11.ÆğµÆ½ÆŒ—\29â×³\31ìä3\7Şì\3\15ñoUxWÛ­Ó\23wo\28Œ‰ğælD±WîÁ¹u,Î¡ÛH¤Õ8û9ÏÌÃ(\12ıÌªÎõ0«\16^3Î\18ÎéÛÀ¼\13T6py¤\0í\7?(§~-#fSí•z¤X\27ìf\27‚…’Òf\9b7ã\12î\5á,íY’\24÷\8Êtˆæ§Y\
0s9\23v%ºœè±\22§F8$©;bÓj\21/X\24äT„è¼Â-1Š'€ÜßK\27ïì\25˜…Ô\28ei4”\28ƒ‰\0180$‰\17‘tÌõ±<‹SM\7zæÒÔ¸€É©'LÇ0\12\16Í\\À©ò•U\21³¹¼­#hÓNS\"\12ß³ÏN?­Áv4'^\13û\14»\"å×\27)¿~L\7ÑŞO¶CbtF›¢O³VŠ?}šı¹Ó¼ô¥Æsá1à\28Ôš-×¨l~.5o–mf\29ÌÔÁƒ\17Üâóaæmúì÷è'\30ôŸfW…AhÖÑ:çèÊ'÷Ï6\31jğNÌC*9ôRyÑ¼Æ,\0058ë‰©I:U_×Œ+Î\4\14ª6ù²$Jx*uĞ$ÎY¡Í\
©ôë›0/&¥'vTÒRK5\31\12\
µë’ß|hz\7\30§ZëLÈí‹f|Æmæ•\28Áåb<ÜÚİéU¿«Ên²Ôğ%aHÍMNÎİÄµ2Á#nŞírÜRß´+¥\14‡Ôì:ã´–»Sc#ŸŸN…Ô†Lú’ÄÚ\"…V«3Ù¦\24ådcf²1SJ»Ç! ë\4m\"mZd‰íœxz—:u‚PuĞÛ4\21¼ĞMÜ£\11´9\18Ï)Òñ,W:]b×\6­ád\13ø$ı:étV:m@\1{1!Ï\18,é'ÙÄ\19RÔdI\29'\29Ò¬–şøbLÆ…$ZëÂEò}\26UşT\14êR1Õ¥Qó,9„ä’.ÔĞ©\25\11\"\26'ŠWr¨ää3İA\11iãr3yşú¦…±Òa)·ˆÆÒ–\31Ø\20›\12\9-éèÊü¸¬?ÈJ\24gsÒÙlbJ36î¤³:ùó“dqõ”´Ó‚\0(ç\29gÇ*S’Ÿ™é\20\23³MV1…ÏŸ\14âÄNZ´›8ãå-Öf\24LÔ$‘Ç\7‹T›<mÅU;9m|î%\15¯®Ln\7¹\31$\30d:ˆ•ÜŒ@à•\29ÜEö¡vı_GÍ¯~ì3>té\21ÂÂùú‘sğ\7s\
p\24LFr¼‹'/\7©\29&¹.ñ!\2ÈÄÓXZ©Å!DnLAÎDÇœUùHDl^ó-Ò‚…ù<ŞœññÚ€İ Ù°–\14‰üÄÇ6'\11\28`oT|~£´Ë)\11š’%ho,áœ-¹8˜ \6\26 fË™ç0r.€j\5ÅúDTörñ—°a\17/[xy·ğ±İÂgt‹u·…\23x\11ŸÇ-V×—šÛÂòª\
¥\2,<=zƒèü^‚øÉÂ×k‹ÎkL\18ª¦-ÄÇÀÎHSZUÃ•ª‘*[jk©G’›R1•‹Ïç¥£º¥;İp¢Õ/AÅsÕ/ o¯ær-\0º½½á]x!»\4µÉÏ`\22,a‹\27Šõk±¡kñ6_lèZø2mRQ\1#5ŒÊ0ÖaÊq3.£v’Ü#C2z@G\23äÖå#\5\5•‚)qáÒfAŠ\12\11Æˆ%w\19\17Y\23[dO\11»q±qb‘6³Xx],£\28ä×A>D¤F,\0183(FrÁâ×¦àf$¥\15@¢Y–ËaˆZ\14C\20WºÔ:ÓìÙÍİ`#´Îh$B{ua—\
ÔÚ°Ë±Ó]AX`\22Ì.\11V”Å&“%¸\15|’µø“¬Å[oñGX‹\5åÅŸb-Ç§XËñ)ÖÂ3™\5{ÊÂmÉâ—/‹_¾ğ™mÛÙ\19ñØ6¶øµËr¼vY×.\11çèâw.‹_¸,~á²\28/\\–ãÛÆ“xÄïÕ\15\15V\20ÕŸ\16Nì•\19rÕ\9¹\6¤›UÛ`-*­Õ•}°òğ´=ˆº¸Ö* †Üu\4¯\18\
×ZkEşq\22ú.|µv¹újxå…0Ñ\18¶ ğ\9²`ÀZıŞemª:àÖy\"”€¹Ú4³6Ü¹†Uu\7¼¦ZH-VÄSPŒhEàZq¨)Å \29rå”Zu&]À{itÈ½2Ş½‘Ö B¯Çİî*Q\18\6°Ò-ì\31\2Y±NÃ–­\24gWô:¡_W‰\20VïÂJ&Œ\30+\"\27\3©D\8M\2)eëÆ' \"#nt\12…H\30^7˜“B\12\12ñ†™M„;†\21Uíå ıA´N Ÿ\26â°+…¿y\6µú×ãYïz|ô¼\30Ú›ZB±ÇÂ[…·ú\11o\13«´ŞK\15ÑÔ¨uğø\28\"}Vºİj6¿\"½­¶\20­6\24©ÕÁ­ã\1üLà›eI¥ÿ÷ñ‘;ï‡ô ÕŸcü·,^µ^ş[N8Å\16ş«9\15ß^²o%×ùáÛkö­‘n\"—t»oqÍ¾éàıf;ı7\127/·²-”úéôÚüÍôÆrİüñáÆ×DÙæ/ŒğL¸Å`¶Pë'±lãBjó]ÄvçKüÍ\0187„©Í|x“È&…ró\127Dl½të_…(;dó%ÂÆıÁ6Ö\18×¶‘O\0096[­T\6ÏS6>\24Ú\2Éf\
“\
º¡³s…ºàì\8¨\18D\11”s%²ihã­É†bƒ9mfN›?ˆİÌ¢¶äæú\25ú–¯ªæ0Wl<_Úx¾´ñ|iãùÒv¬íX\3\27™6\127÷¾Ùˆ»Ám¶çwm\18a+]zûóøn;Œ\27œh3'ÚÌ‰6›tµ\28\25c³#p4.Fr1Ír\127Jlß³°¿d{É«Ó½äFPXµB¸\15î\1÷\13h€;w'\0Š6\9»\2w_8­6Íîëİ‹İİ\23»;\6`’/$×ZÛËİ©}»»\31·»»ow÷ÒÿS²ó\14JB†\6m?—C‘íá¼ÉÉ}[Øyƒ°‹ûíğ½½Ò z\4w>?+\15Â-ĞÎ—[ jÙ®\21¶ce\16¨Å.E1á¡©æ};V‚½^\1^íX\7öºĞ\8©¶×l·am—\30¢’¤ìï9ïÌ\20¥æZ|Ø9\14w\31ƒ»\5‚İgaØ%Æí\18õ÷'Ë\"M›+\14í{\15½¶×®%³ó™›@%\20½D;\
Ö\14Û\7©@\26,qùİú7\31\23_À\8,\0•\14®”åäEåÔ\30’ÇÍ&«Ã4,ş¦vÿsy»‹{îùH\26lrª\17«¨Æx¦a\
Öa+­d?ÛİÖ\19¦jˆŸJƒTŠ\20ó\14a\14µÃvşLBÉW\30·í\28ĞûÚˆmì«×¼B¢£¥ŠìÅ\26\7\"Ä±w®Ğ\6È×™øÇû]Õqı»k202\11n\1,xî†•oÄçy\20q*\127O»‹—îşÒ:ìÚI;Ï(w4h\6ß×´&¨\25;\25vïıøçˆİ’­F‡\23ƒûñVp?Ş\
îş„MM9\11àr\18‹±Û¨Eg\12Ûj\4\22àÇÛ%—6IÂŠ„\21\9ıo\15\16¬\0188¸QŠ[I¶[-¼:»;JBD':\26'£¦AäN}\\¿>ŞÄ!µØ< ”é¿[PŠ®4ÖF\23Ğ-Fšê7~x4kòõ\14ë0&Ô¾#JKFsR\23+q“\11(t’p‹ÛEO\20mÉP\30º\24æ‹Q|âñæ‡Ô&İA\6Ç¹…sá\6…¹·gŒö$ar^?«Ìä¶§Íx´,¹e+,ŞÄ¡»3ù\19|‘A’\11”ç\18*VË@Ù=ä\\ ×\127¨[\0133U¡pS\19ö6|é„¨¨\31—\11\
8\3X)`Ä\8/Š¬\21 ¤³'+rX4$KÂ\21 Ñ¸\0247\23Ğƒƒ\2°¬=å\28\9œåB8‘\11Û\1dvÍ:ŠüùÎ€\25÷ëCt$“æ¾¢{aÍ\\3>í‹ Ğ\"U\"Ñ,Wœ,V\0\8\127'ÿÃ€„[:úw\9¨)\127\31oz¿şÖÙ\127ı-õùñë¤Ÿxîã\23L\23Œ\4¼â|ÅÉg\7\
`†\127\5COœp°6:c\31‹Q•\23_<;W†\25H„'çJNÉÙ­ğçŸÙ×\15Fû\7³$\12iç€µQ{Fº1¦=È@Ò[tÌbTm\"w²ğ5&èè»#´:µ\1äm\25ê\31Ú‡‚‰Ä\19F.<Î3‘‡/ü„ˆ„\4-ÆÍèÂX\11 H§2‡\20åÅ>\23œh>†•ÌŸIñÄ»:Š\9ú‘SşëG —„ ;ºvF·}u×¸\19şúÌH† İI¥\7}ıØİ\0124!Ğ…²\11”òI6/z“æ ñ ËA\30\127Ò8ßñ<\12Z<\127Î.â§£\127F{>íù<Êû<Êû<Êû<ÊCËy¼Ã=ßy.#rğË÷ËMƒùxGBTüM€Öşx7\19|‡ã½û;\21‘ƒã½£o(ÆéÑ¢U”yØûÁÃŞO–œ§¤æDï\7\11z?X\8\\–P\31>\7ú€Q>\26c\30ô3\23$Ùù£\31“ÃçHÑ&æ9xÙxª\17nónnóîÕû~0—w³I<\8\27\20É\29³Xà¶^?î«ÿk>ãò~U¨8«ü4ì_mÇ\1275Ï\127y·\0006Æh\20á$z~/16@¸¸ä=ó\25¼\0UÆ\29«$s^ºğ…„èÉ>4FHÛ\29du\18ÿ\27\27®(YpIQş\14üå íA´\0Eù+\
,K³SÎ:P\15\26¡ü\15\2q¼\9ó\31a\28å¡x\30tùC5£‡Ccèûa7Èš©¯‰fJœÆ¦µ\31­å.çù½9\1Úu\\\31Ó©†\11I“Á„ï\4 İ\17ÚÑı¦“Ä¥¢\16ğ„\18(0‡q\127\15Yÿö .FÒ†Ğÿ\30€Ïíj¬\7ªó$\12\30C\27Mšƒl&|•øüÎ}«ĞÓ3h\29|wh\\<]£ã\24EÿS\28\30ª\
\30]*?^°Cùú—x\30Ã1U\12´ÃÖb\23\16üdD-Úà¶Õ\14ù‡\22?ßÊs\14ò”F!b²Z®wIq\"ü±‘V-\23Óè“êÚ\27xÀÚÈGÇ\5\14\12½’£´\\\17§4³’GÄ0‰Z^LXœojó\27VS°!¸kV{H*å0Ø£½lòá\6õòô¼“’g bt0\29£CtG\11ë\13óûA:\7b\21Qâ„DyøWÓÇ;©\3\30ÿÍàÓòÁóÿÏ~¼?íı\25\15²\28„3”çšXŒå-\25­ŸlÔŸÌáOµDIl\0258=~gßá\18@\29¿­ÑÊİ\2\0290\0# Mı;aÏ–{\5´¹\127›ÃüÆ*?~#qğÅT\18¨§O‘b¹Ï\127ÄN\5\23@<S\18*{ø\31?ÓÓè)T\28N(9\15\20s\20ÑÑóüÇW©&Ò¢\127şƒøåÛàú ˆäÏ\127\18QybTÿaÔşÉ“c\8t™j´Ü;!G»|\20˜4\7Qÿ>àı\31\7Óÿ@8şà¯Ipß€;Ğ\1ı°ò\15Fê\3­çññç¿\
\0215\1j²¢%1É­AüHÜ\25›l\4áÖ’nÈ¾·FŠ*ö•\24¾WtùæÓ\31ş\8çÄ­ÎóS«õ\0196,ä\
“¯Ô¼·>1Ã\9/Fâkş\11I„ƒJ¤P»!ûU„‡g&wØøgcOğ\22ûÔºü´´\0300\18=?\11>ĞáyUtÑ,§OJŒCpÀ|\16MÎ'\19ğ‰Æ1\29t`c~ÂÔ>\4äó‘òÉ–ÿ<\22ËA¿~ü\31#\1³\4",
  ["length"]=21736,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=3636,
 },
 ["version"]="1.001",
}