return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="it",
  ["source"]="hyph-it",
  ["texcomment"]="% Italian hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% hyph-it.tex\
%\
% Italian hyphenation patterns\
%\
% This file is part of the hyph-utf8 package.\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
%% Copyright 2008-2011 Claudio Beccari\
%\
% This work may be distributed and/or modified under the\
% conditions of the LaTeX Project Public License, either\
% version 1.3 of this license or (at your option) any later\
% version. The latest version of this license is in\
%        http://www.latex-project.org/lppl.txt\
% and version 1.3 or later is part of all distributions\
% of LaTeX version 2003/12/01 or later.\
%\
% This work has the LPPL maintenance status \"maintained\".\
%\
% This Current Maintainer of this work is Claudio Beccari\
% e-mail:  claudio dot beccari at gmail dot com\
%\
% This work consists of the single file hyph-it.tex.\
%\
% \\versionnumber{4.8i}   \\versiondate{2011/08/16}\
%\
% These hyphenation patterns for the Italian language are supposed to comply\
% with the Recommendation UNI 6461 on hyphenation issued by the Italian\
% Standards Institution (Ente Nazionale di Unificazione UNI).  No guarantee\
% or declaration of fitness to any particular purpose is given and any\
% liability is disclaimed.\
%\
% ChangeLog:\
% - 2011-08-16 - Change the licence from GNU LGPL into LPPL v1.3.\
% - 2010-05-24 - Fix for Italian patterns for proper hyphenation of -ich and Ljubljana.\
% - 2008-06-09 - Import of original ithyph.tex into hyph-utf8 package.\
% - 2008-03-08 - (last change in ithyph.tex)\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="'abcdefghijklmnopqrstuvwxyzâ€™",
  ["compression"]="zlib",
  ["data"]="xÚ=”A–«8\12E·âYfœƒó7D\12\24\
c\\Æ!\20£ŞFo¯WÒ÷9¿2,\28½+ÉvUÓİ“¦éb™Û÷r_µñ˜7¾]÷'İwÖ9»§]µ³Å’õS?Ûıîæ8˜f°g;<M3æ.Úå®`\24XÂ\12|ïL\19»ì¤ÙR©K.\27¿˜&u¹ã;m5“ \15ú´T$¢€Ë¦Ù§ÎfáŠğÔüDı'\
Ÿ(~¢ô‰ò'*àöq\15Ï¿\1?½:ë%{\13Á–ÖØ›5ö¿\127şµ¦kçNnÛä¸§¢ŸÎØ®4fĞŞ`_fSî¦ÜM¹›öÛ‡±\15™ÃzlÄV,b\9Û±‚\29æa\3–‰\27ì†Ñi\17:\0N+\0\7À-\24\16\7Ä}c@\28\16waÓdœ\0204r·ê!½¿>Ÿ¿;\15ã&\21uSD\0230}è':pê qÖ´Tîé¢×ê±€ÑAO\7}2½D=]ôtÑ\31Ø\11\3Ò\3é+¤\7Bë#\17À¨8š‘Š£Ä#â\17ñˆhD4ÖÙIô\8<U=\2ïg4Èú••ê>±\2ğ\0<\0OuOuÏYøÉj\7¤\7é+’“af;ä¤¦¹>ıIÄ‰y8\4;A› èü&tSÕ}\25ûÅÆ\23\27_uƒ;Xèo\25Í¢ã^\22V(ËÊ\
a¡Ÿ…ê\11¢\5ÑRE$\4ª\7.3ĞA¸<´àM\0\17,5\2Ø ,š\0094\19x#+\14 \3È\0002Ğ\\`ÄÀˆ\1|Ğ¥†÷…†Ûí\29×r@VÊ­”[9¿\21ğª=À+à\21ğ\
x\5¼\2^\1¯€W@+œµBH@\"HÏ\17PdğH§\17`\4\24•\0030\2Œ\0ãnô—6\14Š\1GÀñbO\127d6NÃ¬MªDªÄZ\5uêMâ\28’1E£›\25ˆ\18;pÒ®}¦„:1|‚ ¤J ö·ŒÍo6¿ë&ÂLó\25U¦ù<š¬ÛÊ\12\25 S*3@¦­L\11\25@–†\19É…ÜÂ\24„ôŸOŒÃÉ\20ÎÔÈÔÈµÆÎ\29îz=»Ì®7³×Gƒv7ûŸı®ßêC³{yÈ9¹^n”órJ*5%ÉírEâûeşì\13v“«WM|{Çµ\0092…\22Y`qÁ\22†-:OÑ\5‡]8MÆ2wœã,(Rl¡S«JåÅ\23#–k1å²Úe¨¢'VŞO¬è‰•ßºH\14g\14j\28º¥Cß$\29\18\28oÁ!Áñ+x™\23Mñ\15—ìWûƒ#åEÆ«şÌ)ŸÌq2ÇÉ\12'\13ô~r&'3ÜÀ‰àDpJğÓnOÜlZš¾P^L\1271ñÅ´\23ª\11ÕÅ\24\23]ÊA}©»ëİİ¥î®¿İ5—ı\31Âª,»",
  ["length"]=1806,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=377,
 },
 ["version"]="1.001",
}