return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="agr",
  ["source"]="hyph-grc",
  ["texcomment"]="% Hyphenation patterns for Ancient Greek\
% \
% (more info about the licence to be added later)\
% \
% ****************************************************************\
%\
% File name: hyph-grc.tex\
%\
% Created:       June 6, 2008\
% Last modified: Sept. 12, 2011\
%\
% Unicode hyphenation patterns for Ancient Greek.\
%\
% Author:        Dimitrios Filippou, (c) 2008-2011\
% Licence:       LaTeX Project Public Licence\
%\
% This file was first created by mechanical translation from\
% GRAhyph5.tex via \"elhyph-utf8 -a -c\" (version 0.1 by Peter\
% Heslin -- p.j.heslin at durham dot ac dot uk). Some additions\
% were also made by hand.\
%\
% Created by Dimitrios Filippou with some ideas borrowed from\
% Yannis Haralambous, Kostis Dryllerakis and Claudio Beccari.\
% Mojca Miklavec adapted it for the \"hyph-utf8\" package.\
%\
% These hyphenation patterns are explained in \"ancient.pdf\", which\
% can be found in the \"elhyphen\" or \"hyphenation-greek\" package.\
% Hyphenation examples are given in the file \"anc-test.pdf\", also\
% to be found in the \"elhyphen\" or \"hyphenation-greek\" package.\
% Questionable patterns are marked by three question marks \"???\".\
%\
% Documentation in English can be found in: D. Filippou,\
% \"Hyphenation patterns for Ancient and Modern Greek,\" in\
% \"TeX, XML, and Digital Typography\" (A. Syropoulos et al.,\
% eds.), Lecture Notes in Computer Science 3130, Springer-Verlag\
% Berlin-Heidelberg, 2004. ISBN 3-540-22801-2.\
%\
% Thanks to Thomas Schmitz (thomas.schmitz at uni-bonn dot de)\
% for pointing out a few mistakes. (Marked by %%%TS%%%)\
%\
% ****************************************************************\
%\
% \\message{UTF-8 hyphenation patterns for Ancient Greek}\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="'Ê¼ÎÎ¬Î­Î®Î¯Î°Î±Î²Î³Î´ÎµÎ¶Î·Î¸Î¹ÎºÎ»Î¼Î½Î¾Î¿Ï€ÏÏ‚ÏƒÏ„Ï…Ï†Ï‡ÏˆÏ‰ÏŠÏ‹ÏŒÏÏŽÏ²á¼€á¼á¼‚á¼ƒá¼„á¼…á¼†á¼‡á¼á¼‘á¼’á¼“á¼”á¼•á¼ á¼¡á¼¢á¼£á¼¤á¼¥á¼¦á¼§á¼°á¼±á¼²á¼³á¼´á¼µá¼¶á¼·á½€á½á½‚á½ƒá½„á½…á½á½‘á½’á½“á½”á½•á½–á½—á½ á½¡á½¢á½£á½¤á½¥á½¦á½§á½°á½±á½²á½³á½´á½µá½¶á½·á½¸á½¹á½ºá½»á½¼á½½á¾€á¾á¾‚á¾ƒá¾„á¾…á¾†á¾‡á¾á¾‘á¾’á¾“á¾”á¾•á¾–á¾—á¾ á¾¡á¾¢á¾£á¾¤á¾¥á¾¦á¾§á¾²á¾³á¾´á¾¶á¾·á¾½á¾¿á¿‚á¿ƒá¿„á¿†á¿‡á¿’á¿“á¿–á¿—á¿¢á¿£á¿¤á¿¥á¿¦á¿§á¿²á¿³á¿´á¿¶á¿·â€™",
  ["compression"]="zlib",
  ["data"]="xÚu}Ë–ë6²å¯xV³\\ë\28»ÿ/ÓTJ™}g¥ïuù®žUu×c’J™(‰\18\31ó\30HßpúKš\17\0b\7àHÅÆFD\0\4@\0\4Á[ûå‡[·üNË¯_~ó—\31îÏËïuùýÏå÷\31_~ø><Òá‰\14?Ó¡¡ÃŠ\14ÏtXÓaC‡w:üJ‡ÿ¤Ã\127Ñá7:ü•\14\127£Ãßéð¿éð\127èð\15:ü“\14ÿ¢Ã¿éð\7\29Z:\4:ìép CG‡#\29\22o¿äÕH^äÕH^äÕH^äËH¾ŒäËH¾ŒäËH¾Œ¿Óá¿é@^äÕH^äÕH^äÕH^äÕH^äÐH¾ŒäÆx¦Ã…\14Ãr˜È¡‰\28šÈ¡‰\28šÈ¡‰\28š(›&Ê¦‰\\›Èµ‰\\›Èµ‰\\›Èµ‰\\›Èµ‰\\›Èµ‰\\›Èµ‰\\›Èµ‰\\›Èµ‰¼š(›&rm\"×&Ê¡™Ü˜É™Ü˜Éƒ™<˜ÉîL†f24“ú™ôÍ¤o&}3é›IßLúf*\31\31Ëo»ü>—ßn)\27¿,¿·å÷m‘—4Ý8‹èÂ\20y¤Ë5ò•êép¥ÃHº(Áó’š[ûõÖóqGÇ…,§#Ÿæßù4ü!§ƒœ‚œ„2´rêä´—Ó¢åãÇEñâ\11Ÿ¦#Ÿ†G9=ý(FïÏ||\19›W9]Äô¿Dz—ÓorúO9‰[ã¯rú«œþKNÿM¦\23ÅdšN‹i:-¦ùôD§[Ç©î8Õ¤º“Tw’êNRÝIª;Iu'©î$Õ¤º“Tw’ê­¤z/é|—Ó¯?Š5±LÉí$¹$·“äv’ÜN’ÛIr;In'Éí$¹$·“än%¹{Ià¯rzçtž¾Æã\27\29ÙæIlžÄæIlžÄæIlžÄæIlžÄæIlžÄæ§Øìø4¯Åæßäôw6=s\22ÏœÅ³dñ,Y<K\22Ï’Å³dñ,Y<K\22Ï’Å³dñ,Y<s\22ß\127‘,îå$%j”\0185\127\21Ë”ÜY’;KrgIî,É%¹³$w–äÎ’ÜY’;KrgNîb““ÛËIŠÒÈEéþLé¤ãŽŽ”N>\29ù´¤“NK:ùtS“P–tò©“Ó^N‹–7IÙ•Oó¿D’\0185J‰šïÏt¾ÿr\127þIòDÿ<êŸ'ùs›\23_ùJ,g¹\22ôgqï§[xX\14{:\28èp¤Ã™\14\23:\\é0Ða¤Ã´\28îtx¢CC\7Rpÿ™\14+:¬é°¡ÃËrøË\15?ýßá‡Ÿ¾O3™ú\11\29H¾\5Aö„ì\25Ù\11r äÀÈA#!GFŽ‚œ\00993r\22äBÈ…‘‹ WB®Œ\\\5\25\8\25\24\25\4\25\9\25\25\25\5™\8™\24™\24¹?þ…\14„Ü\31\5y\"ä‰‘'A\26B\26F\26A(¥wNé]Rz_\17²bd%Èš5#kA6„l\24Ù\8òBÈ\11#/„<ÜÂOËaO‡\3\29Žt8ÓáB‡+\29\6:Œt˜–Ãý‘\14Othè@\
î+:¬é°¡ÃËO?|½…/·°œö_nûåtør;,§ã—Ûq9¿ÜÎËéòåvYN×/·ër\26¾Ü†å4~¹?|½?~¹?.§§/÷§\31–’ÿ/ßç\127.róåÞ,§ðå¾(¿¯¾ÜWËiýå¾^N›/÷Írzùr\127\17û{9\29åt–ÓEN\19ŸÈ\6\0269\0059­ä´–ÓFN/’˜˜¦£œÎrºÈiâ\19ëÜ‹Î½èÜ‹Î½èÜ‹Î½è<ˆÎCÊ§£œÎrºÈé*§‰Olá \22\14bá \22\14bá \22\14bá(\22Žbá˜®ÄYN\0239]å4Èi”ÓÄ'¶wä+A§FN¢“Í\30ÅìQÌ\30ÅìYÌžÅìYÌžS\1¸Èiâ\19[8‹ê³¨>‹ê³¨>‹ê³¨¾ˆê‹¨¾ˆê‹¨¾¤²5ñ‰U_DõET_DçEt^DçUt^EçUt^EçUt^Sy\29ä4Êiâ\19\27ºJ.]ÅÞUì]%)W1{\21³W1;ˆÙAÌ\14bv\16³ƒ˜\29ÄìªÉÄ'¶7ˆ½Aì\13bo\16{ƒØ\27ÄÞ öF±7Š½Qìbo\20{£Ø\27ÅÞ˜ªåÄ'6;ŠÙQÌŽbv¤f›NáAÀ•œÖrÚÈ‰œ˜Ä‰Iœ˜Ä‰Iœ˜Ä‰Iœ˜Ä‰Iœ˜$Ë'qb\18'&qb\18'&1;‰ÙIÌNlviSÈ,ör:Èé(§³œ.rš¤\17jä$ñ¸™y”fæQt>‰Î'Ñù$:ŸDç“è|\18Oœ\20:\13r\26å4I3\23[»FN¢“[·'1û$fŸÄl#†‚œ\26±'m\29IW‘®\"\"\"M\"MÒš>Ikú$Ò‹H/Ü¶Þ¤‰å„­ÄÐJ,¬$a+IØJ”­$\13+IÃ*µÐk9mäôÂí5«^‹êµ¨^‹êµè\\‹Îµè\\‹Îµè\\§V\127#§\23nüYçFtnDçFtnDçFtnDçFtnDçFtnÒä…ï$¬óEt¾ˆÎ\23Ñù\"Yð\"ª_$¯_äÚ¾H^¿ˆ½\23±÷\"™ü\"f_Äì‹˜}\17³/”¢¥3#½–åôÿ\30ÿ—ü‘N\14uaFýÃ= é—,'e^#óªÌ«2\7a\14Ê\28\"sPæ ÌQ˜£2ÇÈ\28•\25{7û.tŠLéÆÐ92cæ¶—\20í5Eû˜¢½¦h¯)ÚKŠöš¢}LÑ^S´×\20í%E{MÑ>¦h¯)ÚkŠö’¢½¦h\31S´×\20í5E{IÑ^S´)ÚkŠöš¢ƒX?¨õC´~Pë\7µ~\16ë\7µ~ˆÖ\15jý Ö\15bý Ö\15ÑúA­\31ÔúQú¾ËI˜ÇØ\13>RGxÔ?Ü·•ü<k~žc~ž5?ÏšŸWIÑUSt)ºjŠ®š¢³¤è¬):Ç\205EgMÑYRtÖ\20cŠÎš¢³¦è\"~^ÔÏKôó¢~^ÔÏ‹øyQ?/ÑÏ‹úyQ?/âçEý¼D?/êçEý¼ˆŸ\23õó\18ý¼¨Ÿ—ä'÷¼é¤ÌUd®”¹Šã\3±>¨õ!Z\31Ôú\16­ß\0319ítb&ý‘\1BL»ü\17æ ÌA™Cd\14Ê\28”9\
sTæ\24™£2ÕºŒ@\30cÚé0cÚå0WÂ\\)s\21™+eÆ±HÃå“NÂl¤|ÒY˜M,Ÿ÷ Ì Ì\16™A™A™\13îè¤:÷Qç^uîUç^tîUç>êÜ«Î½ê<ˆÎƒê<D\7ÕyP\7ÑyP‡¨ó :\15ªó,:Ïªó\28užUçYužEçYuž£Î³ê<«Î‹è¼¨ÎKÔyQ\23Õy\17\23Õy‰:/ªó¢:\7Ñ9¨Î!ê\28Tç :\7Ñ9¨Î!ê\28Tgd62¾]NQg\28ê64Ø\29õ\15ë\20fPfˆÌ Ì ÌFJ]£¥®‰¥®ÑR×h©\11Â\12Ê\12‘\25”\25Rù”ÑòrRë¨s­:×ªs-:×ªs\29u®UçZunDçFun¢ÎêÜ¨ÎèÜ¨ÎMÔ¹Q‘¹–\18²Ö\18²Ž%d­%d­%d-mÈZÛulCÖÚ†¬µ\13YËÕ\\ëÕ\\Ç«¹Ö«¹Ö«¹–6d­mÈ:¶!kmCÖÚ†¬¥\13Yk\27²ŽmÈZÛµ¶!\27IÑFS´‰)ÚhŠ6š¢¤h£)ÚÄ\20m4E\27MÑFR´Ñ\20mbŠ6š¢¦h#)ÚhŠ61E\27MÑFS´‘\20m4E›˜¢¦h#)ú><.‚W\30\31},\29<#\127\31[\4n*\31nýmK£\18•¾{+ÒT²J÷gî˜\127³Ò÷qÌb€À€KÌW ’ôt»Þ\127¡0ùÿ}ì³@\1Á\6¨@ó ù\31Ä¿a¹‘´\11²£\4ZäûxòÐ­7Èz‰B£‘ 2E\0€\8Á\19,pë]„Þ…ïL\6d\11\25\16\11Ž`\1±\16ó7ÉšÃÉ$\18Ò%k¾ô.?i`l€ïcç…\18\
ŠG\14…šƒã,jšBMSDBä6ƒÔ}Ÿ\127Ç\24ó\26ùÛÂ½OÎ¶p~_ ¡P\19|r¶…óû\2\9>9”\0ï\15c¡‚9mó‘&¦\11ò¬\9|@ˆ’[’<4¯“ø±Ä¹Ès¤ØR p\19ù\13ez\2ñ}X%`\4}#jÃ\0188ÊÓ²ñ«H·\15”—(\8H\21`ù\3å¨Ý\16Dþæ5‚\3÷§Û\14ezl€Àü»‹ÑÛôÝ_—A¸M¡\0058Â7”\23\15\4P§ˆ \13\5a\
B¤U\\µHtö§Ûøc&ÝZ-4\1£Ó‡[w»Z§\1¸‘¼Ey)7\6ø úýÑj\0`‰±E™ã3 Åä\12úÎèÏ\25¬ïn\7«édÅå¦t0ZûÛ\0\17\7Œ8@D R÷\23È\8,„à\9\0Üz\23¡¯„÷.¼wá;”±,R\4$\4$ì¨+çÒ`\1Jƒ'\0@6\28œ‚\21F_\1ye®èeA ê\3p#ù\3e\"\1pÿ…néHé=t›\29r…êv•Â\18+Í\"ÝZ'\127Ò \0051¾;yn…5b\4c²¯KMè±j8è&ÈÎ#”žÔß×…îu©{]è^—º\17ú„²¹ôŠ:\4n'#“é3šE2R‹ôûÔ»´cÊEC“\11“êh |]¹p\22¤\0EòÊubå5\5)”$¯ébš™«»æ\23t\3\3¯\24x\5­Ws?»jIÖû\25\0‘ÐyB\7~\13`z@Ó\3˜\30 â\12\17gì\4\0@„ïóþ\1\8\17Èúº\7T˜Ûº¨\16n£×å65¢FE’J¼üîÒÃÅ\26\22Âde¢\0póò2FB\21<JrZKdëš›ot\8Ñ½\17\17(í\3Ö–\1êÆ Õvé\25µ¹Ÿï\17\25òÄ\24£tâ,\18»q@Rd•ƒñÉHÜ*Ã\29w”ê\30[ÁEºmQ^òÀô@˜\16û½\25Ê}s …\
­ÄBE](x©—ŽêšJÔ¦\18UÊ§‹ëÁÜÃv>Cé\30—ÎÆŒ\25ÚÃ=k\\º*3^²“'HÏÖ\16\16¸¯èšz\4\
\19!;”±\3A„^K\23?ÕŒ*©TEY†˜T¦\16ˆ\17>PN÷t£qDqî!kT@5¢œg/TC¼»d\13\9ˆ\26v(û\27í´Dø\5šå‰f>z\15QOÃGóŠhqÒ£\6Õ}òeareareaòeareaòeaÒ1€Õ€Àü»\5îñæ\2˜Þ`(ØG‰Å±ZÖˆ%ëóÐ­†¼ÙÖ†e|é¡û3\"Ë\5\12h«G`¹xÁEØû\8{\23ÁËK\23Ð#K¿© œƒ½zbÉA\20íþK©»÷š¤äƒ&„XÓ“‹v¥üò\17\11;Ò­\29Û+&ã{\0\11o¯Î[ß-\23G*n”N”.8\7\22M£×3º8#F°•’# \0uT\"4>Bã\8¾¼Ý]yÃ\8‹ìÊßÒÖv^…ƒ–H\14áhC\25m(¢\13>ZQv<DÑ\0y‚jþ„\21üÉÎ(äh©y6\19Ë+;É,Ý\4šw‘Š¯r\26M&`þ\29\1\29`ª,—LºÆ‹ôd:ÆV¼%InÑ$é}-…£â7ï\26ô=ih˜+9Y\3`!\4O\0à&\17>QÆ–$8BP‚æe³\\¯ÞÈ!Ê&|‡2Üë9Â\14eKXR¹xÕB/ÛC”ÒÅ3GrÐM¢}x„¨+°\31\28)Ðü\6šk¨>ÀHÂCìSArÐM£í<âóÈ“‚!Åâ\0175ÉíÅbt×µ`¨\16CIL©Ä\18]€9¥H,Àìc‰Q­{*},1$f\03175\0317\21\03175\0317\21\03175\0317\21\03175\31Íl•@Ç\7Dn»\7O9\1RDÙ¹à“\25•.Á³\12F,\16<`fó?\24x¶c]‡\16%÷ç8œE£\16FÆñ\30aƒ{goÉêŸ½EÀ\18-Th¡¤5\21\26&\18\27…\21Ôl”ÞlG‹úz¶ßõ\12Ò\27Î\4c·ðÙNõ‘dçËIÆzK\4Û‚>Û‰äEº‚Ý+ÚÅÀ\9\3'pÊJo8ýz…âú\12Òš§[Ÿ\16IµÐz‡ØÛÆ\26ï*‹x\0îL¯‹Øpó,ˆÂ;xø!\0172ÐQ\4|0µP¶hp¢müÈ\28tÔÖË½÷\23¸¦ô|~ì=D½\\s­Ö&\7>¬D%o\13Ù³Y.\1Èt\17ðœ†—\7r‡\31å¶\25‰O¥-$Ï¦\11\18BòœÚ#ÊaëÛÛÞ>KÚ[qi¸¬DÔÎŽ„\14\16GÙz„f'<é\2z/¨ób©¦ˆvKýù°’í\31v:Ñ\30µ\30\22×\26«\23€H\8ž\16@ßÖD`s{\4h.Æ\19‚5Aý>ç\5B‰\20J\18¨¦®1\26çî±‡èöW’,´5…¯ãKc\2;ÎðL®ãy&\4à!Þv‘{›\12#2y‡ºNFÜQî[¿N\8ÐC7SÏY¶55˜)\9Ñ`\1Š!f­†\0174\\L\9b\13\0,1.Pþz~‚„€\25¦FBï4Ì _¡»\23\17Ì\27!õàéà=\5 .(imMÒE%\0Æ…%%ÑƒqÉG‰ñƒ6\4C…\24\
¢ø8—\30Î…\127séÝìýÀŒ\23Ïzïƒ'…’´hZn:P\15$ªGw5®.¬©C\28ªöHÅ2„® 4Œ®8W’CAÞbCk/F~Ê¸ÕB/=ç½\21‰¸´0Ò‰S€\26\24D¨\17*(\30ù£Pó‡ãPƒW¨iŠHˆÈ}†ÇÝ[~¡i¥ƒxÂxu™\7i\25c»\18Ks\4Ë\13”¡ül1#Rª²\28Ë”‰2›kp¥\30”½\14\0ð£\27/\127ÀÝóŠcTŽ`ä-7\23î¦ê Ž´õHy÷•h“‹vò‘N.Ê'Ê¶K(ÞÍÞ·Ù™˜½\9G€–\8\6\16\197Ñ†‹s\18fC\"pp1fG0]W!Àr°¨d_`¸$,ÑJ,TÔ…‚‡KÃ’º¦\18Õc>O–¾u©»¢ºLO%9©»Ì+ \23ìGÖ\8¯žðŠFàfÎFGÐpÅø¶ŸrµSWq¡\16V9˜ªbÙÞ“IÃ³º\20\29\0q¬7ðÄ\0304ÉÃ\13º~F\\øV\"j‡Ù\6\0Ó·(Ó…°ù\
O~÷ðä·\3i«Ï3u\13Ôµ¡Ž–h{T£¹«ŒÚ‡Ñû\
\0D–\26©R¬\26›¦\28Ì\29ƒ\0218,ÑB…\22JZS¡Ù\26¢+Å£\31oÓ×ÜEÌ˜é&\26bê*\"f»‹[{×ç&Î\22\21¼Ÿ»›¾™‡îèõ\21+Ù\2 c\2±ëL¶žÃC\2\23më£))8Ý\31ÞZœ£s¤P’¼¦}n>¢”]Ù£\27\24Èl$\0Äú¸³\8_G¯\9Æn\30J¤P’‚7g\27ÍhÎC´(¨$9èþ¶T”“Ë¬Žæ€*ðý™jU\13¥ed\8ïðŠœ °·Ò\18ÿL\17Ê²%!üì·\30Ä‘ÂŸGª\6-WïãOÔõ•òe\"…?„u Ñe\8z\21\1 \27œ'\0@\13\7¬t`\025318B@Â–WS€‰\21ö\3YÞ¡ì5Ì^Ãì4ÌNÃŒN®Ì³Ñ­•X›\9$ê›•ì\3S*¤gÛxÙåzTüÎ¦r?CE|Ã‘è\21\2í\12iGÓjxûã‰5„hj\13ï‰„à]‘ õís¹yž<Jk\20+ð†ÛŸ5ÔW+;ûÚáìk\7³¯\29Ìév8§ÛÁœî\9¥ïó¿L\11x‚ékÎ](èöžnïèò?ÞCÖ´6ÃÊ¼.#ß?iš6Ë¬É\2¬aë5ÀÌÑ}c'shNt\15f¼p\127É3\27dêÅNt,Ò‡•ìýõD³“æ¡ô§]aÖ™\9^»ºû“:Å¶Õï\16ˆ„à\9ÁhÃ^óÉ÷™O®Ç|ÊýålbF\3³e›IŒ\19N0\28õ\
ó0'\0309\"\0³<Ÿ2’ÔçKÉ~‰\26j¨RCÚT©¦Ëu’±.,ý<Åñ®\7ñ™U¢\25(\25†už]\5MÔ®Bì*þÝúŠ\127\6Ì¦ûšå’Ø–´\22Ìv¶’»AöÉ\15²#pp1f'û\8fô'„­×¸÷@ð*Ö\0Ø¹‚“Ÿ+ø,—®wÅÒõS±týT.]'è\19\13u(bVÀC¨èøï\16Á§Ã¥\2Åà•;]GH2tO;\4XÁÎ×Ù“«£=6\15\0D\13³×à\8¾æœ\\½é}‰4€\16üeó\23Í]²ò‚Ù—\8>íºqÛhŸ \1\31m‡¤³âB\28M‡äD=Ü|¿ù”^¹‰‹ÀrÛ|‚yøSì}\3°µ~q/\2\1¸Û°lSh{Ñâ\0šß¡î\19ÄœíÐ«C€ø´Ú\
ãÛWc>iõ‹ßØ\27\26­z±ÁÞ›€z‚°O|âÞÁ3ö\19HŸôØØR×¶u\3i‡‹{N0µÙÃLhó ;~_x¶q\1àGH;”±f0ÁT\4!\24@L´ÞD\11\26$çW*óÅú¹@B4Ö\12#Ï`\8!!ÙI²S\2@/Ï\14X¤óvl¹<\25\8ÕôÎò3^&\7I4]Ö–\17\\Ø&¤×\2ùVF\27áJwvæä\4-{xÂÙã\19Î>N@¬\16I\5‰»«¬Á¼Õ): \24\\¬õ‹Qv1ù–Ÿ©ìt1žô—OVä©¢O+Ù›×ÎNcžL\23Ú®\21çÇ8‡sòP$…’\20 7\0067Öîå½”¦ …’\20Àœ+¿¶ìÒ\
õ7+Ù÷y—\27‰¹Sì¬Ä7\17\19h'cz[¥\24_\25\\•5V•©q¶\9Œs.r9hßÉ£-\28´í$\2i©aŠÅ)/3L\26€^\24‹¥ÃŠùE1\13\12h\11\21›\7X\28FsŠ·“ÁB\5[x4Ûè1žsô‘\11b¨\17Õòg‰ÅÂíÜù,1;ÿ›^3Í9´\28Ú`\14m’:Ž)%Ožÿ\16ØHP@ËÏÆ\20“-&\27Sø64Ÿí`Øâíî/VÃ‹a§ÿ¼€ß<¾êa)Ä\12\11!f]\6±ŠâÑh9Z\29G\19§‡G?\"Û\27Å\12}Ò\25z¤36yL…©­ˆH\23fe!ÔheÖé\8ÃýÕ›u\16µ;÷o\30¡WÙ=ÉGÃ¤Ž`wD›@åºò\4H€ç9³Ôf‹Ä\26íH¡$\1dß\15Â7ƒä •ù/õ`Ö×@“4›8\3mA\7W‰\17ÛÑTˆ‡/+ˆ7\27·\28BÎý\9ÉöNz\3¡î\22\28ø„”\14<¶\0ÂÉÉ;\31Á\19LÞ±c½­Ä=\2\18!Ë\28Á%\21rÕÌÅ°ñ\0304Íær,R~‹QôÆ\21¸Ònõ\14!Š¾óš\24\22 Âý\21Ã£ü5™ Ò h$aY‹\1¢\30G1‹w\127´š\12–h¡B\11%­©Ðš\7ŸC¥QÀ\18-Th¡¤5\21Zž€²¯ùà+>Ð:æ\30ˆ}Í\7^ñ±ïðáÝlÛ\15³ÀnƒûÛ‡´Ó\25¡\25;‚V\0092…ÈJr\23>CìÁ<ƒdÙîn2ÃK($½YÉŒŸéÝ$;H€}%è½$\12´o¢Î°ÅÄŒ\27LÌ°½ÄŒ›KÌ°yÅ\28µ®RØ`¤\7Þìë€¾\14àë€¾BL\\ÊÛ#@±=\1\0òËÉ>üÍ6w4ËoÄû³™Ìži;y\27ø†ùAÝ\
Ì 7Ìx\"à•xv×âÙ_gw=žý\21yÃ{¶íØÌ0ú›i;6“o\27~Ü±²9ç %ÊÆu \24Q+«\4]Aï\21uš¦Ÿ;T+ó_#½Ø(/²R‹æ[í\2àç¤Á\4BIÊPg_¬W9\24™VŽYi\4iÊR¯û›yÄhëåÅW§Õ \19 ºv¼ÄBÝ›\31o—¯Òƒ\6<\20xs\127ƒtðPéê PBIjè»\16.ZBø2¿å‹œ\11Ìsj:Ÿ¥Þóÿ7¹vÒˆ^³@5Ê\6„\28ÛžóÐqùÿxÛÒÆÔ\22¡5‡\14¢•0ÂÅs¹©›GSó!\11Kçö`GÑ£\21—{ô!'“$›Ôo¶M\30Msýš«øýÕTï%ÆÕÆ¸š\24Ví`Iƒ!\13†4ZÒhHæ\127¾\15Æÿ1²m`G ­L\23ó›•xzÈ\4¾æ\7*Ã\3H&t6Y:\6Tm\27›Ïô\14‡•b>SíÑˆ¢ü¡m¡È¼=€\5nmjIŸ\16Ñ·Bž\4’úÈ%…WÆ\16-7òºo.óòº¯•õM\18•òÞ†)0``\22síÇz/\17\127¼7_u\0\25#{ˆH¡$!DŸJáh[Ä',\
…‚\20”|šKŸæÂ§¹ôiö\30H¿\30}ê½\7H\
%©ù*·³LaùéŽWùIÚà1n·¸È\27lã\"b¯/¿§È{àKœàdÓÖB+kÛWhYÁž±t›Lƒ<Ù¦xŠ$Z†ò¾˜çõÖK3\16å¸Ö:\3±,ƒ\28sàUÖ¶ë\127þâÈƒ¼]Dß±jœ\28Ã\0151ìQÿ\7ýßÛÍknÁc!c²Hœ\6¯\15iûQ\11Ä…àKéA™®ôƒÙ¾ôÁn^ú`¶.•ÿ\23p5ÊÙÝøÒ×EÕôVŒ/{ÙÀ,Æ—¼Œ\20 b¶\25µZ“\1\3MöÍàílÂâ«%ô?½R¢\1Á\6¨ ¯ŽäÿÔ±B0\1!\5ˆ“µq26NÖÆÉØø´6:cãÓÚèŒÎÚèŒÎÚèŒ\13«Öâgƒóÿ¥ÚP#Êj®ú—ÀAù\27»o\15©ÛF<n=–á<3³@\1Á\6\4\19Ð|å§ç?›X\25˜²:ÑÄÎ€ÑÐx\13\13\18\\0ªwÊ\31$ÝÂ]Ú¿\7\19UDj\2£˜\"Î¼©Õhí\26(*ð¤P(\26ƒz§Ë‚ªÇC½ÓgÁä\27Ï\"¡o\9J¾!)\20$‰†\23ov\23oö\23ov\23oö\23ov\23o.\28EõN¹S\29—Í ú\4\26'‘èÁûsŒ¼[°\19büÆ\5C…\24\
¢½\20EAé+E¥¯\21–¾,.ìwW¦¹+RÜ•éíœo\21ÏJ¿*^¡O/¾+º/¶\29\22Y™Þ3-‹\13\1\2Ùå\17\0180ZßGp{LW•çÕT‰5½Ž&(ä SU}-u\21Ô×MS’x`g\11Ö5ÉA‚\3\20§«Èlûûl\12‹ VM@0\1‹SY;NEÝ8•5Ã‘ørø2l¡t•|ùõ$ŠF­\26èQ@µPk\6:\20ˆ©jËÆ­-\26·¶lÜÚ¢qk}ãÖºÆ­õ[[Þ™nmqwSÈ”ý¶¸Ã)d|i¼/Maª)M5¨ÅéÀÔ¸´8õWÞ¹Tt>\13KAQÞÚJkÜÖZã¶Ò\26·•Ö¸­µÆm¥5nk­q[kÛJkÜÖZã¶Ò\26·ekÜ\22­q[¶ÆmÑ\26·Òª:Ç:Ûž9Jð\20-\19e[Ü\22­q[¶Ç­oWñÎ€w\5wG°×ˆ×Á>˜æµµ@p„\0„˜\23•’T–£J)*Ê\16›²H4\6eåÃ#HÊ>uÞ£ÎùÓyo:ë\11Í\12\22Þx0Tˆ¡ ªOØ~aëåÚ.×Þ¸:€¥ß•{,ñ#÷ƒMÔÔ/\14.ØÈ6\15|ò]Ê}¢mz\27Hn\3©ÅÄÚ2ÐÀåoì•\15pÑ\3vð[ß7\29\\›êI\22²ƒŒ\6\7\25\13\0122\2\0142‚í¥\12¼OEû\0\21\7†\
1\20ÄT«å5\30W·3˜k¸#z0÷™ù!¸ï3#\24*ÄP\16s¿tö½ÒÙõIgß#Ë‘Ae\\PŽ\
*c\2?|Yò°2Ê0°\29\0129r\9›±\6©¨Œ6\28\28Ç\27¡Dã\14ü^\7g´+7šÕ®”ÔÈ¡BÆÜèjyÑUr¢«åƒ\31ƒŒ•k•AsÍÇÊõB¢Ô.òÚM\9X0W<GDðÁUÃ1#Z·\18\20\
R(I±\5ÙzD^R~0—\4HÁ GÞºž´o\
R(HqHàrëT´\6§²-8ù–€\30ÅH‰1Õè°PÒ‚§©_EI;\21åìT–2\3å~dÑBµµ\22ª­´Pm­…j}\11Õº\22ªõ-TëZ¨¶l¡Ú¢…jË\22ª-Z¨¶ÞBµÕ\22ª­·Pmµ…j«-T[o¡Új\11ÕÖ[¨¶ÚBµõ\22ª­¶Pm½…Òd—#¡J\11 É.GF\0226×|¬\\³¢¥jk-\21\18S¿ävö=e€¤‡‚ˆì¥zvýåZ\9¨]ÿêÕ¯\\ûè›ï9;0ûç{Ï\22´>v¥‡]á_Wz×\21šü\21®]ßêÕ…k«½ÒA‡Q©_j‘à)ÁQîM,\14Òr#”šîç{ˆ…ÁÐ\18„-¼ŒeŠ\17\31ÿ\20£\31¸\19:\13ÓÐy\13]Ñ¶TJ|YÞ+¥½¸+;OÐ\15ç\5‰\15’‡i[®‘ü5:BÚ–Ë ù‹tYS_Dë\29‡\31¾©\20\31½%º\13\12\24ØÄ…,I3„¥\7rIë\4Z'Ô:Ö\9´ªÄ¹ØÇç:RBIJùíf¶p^ËÍjáœ–›‡r³P÷W(O¯¶0½BIz5*±aÂ©a71ŒO2 ŠÛª\13UÚVå­.'ÍuyP(HÁ‘rG²èDú\14dÑyì½\0067\25S<ÕéÊg:\9ÊCÈ‹>ÿ»Z1ª°YŒ\0252Ü>\31¬ø}ì\30L©±ÁÁ\5\11ýàÂ\15\24>¯©lYÆ‚„‚Ó8dƒQ6Žï5bìé\8ÁYäô¶¼\0225cL\21—«¢«\
’¬+\11´ö!!xB“–\31ä\8Y–^ûŠ?ý‘¯c\6b\29\9\22ˆ}ì\21\127]ÄÈòu‘<\12\1Bð\4Öpr\17N.üÓ[è\\„OoA6VzOß5]e)´4ÇÃ\31ú&I–d[Û$ò–¶\"ÑÓçø/È¿CÂ\14\9ûƒ/êî!\11¼3u”‚\13\
\16DÄ#„\29M\24×á¤£·!;®¨Æš‘\3\6\7\23Ì6]ø\17Âc3-«xÐ‘¢J\1$~\30ôÃ²$w=\21‚\17R\127 5P(¡4vž3iœ<ƒÿ4\4¶©í³\24 0˜@k£+-t˜\3qú\9òÁb\127à””ÅÒ8ÎäpA\12\5ñg Àª‘óì\0182,‚sFŽ\23\12ú‡Ÿ\28rið0N\14¹tx\24'‡ÊÜ\0018TÉ¡BÆôu•Ôu./Ç2·\16³s6E¡€«&^°äY(\20¤P’Ìì\12 ±[nò\4HÁ‘\14i@q‚ê+ã…\19Ö¢\2*i4³“Ãó\127\29\17\24u­ËÁ¶RÞÚJiû(ËZ\28ì¹2õQ–³8Øs¥ì£,c:`Â²ôQbžhÓÒ\21)±%«-ÊUëK•N€Ù\28E$Í3a¾Ê|³3Y9•c™¢’\24\
¢µÜ\21v;HAÑ\
:ì\15œö²X­\21l+­`[k\5[×\
¶®\21l‹V°-ZÁ¶Ú\
¶®\21<ø\9(‹úVðà' ,Zo\5Ûj+ØÖ[Á¶Ú\
¶õV°­´‚m¥\21l+­ b\127Ø‰˜¢ff(OÂ\20µÒÆËS:\21]e-GÌLé\20u\18[è¶l¡óÜ‰o\11Æ¢%\24Ëv\0¯›o¡Û²…n‹\22:‘–niZ¾þN¯ƒÈg`ù]ñ(óg`-\16_KÁ­\21éK“\24¸‡À\25\3g\27Èïlä@+Æ]óM \17ã®{I’w&’È¯\6˜@›Ö\14bÆ\13eÞ\127º]~4»\26%Y·È±„\23Ox1~Î«$\\xSäG+Ó®\21Žðâ\9/\9˜\9NëÚGÜg4ÊL¶À-É1ºì<—tï­\24÷ÉI\5„ßƒÈÅÃŠ·\19Hò²v¢ž¬\24ßëŽ’½Jñ\26‰§ü^]Ç‹æSb®\30âwë\
R(HMÜT\0085YH4yR(H\20m®éš+Úæš¾¹Ô\24_\24télJñÅA—Ö\8Æ\12ý…_øIYÚ\27q)[÷o¦~qY\27\17X\8Á\19\8ø-î˜.\25ò[ªHò^ž•\13;¾•¥šž!áCÂÆ„Iç\24ßâyOÒÎJRu•z2Î\20\12õÓ¤“·Ym 0` \17ù\29¡wy»@\29Ì¥¶­á\23Ã¢DÍ›\17o\"ý–¤#D<bÄ#P÷@Ý#\21\2s•Î{æ$\7œô\6QÓW–2A6ªÌnôš\29F>\1u\4GôØ\6~æ;\11ï(bÅ%f‹1[ðà\3=h!æ\25cž!æÙ8+ŸVÐ°­•ô\27\12™:\1uB*\6\14\24hÄ¸\13YÎ‚\1³À\6Êöjê@\15y·ÃŒ=¹À3\6\0261nF–\2{(\25²sÙoIz†°7+IC\29©ôÞ¤±ñf%j¡\30ú\2Ô\23¤Bà-@ \21—˜kŒiÄØæd)\24\7^m[Æ#PÿF[ÿ\22ê\4Ô\9©Sj\20VZ²’4ÈÞ”\26L]º1ËÒ¡\27!>HÒ¸hdIMŠjEí\30å@#òû|ú\127ki¹ºËW\8G+§\2\21c~JÍÐ¸\21åV`þ+¾³Qr\19Ao@\31±•ÈðÑRé\11“ \7Ó\16¬xLÔBt\4x\28ä\8\17\16Ïø-Áä¥u\1276Éš³†¥þð\6\23Ia\0152mCà‚Q>»èg\8§m\14\\ôÆÑ\27SªÌ½hÅ¯.Ï&ì_;}~°\9¼\22\24ÑâÆ%–\21!«»s±d;\19\27)#j^¾<(H´ž¡¤G¶3AM€©²˜w\26‡&j¨RCÚT©ÍC™™5\7\28š¨¡J\0135jS¥6þ\
´6.5Í¿òÇ·?ãë€Q^ê'\2D\8ž`ÛÉE8¥ð÷øBéoñü.Ÿñ\\:…=ï›ø\30?á‰@$\4OHÀMäÆÉ\16\30?ºœdýè²%\4O@\11³³0ë} ~A¸}È\30sk?>\24—\29B\20SÜ\18Éa‰\22*´PÒš\
-cìæInmú½b½9$5²Y°Ña\0Ž _äyÏ\0310Þ#°tYZG@`ÑørêsE\31zïCï|Øy\31NÎ‡÷áä|è\15½øð[ú8lc¤`ŠÂG\12{Ï\31¦mL`€‚êcjçiÔ\25\"\27\19\3xCª†©w+£deUÈÓÂÑ==\28ÍóC¨\31ˆz×o¤\0241}Oê·(õ6ìûü;P!0n'§Ô¸\\Ö3\0u@ª\13\28øË\13EäÛ\13#ÙüŽ$\7Ñ´\20R:\0äã4ïøqš(Ê\13^]ì­`UÌ6{Ž&àÃÆh­ð‡\17¦\28eK·Ê[o®L\2b.ÒNP\\9T~6%·Ó\1r”Þl~é\14(90``0nlláÜ[‘wñÏÅñdÌŸŒŠO[i:cøÓV˜ÎÄ8™\11q²—á$›|G\27¶Q=åy8‘Ò\12\30‹³Q‘®Ë‚oÓßÔ•%Ç\22`6®Y1[±\22òeéS\19Ûë¼¡JqNê\127ÜÆŸ$PòBåtU\12!x\2\0:<1r0\6\15Ò¾Ë\22˜VŠ{ùšÀ£\13:š€“\0138\25åÛ¼½~„ôc$\6Ûqµë\12Ä;ù:ŒÚtK0RÚ(V‰FÊ\27ÅæÀ\21\6®Là‹\13z1\1±)É[‡6&0ä\28•í\27\3Ä\\aÌ\21Ä\\aÌ•IT\3’\15Û@Ø\6,nÐâ\6,nÐâ&•Êø]\7\21‚\21\26+<\27A.\17\11|U¸·œ\0304kß$‹FûÉRO–x24^j‘\2ÀQSÍæ<SÉ›ä5¶ßÐ[‘÷ƒƒ@#Òvlúä‚$ý\8Š\6Šô[”&\19’ÿ¿åÿúI—w³çÔ»ÝsêÝì9õn÷œz7{N½›=§ôÿ7ëãh…Á°~Éí\20\5õVä\15\"ä¾µ\2q”?ÅÞù\20{çÓ×<G?}53ôÓ×<??}M[ÈDÉ„¼Ùè²ïÑo‘Ô˜ÿ!ýçZÿ+¹ {ù/É HÜÍßB²]¿G¤\17â<áûå.nrÄR\\åj\3\3\6f1mÝ–$\19¶Ã÷'³†*Nôð'ô\
~ëõ5Ët‹Ë°|†Äã¡N\0155ú.=õëj¾;\\}¯ÑC®ïqÖ²¥«äIWËÎç†.áð¹QÁC\30jôîº‚Î\26D<õ”à)iíH­0ÔJBµ\24\20\26Ó:±B­\15IºC-J5Ääm|é£’»eHø³(¡\30e‡o&TSÒÕÓÑýI*º²<ÇåñEyF<•ç\
=Ôé‹–³W{vúÎ^ÑÙåñÙe`’u‚Uú•\22‰ýKÞnPI½ ù\19Ç\9ÒxÒêæH*§(‰ ;sÉ\127YÆŸ¤¥>ï3—ÜîÍns\8Æ¬J¢\7ã¦V\5\6¼¼_™ÈyÏ²wmžµaŽæ«þ§¦/\
Á\4\4\27@Ëƒâh“\23\6é\127½`ùRýD[`žãG¿¢¤ŸüZÄ !Kú¹¯÷¸\12uŸô¥ÿ´è<¡—¤W>*\26ÿÇÁ\"ëL\1Á\6p\12Kj“öe„\27t\20Wšg™×uoAä\5\29†n‚ƒ\11Ž»Þ½§ýîÞñíê|\21z„BA\
%\9\22œ&$¯ŸR—\28)”¤¸„Özcý\0\15ŒíÁ˜0¸|RJ-© ûÐX?¯™¥\1Á\6È>7†ôœ¼M¨ÁÞ²ÿIsÖ\27A³\27à»Ý\13ðÝì\6ønw\3|‡Úej\22ÛÜ$C\27-gñƒ~ñ\127\0280S¡Ë\1!\7Èr¾ìyºF\
†\0126_sõ”¡\6·\13²\9÷oÜ&Ð\127j\19ßc»\21ÿË\23{­DÍ¦\13ìE2›e&Y·Ë\4Bð\4\11ÄM3ANáz\1¢¤9-b€À€z!”j¤ôŽD” bz\31‚®`Þ_ñ=í¯ø}ø‡nŽü`\4ÊÖ¿™½Íÿ–÷6\127 »+íê#[\14.w\11ƒ\4ƒÄ;ÂA$½\23\28r`ÀÀ,Æ–ßH6L·à£¹¥d}ÖÍø\12z¢0iiƒÈ4 IÛ$F)n“x¡§ªfO^A®’c¼A»AB4²Ó; ²ß;Dó¤`IñcÙ;y±'\0014NG„Æñ\5Å#ÇBÍÑqh® PÓ\20‘\16áwPTÚZIß§¿ÈW\11Ó¼ò+—\24@\3¢]â~«¡´$¨€C•\28\
r\31·T4r0rÜ·wç\17j!\16úDY¶LÀ2²ŒÛ}×P§-‘·¼%I…¾¯\7p÷áO\"H\0n”zq\27¥^hÍJÚÑóÂkV¬H\1\3³xCª\13{^ºÄ¿¤-@/òaé\30XÝ‘\16\28!¾'\
\26‚Ó\16¼†\4ÄÊ\13rp\
¨2{\11³³0{\11³³0;\11.<æu\
g™:/×x\25iu\21 ²Â\
I%òÁo\24ºh]\17më\17ºÛzÒ¹@úÒ\3^›…˜<Šq˜<ñàü»\1?Ì7½\"¦»b\3˜vÍ/0Ë\5;Šƒ'ö%È/xwfžÉuî\0˜ˆ+˜#\26PÝÈmþ~DS\16‹Èò\29‰PñqUóqUñqUóqUñqUóqUñqUó±4ýÌ71gÚ€°á¹ÃdêÏ\19mä¸k?ZÈ@ô÷Íûz\21 7–NÞ¢œêI\"Håšoût\31IRÈÒ\28ŸŸ\0269D9Þ×\30õ\1270ÿ¹\7cB¢Dß\15û&Í\12?/}¯‡\30\"R(I\8iÿ…Ÿµ\2\"Ï[\19\20\
R\0Ò,½HÎ‘Ø£Œ-ÔT\9Ùæÿ’©±‡*¤Ø?Õ\24ñ9á7+Q·ßŠüÆ°jœ×ì”êì­ÎÞx±³^,=þùûÐ.\23'6c\15\8È‹ªˆ\28#¢ƒ\2úŸ\6\4\26\16l@\20þ«Î\31°4²|¾2\2Á\17‚'°†W\23?’9>ÑW½´\11ö`\1\29€[$Dä\0307XÏÿiZd”¢¸ç\9³QJb\20žîMÔ1\31UGpH,àÔÓHñAlxµ\30=Uˆ¼¶Ž\19uJ¡ôÜ&\"Ê\16dü«rhùõ¢%b!c4…òoÃ’Ï¬þÛph1Îr\27ôöZoïûðì¬1‚¶Æ'åÄŠ4ÿ+æ2cÝ‰øð÷’«X€ø²\26Œ«šñÂ[±¬`XF\23åÑ;}-Pû<ôFRÆt\7øWO\0125¢\7cs÷­Ä¨Ò:0TˆÜIÿáV™Ñë\25ò²~”vV¢Ç-ILÿ>ô_¼\13Hp|ŒGc\30\21ã‚I\27\28\\0Êg\23ý\12á²`\18¢7Žnej`Là\9¤£H\31tå\30bZÒÿH’\
–õq›žµ/Eø\0\6\16àå¨Ž\0\0W\2”1œ\
\19øs‚ÌÀ¬ÀŒ\0\"¤‚wvF2¦r\11{ìÕ »\21ˆ˜Å$\31Qž\127‡Ë+H(\16¸†Ô_q‘–ÎÊÏž\18\
ŠG.…š‹ãÐ£àBMSDR„G`ñ#T÷\13búØß\19ChA}\22šd}\26\
„à\9\22ÐŽ’•mx|\15\16d~à`8zpÐlå)«ÜZIwòÑ0}jœB\17\16‚~\27\1H\8\26b¨\17C…ØÔˆMI¬Ð<I\31ÿ:\"Âq2s«Os-*Ï¼-,šÓw\17P³ƒ\27]Í‰Îk•Ï(\20Z\0176äP'‡’\28ß\26/ÝÍ¨PiOv`eÀ$§­d?Â‰œ\30¦zº\11H\17ÂŸEp\1r…ìf²xåú\"ÀºÔÕ\29êªîtugŠë—7œõ\25\2¨Â]yj6vø­Ì~ t$óšcÓDd9\24Y6ñÊÒ\8Ò”¥­•Ò\30^f\14þÁÌ¿?˜8}ÐœP–éæk€à\8Á\19ø™1F0rÞó,!Á'2îÆ¶C™§\9R \4O ]·âk¥–½\7iç­øj)¤iïÁ¸ûGáWÜý\13}‘ýßJÌ\16e'µ\17ò\1ä\6/hÞkÍ|Ìë¬\30ê§¼\18\16?ä…\4\11DÿÏ.=gŸ–³K‡%Ä‡º<9¦H\0$\127tŒ†ïî£c\
åŽ\1\9¡üÑ1Äç.øÑ18’ìsE\19Oö³c<†A\14­\11\7DV‡c´\158R´¶*¬•œç‚óì8®\4êJ\7ŒæJ_AŠšÆ\"Úè8[Ä'\25\16më\17G\18kËÿÂ^Æ¤¤ \22ËJI\0125b¨X‘4”\24UðÒm‰\21DÙŽÌ–œ¸!YQ˜>ïÁëê|ùâgèNSo¡PBIbŸfOÊˆæí÷yï26!š«H\1$y8\31œ7\22 Gð·=\16@nä»¢\24Žiy¶í 02\18Ó²¦\0096§É\0010¦¨$z0Z]Ó“\7ñ³\7çnA\0125bÔx,õ\29\11mÇR×ÑkZŠÁªÐ…`¨\16ƒ'ÆüÛðb\29È=\3Å¼ó$„¢\31\27~{\26\16yƒÚúàH\1IÑ§×\7tHåè\13\4\7\12æ=ˆÎÒ-G\29€ª¦’Z 1-ß0×e\14Ò¦ã\27ÊŽÀ_\19Â\8F¾ÿGZFFÈ3?ÿˆµ…¥øì+\5z‰^17²¼dn\9½•irØ\6#ù\19¨ünÕÄ\19,ôi¾§/zWâÏóeQ©ô¬Áút…Àg09Þ´\20$³\14¢\25¿Ë\15ˆ¼ÏŸ ydÎý³«>ã¥¯Q\"Âß£ä¾ÙU\31ü2\9\16!A<\30^\3‰‘†Z®bl\31<Ê=Û&µa!ýÓõ.\15y­ËCZçò×¸ˆ¥Ñ~H3#¹k\31\
R(IYSWDë£_\\TFüî¢†c|•è\14ÜÐËß<\21\17—“0\26èoACDs¾¡lÂ5WãÿþËŠ;¾|F–‹\23à\8Á\19x\9ßŒ\4+§íYAƒ\5–úýhƒ“´‹KüXÒEÑ«\28\02400‹Që\
´bØ7+Étq¦~³\18\4ò\"1K}ýáûøkZô\19ÿ‡øß®þ\23)­þÏ\1\3³¨«ÿ³dÂt=óÏ&²‡ò*f !”WF—š\26O¢\21Ž”¡¼¬¹0gHºÜÛ!qC•\12…‚\20JRü\
×„Pü\30×”¡¸\19PK«,\1ù¤w´,B½O€øaY”Æ/ùÿ”ÿó‡´ùÿ6ÿOßj—€\31ïO_yµz\12\0039\6Ë›K–‘D\9\5%xJSP\26 |ŸöÈÈ€:*\15Š¬«\9I”¾ (rëX«>ßƒHE\26-fh¡B\11%­©Ð\26G+M\22\6Ks…±ÒT6Äé½ñ{¾FÞ¢L7ã³‹°C™\23ãg£Ë=ã\01263 1îoÞÄÕ\17L„<WNï½\20Ø®Ä²;1Aò²#$ÉC´\4Á!Û\\£4Ò‹‹òâ\"¼ú\8¯®d¹Œî|Fw.cåÑM…\
Ö”Øƒ37{s\0ÄEÛ^/d\
-O¶*F\8¤ÔÆ§Öô\"…>­æÿ¿\26ü×„?ðh­Óµc*…(¥e»ñ\127Ä7²5,³ãÞË“EC\21¥/p×Py\0Yªø¨¡Hæ{_êÕ'Yûõ™PÈÜ•°ò\11È3w¤³Bj’œÅÑ[\28E‘ù92ïæv]2þï’ey!ˆƒøQ\"c¡¤…\
ÍF=VxGÃ»¿Ñ÷\4¥<GˆžôY,dZ0ÒB©­©h3\24$\18“\7\9Ã$abTú'®÷ø'®÷ø»†rö[»\25´ö+ÔP¥¢‚c•kü“VòŸq…D÷ƒ\20ò¥$ìxGHù¢uÄhD\9`¨\16CÈ\26{Z¶\16¿ºc0~I]ÁP!†\0261kLßüF\22\14H\14…^\11;ÍM]sS’eÓ¡‚œá€äš\27\25vš›ºf\11Ë…hkW¬­\\±¶vÅÚòŠ¥Ï\14;óm5\127Ûzþ¶ÕümëùÛVó·­:Qs¡ê@Í|Õx-O+9Zæg%75Þ2ö|ãÝrL ñç\21ÁP!†\26‘5>Ë\14>¹F\8æêSI\0125bÖˆõ)Q±>\0019\20z±>\1¹©knJ²­O†lë\19knØú\4ä¦®¹)®X[»bmåŠµµ+Ö–W\12ëS6ßVó·­ço[Íß¶ž¿m5\127Ûª\0195\23ª\14ÔÌW×ò´’£e~VrÓUá>®ï†\6 k¹Á9d\02603Sô¸“š·•vT{ðöâÎj\30O;¬=Ô-4\127fÁ_«Â%Å\11—\\„àñÂ%\23¡ù3\11ÍÃÿ\7!¢\2þ",
  ["length"]=63005,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=4296,
 },
 ["version"]="1.001",
}