return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="mn",
  ["source"]="hyph-mn-cyrl",
  ["texcomment"]="% (New) Mongolian hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: mnhyphn.tex (2008-03-30)\
% Author: Dorjgotov Batmunkh <bataak at gmail.com>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
%% mnhyphn.tex v1.2 2008/03/23 (2010/04/03)\
%% Copyright 2007-2010 by Dorjgotov Batmunkh, National University of Mongolia\
%% email bataak@gmail.com\
%\
% This work may be distributed and/or modified under the\
% conditions of the LaTeX Project Public License, either version 1.3\
% of this license or (at your option) any later version.\
% The latest version of this license is in\
%   http://www.latex-project.org/lppl.txt\
% and version 1.3 or later is part of all distributions of LaTeX\
% version 2005/12/01 or later.\
%\
% Special thanks to: Jim Hefferon and Robin Fairbairns\
%\
% There are few basic rules in mongolian\
%\
% 1. If there is a consonant then it can use hyphen before it.\
%    And if there're two consonants then it can use hyphen before second consonant.\
%    Are there three consonants then it can put hyphen before third consonant,\
%    also are there four consonants then it can use hyphen before fourth consonant.\
% 2. In the case of hardsign or softsign, it's possible to hyphen after these signs.\
%    For instance, Ğ±Ğ°Ğ¹Ğ³ÑƒÑƒĞ»ÑŠ-Ñ, Ò¯Ğ·Ò¯Ò¯Ğ»ÑŒ-Ğµ\
% 3. However one vowel can be belong to a syllable, it's not possible to use hyphen.\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="Ğ°Ğ±Ğ²Ğ³Ğ´ĞµĞ¶Ğ·Ğ¸Ğ¹ĞºĞ»Ğ¼Ğ½Ğ¾Ğ¿Ñ€ÑÑ‚ÑƒÑ„Ñ…Ñ†Ñ‡ÑˆÑ‰ÑŠÑ‹ÑŒÑÑÑÑ‘Ò¯Ó©",
  ["compression"]="zlib",
  ["data"]="xÚu›]–£8\18…·’+˜s*+{\127i\12¶ë‡ê3Ë¨§.\3i(Ğ\22ì®\13t\21’\"B\23ˆ{‘>I\16`2?İ¯÷_/Ÿüö#l\31ÿE¼`»‡íŸŸğaûï?ˆ¿aûıõñ\3AmŒÿöÛ\1À\1À\1À\1À\1À\1À\1À\1À\1À!\1\7\0\7Š\3p\4p\4p\4p\4p\4p\4p\4p\4p\4pLÀ\17À‘â\0œ\0œ\0œ\0œ\0œ\0œ\0œ\0œ\0œ\0œ\18p\2p¢8\0o\0Ş\0¼\1x\3ğ\6à\13À\27€7\0o Ü@¸0ƒ0ƒ0ƒ0ƒ0ƒ0ƒ0ƒ0ƒ0£KsêÒ\12àLq\0\26\0\13€\6@\3 \1Ğ\0e€2¨kP× îŠº+ê®¨»¢îŠº+:³‚°‚°¢3+8+8+8\0278\0278\0278\0278\0278\0278\0278\0278\0278\0278\0278\0278\22\28\11\5Ç‚cÁ±àXp,8\22\28›’c\1´\20\7 \3Ğ\1è\0t\0:\0\29€\14@\7 \3Ğ% \3ĞQì÷\0ôÛ°\13@\31/Øîa\27€Ş?†m\0úø\27¶=¶?°\13œ\0038\7p\14à\28À9€s\0ç\0Î\1œ\0038\7p\14à\28ÀiÀiÀiÀiÀiÀiÀiÀiÀiÀih€>è±q\0¶\0¶\0¶\0¶\0¶\0¶@µ€´¨Û¢n‹º\29êv¨Û¡n‡º\29êvèL\7B‡ÎtàtàtàtàœÀ9s\2ç\4Î\9œ\0198'pNàœÀ9s\2ç\4Î\25œ38gpÎàœÁ9ƒs\6ç\12Î\25„3\8g\16. \\@¸€p\1á\2Â\5„\11\8\23\16. \\@¸€ğ\5„/ |Aİ/¾üëı×'\127Øïüá×ûõóãÇ\27lD\30õz\31²7doÌŞ˜½){SönÙ»eoÎŞœ½å“ï×ëıwÚù\17b÷#îB\7×\\mÍÕ¶ìmÙ³Ù³ÙÛ#wÜ=\2wŸº×??qèÏOŸÁ×»Ëu]ªûxO^Œà\29²wÈ^“½&{G´ô8~\14\3y\28ÃÑ\127ÿÁ‘.—îréSöNÙ;gïœ½Kö.Ùûú9\12ÃïÂ\8ÃîGÜ…æ¿Çcßã±ïÑì£Ùûyâ¯ÀÏáì‡İ\18wûË\127üŒ\24ÂÕë\15½İG¥'¥Ò«ÒVêÇë«*\127}{¼s=¼İ\7¥EùQ•Ÿ”^Şî›ÒVi1^£øFñö·ûUi£´“úÑpí$ïqõƒ^•Ş”vR\11~Ğ'®\27Õ^«ø­:ŞÕZğOò|<zÕÿ^ñ{Õÿ>õß†{\4æÇ ô¤ôª´UZñ¨ÿE\31”n”>r}Uí•–üIéEõßëYéMi1\30£òaTûyş\21=+m¸vª¾Sí9Õ\127'ó\21æÛ ´‘Zä³Ì?Òä?²¿^ëã’×Êş—ùJºSÇ;u¼—ù\14ÚJ\29Ëû'™&<?•\25Pœñ‰£k¥óXœ]—É×nq.4Z¿\20¿óÕ+étö“vRçì'MÙºÒ•aXÌüG›bšm\20£íkœE%v%NW»ÙÚ_”\21Êq…YEêš{ÃrIj\17\20#J\26Qr\23Ê‰’\31Ks¶(Ç\0212XT[T'(bìi+Êr\21™ïo~7<¾Æ\29”\127»\12oYHĞUéIi«´ƒş`©'E\9%E\9%E\11PQ¶(ÃK¦4e…A\20Õ\22Õˆz-o=%T/˜}*¹ø7Ùw‘\5î\12•3VÎT9¦rê¶6íP_¹ÓKg¬ÊäŒrÇVÎ.\29SõÇTä½\26…«j9İV9SÜi¥Óè¶ÂB<UÎ¬\29]«Óı)g˜;u™Ôgÿ\22\28\30¦ù)dÖ\\[¦¶ÖÚÚ*+÷œY§Úê•õñæŸ†+k«¬\
ÿ\17—8n-õ€–šµÔÉÙË5À,SY¼Åà\\E·‚3ŠlEG—1¢µèè2›èdp\\EvOÊ(NZ|…S—Qãâ3œœ¦ªu¬œ¶r:İç²Ze§\23‰&g­\28[9»vh\20{ø!‹­ÑQ‡\26\19éV§Yi#5å€´)¼M¬\20Q—L“Î\25#İJ^\25SÑ¨\31o[SxKÿ…ùd£|\11O1\127á‡'©÷¨Cizœ!E=ÎŠ\29K÷¢\28Wè)©FÔk™Â}R\28NÏêg§%Çrf\28ë‡¿W¿³SÂ4@Yû+÷ƒk\26RÖô¬t\26\22Óà-ù\6?\0085\
5\0095\11e„Z…Ú„²EÑbAj\16j\20”Q\28›„¢\27\29©ßB\25A1¢Ş*ÆçÕ­¨]ŒÈ\9Šã\20™A\127\26Y½tRIuB]83LõA¨I¨ßBÉz1Ÿ6\5ê‹Í\15k\20ã\13\19qÎ¹eYµ,S–åÉÆñ%\21~_å7E²ØšÎ\28“†Ä\28]Æi'=É\25ï­lúdMí$Òap\29•©ÈµUÚIë0ë«âM¥=\27'\27ÖÔ¬*oTù]µçTy'Ë§UˆéÇW®[Y?­>YwJ÷‰W.hÃ.g#rV#è{yÕ1b\12e\0293qİZãnó«œÉ\11˜Õ\0142È\28Ê¹pĞ\26sÆªÌX‘ÇªÖR•YªÖME6\21‡†¤ã´£k¹Šìt™t¾¥ã´ƒËZ:tšŠÜêÖÓı–9½\30Wš/ÒY+ÇjG·Ş§<\127„÷Gäkã:g\"ê’‡¢\29×¹\23\11›YCåŒ•3UÎV9V;Ô·¥š³Ü9VN/kÕçkE\30+gªÆE\15ñÒ±ÚÑ=¤\27!sLÕ\31SqLÕ\31z„ÓN]K÷ÇU­;]«Ì‚¥º\26–êjàN[9tšª­V÷'­Ìéõ¹¨çaúyO:V;™¼†OËb\30’3Vev]¦\\{¾›\13JÏJ¯JoJ[©©\15E7JŸ¸¾*şUÕ\31ÕñQ\29_T\127\23Õ¿EõÏ(Q¼]ågWå]¥e}—fíïÆNj‘2«ö|7\22Ç;Ù^™a{¾;OJ[¥Ô’ß§™¿‹OOY\27¥ËøÅ§ ¤Ùx£¦‡Ô-ŞÖñ¢rŒA?\19×Ä³ù\23ÂI(Ë\21/IóÈ¦_\15•²\\ñz4\127ŠÚ„bõŒ`\26Aqâ˜\24C:c6ÿz8\11e…r\\a&Ù˜¹ıñ.¾Mr½)m¥FóYOJS\2²6ê¸Sí¹ê8º™túÖÂµ‘\26\0190ëFòÒ„gZ\30ïU}šÀîş+üEI~\20åzUzSÚ*í¤Æ‚•õUñFUŸ¦WÖF•7êø®úëTyÊoÒé\2cZŒ?}»Êº‘í¥ü2-÷ê8å;êrş\29~\2*ß>¹”•6J¯JoJ[©uû4^ÒWu|TüQ\29_Tÿ\22Õ¾Qõª¿«ñìª¼«µ•ZğÊùÍšòOú¨Êw’_Îçoø“ÒFéUi+µl?]oá/·\
-ª\31Ô–x˜vâã†\19\15ÑN<@;ñ`ìÄã­Ë­£P³P«PŒiø±œcñĞæÄë‹\19fN<–9ñHæÄë\
”XÉ„SjäÕ«8-\27->·9¬ıÈ-}dÊñÈâ‰Å¦Ä¡?9nYÜ§8¶\22ã8ïslK\\ê\26VŞ•\24kLøâ\16Túr\\úRœp^¹SÚgß›\27áĞCvø+?ù×\11á—Úğƒ\15\127P¨<£½+Ñ¸÷Œ\23g–ğèNVyN{MÍ£«¬òlí!Û‡Ç1}~ s-©rLåXíP¯¸ÓKg¬ÊÄ\15BÜÉ™á©œ­rT\127LÊÈQ~haNÉøQ~z‘\14f\12sºŠ\19_Â”c´C™\15WßáÊkâ®».|(È¿\24OÒ¡Ş\23'õ¬‹•ûğÇÁwó9ÎëÊH7ÒgöøÜ6ÏmûÔÆ©Ö6]\13Ú¦S\\Û˜\11Úo÷Ïìá¹=>·§ç¶yn»§öÿé ÎÃ\19»}nŸk;LmÓµ®íşi¿Ó\21_Û\30ò9ıy\25\"\19–:ŸÀ\16;üíu¼:½œJ¸åĞ\15ÅŸ ğ…Óù)½B„ŸŞÑA¿ì’nâGßøÓ: á2\12\127Ìó\18W÷ûâƒ=üñhhßxáCßÉĞß—8ÉC\15qe†r/ñ\1ôş\17ƒ.\6D-!s÷\28>ş¦\0167\28~”p)áÃ0š\20~CèrkéN”Ã\18.%Ü_JjÂ¸ğ\27¸Ïç\0242Šûvx¿x‰KIø–èÃËkø\11q?ÕSèçC<Ñ\127áŸ5b\12tÿ\22Oğ[*\18Ô†¾„\25€Õ~$AË\23~•ñyü\31¬U‚Ã",
  ["length"]=12893,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=988,
 },
 ["version"]="1.001",
}