return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["characters"]="adefhorstw",
  ["compression"]="zlib",
  ["data"]="x⁄ÀH,J—-O,JU(ŒO+\1≥\0Gû\0074",
  ["length"]=19,
  ["n"]=2,
 },
 ["metadata"]={
  ["mnemonic"]="pt",
  ["source"]="hyph-pt",
  ["texcomment"]="% Portuguese hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: pthyph.tex (1994-10-13 - date on CTAN) or (1996-07-21 - date in file) - no idea\
% Author: Pedro J. de Rezende <rezende at dcc.unicamp.br>, J.Joao Dias Almeida <jj at di.uminho.pt>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
% The Portuguese TeX hyphenation table.\
% (C) 1996 by  Pedro J. de Rezende (rezende@dcc.unicamp.br)\
%          and J.Joao Dias Almeida (jj@di.uminho.pt)\
% Version: 1.2 Release date: 21/07/96\
%\
% (C) 1994 by Pedro J. de Rezende (rezende@dcc.unicamp.br)\
% Version: 1.1 Release date: 04/12/94\
%\
% (C) 1987 by Pedro J. de Rezende\
% Version: 1.0 Release date: 02/13/87\
%\
% -----------------------------------------------------------------\
% IMPORTANT NOTICE:\
%\
% This program can be redistributed and/or modified under the terms\
% of the LaTeX Project Public License Distributed from CTAN\
% archives in directory macros/latex/base/lppl.txt; either\
% version 1 of the License, or any later version.\
% -----------------------------------------------------------------\
% Remember! If you *must* change it, then call the resulting file\
% something  else and attach your name to your *documented* changes.\
% ======================================================================\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="-abcdefghijklmnopqrstuvwxz√°√¢√£√ß√©√™√≠√≥√¥√µ√∫",
  ["compression"]="zlib",
  ["data"]="x⁄\29“Ar‹ \16Ö·´Ë\2Yÿì\11çA\16\1b\24@X•€ƒ^§Ï*Øúlºı≈Ú~-˙’–îæFb\30û\30”ÙÙX\21W’¨ZT7’¶˙˛Mº\16Øƒ\27ÒA|\18_ƒ;Òoz0èøàD»3Úå<#œ»3Ú\12û¡3x\6œ‡\25<Ég\12ﬁ˜ü+1\19\11q#6\2F˘rÊÎôog~ú˘yÊ◊ôÔgä≥úÃr2+◊äµR≠P+”BZD\11hÒ,úE≥`\22ÀB9(\7ÂD9QNî\19ÂD9(\7Â†\28îÉrP\14 A9(\15Â°º(/ ãÚ¢¸F˝ºû9üπú…\30#<#<#<#<#<#<#<#<#Çà  ËÒ†áÉ‡\0\16\0\2@\0\8\0\1 \0\4Ä\0\0169c‰åQT\20\21EEQQTÑäP\17*BE®\8\21°\"TÑJ¸Gíî$%IIRíîÑíP\18JBI(\9%°$îÑ≤\
X\5¨\2V\1´Ä\21`\5X\1VÄ\21`\5X\1VÄ\21 så,%K…R≤î,%£dîåíQ2JF…(\25%£\20æK·ª\20QET\17UD\21Q\5™@\21®\2U†\
TÅ*P\5Í~^Ù˝ºË˚y—˜Û¢´∫UΩ™Ne-∏\2W‡\
\\Å+p\5Æ¿\21∏\0027\1M@\19–\0044\1\13†\0014Ä\6–\0\26@\3h\0\13†ÛíùóÏ¢∫®.™ãÍ¢:TáÍP\29™Cu®\14’°:‘Ä\26PC‘\0165D\13QC‘Ä\26P\3j@\13®\0015†\6‘ÄzÜzÜ⁄EÌ¢vQª®]‘\14µCÌP;‘\14µCÌP;‘\14u\0088\4\28\2\14\1áÄ\3‡\0008\0\14Ä\3‡\0008\0\14ÄC¿ırUÕ™€d.föµûµûµ^Ù{—ÔÂ≤®XÀTº\19\127ßõ∂o⁄æi´^Í‘.m⁄‘€‘€‘€.:Àèˇê∑\"8",
  ["length"]=1444,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=307,
 },
 ["version"]="1.001",
}