return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="ro",
  ["source"]="hyph-ro",
  ["texcomment"]="% Romanian hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: rohyphen.tex (1996-11-11)\
% Author: Adrian Rezus <adriaan at {sci,cs}.kun.nl>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
%% ROHYPHEN.TEX, version 1.1 <29.10.1996> R [7.11.1996]  %%\
%% (C) 1995-1996 Adrian Rezus [adriaan@{sci,cs}.kun.nl]  %%\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
%%\
%% Romanian TeX hyphenation table: NFSS 2 encoding, medium.\
%% Contents: 647 Romanian hyphen patterns, with diacritics.\
%%\
%% This file is part of the Romanian TeX system.\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
%% Romanian TeX, version 1.3R <29.10.1996>               %%\
%% (C) 1994-1996 Adrian Rezus                            %%\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
%% History:\
%% ROHYPHEN.TEX 1.0 <10.02.1995>: Plain TeX and LaTeX 2.09.\
%% ROHYPHEN.TEX 1.1 <29.10.1996>: Plain TeX and LaTeX2e.\
%\
% -------------------------------------------------------------------\
% \
% TODO: fix the notice below - it only holds for the old patterns\
% \
%\9NB This file must be used in conjunction with either one of\
%\
%\9(1)\9ROMANIAN.TEX v1.2(R) [1994-1995] [(La)TeX] or\
%\9(2)\9ROMANIAN.STY v1.3R   [1996]      [(La)TeX(2e)]\
%\
%\9NB Romanian has LR-HYPHEN-MINs [2 2] (like German)!\
%\9NB Romanian has STRUCTURAL HYPHEN-AMBIGUA:\
%\9   i.e., words that canNOT be hyphenated correctly without\
%\9   additional (e.g., semantic, stress-mark) information.\
%\9--------------------------------------------------------\
%\9The Romanian TeX encoding of the Romanian diacritics:\
%\9--------------------------------------------------------\
%\9Romanian TeX \9DQ-macro encodings\9= (La)TeX macros\
%\9--------------------------------------------------------\
%\9ƒÉ = \\u{a}\9\9\9[-]  \\u{A} [not encoded]\
%\9√¢ = \\^{a}\9\9\9[-]  \\^{A} [not encoded]\
%\9√Æ = \\^{\\i}\9\9\9\"I = \\^{I}\
%\9»ô = \\c{s}\9\9\9\"S = \\c{S}\
%\9»õ = \\c{t}\9\9\9\"T = \\c{T}\
%\9-------------------------------------------------------------\
%\9NB Romanian \\^{a} behaves like \\^{\\i} as regards hyphenation.\
%\9NB The capital \\u{A} and \\^{A} are rare in script; as such,\
%\9   they occur only in records of the Romanian substandard.\
% -------------------------------------------------------------------\
%\
% original patterns generated by PatGen2-output hyphen-level 9: do NOT modify the list by hand!\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnoprstuvxz√ÆƒÉ»ô»õ",
  ["compression"]="zlib",
  ["data"]="x⁄-ó]r˚.\15Ö∑¢\21x∆‡¸ˆ„ÿ$•\127€x0d:æÌ*:›C7—^dYÔs»{¡1·C\8ÈH\"›Ë„d›8l>\30|›i›îCo›\28‹¯ﬁ>'øÓÉu—çÇ\0¯Á78TØ˛√∫ﬂüaµns¥\8Ï¨ﬁsœ/Î\14˙œ/†\14\17∏l‡ÈlÏÕç”ﬂßç”[ºÿËÉç∑‰ÈË\24a\16.6F\1278u´çK\12ˇÿ∂\20\27›J€¯±u6^6≠ﬁ‚\11Ωé\27∑·–,ª6.5&w∑±ƒad∞d∂î°“}~è\13Qƒç¨ıUá◊Yp\23,ÇMê\5á†HµÍ∞\1ü”‹ﬂgo\127ü>\2R·Ô”≠\14‹0œﬂgæs=f±≈ﬂÁ¸ÚE\11JÏ¯†èñ˚*xh¸å÷_Õ];ªé:‡*1\23\6&⁄lWå”5,¬`˛\26£]›BgX‚j`µkÍi>Gm¬\
◊Bì∞Áw\28∂Ä\0004Î'\27¶Œ&›«pÑõÑEáMtÒæÄ]\14\7u 0E?.ÅèK\0na‡ÿ¡s§?,¨ZióÕ¶¥«—\21Ã:•ó\16Ùò–c‚«T=™˙\9„Nı5˚∞~∂aÓl\30a“‹ÓÓÊ…Ê0\28¬”«ÕfÓ-|\9vÛ;çÛÊû¡4¿\21?W\11˝8\9ﬁ\5ã\0ÀÉ≈BìJ˜a·Z/—\\`Â$æÖi\25]\14\22fHç\5\3t\0122A\31nÃˆoå¥uçó`\20,ÇU∞µô$\20[˘\20¡ u~\1278à•06¨i√æÅÂó\0139=é\
>Ò≥œ\12ÁQ†´ÖåÎÇ;,\28~BÏq)RW7ÅH\28^‡∑L\20t#¯\19ÍÖ…><t∞˚`‚¥p˛}^@úfä‚d˝m0wÎÃs)\127˚˚dãª·◊[‰æ˛ñ¯UÏv)’˙ª3wÔÏ.ÊrŒΩq‡\14‹ÂÊª_\5õ›\19Œˆw¯ƒœáπ7ViÈõ¨ı\22˝\4(–ﬁëãΩ\13Ã…íì≈—ìTËF\1öƒÊ\30∂`\0¨<”ç£ \8¢`\17lÇ,(\22c©.∑\13ò\25\
h√¢\13K≤∏é%‰¯èIˆ\12[/ôõªk˘¶Pà®≤=XútX\"3≈F÷∏Àp\17Û«√ﬂ\16\11«cã‹(?Dˆ:\29§/«(gDe\
`\21ls√*<\4l<±ŒÔè£˘Y\16\4(˘˚≥ç^(ˇ1îcCnÛ˚ì_cÌd\6\5CiÛ(IüÛ˘\\¯¥¡”z\"‚\29\15ºœ4,˝\30[\28Ω/ˆé\19ﬁ+\"˙ˇ¨_lX:[∆<Í\6∂¥|§Oã˛Ö¸≥@øe∂E!‡ñ\27ÌŒ\30$.\"”\"∫\0eÅ\7\11\20pÀN#∆\23%:GÜv\11G{b…-\0047ÀV<ø¬ªU\4_Ø∂^\23ÆÌ\25\8∂¬O\6o¸à6¨\28¥6’˝™ËY!è_ì\17=wÂ§UQÊVNY€™jÎ+ë¨\15\27®\8~\27˘ˆ„lX\23∆¯Mánìm‰±£!Á·'O\24n§Ñk√≠·Œ÷p”˛pg@G1àmÑ–⁄\24Ω{¨≈n\13¢-EáÄÛ\27⁄n˛›6)º%€\18\9ü_\4˜&1õËDa“≤√Ô,¿Z\12\15äi∑\21€ƒØÌUõ†®] \17ed\20p\3J¡™Æ.øùñ˙Ònâz\8\\\21üi\26-M-µAÈ§|i\9_%BŒR\12Si_ˆÔñVíù£\24§u¿\127$°DÜ mk˝N:lx◊Üûƒ\4†@ î\9∫A\0169V5Ü.\23\2ìÊãDˆπZjI+µ|ïä®6XjCE\1ó»Z˝ŒEv‹µèFÃÂñjví∆\30¶FÕ˝UÅv.∑+ÛJªÆ·)L\26e\1»o\18”ﬁ\12æøJŒÓ\15Å¯∏√|uY™®AD•`ÇπI≠⁄5d,ò!øroû-3ì\3Ü\5°\11⁄dqa |_\14À\4Fæ”®\15CFjVtd\30\25KT_…97]sº¨⁄†¥†!2e˛èF*Õ´\0040∫µ¸ó”=è7íñÀª&†N∆›Yu\22‡\26π›(\23À•éédÁ≤ˆU•G–6…'\29\0286\28ù]éëÜ˜h\20◊£=CÃQW©≠\24ü;%0ÿ°p?¬Äâè¿°Gê¥#4Î\28ÓÜî\27ûˆG¥#˙ùN˚Ö›á\3π\"˝ëÏ¯ˇÀCä†ÔQx’]éj«+B%Î˘≈±œØ—h-Ãü_‰ }Çı2≠Ïã‚`l∏hNq¸¸Rû\127~ërû_z\0251íËBh†¥ùz[µáV÷,,+\4pÈ¨¥ßé+\11ò≠Ë∫%ËE⁄ÍƒH\6§◊¢É\5d\0I*Úii\5≤DUØ\"m\
 îWv-ø?¨RU,TE_í¶S∂í\\¡Æ%◊Æ·“0!µ≈oÅíE°]⁄kàQ®Q^L, ÂÕXﬂ2\20oTﬂû®œÔW<4\
´¸`¡oÙ{˝\8\13c√E\19/”~Ûr~~S°\1eÜ⁄€?T™zI\2≥°DµJ°\23†ZÖÛ£–/B≤BΩJÂä\13Üzgm{\11’ˆ\22™JØU\5πÍ\31DUU÷\12GÛ9\17Ä\16øhπÃ[Uù\1‘\4ÒeU\17¨kº  ;≠G\8\30‡ÁpH\20ˆêQË6sVô∂˙™˝T€\30¶?:{4/>öu\30≠ñ<∞–„Â†\7ƒ|§|çxƒ¸#[O\18ˇ¿f\31ÿı\3•¸G∞\15ÌÚ\31XÔÉS>`\13BŒŒŒ◊SÙ$/ú¸Ö‡ÅŒX{á\
aÿ)ãü\24¸$∂xeA“”â\3')ı|q˛t\15„\1˜˘?Zıóe",
  ["length"]=3439,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=647,
 },
 ["version"]="1.001",
}