return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["characters"]="abcdefghijlmnoprstuyz",
  ["compression"]="zlib",
  ["data"]="xÚEÍA\14\2A\8DÑ«p:\20ƒ8ƒi¡\3¸\24Oo':qõë­Š\11\21\16ãVâÿ.º©`\24œÑ\22N±\13Û±\16yÒ<l€\29}dL\19š©¥ÞWkx¨ôÕ¢T1,‰õ¹\0‰\29nx³‹.ß\17‰çï*µ‘†íõe3¶¡\31MÏ=…",
  ["length"]=168,
  ["n"]=14,
 },
 ["metadata"]={
  ["mnemonic"]="us",
  ["source"]="hyph-en-us",
  ["texcomment"]="% Hyphenation patterns for American English\
% \
% (more info about the licence to be added later)\
% \
% This file has been renamed from ushyphmax.tex to hyph-en-us.tex in June 2008\
% for consistency with other files with hyphenation patterns in hyph-utf8 package.\
% No other changes made. See http://www.tug.org/tex-hyphen for more details.\
% \
% ushyphmax.tex -- patterns for more hyphenation pattern memory (12000+).\
% Also known as ushyphen.max.\
%\
% version of 2005-05-30.\
% Patterns of March 1, 1990.\
%\
% Copyright (C) 1990, 2004, 2005 Gerard D.C. Kuiken.\
% Copying and distribution of this file, with or without modification,\
% are permitted in any medium without royalty provided the copyright\
% notice and this notice are preserved.\
%\
% Needs extended pattern memory.\
% Hyphenation trie becomes 7283 with 377 ops.\
%\
% These patterns are based on the Hyphenation Exception Log\
% published in TUGboat, Volume 10 (1989), No. 3, pp. 337-341,\
% and a large number of incorrectly hyphenated words not yet published.\
% If added to Liang's before the closing bracket } of \\patterns,\
% the patterns run errorfree as far as known at this moment.\
%\
% These patterns find all admissible hyphens of the words in\
% the Exception Log.  ushyph2.tex is a smaller set.\
%\
% Please send bugs or suggestions to tex-live (at) tug.org.\
%\
% 2005-05-30 (karl): in the past, ushyphmax.tex was a file containing\
% only the additional patterns, without the \\patterns command, etc.\
% This turned out not to be very useful, since in practice the TeX\
% distributions need one self-contained file for a language.  Therefore,\
% ushyphmax.tex now contains both the additional patterns from\
% Dr. Kuiken, and the original patterns and hyphenations from Knuth's\
% hyphen.tex.\
%\
% The Plain TeX hyphenation tables.\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnopqrstuvwxyz",
  ["compression"]="zlib",
  ["data"]="xÚ=Yv³¼²@§â\17d-ºÌ\7\27\25ó\25\16¡±ãŒþî]üç>¸$Ô7¥j¤’üÕÞ\30õå«íê.­¸÷b\7Ž•pjZ¹¹\9{“ÍC3éìñQí)>†fÃ]OXïC:Ý\15ÎV™y+–€&Øö´6¸{žtŽ¢\3¾ê\1øž)öÚÖ½°™[­¦´kZIÍjXª¶)¾¶=ã®C\9<v*¾|ÝÚ©^’n4ûÖ.msÕ]›<êÖté–ê‘‚¢ç·Ç0Ž9-æ6ì\13ÃpË•eä:ük3;6]ª§<èV9 Ñ‰°­¦ºn¸íC¦[]¶žîˆÀcº\18”Úu\127„»UäHW*OÑ¯ÔSs\26›NX%ú–ævªtª> ã–~šch(”,Ö˜6\19\28‚O¢Ø{\4Üiìdcû–2û\20€yªu›LiýÐ´ÂšQé£ƒvî\28\0Üæ‰c¦GZs„E©´\11‡ê\26Ðò\31ynÒ'\\Gã‘_´aèêQ˜G’\15S5\9›e˜qçBPÝ\6\29«\24æò\25AtnX\29õa\19\11þ\29\21þ±­oŸp&áÞ¤\8Œ\17\28Í>¦¾I:âÌ˜–\8\127QÉ8ˆ?ãÐÛÏq(g¡m$‚á›Z\"\26Ý±É:³é&ðCô™,š\1\20k§ÔìÖ:\13[\17pwD&:œtªÕìG³›ýØ\3ÍæÁ\9Ï])è¨%ß\27×\8³ÒŠ«9\
Î«8ŸædÇ7oõÎÀåýáÇá`/©kÚQ7\
Ð\25H¾\12.‡\5\28›uJƒÖä@¯­U¯íl'×V4t\1­É\30­©™Ì¾¦íüÚv—ö\26Cµ‚ó\7N®\127„›H¶æ·è¸\0305p»\13vyKã½\9g\12Ç‘ÝX’.÷íA¹Û\16 (Å¶\7`TèÄö!bo\9ÙS\0ÆœÌ»™ö!Àh8ÈââÙÏ\"pÄÇ=Ïu«S/ÂÅIØó!±Ù×áÚ\0284÷˜‹VXÝ’N\23\20†Àø²\16`Ž\4tôX\24ßƒQ\3nNþ\11\28ê’nÐ—÷\16ôàCSëöúu¡\15Ì„p¾´W†³½‚\29ŽK‰\15Æ¯½ê\1?ur3\14\127æ]ýZYuíµ:(¢†\12]Ú[Óš['Sì-åƒ¯\2Tãƒ¥FÎ’eÒ²V’\17,\31ýÙ,k¦¢\27ˆxÇ‰2oõ1]Ú’\2!á&íhÜ×¥l;‹è\6ZØUÃM\7ÜY#,\7¤­M7\28f\28“©òÛÜ«Ýìêí \29ÝaÊãf¸Õ$èE›V‘°-iÂý^Ó«ÞÞ÷mM>ÖäH£úTg²÷‰ü}1è­\13.HRöùRµ½£ÒWy¦•M\127Ø°¾‰1ê?Ôùh\5Ôò0_õ ÅàIÛØ\29zÃ¤\12ÍHÂz°V\16e8\29ÓA+ø(þ]Úg¡oŒÙ\25«–1‚î¯´fdpÊÖ^Coç\8O°1*\24“eŒ´¹\29ë¡¥¢1z;\18ó2ç8Üt&ÓæþË¬Ÿ/C>Û\5Â‚³ãŽŸNŽ\31Ñ`¢ÍS´a¢ßÀV43hc`ë‰µºé\6‰ 8E,½ôÃ‰\6Ú×)0a¢Ç$+'q\7bD\8Ô…æNKô›U\9cfè©\127nÍWÍb\29a+%â¯‡\8Û\22ûÎr©7\19t¶c.:Fœ\5!6Àø’‰-\24z¿í_ñu0x3=™ûF\20‹Þ‰›\11›\\ÍCŠÒ†ên9Ã”,g˜†pæ\20q9\18.áß\30áì\17t˜ç9\14Œá<³ŠÚ9×Öw½’ÿv.·ÖTÛ-‡3GemÕr\6í\1\15»½3~)•Ð_‡x.÷5‚ÞV|´\1]áó!rba”€Ê?Àä:­\22x\"±ËƒŽÔ\11BCkœ.…-•s\3ÜEÐeØéG¹Pæ’oér$?gjè[ðÖ8RÕBÚŸ\3\30^¶%E­\21\11ü\"Ž@“`KmL\11¡c\4Ni7˜æ÷:\21ý^ëöÌ°;®²šá\21ßG|½j\19¾…×\24Œµ¾=\\ä+ËßùXëÎz\27$\19š³:å+Ë\"ÊL›•×÷! MX]\26tÃæ¬Õ`9H@P-\17kŠ¨Ùæ¬1Éké\28®å\20™2<…2cÑÃ>#ÞöW?€5EÓœÛµ\4'êv\3Û¶Ú…³Ë”¹=\6Ò4[¬Ëj\27®\1o®»MæÞnOD+òˆŽ[\6\27·fy\24 Ž1èâñV8û ‡Ä»t¾öª…K!c´·ø\24s|Ð²=5\0065éö0&õ9œù+\28×©Â,…*)ÌQT\18ùÈ!±ØÍõh’Äb\127Xù^KÊ\8Ë“ñƒÜe—¨AÒ\17 Ú=ÖÐ^¹ì™Møä\26ŸâS½K3Käf“çÉ‘%l\9È,E¿\16_\13Ùëí)Ü%8»\"„\31\15³\31\6\28Qåap >pá€^\28ˆ†íÑ#‹´GÕ\31\6ŒÐ^Xhg\8•À|\29ûã¤´G\17\5¿Èÿ\
\2×¼ÄŠW\
Bõ:ÇéÅ*šO‡*^\"ÑëäG¯jèpºŠW^¡[ï–4o§ò]KÁÞ\27Óþ[;4@ZñQ6jåÐíÇ¸¿³¨¿?–\23|úër…aõ\4©L$àˆ|\0ÿn:Ú‡[\27\6Í\1®pq¡6\5˜2\\Š+\8LÎ¿Ky-®—ky%yuµ¸+Ô·½ÔW\4¸úš¨'µÏZˆÌF\0l\24í¤k\3¦€ƒ°\23Âæ(:x‹1‚A42¡Q\1fFAç0h³Ì\
š\22J\14Creñk˜s‚\8!\26ò\5\0204ŸLSïä¬\30—ëPÒæ\1Á­ºBóè\30“t\1*¯\"Vq\29hÃP)¤\\Y¬\13´\14—\12¤­\8q¹_ýB2¹*dRR%qÑ±5C`’\15EÀi¯\14B\9–\\O\17ý\
?epB8G\2Lö„ú6#(e<”R\25ÅÉ&Óº™Á¡ØL\19rç´dg\0085‚)¿æ©¾\26¤\24xuIØ\30ˆGsÍ\8:”’W# f\17”\2Š\7Ùa„s\24\27­B)£öŒ€èl-ü}/×5\4ïòÚ \28_·Ìp”W‚wÈÈ5rØéëq¯ï¢À¼\3¬œÂ\3nl\8]8Ð‰\13~\0027\25#ŽÚkƒkoÑ\17hø\17ãˆÔ\
, \18×æM\
Dˆ«˜\\ ¨Ý\22á&·¶€*ÝB?¿!©1‹È\8Æ%’ãƒ Jqó\6E\31Í£\18\27)\24`•ßNHíBFÑ Æÿ&ÖÿE K\29ç\19…/t,Tä\9g\11e\11\23ÊÔ[âfJ©\7~YËÕÊú»¡ËÜà$\13ÐÕs»åi‰/¦JxÀåÊ\27ˆPßRwB:ŒÎäÜÒø¥\23i±¸¡óÍÔ¶™”°\8ƒvár¹)™O†Ã\30\8ÙX¥@È\16DS\15\3‘Ð8nM‚äá\127;L6øa½\15\8<UÂô\28‰G£ ÂX¨é\2`Û¦I\31\8uTðH0,\18&Ø#¹\21¨ÃÙL¨\24Fa°NC\25uyd\4\12áD\1à\21 üÓŸ­ÆÝ‰âf¯ ÷·¡T_Ä‹Þ{\27`25ÂþJöá®tË\23õ\15Î,éÁ4\20‚I\0ZÔ,YCå²@÷\11Ô\17z:\15ü²\12è.ú\2“@9\11=\24\16^Â?DE¨e§c¹…-\29v±‚œ Æ³àWÙØz´\4å›\27ªÍ)^4~Sä˜jçCi\02401ô£¨\4/,\16Ën¹ÐÞ2\3\\Þ²¾\26‚rË¬–[\6¹É”U²\26\28SU6z\
Ä‹…~«³cŸÝ\1\1:Á¹Z\8Ï‹D\2‘®ê[^\25Å¼fˆÈ-»ØnùU\8’5½\0273ü5\0067\127Œhñs¹­\"65ÓŸ¯Ó±<ÔÁ6BAƒúÆ\"\22\16IÀv÷—\0ÍF­ÎÀ:°RI:0€·5Z‚ƒŒ§\19\8½™b6û_Ðv”_\26ŠP\17ó´+ÍÜJ¸ò­r‹á\6rÜ\14â\7Ä~œ£Ž°÷åvt¬§ú°êƒ˜\3Šû¡êcôc¬Õ\28*<0õÛQ¢h \19\"oßŽz\18Ó\14\26{ šqa\17+óØŽ\3¥½e¢\14\224Ê´5z4ùBL¾AžXçõí€ð\0217rþ1žEW¶\0238(ÊeWYN\23´©îÚ;!Ìw‡VR\2³\14\29·\17>\27SÀôa‹»Þ(¹S×¡,dÓN¡@ÿçÒÁm;\22CWt¬ßŽõÕ¥öN1IVƒSCÿq$_~±4p@\"ÖFW8s]ŠLªM]\
Í\13\7ÑêÇ@P­«Y.ÐÒ\9â\3dæK®s‹Äâj”ªÍ`8\
}NVX«Bu©bau*ŠÍ=¾\14`±è\0053»´\12¶ªDžïªôc]ëÃÊÖ‰àu–y»3aá FW¦Íj‹ÍF”[cÙÈ¨ƒåÉôUË¢\6{ŽØ§÷\5@`\26íé\7PÐ\16ùQW¡r“Ne»+{‡òQR7\2&c9T¤\24¤8Ý\0\13§9°\4\20D·+…)+{Z8p\3…™rt’:É]Ñ\5Ñé‚æ©5P\11²\2\29*ÜMà\7ÿ&\7+¡\27Vú6\20«E¬n™uîŸ‘\9šM½ª>]éÒ!«ýA|èšgIg\26É]§ä ì\0022DµÎ&Ò)/‘\
õ³\27íâä\8Ìb&4·ËŒ&\26†¸”\19Išìà@}º,!íòèüdÐ€±…Ö8\29YE\24gŽ¨\\uÀ¥^Ì·Zäf…ù0\9¤€€_ª]¨\"Ö¶o@G”§–ž©¾\0$è\13.c¹ºÇ\
\28p÷Š”(ÕÄ\30\11ë—¯h+*lQåö\22Ð±\18^[tÌ}q ·vGé’8nzo’È\26wÿ:\29°éh\16*;ä\18Ðà\24\25÷\3‰I§¶uÇ¢\0156ÐÅhSG\9\9é>´ðSo\4\127P’.©pE§Ð=SÛ\21\2e˜\20\0024ÝRšæc\4ŒMø!Ú\7Îä~pjÜJHª©Âú&T½õc¸Î\24Oai-+Ú’E#\29Rñfâ\0139:µ\17\27Ê\5Î\3’˜Ôiï—T·Õnå\11ðª\"Á\11\20\19\"\2'è\0074BÑ\"œ-œY\8ùHÕ•†‚ÿ4ô<\30H7d\31ºÎZH\12ì†p‘nå`\"ô\27‚äÆàÇéK§ûÁ©àÆé¦Ê\9õ\25 ãI>9…\3QM0½Ñ<M§³D’\12ã3nµ\8¥Ö\4_Z³-ˆ–­Éb‘`æp’\17‡\17¨hÉí¾–>Bj/uê@Õ\4ö;ö±\127C\16\13\13?\"mþ¹í§C©|ž$ÍŸ)³ym\"˜_ê_ítg5]s°Ì\18Í\4(‹ãeäÓ\24^Õ1\2&½P\4àR\24\0CLÉ=_BàP©I¿4Þ\25»ƒ\30éR¤{|¨¬' eÝ]\24©º»\5‘îä„\30W„ÓPÏ1Äžú~l\
©GàL½Ç%©oì]\31hÕ+óP]Fâ—sÝç¯€dï\11»„âÅ¢LPÅTÀ°Ò#Š«Ã'(c@VNC_êëIÎx¹\18†™\22\23gñÃŒ\4Ÿ†µ6e`-ŠÐÃ\8;\11\5Kõ¿ƒ¸\127Íá,<Ý•LO©\14ª\30\0ßW@ª\27Ý\\Ã9·i\12|\27øÛ:\26cjJWƒUn&H&¯\24\2*\28\3Ç˜÷btˆF§g\20kQI®âÙ\24\12Í\25sþ\00951½ãÖŒ¢CM¤=#’É.UÍL±=\"è…@œÜàJ*\23d\26Ç\\›5Û~‘(</ÖáN\13©öhÛ\17ý:ˆ®'»\
tô&ñy‚B´:\20W £€DÉ52¡p¦élê$Ã–\31÷®\13÷;Ëø\20CHRÍbéd[§³­°lÉÆ\20ÒkšdHðm\8!pF}5j‰LâÁÔ¸‚Òt -¦jbæP&'×Â¬@†\2òPKNî„Òztá6`2È¥9ÇV \14¼,œ=¢`ÖH\3émØpÛÌ$µ\0ŠN³C|îs¦Øç4â ½6·Nó,0I4¼žEÜ¹ÊàÆ,K@ÞhÜÎ%ÑþH\17‡îMMH…\20îæ3At\\~—ri\25\
Ú©r#.·¢Š4'«›&)Ž\17.Ù:ÓšÐŠSp9 \21–‹h³ÀÕÒÂ¬9\20‹sU-*d„¥}P\23HË#YˆÜ\0129È\\VQvipÚó\19”X¨WÄZÖ3I\6\5\22·äH¸«Á\17xDÁªÈ\9!=ý\28C%vüTxèó\
\31L«,Š\25\
V³Ú/?ÜD+\19z\0«\26…Ù³»‡~”8Ã¡\30‰ú%\31«¢¢Žê5‚Xð‰•™Íñ%zêÜ\28ëUÕ/Û |Ô?\17'²­±ÅG˜Ôn-¬«°ÿˆÔh\5i\29nOk\28\\¨kl»%P˜$Ù¢E\1Øá\17ñ’€uxYw5Yb­nJ*È¡Å\5N¯Jže \31Jº«xu)®žßR½|x-¢m›ËIÆ\26ƒ³Çx Hà7\13ò½e¾[>Š­vŠ6pëë?—\0186é~¹9{[ssáV›Ì‰ÈSºr7'ykÒ\25¡âN~jûúÏÝN÷%£\
’²=,ï\17\28½pí”nÛ\
;K\24”²u{ç\0QX\18µÅÙ\14+m\11N¸\0135\13h¶§s·©ßPDÞÀó#>¢Œl\17…\"ÅV¹­AÐ2HN6±‘At\14ÝæSÜA\19F|\12©»7%\
˜MVØV\6§DÒ»ºÝ…Ë¦_‘À¬ìˆ’U§fÍ„‚—ö\20´\29¥ŽÄû#wH3±¥ëñ-’)\11Çúö8Ã1l\13\24‹\9Q9T£´Ï~D?ª}=¡YÁ©›1«’\16_’a·{7¿$\9{ó™„R\21Çêpö\16ÿÒáYu:\\ñ‡'°À¡aè\14w\18Ó«-\23ûôj)éÕ´bwó’ö!a${Ií#L–ái)ƒÿ\
\22D˜+¯x\25R9›¯A\25±~9M¯@ïæ%®6/ñç-Ê½ƒ+¼¥«Õ\27ôðÀ\21ø\31Gzƒ÷Eú]@ÔÒÂGôŒ½±{{¹·\21küÞ^«\21X»Tï”vo\29×»›`\17\2ãáK&qiî­I×\6~Mî=Ê€šŒi¾·hÏ¨¨wÈP}Gƒ¼SÝ\29A´\22º/xOR»\4­\1î—ò\14Q»Ë'ƒxÜÓ\\\0262wÔ~g%š\16Ì¸'ÔÛúŽ\24äÖá&„-Ü\27D\30ê(ï60D*>ÐæîHýw\
U]+ïqÌYë@»ÂQ„<šâ“%CÊ\27³@ 3Ò(Vµ§“\"å\22\9\14 Z\17e\12ýƒ®Þãxû>ü·ax÷l±¼»§uWÉ\3 :á”¬;,\24ež°ÚÚ67±îž\6Ü›ÐÉîcŒû\24œå^Ž\31G’%tGe¼£àßYAü<]×Ù%íÍžU]”ñPúqX\3:t\2\8·ÃÙbN–Ë}Õbç\14C!t•\12á ºÝC¯ºÃÊ\26Ç\
õðN29ÙÝCŒêN·C/B‚¤\3nˆÌ†Ø©C“\29\4K˜$PÙù.ã)˜ƒ\2!«oï\16r\4NôPà@€šgÙ#à÷m£ÀÒ‡ÜÐŸ{ª½ç–\127~!]Còð\24·6\12MZ#\20‘ˆˆ\5Þ·$®®—ÞM\14‰/ »ô)ý‘\18YŠ†öŠiÛé°š\9µiÉˆZ…µO¡|\19AUÂˆ¦V˜>¬=dAcƒÒöÉo’ìÆ*›÷njÕ}ÀÛS3MQµëûñh€ÈyýCþØ?B\"è\31Ž)òõ\0235¸ËÛÇže/Q#TŒS\18§p\24^c*{ïäô\8Òîì\18?\0274Ó\"\18ðµ™\14•½‡þñƒ`v\3Jã‰z\25Å hý\8W\5h¡„t\14‰*zTÜ~”~÷¬Áž´ÌN/\14Ò,{d×»‡Ø3VT<Ã©éHôØ—³]«\21É\8ÈzAÑB“\4Õ†>_íCN¶Zq¬Ï•ó –T÷•»\5~t¹1ÆýÞ>S\8ølsÁçlû³#à>d_-”\13'Fžíl;\5ø)­ÁY\30¤ktÝú\0007hÃó\9—Ž {ÌúYn_ºPGÊ¡Òõ\0Mû!‚91\"¢X\127Ðíª?40)ûÃá\14£1‚œ\8TÓºW\6è«7\13cÝ÷Í\7a¸ÿh‘à.9Sñˆ]½Gë\6¯p¿<?\15ü\21Òó£\29ÛÊˆˆQ”O\7|ÓŽì+¾zaï.A¸ùrn¹ÿEä3 -~´Keu\8\22®ÝÉÃSë\13g… \2»Êd«ö)8aàð”GÉ[cÊÃ#¦GkÙ\127ÐÍGq½\20„Ž_\1I¦ÂO.„\21Ö\13ò=å¦Æ\9|@Á¡8\15u\28æ8Ü\9Á¦Gšê\5X’\19¹°\22zîôPz\6Â/U\21¨.Å\17¼\26å5¾Rã@zÖùPY8âƒb‹d\21¥[-\24S2ÚrP8\28â ù\0244‹z\0125Ëé\1±¶’5ð`\29¡±>bçÿáÆ~2\21%ÅÚy\12²wýg\8\13\02868·\14Äí1x\4m`Éº\127<ù\21¬Î‡zèåQÚ[×Î`8s:)×–Â\14äÎ9Ã¡\20WÃ#C<€£ÇÒ\21®\13É2ÛGžR\5tÙ=r\3=\":Ó¿ì1Ä#ìßŒX\29é\28\27?~1<±aŽ\127sn³†¢Å#\31¦Bó·ÈWPñ\7\3W?\28…5%\6fÍ'B­Y›\15šÎBx¨S@¯œö]Ó\31ØÃ.Õ{¸=ö8ÙÀC›°¤ãD\28›æ‘\15—Å£x“úÝ®x?H\1)òSÂ_\6T¡„\23\15-rú ¡\14HL\8ËsPK\26âDY?E\13\30ª\1%ÿC\29„\31ý`W„óó¸ ª\19sÓñAƒ²]gðCò«\31y:\28Êñ(pð\8õ‚¾”ý^©úÊx\26pØ\4÷uÑ>Û%üDkmöu:”êy^||ðßÀ:·€³ðAßn–sC~\27<E²£·aá£\26Ð\5ÉÅÊ È3úzp³ŠŠÖˆX-ÎÕ<Üö£\12¿²èpîV\13aF™\7mF\20Y©Š:ê\14:8t¡[â\16Ò%í[†ØÉ\26Ê.bµ-\25:F‹¾4\0292ÍÐiSBdvˆ\29-“áw§Øba~CØ±\13š´Pé¬¼\28\28íÔy\28;$˜;\31#Ò¹L«5Æ5åI9UVa\
6\20žúñ±Ýô#\20ãßéþÐ{l\4\12÷»\20i@†[P`\27*e<àh\8Â\"\12jèÝz\31ús®\17Â\2Mzê¨Ü’!b\24\3Î\1©©Ö\\nÐRŽ\0T÷¡×\0j€GPv\127À\11‡¾`4‡êAI\13‚ÌPýÃ÷¤©\14û\24ç3îàw¢(ë•\25Ãî\12½:Ñ¤ØA\26F%TäÁ»\1ƒùDÀ±´Uc\0126$r³\23£Í\26µæQpl‘ˆ‡q6Qþ1\17+ŒblÑXé±ñ3La†6hïF4²À®è E\24eMÖ‡„\14_\28&´\17‡\127ò`xëš`Ò4V\11·¡œ\14K‹ýOe\9Ô§\
\21VzHe(ìÐ3m‹Uz‡\25tš›nT›(Õ»‡Ê-\28|ë‰Jq^K:@hT£låÇ\16\31‘×Ï\28ð°\28\23È<DÝŽQØ°\13s\1=;w.¿@¬949ã\24\15r>\5£¹gé\7ò†Š_\13B\1·øpl‘‡4ƒ¶!§Y\18A¬} ‡îTrXÇ\17†g»‰0 ¬\12A‡\\\"a\12\5ªð\0)\6Ìžd\6—pØ³DiÈÚA\13yÕ_£1\18`Ñ`•‘Šx\4ÇòdÕ/\22»<V• a1Ëâf+p\24-††êÇeþÓ\28\9äq›¦;Ê5bƒÄµõDÃµ%÷ªv4P‚(II÷€Î\28\14-Z\27Gß½”aUaÁ©\29ÝupÏ¿\25š°%#P\18>¬ò£\6GtXµ\28-\7\4¤aóà\25öçLo’<‚‹›!š\3\12\14òææ\8bÝÝÔ\26Â\17ò\16Í6XÝâ—è¿iA34›MØþSÍá§¬°-8'\31“´jcè¶\28F÷ƒÜkØÊ….lõ\"\
xåA.,qÛ6ÍaüJ\17¸·¶·v\2Í³+¸àVÓ—ÛaÕ1ï‘Ö=\6çO£.ƒ\26f»ò°@(\"YÔi—6(#‘\22!CÖå\\[\5¹\6±¾ôÌÛC\127•ZÒºgå'C·kÒx1ÅdÆ@6™\7\15›'#\26zk C\6G“´ì®p‚vK9D¿f?ºø\14î\127´¾p\25±\\ÏM\5XÉ¯°®ÀM«ó÷¢úÓa\\_Aâ›—F=d\8“{sdq¬Êÿjf<XõŸ\19þ\7!l†¿<ï—æ_{ù×Þê\31 rQñ/]þÅÙký\15Z®‚¬û!ð]]þy:×ü;:”‰'#ýÔ^ä)&=[ÏúŸšM>‘,Ÿ%2[ñ„œ<\19ø÷T?#uìú<¥¨OM·žUXÊ>CÝzV÷Ëóav´…'\4¤yÂn/ÏÚa~\14#’èSÃÉghIÏ!”åç\127V%~R²Þ3\26\18ÛÞÏ§Å1°ÏÑCà'HóDt{JÙh]\9y*§>ófÅ\30Ó=•—Hª˜ô¬aiO$Ÿž6>\17¿Ÿ\8>£fG·ËX·\8\24c{c,ñÓ\24\4þî\3DW\2N\21ºÒè\22l\28dŒ:HBñµ›x¥Å£æŸ@e;ØŽ8êiròØs<µà\17Òn÷B`,G†vÔ\4àâV^Æ\27tfô®H9ROi#<MÿÏ¡äÎÖujßc\5§\31ã\4kLe\11p‘Œé¾£ÉÁê¾\2ö†O æèA„Ø¯Å7\
þèî¥§*\16ðB#pR(ónT\3WY7\14\29!í\
‚Œg\11j%€Ñƒü15š\"»#òc\"­ÆP×Æ*½lÑ«\22ÇO÷\127ß›I?6ã“èæý\2\23^í\127OÏ\20PÆžA¤\30·eG´M\18ÁíÑ{AË\17±s\2jmû\23a[@èøˆ<\8¦ƒ7\6Fu\9Ku3H\8ZÂÑoÇÅÃ¡\16þ;\14Þ\25 =ˆV|xbgªûÝü\0082\20Ö»ë¤¶\29-ðx†\15Ø\27ÉÀ#\13€®á8ëƒ{bD¨B¡³\20:LžÖJm8&›ŸÖJ{s\31\5ýà÷ |tÕ#jhžƒØ!\26O\"e'_ÑºÂÝñße|¶Œ\17‹vÔ‹Ü=².Æ8S\27Kd\
ÍöÉ^y’6†ä#\28\3ŠÎ:dòøŒôb 9lò8BZÆ1ÿ ?ãÆ^\8Qˆ–åÈÈÇ.Ð8Å–åH\127ÁÒIM\7TF¹¯FØó˜¯ZÉY\29¹\30óÝàÞ\21F‡s|0\0139ŽÏ)Ø‚²;«£Û\12Î*ú“(œ—daòa\15Ý¨<ÃV-wùÎq\3güoóató\1à’ô#/\15ÏÆNßÇ\24û›=°\27s˜ô¢\1Ò7\26øÂËèÇ…¹‘5à°kí>.qÈ:jÖNg—Ñð@ÕÕþº\2¤(c\9sÅ'm\29Iè©\21°Q×F¹Üèî¸0š\31çú#³ê~Ñ¸KÝF-˜GÕ\8€–\4ãÑ\8<·\31\15w%ð3˜@ÄµÑý\15R xŒ‡:h3\30“E\30Óü\21\31\
j¤eŒ\0147‡êñ {Ú;\9½»XŒ1«/K\3î1\127o‚]—ŸVÀP|˜l`\28ÁŒnDÍ‡®\22TYN0Š©-AÑ©=m\2ñ .]¼fæž*îl²\7!,³\11\13…¤Mmì\\‘\7dÃq\11\"\28­»¦Ö†Oçæât\26l’m1ù\26\0228áùÃY\21\24p¹\9ÛnÖ.Í´r·¤]¿;CÔ(\23Û&nRNÜéÊŠi.S£A0+8°yººi_OÚ$NnNNÚUM\26p2\14š\23LZ\25Pn“\26øÂ”J2y*<ë€]“ö\1Sš\
hVá\14 ¿Úl³\6öÓyÙŠ\18\29«8K\0002ªÂ£¹Tê\9\17aÛS\20\11Ø\28l(!ÑÚ-NaçÉ\"TmœRq¦ÝÁÖ©ö8Öõ©®m Ëcò\16ÅÆFßŠ;…=H\4;žÜmŸ†®>!}\25 ÀÕ„ÆC\8tg4{pk\4O·×&UŒ8•Žˆ¹\24µ†\8í\18E÷ˆ<ðg\16k*L°\\N€ÛŒñµGžÍ¶!×\"¦MeÌöÓV’\4¶>ú\19ßŒD\12dí&&ÞÌð\"ÿLY…\\èÜ^¦\\vÅÅSð\12D\28\0216›CžŸøåM´-3’ÀàÝ:}|Å`H†\16õN7’ÎQîœ\17ƒüú|YËj‰k«?*¡ŽÑ\27˜\26\22Õ\19\20\9ª7¹Cú\24yâ–\22¦ªƒ:zOôÙ©Zl\8TGTP„ž\22·›'ˆ\15Ó\14/Ñ\14ÍË¤k„\17´Ä®\21Î\22{$$‰Š\22¯¢N\11’©å8p®ýI:5¹A4!Óó½3xLÎ1†ý{ƒg÷k\31*Z|ÐûÃ=ß\9’1\0295ºæ\4]€/”sÑ–×\11óp%pnQùgïõ]Dî\29\127\31×ïf¯\5\16\1NÌ.òÖ´£ñq\17sv×hng…¬Y\3mcæÈâ\13QÍ\13SøÍî\30Ÿ\23A&kÝ\8ðªñ\28æÙ\22dVä\127ÒÀ\14\26o…\16xðu¨RV¸¦xiV=\23WªÐÐ›¢n\18^”æ‡m¿=R\14\7J`\24ã;ÇÍÃù\22»åPLg÷~f’æØÃñB\5i\
\22´‡_J½sçÎ<\17åp7ÆÜ•ûˆ\4\29´»Ó¸uîÊ7R´L‘€€ä ¦kuèE\"›\19*\9\9:¾=8ÁéO‹\25¢ÀÕ9®pÏ\26­P´† \6±\28\
/«Õ³Ô\5½?\27º\8Ë\31Z“¬)D:µcëÕB >\26\11pó´PŠ¦f·Ûgo.èßÃÿ¶H…ÇY:ÂÒyECÞt‚¾Æ=È¹ê\17/fÏi\24q—•å{ÄBù}ã`Ç¦ÏÜÇèj¸dNûÒçWm\26pt.z‡¸\7\15g­9™9¸ßüh\3\\+ \18r\5â5KI,–EÿÕ\16¥±Y\5vvçL¯=\31Ê»þæ4j›5³áS¬+P@È\27È\19æísð™9Ô\15rgCD—P[iS´ZzU{\30nydKóªÄ\\ü£ÅÏòâ6ëjä“µ=?Ýàš‹çhwDiê„ \11 „±àæÙ\0»4ê8ÊÙC‰9W×ÑñÌ7³WÐ8ªÎâ4Òã\28;!sVQÇiÜ×o Vˆ[›É´ó›ÿ\22G\22K(oúè§EnZ[Ælfø\4xÎ‹%,q——¸Õ-¯Y‘KR<gä9v®ç¸/M\30 ÎH`TwX¨j.ó”ßÂb¡yš\7ÏËš\\½…ØÈH­G-I6Í[T±ã$‹%®@5×\27Ú$\1\3D\29\8o\"œ\1Ù*é—ÜH¼84\27DsþïÊõ\12ûŸÃ&aÞµ\
Á)íÝ.êí':ìà\3s³+´À®‚û\27\7\26íž«Úñ½6ë!¯˜µE5lŸ\15·=ç¸\16C\1\7ÓZÍG\0218!Æ\30ÚwÍÒ\24á\14qu0äÇ‰\27/úZ¼éÆg\18,N=ÓR)•äö’Û®ºdoÒÒíì\17\16Ð‘Îq1\5G›â|­ÚêJº+‹8_!\6—\\ ÷ä\0185’€X³‚cŽ«×Y\27Ï¬\8™«¸coè9—\28&äù4ÞÄAŽÏ·Êíª|kNvš½\26p\1ï<yË·]T0‘›‘¹¹\29,oäô\14BåÍ%2v>6\0~fêê2*\28Ña®{ºtª†Bä&E\11™ˆ\28²\12Þ\23ÙX¡ù\30ü,ß\7Ï-sé{\5¤úüe©!\21\20\16Áì¾åéd#,\12ê‚lJ4¨Ÿc7™\8ëë\17^/UîÅo¯c#v’‹ìA €qÓh<C`šK\30ð\0137q/\15•oƒäÁÛÞY\12Ìî×Rp L\30æ¸0”\27…\6E\13D¶ìk\9I7.8äæ\31U<Éñ4ð©eqv§ZËl\2Æ8'Éhú€® rŒ‘Q›¾…Cm£·P³ª\26\1C\27ÐY…\5 œúUß/®×ÑìÑ´FóF!´Ë0H«_Žn¨–g$ƒ:Æ]¬jæð¨\\ùµXTiÝÕq\0138EÛXádDÚ ÖYcdóä­¬¬H\31þÀÉ«ƒ9”ã\\š\21m\15!\".º°¸sX?ú¥\0\8I²WS\24~äÓ$RšÅ˜ÄÕï|î7yš¼³ž\21ñ¢\12Ç;ì\28ó´¬™¹+\9ðE\4)›Ã7·\17pcúg\17¾Ìæ‡!g#‘Ó–1ËrL9D.‡'v¸s\24,féøÇDà¸_yò\11â’çMâ\22N,\15$y?CáË>?bú}¸7Ö\4‰Èó\11\0170gp,»-,$I®A‘Ðts•Wš˜Á\"º³Pä‚¶\1”…£\5»R‡ÓÓ›Åi]ÜÊÕ\17q–sþCe%Ì\17B\12@ðËÅbtAw–\15eCˆ³[Õš¤0êõê\13V×¸†\23º\30\16ä8ÖÍM˜\17²¤Ó\16AbÓzJ=|BÒòêøÕ9®×¸Ù\0303¸ŠkÌ`X\0\26±;Ý«ƒ\26w£óŠ bÒ|7:\31Ñ\6¨:Ã°Z‹†úyÝbI­ÚYûzÈc8\9,±Y\29ÛB\\Úä Yk>Ø”«¤Únð´:ë¯Ñª/kcGÜ\127ûÛd\26$-ÛÙ¾°¸Ëî\19fw¹ñ9\15›â\20\5K²â\25‘Áü»}Üâ’\28öëyO£[¤yýÝ,‰ôí\16”\26íàâL\13TÔ\20ÄýDû½‰Aƒ+E£µúÏ¡¹f„[à\1Ê\28Ú€åÃ»w8*0ù°•Ç\28·#p¥#GC\16{iËK«Ê\20®Øêö›Ôëe±¯A†››W)â}’º·Ççù}.ŠwA5o¥ƒ\\¿éû‡•U0\20KÈýKX¡-í\13Z½Ômwi–¶g\0\22\16© Xw–ðŽxUá€Ö°œ×0—\22•\
ˆrDiËq\9\13éjü\26¦¿K\\Õ¿T‹j\31æ­[ß\1ò¥\2º±´Þ&[â\30º-Øµ$ñóaÁç¹óâm+Ê@€YÐþ—\14ÎëÞ\18š—MJ¡h,Jßåâ>7áÈõBªQó¯u<\9ZjTß%%d%=\13V\24_Î\11WK˜S›f&eŠ3¬%ôøE™ûë²¤ÿzWÇò]b?•@8Ç®ë\22‰.º{DÎ~ÀS…»)µ\27à£xÙZ³4^ì'r\16Ý–;¿žßƒª\30¡\\B\19Ü½YÂ¼[¸\25\21&LË\3V´<B^ðÃÍ…*öÌ–G9êÍ×€àO£cir\7ÊgØ\31Õnð\1B8ÒªÏ‹\6\0@ot†C¸—Ö—8ë\\d¦d\25b>‡t3ÄÖÇ®êâ×HK}¶h‰\19e˜»:üÙ\12…‘î4úÖ\4\3;0Å–ê½þr©\16º‹Å‹ØÕ\"c\5(ž.c4l\28âòÐâÖ\19 6^KñÅý3á¤¥ãRL–D¤'•ÐN˜ë’}Ä\0…;¹«¾xö¶d­ó\27\29*ÈãÇz²‡¶‹§)H¼è\3x!F\5”\23¯ga‹\22çKl?’U»…E¬½€ËRBñ\22pÒÁÒâ|Ñâ<à\26¬´d“\127/kÉ¯ýx ¯Ñ9ÕžæÝ>‡d[×tw»Iy[Ü$Ô2Ö¤N¼Ä³\22f\8Ä!îe)½«[7•nm’a\19óª5»Ô×\16Ít«Qˆh®ƒ¬].Êð‹\18û²ÕÌKí\11\9„’zK—K,Pov-;š\22PExñ–çr Ñ-\7*ÌâžærŒ\21\1399ÄƒCµ´Y\0167ø\22ß\14‹:ÂÈ{\9©zñõ3‡-^AsÈÞ—\31HåÏÑB\5ËŸÃeþã+;BšëÎËŠ\4=\0½õpÐ Y­­Ö©:P³µlõzc\127õ–W„L\6Í>’\19O±ngÃÐ–€Kœ­ž\6lèJÍMHÇô'\22&.œ‚r¶KÜ'žÒôfõÕ\8ËQoòëÕ³B¦4¬:a\127Y¯H¥\0ä¼5\4ýµ¹ª½¬×óêózES]‘sÖ\18š¼z™ü²Æ\14Çz^íXY”ÌÅ\26›\26ëí˜*‚:ÈÍÚ!V®\26›\0044i'ÍFý\8;\2¯\17¬©0eRÝV X™\20$‚\23\31uû¦-ÞÚ¡Øtk'O×‹_kÜì¢\12‰*…t\6Åc;kêÄ'\18ÜAÕ5•w£4\30¶¶Ê™ Š‘LÚG\26\21©}=bõº\13—¾Òæs»”¨lŒ/®­é\20x\8ƒ£¬…\22dkÚÕ{\3&[£€Íºj•GW…w«|%ÌzdïÑaMàI#oÑ\25ê?C÷(\11,#å±ë\127é¯_‘éœÇ&½š³7ZŠoÿ¹QøkˆdÖûäz?h$óz?l§î)M›\25¦°\23ù*\15OÖ^ºµö1-š\12l\1‰ö\17¢µW£_}µdõjòêõÿõaƒ¤€^Ñ {q„\6ÛÔ{à[#BÆ¥X˜*Ä¤\17v&•Š¯aáºžÇd«ôúv:T«\16P)dõÍ¹Ù¼=£¡\1ÍŸ\31^\127Z5uaa\12“åÄ\19…ké9“;úðÄ5Þß\16¦€½\5gc‘m\5á¾(Ä‡‡{¶éÇ2¢ÝÎáàžÁ\26:Î\26çh\26N¨$¯ª“)ös.†S\24[Ã\0Àbá\29ñ\8œ\29\9s»Õc¶=\28zRýãç\22ÎúÔ\18S(‚\21¤\27]Û¥7Ô\16\30†> %ŸWÉÖÊkc+üdõt„„¨@«\27ü\4œM8OÐÂ¦Ãõ‹›Má|jÆ»ÆÅë\21\29eÔïHÇ\11%†|ôÛþÂ])ƒ†ˆ@]}4Šôù0\0¯•T'“\26ýŸR|_\4ÂízËP<\"3¬\19ÿSùiÍ^B^óiâ‡‹þ\"dLU©Æp\"«;äñåöÏšódfXœf‰¶ù|­`\13Ã›5îzúÀžüÌ—\2ÌZ{\23Aç#|§Åãš\127\27úF• \11¡M\\¾Ò\6Ö)\12f¸.5H¾žºÎª\29äZ¸Êc‹IÈrª×”Ãlµ®îä­qéh]ƒöÚ\
 §Zõ\
\7[‹º6\31%Â±\24Yš×Šðn\18²‹ZˆMˆ})ÂšWdcº\27¯ù¬ÞïYÏû5ë†ògÈb$$r\15Ûâ5,X\16æ\18IÎ+38²\20mT¼3n¸Û—ñ˜¨\8àý\28‚¼„ªS\0175~Â±kµ\
ÌzÒ¤a·šÝíþõp…\31•[Dk\28\28®‡\27\"øEbX€‹J>»\30ó³\17Æ\\4ÇF—½(CŒ»çëKÛ|êð¸pý¬AÍ¬°Ð¹ŽK/øí\14]þ(D­\31ÕÈõƒ´¸µå¥Ü\
\31$ÙÚÛ“ï›Ç\24[Ü¼&\8o«\17…\14\18Àæ3sáß/Õ¦ÁäÖÆ\1\26E,Æ*Imm¼Î³ùŒ\19ð0³V3Æ¼/õÖ\\/[<ùÒè‚Æ›O¸\\T\12;¢}EÿFø£Ôû@ÖÜ‚ô¡'\6iÚncŠ\28ð\30THÄ\20ß_[>~ÄÑÀæ©\0UY ‹gS§Øâ\30\13°y\3Ë›¦#›WhêMãgÒh\9>u£ñ= ¯lµ\13òz«Þñ\30ðe¹ÐÍ]~“‡A6a\14IàÚq”:7}|x½…¯½;\0293¡•U|…m§gq†­\26\17y]\17,4@ÝBµßâY\25ªvÃ\2çEH\\9ßPõ\7C~ÉVÝ™ÍŠúÊ\7\30ØÍö!P€\25â­˜í¡­`µ=\6\6þ18ðh\16\23­ÍÆN?k\4è”k\26ÝPêƒñ\26\16~`Ç·\27Y\7ßÂht¶p\24\0307öÑv¶¸3·\13šbóá]ž-*=¹Ë\22ûø[P\8\22f6\4Ml‹§ÅpÊ\21àô\21\26ºQÑ~¦9\12xéû»l>Î°=\25ú`\2[\24'\14ý.P6¶xŠhÓàb\02757·\17àn5Q\7ÚÜXéØMOˆé•, ÙâÀsc6\0274œ-\30rØ˜ƒ¬B½å;Rø–ãþñ–Çª£šØñ#c\6\27ª\13b\11’j\0\8™A9ÝÜ¾bVÝº\15»\7\16£9í\31Â\5W³\18é\22OEÕ[f‚Ðû\7\26»8T^x\5 @lK ”ÖúPO¢™Ñ­D‹¤ÂØ_\2f¦qñšËvšG(AÑx´«ÐA^œSÂá\7\27’¸TkÓf\2Ýc“În[»ÑÇÒKM\27\11ƒhÍàíÃ¦Xæ×nR—§v\21Û\22¢©RZÔ²‘cóŒqó\21ÄÍf;’JoÛiIJÒ7\21î\20VJt…dÚÛ)Px×ŽË#\29íßÜÌqU¨HøH³;\30›\27\
ÙÏò-ôE-®Ïm\30(x€m;µ*Ô†ÑÉ\9cÂ-\30’Ùbÿf;\22ŒYM\21ËzÏ¦ÚóTµñ%FÅcv^»\\-\30gÓ¼°3~Õd>>?á\12N`œšSúÛn¡fn$9”Ñ·£F£ÚŽ²\23zX¼\29ƒèT\31F– æ¡©Ò&Ù\7 \20o Ã[<\127;‰–ûqá}HÿñYÑí£¤v)|ÃKcLÆñz‰³\22—$\0319njÁà\6ƒ»¬\31*¹ûPiÆ)GÃQEwßÏ˜u4\3Çyê\15¹i7Eu&³\4÷­ hÖ~>Ò¥cAh]æ]o\1MUi\17²ÇI\9‰¶\17N\8s»\31fô¢Ìî\22\16M\127ãûUt)w¨L½“\12¢\127Ù}ò\
¢ºû¼&Í{j»ÚV&Ö÷ž4Ë\3!¼\3¹ûÜ\14L\27RTì‰:S_ûí\25„\14Âîîýjmþ\"ÓH÷R9Áýö4i¡ìkŒHÆ:·€Qg˜0îŠ:{¨6½_\12\6ÚŒå.Öä\17¹xYuFÂ<}„Q+\1Ã†pâ&^<Ê8ì\17ý²ptwU\127ŸiÜlœ›V~\8~ýØ·»c€Ú·CÐw¯+\1K\8,ˆÏ\4>*_ÊÄ/\7Â±N×„\31ñôB8NÇéZ¥h\9¾?F#²Û?^\13Ö\6\17—¾y=Æf>Î{dÔê\24°¤Ä²Ó°¯Ü}Ø¯Žåµ‡B\",Ž‹W‹\29noœ³Þ\24à¡¹Û\13d&Ÿp;\0088/{\22q¿\25ÀX\14S\24Mï2‹=˜Eœ\4~…ã¤BÍ(\8‘9Þ¡L¶\26c\31ª-’\"\22j´5™hËá_L²…Á\30Éà·»;È…’\25?0¶pƒŽ¨¿HðG{KSÅª\8£j2E\11âõŸ=^ÿÙ=j\
Ç%\5WÙ=3¦ÝsIyTœQqö\28\15y‘ wŽT¾\19¤]<\17®ìÛX»\0071¦G±ˆG¥!œûù\0\16ù¼H\0094ª\\Mì\21þ‹Ç}¶Y\11—f×BžDÇnôÛ÷\7vï+yI{w7EØ¸ŽÖ0ŸÕq£!\\\20‰=,êM£\8‰‹\16¹5xPù…\14æêÓ\22\23–,shnA^Ö¸h\25Û¸®Y4H#‘3\17u5}À‘Z×ºŸ\8”YájŒ£cJ\15û€Šú»»U»V{»&Â»ïLÔ{µ\27è\14ýÞ8²;‚d\1ÝÝ=ùÝ\15mê\9ºRÊ\0017†¬¸\"Ü±jˆ\20\3\17”H0\7]©ŽÅ™ô|”h\23éq.Nø\18e\31Ú4\17½Q\4{G£ÞTó\30¢áÂK\20û§¥0ÈðþY\18dðãE†zgJþ”x\14ÖÇÁè\2|îüÐ–\6è¹Í®[vÂ*Â\16¾éˆÁ\16ÁãJöÃG‚.G<í©\31Nw\20WK¨Ï\19dO\26@È£\2¥Ø::bF\15¤áÊàUpþö¹\28Þd::w,Ž0†Áñ~ÍQ¸Ö‰\24Rw:›\9\24‹£Ñ<æ¨;¤…£óéQü–æ©î\17VqÇ¹³s¤x?©:î4ÄËE¾Ï\
\18\29aeX\30Cy9†°…9Ü\0319âÝšÃË\18@_^?|Ô\5\16ögGó¡{’Œ•§\5\20ýòñrê\31UÐ\26\29*\29ã4äP¶<4ŽÖÛ›\8Ö\127„UÓq\30´\30§Â\127Œñ¾¶NŒÕÉÕ`ºÕd\1ÊÙ\7|€Ÿ÷òŽ±ˆ\26]:F€iG5\30\22\6e\2¾.G¼›}Ä\3 B¤ž£˜\28¦sãàð‘6&m*—ËÁB¦Ÿ^[?4è!%tìð\5jC\25¦c>[9\15¬‡c®\28Þxbå˜}\2Ø=†gŽEpÌ‡\9š€­óê”e€/n\28\5ÌèXâRÁÑ,\14Æ©‰\31j”øiÒ²„@\127,¡Ó\30îù’Ï³ËÃ“£ö\0DH\17«ov\29«¸ìÿ\3\28k°\23‚}uTG\\óí\7\22S<¤tÄ™¢a¢­æ\9®0\26º\"k\28îÁ¸§r¸\15\2TÑ?ÜK\8ÈÀ„\30ÓD_×\16ê\14Õn\19(½Qò\1jÙ»\13)LHu›vFèÆ Ü¦1î±y6ê‹Àb¦Ïz\28[ì\15\29Þ†9aGá®\29Ô\17o/\31^l9O©)LTŽ¸¾R\31J\28Â1 %ìa\30Z\31…²f¼Ya÷N‹•ã”*ó•äË\17o!6Gœ\1ñQPëî‹8ÇîÛtÂ)ä!R¸Ú$ã„:(èÌ‡›í‡¦)ÇïÁ:‘¶\20/$ˆ—¢Þ+ÞF{µ7Än\0292¼|ˆõ\21o£½Ú0\17}ÅÿI\0\11c\21à^çg\28†ûåA”\\íeW_öôÅç\11…÷âVé×ÅW6àH¯ä†;ë\20\\\127ù\14ÐtMÌÐZ×.Âð+Þ´ñƒÒ\26ž‘z\15×œ¡›Ÿ•MJ«¯ÅSgX\27\24ŠÂEšr³öÍ:ãq•W:aœ(¼âÚÊkð\8œÚ¼…\9\12\5T\7)Í‡>Ò\127¡[84Û—…ÉÔÓ\24MÊJ·wÝã\5-‰‹Ç†_âkýŠ'”_¥¯€¾¼©g\0163ù\26<U!­§k¯Á%öÒ\24‰B¡Ë/¯eQ\20âG\14x˜\13ú\1Ð¾óå‘uõRg}e:æ¹VõÊO|žÿ¸ÍœŒ\26wƒÑ\31_¾\0\8\12Ë.\28Ò¿â´ê\21§Sõ++ÖÖ/\8ø\11}\0ÅçŠ¸ôno—÷ù\24ÞÛçÿ€¾<F,3øöbðÛ\127¾\1n\0015L~ËïI¤ýö}@fæ}>-òN\29ÓóNþ½\
\16‚÷ö\22:IMŸ|\12ï­YÐÛwÏßÐø·×ÁßÿIsïó®Ð;¶‹ßÐúKõV,{\15QöðG»êçå=z\7ì-¡æ\27ZP¼3…ä©\0„$òn–Ë[£ü·£\0a¼+HåÛÓÿwØ—½\27{T¿éÕ§¾ü\"\17ü² Òå·nûŒ\127ªô.ø\16i~+èÃoA¬×!Küzöñ+\19\3:Ÿ¿Åãòû K€‘\12\15(ã/|ú×ÿÔøõEÜß0]ü?\16ø\29Âvï·\"c¯x¨h‰‡Ô~\23ô\17”q\\ô_H\5±àÅ/ëð×½¿ßßúòñ(°ú¸­ö‘ª~˜‹Oq»|<'ú„ÕÀÇ\11‚Ÿ8\11ûÜ\20…ð“\15¤ø£ôûqN>¬¯ûåã%¯\23G>*:õ§\"g1P\4˜ö\25Ç8ÝþxŽûñæ3]}¥ä£Üú™\22˜ÝG\19[J\19ù?îV}|7ìÒ|æ_\
Ê$ó¥üO-åúD[rl{\0192oBÇ¤\31Ù\15°²ò%\27ŠÀþY´Î@R¢îÕ[‚\31ßë'\5ãþñ,ñãÎî§ò1§Ï\22V*:™\17r\23èS³Ä>\26d}¼E@”¥\5½þht2_>qpð)Þ—¿¶¸ü5ZDÿ!l]ê¿ë¥üK—?/×ü©³ý9l\127Éªÿâ‚Å\31\3õ§,ó§þÙüAìÿ¦KñG¼×Wÿ²ÿÓôç+Eõ_ñW’ìïãŸ01Lñ\31LM<–õÕ!\27¿üï¤ýQ|¾ÇÂÿBªGÿ®ÇS(€|Ù·Å¾ú¶Þ\
±ýË\127%\1™âŸöÂ¿5ª¦|ºËw\27îš“ÿIÔxÎúõdµyUéë™¿WV²\127.”¾\7Eò¯I«d˜Ì—Æ«­ÿ&5yÄSÞâ¯‚Š-nx}Íé;WwÜœ|$\31w.¼\29ñå¹ÿ†µäm/Ú)þÅ'ÜP\
æ\"û×:Ó\16ÿ³3ir\17ŸÝ÷é.õé®§û­È\28\1ŽÈ¶<¾ãß–¶eˆ‚bë 8ï×î\11ƒŽãž¿\23ÿ\13\
eç'þ\23Ç?\9ˆ¿ÉI«ÿó¢'Êû_ïT^í&ÍóT\1ÔÎîÁyåÅÿL¸\127ßãÿ;¦Â\127™RôOG¾?þ\3H\6/üÇ‘Í™óÏ9^þ\29ÇPø—#¬P\21¸øF0hÁf\9lüó„¯pû\7\18¨aîšCOX5»\127\0¢æ½\22™k÷ïPçýŸ\2ÿ;©U\28E‹òß\4|´¾½=KE¹kËÌe_ã»B‹\31ŸxÁß§ôáOñ6~˜©_™h÷\25¯ƒW[¯ðž5>Šõq¹\22>}ÿJ>m?{³â:\14ÿ¹\25·ôåù‚¾â¢”\"å^®êX?¾þþ=”ñb|x¶ó=xYÝõØKOä®ÿ\29ÛßüÓžÂ·×A\6U³úöØ|\\|«\30‡ïˆû†Öå6ôU[ù^øÌ¤ù\2·/s3‘â|ÿúØÊx‘Ú\6û\8u¾1VžÆWG}qzõÚÇ÷Í·ŸËµh}ëÎÇœG÷ßºvo}€¹kâ¥à²Sfí¨eŒwŠãåïÂ§ˆoç\21¹.\30ï¬†x±¸œr¼k\\Å“Êq¿\24­§h‡\14÷ÞÜ×x>¸`µ0\9ÝPÆ\11¹:«oàŽ>Ø¢Ë8ùÊnóÖüÏgt\11í)Yìw\6—*\17s‘®Sßø¤îTi\19ØUnÅuG)\11î\16Í\23zíS³õ\28ªVÒ\0\0§ë\13íŠ#n÷'ªÚµmLÅ˜}N\17%í×'\18Ã\
§Hß‹ïM&Æö’J¤©º}Hp[ÚÛ÷pù\31ÕQOkÒQÞFÍ³ïéZ¬Gë\19`“§·\12\15<å>øÿ\27Ìö}l‹þÛ‡¸Æü\14ìD‘;òzéÓ\\Þ>_ñz\19óÕ?Ð„Ó¥?G¥O\8¿¾\4Æ·K­éÇ¬ÕÃ¥èË\25®æóF…–·=Hè£T%‹ž²qó\26×\23z8\
CQüµ—xZ(N®zÄ\16_(*Ž=ÞÝ\25|?ðÑ–>\23é\0197í~£ëô[Â¯\30\3„Ã·ú\30Õ aNá‹8^0ù»<$¶ïá– ïÝ|–\\h“4tõàK\3wÿÛj¿\12}\\sÁ\25öx{¢þ÷ôQ\7ØXå{\
`ˆ˜\127>¦à_*\13ëš¾_Uöù\13Öú0‘Ê5”›Á¿\6ƒÀƒÿÿÚY&ÿ¯E\26(\20lÿ%\8\
k©x¦ï˜éâ\25ÿj\1B\22Ï\28âì3Þ#ô\31æèŽ\23”‡ïÙ\13A¯-7·Tx/\20œ\25Â\25Æo¦Ö©ø>/ñÊN¼Òšn Þ·—ƒ+f\21Rà3·#¹³7\18ij!û\30Ç\2m\29ò\18\7ócãõ)ï¿¹¸Â„`?c.û¸\3™Û®\22OôœuU»—WÏN\127.ãácãÅxÌOåt<ÞÜk½Äüé¡\27^~ü4ÛþY/\19¬IsÂ©\20m=z9|f|b\1÷ò\6/ò•ÞŽëÀrÿUÀ€ü}3Æ\0210WdûÑÓPu’ƒ¸\16ç•;IeÑzMÎ\27\2^\18˜\28>M\16&iú\17³ûÿ^ïU“t\5ý‹Õ´Òcïª¡\4\23^-ƒ2ù¨×”YL\8}Þ9K\31o¾åYK}ï±ÍÙ·|Ðôó÷y%’¨bûŽKf5«ã2¡+€ž^\15cb¡ü—é`:²÷¹ DÍqñÏ¯NšªäUÊ\13/sªd\19^ï)¶ç\16w•¼t4CP\16Îæ{t+ìU©6Öÿì»kÞÆè‹G\22nËê½–õX.óù\"^3ç[0)R!t´ßÞ]™\26Ñ‚\26ráß\8^B\12ø\9gPØò¦I‘EzzöJ“÷@@D”™y«§œ½áÜgx\15Ë9î00h¹;UÆÜ\13ñÈdFæ`8ò“\14í§ñüi}?\14U\31dQ£{\16\0161HkóD)ß—l;Oƒï¼Nm¸¬eYŠ^\13¥¥/_adüÐ,Ü[\9+ø½j\127ÜÈ\28µ\127¯·ó/²²\27\
\4á«¼\23¤‘o\
Æ­ñn[ixÎÚ>G5ÿ\14,±0P\29¿½£¯ùkÿ­B¢ukë9°AS|·ÞEY\18\12¼¸,(\16cü5\20>7°Š¤ažR\24uhã¨ï\26–\26’h¬èV^±„G\8aI³Æñ#\19U7B\14›Ú*ì\6\11ÿèLSÁÒ\7n—5—·Ól\25†Å2[†õ…\6…\27L€\
qª\14‘\15±àÿýwün:»;µ4Þ¬ÑØ¯¹Æ[†?G\0117§Ýø¾ý3«Ê mX¿OwÓ…ØíþÙ‰Þê%×‡uŸrXµ¶WÙ]Öt\14¬ÐàÅÿöëù„Ýæï>Œö|†oõ/æ\16C=bp\0205Ži›¹|„-ž\15\4¯\21|Å{%«gõƒ–ò\26±íßþk…†_ÌøÕ\26\6Y-rx0ÚïõÉÇÓ\21±\22OÿtŒ\16\13’ü/½\31o‚Ò]Öÿ­u=ËÐ%ƒ¼Îû0‰;×Ú°„ §Y\9\4\2¤Ð$äaKIt^Ic?©ÙÖŠàÿ¹þ‹ÎÖVq™tÔ¾á;®\
à\17—Ç0jðßŠ6\20¯ìß\25°Œ(d€Hí\4Â\23cgt»}@òâ‚0\13E]´\2°‰\11Z\4¡Ó<=Ì\8vWéöÈ±Ô`!Ïy@ßœßI{\23\20\16Ð\7v°=?¶¸ÚÆüjaH\8C[™ƒh{*]ŽZt\18„t\1\19\9wˆcèøßÇ8s.tÅg»·°Æí²GÌ{ŒÁé!¤\18IÐ¸7LÄ\8:ƒ\24\25çóÛ\127+Î?ÎéçÆ\19‹Â\19áiñ\4\21qp‡€\14\30\15¯Õ>†Ç-ÚmoLÈBv1Åa,-ïõÿ¿I\2¯\19lûQ,C\13»„\9E\28»–\26j§o²\127æ›Psÿò²½‡iúŽƒS‘Hùeo!R4Î\19Q¤¾Ë\30,m¾€~hghO$F'ˆSJTw`\21¶w»wRa”aá\25\7ŽZ’è\20ëwö\\\15¦—â0\4©8ûS\28GH©G•.©š[ð'ËF\20\28\12*Ô ð|Ld$\
óÍƒs\12÷\1Ý0{\30\21R«GMrrÏB;f”œ\7$f|E\24?zâƒ['E¶¸ð¦ŽåT±\2\20\31<CYó½Ž¦²@îq€”‹¥ŒSÆU:\30wãþßï¡Š|uñ†\19‰7G†‚\29Ä»Â#—9\14oŠ7£÷)\23ß¥8 \19klù³Îâxýhü;ŒÏåH\12ü%ôƒñ+v›ÃÝBd}\21q\11¥?¬\13ÒöåÕ~Çßw¾Ú£ÓŽÚ®†üæ\3ÁE‚\18½\\?Úl¿†â5,¡Ã¼2j4\28ííßAWïï¶ÄûJ>~ò\6ß)=\11w¸\\G¤Êuü•ç[\3cÿ5Õ=ª\16‘~‹ŸË/\24¿U——˜¡ú\31\31&Ð4€%ç£ÍŸ\20»ÏÅçòçß\21~á0Vpø¿ò¯zÿ\31®D°»",
  ["length"]=31488,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=4938,
 },
 ["version"]="1.001",
}