return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["characters"]="Ğ°Ğ±Ğ²Ğ³Ğ´ĞµĞ·Ğ¸ĞºĞ»Ğ¼Ğ½Ğ¾Ğ¿Ñ€ÑÑ‚ÑƒÑ†ÑˆÑ˜ÑšÑ›",
  ["compression"]="zlib",
  ["data"]="xÚu•íqÂ0\12†Waì\8ñ]\17rí\18†â#\7ØYAŞ¨ú²,‡ò§}$¿’\21Y6!Npƒ\12å\0Äu†\7DÏôo\29\29gH\7(\22W,ªŒ1eŒØ\\Œ±úIXCg\
7v\26Ü¥\6Ë²Nğ‹œ\26Õ\5¹àJ\26Y!\11’·tÍ´ºÊ¶Ô•{Àè\16\13îu‡\11U¨Ô}±¯NõËIØL£ÙÄWXë¬¼Â\11\9\1w½PçÔ•ÁÁY\7GÚ;83~Û\3\
<:OÒcg\14Êì—ò¨Ìò-İ´@­PY¾Qyu\28=ÃU-ì.Ü:ÓÁª°Î=1qKÆ\\\28'Çmp\23Š\20²Ù]lÄù\16•b'ê|[§|<â\23.÷nœÔ\127£S›ÚÔãd,wÖ\27°Qˆ¨K]\14¼‚'õÂúŒQ×¹8N£qv±ÙÅf\23›]ln±|vOløföFÅ=[Bs´Lİ\17\7Gıysìr \"5\7LèÜ*fvš\17¹àY8U=ªuv\27![.ââ89–\7Cû\19¬#Áú×\8o\
3Í—0kh$Z¹\1FÉˆrÖ\19D©'õn˜µ\24'Ç…¾)Ø\23\5«;´ª14Ó\20%¾á”r–!£¦\4oÑÖÎâæÍrnøç*\15\11oøî•\7æÿ…O™ä…ù° C¿ò\5àâè\5\26\\Ü#ºm{/ÿ\0ì•Q\31ÿ…Æ™vâ>ñME1·kf\17\21Œ¯´Ìı‹„<\3ßòÌgªñ%¸w¤? soŞ",
  ["length"]=1800,
  ["n"]=130,
 },
 ["metadata"]={
  ["mnemonic"]="sr",
  ["source"]="hyph-sr-cyrl",
  ["texcomment"]="% Serbian hyphenation patterns in Cyrillic script\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: srhyphc.tex (2003-06-09)\
% Author: Aleksandar Jelenak <ajelenak AT yahoo.com>, Dejan MuhamedagiÄ‡\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
% This is `srhyphc.tex' file. It contains hyphenation patterns for Serbian\
% language in the Cyrillic alphabet. TeX font encoding is T2A.\
%\
% This file is distributed under the terms of the GNU General Public License.\
% Latest version of the license is at <http://www.gnu.org/copyleft/gpl.html>.\
%\
% Version: 1.0a\
% Last change: 2003-06-09\
%\
% Credits:\
%  - Initial hyphenation patterns for T1 font encoding by Dejan MuhamedagiÄ‡\
%  - Improvements and adaptation to T2A font encoding by Strahinja RadiÄ‡\
%  - Further improvements and integration into one file by Aleksandar Jelenak\
%\
% Current maintainer: Aleksandar Jelenak <ajelenak AT yahoo.com>\
%\
% \\message{Serbian Cyrillic Hyphenation Patterns `srhyphc.tex' v1.0a <2003-06-09>}\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="Ğ°Ğ±Ğ²Ğ³Ğ´ĞµĞ¶Ğ·Ğ¸ĞºĞ»Ğ¼Ğ½Ğ¾Ğ¿Ñ€ÑÑ‚ÑƒÑ„Ñ…Ñ†Ñ‡ÑˆÑ’Ñ˜Ñ™ÑšÑ›ÑŸ",
  ["compression"]="zlib",
  ["data"]="xÚm]Q–Û,³ÜJVğóOr÷gÉ–ìç<ÙñÃla\6I‘Œ¤-Ø;º¢«€nœ‡\24ªAP4\13´Úxòßë÷Çÿ^÷ğq\14\31—ıãù7||}<¿\127>¿çôº*¼<¿^mÂÃëğ†§×!ã§ÛŸ™\19¤¼øu}\29SÙãù¥òÃ³3hShU->T\11kh=?·£A÷¾ãU•\30Ÿãëøª€ûb,ıÏ8ê^˜EÎ=Z]\20Jmî5´ò\13¼ìúúõ\28>B,y²F¥>K®ÿœ\3S…\31¦îcoïË”v\
ùÀ'r_0\127}œ\31`Sº½jÃõğj\18Úg$´¦ğü|h´óô\
‡Y›\21^Š§·ç”Ñ®ƒÎ Iñ\26^ÕÎkHx2c\16›R:™c“„½Æû¼§ç_×½tI¥ë>\31¹çİÒ¢…\8Ú9klX¯F[k°üÔË®Úï ^\3S?,\0295œÒ<\8\\“ªwØïÚó\26N;1S¾ªÆ‚X8åµ\6AV\0 æİes\7\\4³.,šülc}5Êôƒ%\7û´Ğ\27¨52ïÓ~ÒPs\0228i¸¦5\5h:’\21¶\24AÜ6\22Y3ƒš‡šdÂÚ@=S>Øu†;Ğ#Ş,ë\0\7\13—\18êg­òÂÒÌ#V«z\7•1µ\29\14ºjµ·l, ¬¦/\11Ó¶\25\5«š\26)7pû$¡)\13;¤…“…iTC4—ŸÏ.à\21z\8œÕ\22ú\29N¦ï€/?_w•?Ç|õS˜1/ûOÌoªNÍüsÄ\25ì§¡Ñ$9\6¶«oVÒo•ïU¾SùIåU‹¯›’{•_T?J¾*ùAåªCşç«ú\5³Ş\13å\24{\21é\22v±°>dÎß¥‹•rA[‰ª#ÆĞ[lÛ\22É­xâ\17YC\18z\9öPÊÄ\0òsq\15\13’çø+¤ûîöõ&Y\
É#Î\1$;¿·ç(³O&\11\16<a¥˜:\13Z\22F\31-0âh3òLğX¾MïèvÃÚ8ïÿ®ª\3do\18İ÷1Z$Ñ¦Útû9g§„ÏÿŠ\6\6íW8³©ïIJ_mXq}p\13?%÷œd-aÇ=dIğäö1ÌªNØ„á](É>‚^K¸Wh<\25|Ô½ì-8!QòAD$\30 è0J¶`AÜÁ³\12§Æ£Ær^ljtµ}‚ö»öu\
jéäƒ\26}5\1MišÒ\0145}<ÿş|ıFNü­o¬X%éé5MÉ[4x×H+\26Ë\24\26š’Ç·\26¼ìco\21Şä\0Ó-nÁ¢U\7ƒû\17oz\8Hlj¢\31×ç|Á\22>ü”üÃJ#Ù¹¦ä+N¦î¦8‡wˆ)÷\"ëvÎH³\19¤G\19VÙ##ñ½[U:\27í\7ÿnPc]±ûi\28VIêm÷wÃ\12*¼p—É83=b\31$\14.*·\17Â9õ\21O±)aS:Á¦t~M<½¾c#Ö¥F\11WË”Î.æÒpXY\9÷9Ç=iJ§Ü”Î¸)pS:ß¦tºMél›ÒÉ6¥smJ§Ú”Î´)hÌÉ\14ı]à¡ÀS¥Gœ‡Ü‡\19’7…\21ÚK2&óôD?)â\21«8¢}w«tû²'x‹uëéÍQah%áI÷ øRà¶À¶}xÁ\9\7Ç°Àºÿà+ÜÌ\8\29Oà„÷g2£G°6ƒ¼B\3v¶ˆ`CDÁÚlù„óWK”.\31z&vêÙ€Ìs+,\6h_e\23\127\19ò°\28æ¥ÿŒ\13\
gÆ-¬\8-1hŠ{ q\24Ï½ÀµÂkzCÉ\0183Æt&MÚ\15Ó}\2ë^)™Ş$s)ÁÊ4uT_b\7g±.EÛ\7­í\29¥¶ÃÚÈc\22?iVsVkëº\7ƒ*SS\00283\22o²5èDŸ,I,2=­ô€4^,ÎkPÎùÙ”\03043Ñ]_à¥ÀÎàIëHöŸ¿Ey«q8o\21æé$HYö.Ÿ•¼RyX\29¼ÙÈ\5hß[dGŒ6\4iX·{Ëi\28ôƒ“\15«%\25÷j¤\1wáMio)÷Ş)Ë‰xÑHÕ¸º%¯™Â:Hö‹¿´‹èCÿ5¨3hKö\25%cB\11_h#Šk3 Uâ}mkƒ£E¼f]ĞGŸ4\14\30ÁS\30Gğ\18T>®DñÖåİô«ÀC'Ã¾eËq²\18ïÖ§ô\27ğ\20Î05\26—=\3…\0075w.­·XşÇ ÛVMOš\18µë£†XšÒ¶H\
,-†w\9‰\4ü\4;…‡\2O\22Ç½]ÕX‹\26ÇŒw§ä—XÚç›¬Ã¸µ,°…lø‡lú‡ì_í­ï²7~“\29“È‚CI;\13>ğ\7–+¼;Æ\19¢·ª„\12ÚŠ(D]bŞ¥8­‹Ï„.\16áòV°jA\12lF˜bo\20ôqéehJ¹L\5¦Ğd†ºí.1\17\14T\30áƒ\1¥$0D$t)!F¶ŞDg9ÃQÃÁ–â=3CEEà¦ú–êµ†«ÒjŠ“’Ùœ}ƒ(À&£DüFEA8\20´ÀÇw™\12k+\8\17ë<~\9Ğ\27hæu³óºÙÖcd3ÁU)\11¯MZÕAóM†1`™àÄÈA\22Ä×º(˜ítT¢£M\9Ä\24­ 3\20\31¤1P7W›Ñ¥×\127\5UWu½\24»LH­ÃgÿÁˆW\2«\2\\ããë OàÅ6¿\2\26\28:ŸCPæ\22B\13>|,òÁ¯¡şîƒûc0¾0Éx0h*Jáú&lÛ¢S\18ñ\20\22’Á‹\28Ë\26\127iÌ—¦%~ÍÆà™ÆÁCQ>\20Ï\0152Í\9ó@ı=TÙMÉWİ*B\3\6\31\12ë•›ºÂÜ‚uUõu(Æ\21ğE\28\18%ÑL\17ş\20+_ÔW_f\4\7~U‘p\8èY,nÆZ[¶öQ^ï\15FâÕ˜¢\21¼®?“6B~PùIå×œ\23s^Âzè\17éw\6O‘GÂmÂxµ\\\12\30ÄùU8Ú˜`—µD\28\15\\#‰º¥\4\27¸Æ¶ü\17ÇL¼æ\25O\18ên7»_a~5\
ëÈà>µ\23ñP`S?®\2–ÎÅÓsÔ6ñ£À¾èİ'\13E¼˜Ş\14i\6ˆ\0116‡h\25ÄuQìŒí»‚¯+Fë\
~.®NâÑ”\15yÏJ¸(O\22'ØŒf(t?\20ºa#…ÍÌâ\11hóÄgóÄ(n­ÆªEÙ»‡7Ij1œ\18zÆ³ÆY^½K¢ÍÆc\7YìØ¯c\12o‹_0Ï«€é\9Â6\18Æë\9ñëÆ/\25\"FÈ>¡¸*ˆ\17rYqİƒg\3\17¿i\\J‰°]q!$•=\24xLh÷n.\6{S\23§JÄƒì´\9)N\15\4\17\21‹xÙd5—MrKµBx\25úû&éŞ$[))Ú©,–ı1£‘Ş–‘¼Õ™’Şnªdå^±Æ\0112²×&¤ô´ò{p´‘fJÏa˜{¾hGÜ«<‚j\25M\26™\22Gäáˆ½%\20Ù'Ï$æ'•w)ÿÅk\23@9`­q®­lPy\31\9q]¯éÊÏš¼†5ù\12­êÉà\30÷\6=\12Z5Š:\0224šçÆ<’Ì2Ï˜œÈ³Ê?TŞ«¼Ëz\0194)¤z\0204\24dkæQˆ\6÷Í@\2/Xy\17Q*;\24„s7ã:¡\27Ou\"\6«\18‚…\8:H@(æÏ*Ÿy\28\24ŞÉè¢k\6¬z;Èy<\24ìeWËØÔÆ”PmjX_\
÷\5\
¼\20xµ\24\22B<èÑÓûM\8+1•µ¦¬7È›š•Aµa\24°f8™>'Ó\11¼¦Œ*ƒ´&eC\7e3\7X\25gô¦äšÃjfw5ŒVÓÚjŸ£ç¡°æ¯ùÆu–ĞE#İ\7ß)rM¶ÒÃÆï\26ÅšD.\"9³ş\26Ô\0254GŞÄcF™)PäÖ‡\17şUù/Å%\7\"\19¶uùf¦ñPà©À«ÅÑn‰·¢½­x~‹³M<*”¬¾7¶Ü\27[&Z\20š²fÒ\23f\9Å\21Ş\27;f™måBœ7Œõ\19«EæùM=_«üQëŸojñ\25—WzÄ¦\7Ç/\11×ôÆóW£¸*ÓÛÏW\23‹3/yó¹k„¯\9\
ÉbêW\
­ì[{±«ña×Âƒ]\11ÿu5—ºVs­k5\23»Vsµk5—»Vs½k5W¶Vsik5×¶\18Â8ÌÕ­Õ\\ŞZÍõ­Õ\\àZÍµ­Õ\\ÜZÍÕ­Õ\\ŞZÕu§¯ÜR¾Ze%ù¤²W‡JÉ?êüÑ\18úô¹†K}õ)†%yŸòñm=#ÖÛ¢g¶K½ÂÑ÷Êx”1oÊßŠe\15u\5ÔÈ\
\9v[…e\29hÜ\21x+·íMi\7/dE»ÙÏ/eÛ?Ú+û¨J‰ì}Q\15Ñ\23Êå8á4ÖzçÂ–-ct\17¯¦ö*{dF'¸Ò#³Cˆ\4qÕ(Ù\27ö\5.Ú\16ÛÓ¸*ê»ò‰ıÔ.\9¡Ñ7ÉÑHÌ\\$¯G—\6OZËÉ\127ÉxÕZM{¾ÆÚš\15éº•Lo’ÅJd%j¬Y\29Ó%â$á.ª±^…WŞ®F6\24\27p…};«\27ìù\5~XlV¶DËŒ]AR\25É*g¼Â\5‡UÛ•`Ãi×Íİbû|ò\127¬¤.$]'Ë’>bÆÇÔfXÆø!Äh$“ü¬âhd\15~#”%+¯ƒiIü\26e“Ó4GJ7å]-s­wß´K3\31×ÎnN\31Qçæ|ŞŠ\19Z—×E¹ğ\9«G½¡k<\25Œ/ğ5æ\25%r#}*eüéI!+ŸİOo-•§òğ…c)é\25±Ò²™>¼’1Âo$ŒmÙZF\31)Îo$V\7Ù\
³$îàIr”›¸¿ßdùê”‘ÿS\26£ùZÖÅ]JÉâÏX”l\31×Ãê\31Q…·ö\\zç\127—š1æ^­åFIòZ­äPH¢¯ªeñ2{)\27ş!›Şd‡7IÒ…]#Z‚Ubê$VÊKR\24k0œ\18y¥\
âó\5<Ã×‹ÓÇÓñ²ï›”çu!Ëë$Iÿ!9&»T²0ú}›\8\31á«\0278á)\127f7—!‡3\30óòõdÌoªN\29ŸÕwQ“ä[å{•\31T¾SùIåU;Á1Or¯ò‹ªóGÉy\23ßà‡ÅAu\
kvk\\ÌV\18Œ]KÊ\26ápPX•ê¾°„\11ü]àÉà\7–Œ’ø\2;­Ñ\24\0144¸,×šæ¸~¾.¿^w¼‚&|Æ‹#p¾okğ\18{Ó7l\21~`³´’ÜKª³\21’õ­\21á‡7Ùô.‹6“îõ^4·ÿ“dÃF¥qÖ‹à\0017…\11Éğ&™Ş$«‘Lá`²\18£‹-Ş\12±’¢-_ãM9#+êD›ÑwD\11É\16W\23n‚Æİ€÷B{ƒÔÈå¦ÅÕbİ»”×E¹3xĞã‹·è5.Ëõh\4W\5¶ı­–ŸŒõQJì3ñ®µ–\0205zmÄ»œ¦<²ämÍ×å]–ô\26ñR<S¶q48sŒX×\31’q‡ó+Í©º£™ğdJóÊO·6UÙÕ”-¦ì`ÊF…\24\0185Ø–Oñ<Š8í7êF¨Á]u{\30/ş\6ë\17{¹1¯{X”­â.ç G\30\3Õ\26›ç]>\3‰ù‹\6-Ã£$V×áU¬Kû†¹³YH†Rb¬Ã©un^Zlf¯_\26ãu«ÔÅ3Ä¿^ÕÿÁê£†äàÿ@9b8JñK–7œ\\§W\21\28–*|çüı\19\2æÃ»˜Ë8ÿ0-Õx¨<\127à1·²ø4c\
\
Ã¤v\28¾\11À;o@a;—S\13\30\
<\21xµX¦ˆ\24W=¹h\25ùÃÏï,\22gL—\15\5\11ü(°/ğRàµÀ[Ñ\127]àcQße,ÇÉ [È?f±2x«…$0=&'õ˜\\ÔcÒÃ1ø˜¸\30ù#¾¯\24“È\18ÜóJxˆí\2É\\ç²ƒBòV\21\17—FFgx\0*,3ñ NÆ›Åš3\"\24\
Í\6-\6év†cÒ%ËôØ\28w…e.Éq?&·ı˜\28õcrÓ™Ã›\127Bqó$\23Ï‰\0311'ÎÙ1¹óÇäÌ\31“+\127L{Ü,³\4ïËF\26®Û*t0<²û~Lîx¼ÉÒñ€=&Wø([’Ç(Óöt4îïQ9²¿-†Æ¢Û™ót\14É½|¨Òèn\30“Ûx1¨Ñ\8zLÈ\27´`ÜÙı4¥ºx h<XŒïK³Db*J\18ï\13\24ÜX¬Ù\
öEıº(×\28W¥ûôÃuƒ\7¬C-y{\6Î¥–L\6WÁª\20\11q„uO”¤§âÚ¡+üWå¿T¾WùAåÓ\15ã’dV-ß”|QyXvò€z|ëIÄ{•\25Q¿Ñ¹º\27¤Ÿ›83±L?·Æ•1â»é>iL};•\17Ç\0034ğõTádiü¡yZ³âÏv€’‹Pf\21µjÊ'eO,9O›Ğ.İ1;tœÇŒW‹åü‹-\0293Gqÿ\22”\30\29~\26–QZÖ¡Óxµ8÷›œ¹cp»Ò+nB‘sÂ\15´1ÚJØ\27„\23íÜö¡À\21VCÂ5,2=/Z·\14İÛ\15NˆñƒnF¡ÇpÉ]_²×M|¼~ÿo_y’Ü‘œ‘\\$Ùµ+É7„-P\15ô‰ä\4a\7Ô\0Í@7 dğ€¤‚pÜ“;HÜAâ\14\18w¸ƒÄ\29$î q\7‰;HÜAâ\14\18w¸ƒÄ\29$î q\7‰;HÜAâ\14\18g8ƒÄ\25$Î q\6‰3HœAâ\12\18g8ƒÄ\25$Î ±'W\8g \27G²@x@R!©Q&”ÂW)Wfö}Ÿ\18iäéşÛ“\11H_@ó\2š\23Ğ¼€ß\5ü.àw\1¿\11ø]Àï\2\14\23p¸ óà%î\22$™\22Õö\12%á×¿Ì\8/‘ÜÙbÑ\22‹6\22íFÍvj\22í\18>åbeŒïòºËø^g&2+!=3½ Åˆ÷ô›ò–¸'şdz¢¼#n˜^)Ÿ‰oÄéBùiÅ´f¹èêÕ‚fKš-i¶¤Ù’fKš-i¶¤Ù’fKš-i¶¤Ù’^Kz-éµ¤×’^Kz-éµ ÷œÿC\2kÙÓ;Ó3Ó\11RĞÜÓoÊ[âø“é‰ò¸!™z¦\11Ë+¦5åĞÚ\13´<\19²ódåÉÊ“•'+OV¬<Yy²òdåÉÊ“•'+OV¬<Yy*k\1\9Ymdµ‘ÕFV\27Ymdµ‘ÕFV\27Ymdµ‘ÕFV\27Ymdµ‘ÕFV\27uUÃÂjĞÙÓ3SXXM\11«ia5-¬¦…Õ´°š\22VÓÂjZXM\11«iY5-«¦EÕ´¨šJÂö³¯ÖßLÏL¡\29Gí8jÇQ;ÚqÔ£v\28µã¨\29Gí8jÇQ;ÚqÔ\11t\127eÓ\14É\25ÉE’À! \22É'’\19’\6É\0215g \3’\
I2éá§|KŠLØª ¹ÅÌ\1™>Öéc>ÖéÃÖ\0252]¬ÓÅ:]¬ÓÅvºXÙÇÊ>Vö±²•],r(zış/$Ïo&aŠ$=3½ …zöô›ò–¸'şdz¢¼#nˆg¦éÂòŠiM¹(ğÙƒNO\26=iôì¾g÷=»ïÙ}Ïî{vß³ûİ÷ì¾g÷=»ïÙ}Ïî;tß±ûİwÔBG\26\29it¤Ñ‘FG\26\29it¤Ñ‘FG\26\29it¤Ñ‘FG\26\15¡!;ß<\19N‘'9Orä<Éy’ó$çIÎ“œ'9Orä<Éy’ó$çIÎ“Ü\2r\127ÀÊ‘•#+GV¬\28Y9²rdåÈÊ‘•#+GV¬\28Y9²rdåÈ\
kûë\127ûÇ·ø9!¹#9#¹H\"|¾Åë\9Â\22¨\7úDr‚°\3j€f$\30É‚²\
I\13a °¯ü ‘oLŞ7&o_óa\11láµp\27[¸-ü±\22şX\11\127¬…ÛØÂ-ká–µpËZ¸e-Ü²\22şb\11\127±…¿ØÂ_lá¤µp\20[øjmôŸÚè?µB9ø\5’Èvıì¡Å\30Zì¡Å\30Zì¡¾\30êë¡¾\30êë¡¾\30êë¡¾\30êë¡¾\30êë¡¾\30êë¡¾>nQ}Ü¢pgh'ö\9í}B{ŸĞŞ'´÷\9í}B{ŸĞŞ'´÷\9í}B{ŸĞŞ'´÷\9§ö\19Jü„\18?¡ÄO(ñó\127±÷\
I² ËOÑ\20f¼ÇŒ÷˜ñ^”\0256ò\12»]¾Nà\127\2ÿ\19øŸÀÿ\4ş'ğ?ÿ\9üOà\127\2ÿ\19øŸÀÿ\4â'0>ñ\9TO z\2Õ\19&ù$,wtC\",;Ìu‡¹î0×\29æºÃŠé0å\29¦¼Ã”w˜ò\14SŞaÊ;Ly‡)ï0å\29¦¼Ã”w˜ò\14SŞñÍE22÷]œûs\31ÎA!\
\29wĞqGöğ/\26¨·z\27¨·z\27¨·z\27¨·z\27¨·z\27¨·z\27¨·z\27¨·z\27¨·z›øúÕÄåÕÄåÕD\3n0\5\13¦ Á\0204Xu\13\7A'©¡“ÔĞIjè$5t’\26:I\13¤†NRC'©¡“ÔĞIjè$5t’\26:I\13¤†NRÃt\
\6{…F¯Ğè\21\26½B£Whô\
^¡Ñ+4z…F¯Ğè\21\26½B£W,¸+\20{Å‚»B¿Wè÷Š\5w…š¯Pó\21¶2ÃRgXê\12Ka©3,u†¥Î°Ô\25–:ÃRgXê\12Ka©3,u†¥Î°Ô\25–:ÃRgö\30-u–:GKa 3\12t†Î0Ğ\25s{ƒ:oPç\13ê¼A7¨ó\6uŞ Î\27Ôyƒ:oPç\13ê¼A7¨ó\6uŞ Î\27Ôyƒ:oPç\13ê¼A7\12ÈC\30êôP§‡:=Ôé¡N\15uz¨ÓC\30êôP§‡:=Ôé¡N\15uz¨ÓC½Cg\30:óĞ™‡Î\0220[Àl\1³\5Ì\0220[Àl\1³\5Ì\0220[Àl\1³\5Ì\0220[DK\1y$\11„\7$\21’\26eç\26¼Š\13d7İ@vÃâ=`f\15˜Ù\3fö€™=`f\15˜Ù\3fö€™=`f\15˜Ù\3fö€™=`f\15˜Ù\3fö€™=`f\15˜Ù\3fö€™=`?ª@©\2¥\
”*Pª@©\2¥\
\\*p©À¥\2—\
\\*ôP±éğwC¯1sûÁ/±\30`Ï«\16äØ\19Ğ`°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£b°£Â\\!æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQ1æQá ¨pPT\8}T\12}„ôÎôÌ\20$=Iz’ô$éIÒ“¤'IO’$=Iz’ô$éIÒ“¤'É\5$ÿ€İÆ„$7’ÜHr#É$7’ÜHr#É$7’ÜHr#É$7’ÜHr{n¬W1­)wL1ï\7®™ĞJkZiM+­i¥5­´¦•Ö´ÒšVZÓJkZiM+­i¥5­´¦uÖ´Î\26l\0258©\0248©\0248©pnTô\9Bzgzf\
e:*ÓQ™ÊtT¦£2\29•é¨LGe:*ÓQ™ÊtT¦£2\29•é¨Lñ\21^5¶š\26[M­¦ÆVSc«©±ÕÔØıjì85vœ\26;N\29§ÆScÛ«±ßÕØïödC•\
I\13¡ˆşW\29ı¯:îE5\22yÕTc5Õ°€\26*>†\29ŞáÈq8r\28\28‡#ÇáÈq8r\28\28‡#ÇáÈq8r\28\28‡#ÇáÈq8k\28Î\26'ã\8U*$5„\14I8r\28N\27‡ÓÆá´q8\26Gğ\28Ás\4Ï\17<Gğ\28Ap\4³\17ÌFP\26Ai\4‰\17$Ft;Æ8Õ\24£RcŒJ1*5Æ¨Ô\24ƒQcŒ81Ğ4FÿhŒşÑˆ\8ÓÈ\8SHïLÏL/H1\0FšFFšFFšFFšFFšFFšFFšFFšFFšFFšBº±^Eì˜ÊÀ\17qÚ\19ÒëI¯'½ôzÒêI«'­´zÒêI«'­´zÒêI«'­´zÒé@§#t:Òé¨¥t:ÒéH§#t:ÒéH§#t:ÒéH§#\29D¢FXã\8k\28a#\2R#\3R#Î#IÏL¡2O®\\=¹zrõäêÉÕ“«'WO®\\=¹zrõäê9£*\\@ö\15\18,\29¼\12WØQ%=3\5gGÎœ\0299;rväìÈÙ‘³#gGÎœ\0299;rväìÈ9ì¤?_ç\15^!ˆÙ×Ÿ\31ûŠ\12a„AgkfåK÷?\26ì%¯6¸ÔáR@Ìî\\˜¤\27É†‹“ò=o/?¸ZÃ\2Hx–«4\6ÆÚø™¦®?Y¡H\2>ãåFqÌîÛA’?ø\127Q„\27\\Ì†?5ô;\3—³cìa‰¿ Í\21!ˆ5^\127ä\27mfÃ5•”­r¶NÙ\\72\13Y2\21éš¥ñ1¹Ô•şgë\15õŸl¨ÿaãç«ù«n”\13S\22³áÎzªâ˜åÕ\12Ò\19˜äô\12ïXì~85—³£d…ûßœí~à§4òóvfW\13\21¶\15ù‹€ç”•‰”ì*½…¬\\¼Àïß_{¦\
±¥p…O.\12xşö\28@ş°JÌ\6­Féš¥‡\31¿ø·DÿK¹}ñ„…à~¼.\31;ıso'äo’÷ò¹Èç&òZòîÇóoøYŞş¹/ßğÙËg'Ÿ\15)½IŞËç\"ŸûS_áêgø\28äs’Ï5|¾?öE¶8,µ‡äoòyø±/§]\30>%\31Úé?v•îŸ¡~/õ{©ß‡:A²×\25¤¯Aú\26¤¯Aú\26B_¯“´y’ñd¼'y¶“Ö:i­‹’]?Ôl¤f#L\26ée’^&ée’^&ée’\17ÍÒÚ,­ÍÒÚ,O=„¹—R/¥^J—À\17{Â\127\
aÒÂ\"4¥“)]…É*LVa²\
“U˜lÒã&=nÒã&£Ø­ª\13Ÿ»\5†Ï‡Hn’÷ò¹Èç&r©\31´Q‹öj©_‹ä\24z\15Ÿƒ|Nò¹†ÏĞ»“~ôëd¤£XÎ(–3ŠåŒÂp”š£Ô\28Å~F±Ÿ1>åş\31@yCÛ",
  ["length"]=28148,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=2425,
 },
 ["version"]="1.001",
}