return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="sv",
  ["source"]="hyph-sv",
  ["texcomment"]="% Swedish hyphenation patterns (Jan Michael Rynning, 1994-03-03)\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: sehyph.tex (2003-09-08)\
% Author: Jan Michael Rynning\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
% Swedish hyphenation patterns.\
%\
% Copyright 1994 by Jan Michael Rynning. All rights reserved.\
% This program may be distributed and/or modified under the conditions of\
% the LaTeX Project Public License, either version 1.2 of this license or\
% (at your option) any later version.  The latest version of this license\
% is in http://www.latex-project.org/lppl.txt and version 1.2 or later is\
% part of all distributions of LaTeX version 1999/12/01 or later.\
%\
% Last update: 1994-03-03 (March 3, 1994).\
% Revision history:\
% 1991-01-08: First version available for anonymous FTP.\
% 1991-08-08: Changed \\aa to \\aa0 at end of line, to stop TeX from\
%             concatenating the patterns.\
% 1991-09-03: Cleaned up lots of inconsistencies in the dictionary.\
%             As a consequence, the patterns shrunk a lot.  Also\
%             added some 4000 one-syllable words, some of which were\
%             hyphenated by the old patterns, and some 1500 compound\
%             words, about half of which were incorrectly hyphenated\
%             by the old patterns.\
% 1991-11-01: Added another some 6200 compound words, all of which were\
%             incorrectly hyphenated by the old patterns.\
% 1991-11-13: Added another some 6500 compound words, all of which were\
%             incorrectly hyphenated by the old patterns.\
% 1992-01-30: Changed macros to ^^, for use with LaTeX and dc fonts.\
% 1994-03-03: The hyphenated dictionary now contains about 118,000 words.\
%             The hyphenation now works much better for compound words.\
%             Patgen parameters: 1 2 20, 2 1 8, 1 4 7, 3 2 1, 1 10000 4.\
%\
% This file contains Swedish hyphenation patterns for TeX.  It assumes\
% that you have fonts with the Swedish letters in the positions where\
% they occur in ISO Latin 1 (ISO 8859/1):\
% Letter:   \\AA  \\\"A  \\\"O  \\'E  \\aa  \\\"a  \\\"o  \\'e\
% Position: \"C5  \"C4  \"D6  \"C9  \"E5  \"E4  \"F6  \"E9\
%\
% Load this file into initex after plain.tex (or lplain.tex, splain.tex,\
% or whatever).\
%\
% The patterns were generated in such a way that they will hyphenate\
% correctly if \\lefthyphenmin>=1 and \\righthyphenmin>=2.\
%\
% These hyphenation patterns work quite well for simple words, but not\
% quite as well for compound words.  I'm working on improving the quality,\
% by adding more words.  If you know any Swedish words which are not\
% correctly hypheneted using these patterns, or if you have questions or\
% comments, please contact me:\
%\
% Jan Michael Rynning <jmr@incolumitas.se>\
% --------------------------------------------------------------------------\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnopqrstuvwxyzÃ¤Ã¥Ã©Ã¶",
  ["compression"]="zlib",
  ["data"]="xÚ5Y–«8Óh§Â\8r-Ó\12\8§1‰\1Á/š:®ñäyø&\19È‰Ý½ƒº\15ŽPß+\26)„?Úú^|´÷f\8¸L¢*\3?+@ý\0T\15ýj\0036}ÛÀ¹\19fh&ÝS½š®š\14à\\ßõÌk\21\9fÃÒƒ¼†–©é,,õu§?5ý\18ÈÀõ¶\2·r´¬mìv}µ°Ùö.Eènk›Ý†ì•Q\7a6÷l­î¬¶ºø¸ûkG\11½wQö}˜¢\23÷ÅÒïKÞoÅÇç`âÏ7]Y¨ùçñûé}7ÞN`5ÕTÔ•S3P»%QUW§ßoCs5ˆ(µk¶±e¼º­\26mF·5c»Šm=±{Žèj§ÏÝIwA\127¨çI•Ï.Fý™ÛÙLfÐïß¾›ôÿþä[û\31v\12ú’ßQO¶¡?6’|uå\12<štƒ}\31FÁ\\Ñ„¡Lôt¨“q©z\8ëÞ±\31ÒXFØv!Z:ØnPµ1)–1¶i«\25°qi¦A”wGsÌCê«ÿ°ÙÇßŸÕˆ\9÷ÄÀSüÔÝŽÒQ›‰™ÛNÌxu™\2ç®v1ÍCŠ©˜_¿?SLÛ¼$\7vþý›ª\11×QÊï7“0.º~rÔ“È—ºL'ÓR3>é÷çaøòy\27YzËhÇ–jd>—rn\3’\127™c¥,•ësIvr©\12Ï±N–fû\4Þ¶+b›\2în\0°eÅ\\.7r¯”³¶k\12Àê\18íÄM,Õuø\0153­vh=îÕ48È™\1É]ÝgQ\25™ò‘lS~Ï%ó”\127\127ÎŽ¥`ÐÖºl·®w¥lCCC7ÆŠNoN\19#²ï6{›Ž\11ï†î­\11Ã­s…9[†\31«+Ã${[Ý'‘ÝÜ™8=¬b÷×>Dmû0Õ†\14ŽÎ¾\\ÝÜs÷(/\\\5úýn(á¨\4Óîø\31©/éÓ±ÒÏ#(Ç‘M{”n½£¶Šƒ\21âR<bU¤<Ûì–9ÛÝVãè\30\17õû]özËøCÊwI\1ïš*X#.Æß¿¹vëüþ\13ŠðûwUñû]eZþû#jË{ÑÞëûQ´Í½ÃÙMõ&*…·\9PM­•\14jòð©/\15‹ù¶Ï€£¹)â³\30!f¢A4VÆ€Žz%Å£í…Ý\24¢\31MGø£z\9–H’ÛTHd»âÖ\0027cò0\5¢\2Ç¸mºGÑ>ëçRTíóÉ¶¿µO\18\25¶/¹ho=\13î[‡\0247*ûîƒ\27K\11Ha}Ãª\6Å\8ÔýAxýE+¤\21m5œäÃ\7é\"|líxÃ6mo#•ŒUÒEFv[;ƒ2KÚð¼0–#Û²¥E#«ÅÀÝ†¹ñ(‚¹Œ\2ÎN\31Óc\25LKQ·Ð\11’9ÒSÓ>(u\26J¸F[N\16Z˜Êè\1\27%‘uª†´™ÂÄ`Ö\19ÆªÅ=•ìkØÏÈ°´ÓäÄ“~úý\11šÝ»T²XILç´5«UºuÉ´\31\1Íz›t\31vl‚…\24ð¦¦¹}\22ð³A\0‡kç\27Qse\31Új¶\15\9&J\5©j§g <ŠX'ésh€,\3CX\0Îeª\31G\
\4!£‚Ô™\11^h\\ÕSQŠiKÃÁÔ$\6\25¸”ƒI—1àj¡Û'\3“¶jiÛK_ã°§a\11´¶f¾mWŠ}¹Ð›ÉJÛ\25qõþ\
˜ìäœ%z]¥˜\28ÒßVWÓêjZáz•!”½Ö“Ëv\13‚Hq+51¬ë\26\3¾V±gDô­Y³{cµókµQÞºAd€ v\17oÖ·€y(£ VrJòIñùÎ‚É÷ÁXÆZ7ÏŠ&m~È’IÚ%\22xî›-’}ÑR×^‡\30žIb×v\30«hxnÆl1“À…–áŽ“Y$\16.kÂi].7sÉÛ‰Í›ÔÑÀÓ\28»‰óÎŠ\
ß\17%\30Véöjò±\25.ÁbD³Ãš£ƒ\22¹Ý;f÷&5ÙJÚÊ<6ô\2áÁ±*åo-T&G\16eÆˆ9¡\1Ýhð’1`ãz\0_ÐB¶æÐ#\9—\7µî|Šïr a\12Ç.\0111‘°Þ#ˆí=F–lw·\13>E\0308-ÍßìÜvL\1\29í­<¢Ñ’ím»\27÷]¹Åò!jg\24l\4¬­¥BƒcÅ•ÖWE5u»+\23\18^¹\8C\27q.!}’\14|ã\21¸‰ê bŒ?3·3L’Ÿ}oÍPîvaZ€\11éƒ/’\28vÄèÓ‡£lÁ„š\22zzì\11Ä'ØOÙÞN\23ß)\1¼µg\31!,¢³rn«S:a\15o÷²¨îmqGD\30\2.À‡âÄ=8(Aã\18ð\0¦+h“áÝ\29Þ£¨ï÷\2&D[…û^ÜïPâ;¬\7POÌ\16áÔŠ\7A\12çƒ\
»âÞUˆÑ F÷m$¦›\30ú¡^DB²„4Ñ †\27Ù\23~OXŠ°[Ž0h\24AH4w$MÝAÂ\3Yn³Ea{\14x\
mq÷§(ïÕ\19Ð|Ñ\26:>Ð\26\"†D\26\8‘]†DCïÕ‹‚\16\5îÍÄä\
éâÔÕÈ]xØ\13>–\6²\7„\15Ï`\7\17‹ò…6û<[_\"€L‹b’¢;^nHlÍ}I8³\11[\\#c)Ô;h DÒðm‘~³\0006Û}y7–¼Ú‰\12iGQ¡}á!\127ug}\0202û±½|Ý…(\0A@žuÏ‡r(¡o\1!”g´\4ù¾UŸ_LÝ&•qêžÂ•pD-\\¬JR››\17f\11!yÜØµw6QugúÞCàl]B\13h‡t\18ô- \1lF\2>Ë¢ùDÃø„ÓÜ>\17‚>»$/¨ÀÌÜgG3‹úóëƒ/V=\16NÓ|~-Ÿ\6ïÅç×ï7º\3è'×\0201\20ŸCÍ2ú\28\16Ô?‡\21™¶þ\28)Ÿ¡\0t\2ÒŒÍ\11€Lkb;~*\30|:÷\8A\8\25É%÷—w×GkF…|Å#\24þçH—õœmÀˆpoQbÀŠ^~N\29ÒÝç\18 ži\
¥ä…ŒõçFkab¬˜G[À]?ŠúìT nÑ¡Rv+Ï]\8\19âžu¢A˜0=L\15ÏÒ#gy¸Ý\31Ò\19à\14\25&„¥þ0ê³x|*…–Gñx°Ú\31q}TWñ`ÛãDNk\3v\1\7#%ô\15E·ÇCêX=ƒ\31ìW†\20ip\17²mC\"hE’e0»˜–Ôl\7“\24ô\18G\9‰~t\21Ò\7B$mD¦\29°)³H¢\9\
\29ã.u\24µ™aë\2®@\22Æ`Á»!ô“úíáíY<žŠÅ­žž–÷\19.·7tí1@²€\13’ëc(Ù\127ÁÅ@\8d\13Ê—ÈŽÖØ×Kør@È¨p\13\15õ\13ˆ\17ŒÙò07[Ðñcì.r\1º9Ð*lö\8“3˜P±¤t¤«\23bîãu¬ðZ†\30þZ>*t×úÑØàÛ,€R@‡\31¥\3‚²j£–™lË,«l\30Ð‹ÇR¯¬\14²)\14\19Ït\9ig³°\11\31Kõ¶(èÃ£D=sn]f\8\"}xàz¨–.\27Ñ¶IÃtAÒ•ámj–º…$¯Ûù”•\17‹0äúè­^~¦'EáÈß\4-‘\
õÊ˜ÅÑÌ\11Ù\1;Ëú¡ô0š^¼[…\2d\4Û|(‘=¢ÖrC¾\0191ÿ[Ó¥/š°=\13`N·\16¥qÓÔm´‡èáD\"¸¹ìðE\"È,y©î±ÝtÖ“MÙ¤ß\20æN\"ZžBI‹\25VSÉ\0\31Ê\29x\20<\"Ën3ö®n#Œî›b°äF\9Š\2\14k9u±à™XˆØƒ0ôd¸\3}Bšy\28ÐðÇQº€Ž`S\15\4G‰ïÃ-sÔçá¼QHuÆâø‡2ÞÅã6“DÙåð/£öû\23¶\14„8>B\19y( \1JèîÃ\29Ç@n7Ã\127ú€ÔÎNtuüþ¯.º[[@š ‡t\9ºÔÝñ\"Žz„ƒÚVwŸE'\19è>¿†ç³\1{®AÐBº\7™ @[Ñ=äã\29kü\0¢\15vj‚\19î\27kUÍšÝAÄV\26¶-–@s©zËÎrº¡èºrlt\"Â\
‰cKwO(TÕ=w½=\25Ñ\14\1øúÎâT\8»¾TÈ 8Øp×ˆ)\16.Ëxu½Kºð¬‰\"\18ªÒI[qÚˆ¡/\1MO\\ÅBîn¦‚ó\127é´ý·\23­¯^‡\0RØ5/\6¶“xtª”\0š ,N%#âŽžd0Ùd\"\8%\\$\27Í&¢{èž‹)\14ÁiŽæ„ýày\11¬Em²›ÔDA*\9ŒÂ\4µï¦8_\3\
”F>íô\20„¬›*è2p2\6\0052ÜWyÔÈÊ¿\27²\22Rk“4\7ƒ\
©>‹’$‘p&`¶3Íl›æ\5¥\11\20:g7¯\30‘v©‘ÏtejO<õ§\11(ÅL¦Ž!K]¥0QvéeÚÑºSÅ\14Ô“\3ZUJCê›ÿ0Ü°C7œMiÓT\0­i‹ U\2Ün@Ñé$¡ÿ9i¯¿Z“ì·\28>¦ûCG\21rP8\0025Î|“PehØÛ\14§è°‹ya\24\0224ãŽn\18Cej‹\
\"ÜÊ¹¸:¾¢úU\"U\28¢©qu”W9n·\30ÕÝô6+ß$Î,Hb³²e—ûš•’ëþ\8è¶íÔëà{\3Ù 0¡.Î +ñu@Ðe\22•ÝÍL¥4É•ç\2Š3\11y'#”Wãä~òOöm¾¨ aÛ\20>›ŸC8îr\28Ð\25e«³'€”èèäc¶Ü·Îß¿\15ƒ\29#X;…lM;‰ª6“J…¯ì ÌÝV\127Ñ‹-ö¿ÇÝjL*âØ8ë«¢%¢\28¡¨]d\0074ÈP½™f7’s\28Ô·\11…°Cù‹%\25B%Ü\127¿\26±\7‰`pJéÀE€\13^²Á1\17ª\127A\18è bQÄ¦Ýv§\6UÏÚè¤\7†´Âe²\15ŠjÝ\13®Ý©£Q–\11g\11Ÿ­PríÅa¢ Êu¼ËPôÌBOc:T8\6sWt§,êÙÚ9ÞÑÄ€ÍiÕ»«oÿWW”üûýÉì\29nÝæ˜?„J¬\29²¢oGÈ\17\12¦ƒ+têt³ˆÍ¥6Wu\127\24¸?ô‘,”÷D¡{¶Å³¥P€Û¨~J¨Ð‘'Êï\23PÉ\31¸ËxžìãúÉX<UÎžf€‘>%±O‡–Ò\28¼Åp„­'”ùù|Rü\19%\15Èø\\te\0<\2¯-A c\"ðAdŸŠbÏ¡xÆÙØsP\9éÁÒªçšmÖ\19§\19O\8¯%\13%3S>Ñ½nOB§\5†c;I9·ÈùO\27„^ò\\¦R0ÞHÝ°\29ž\11¤\9˜eòÏEíß|k\1­„žx9ôõ¬]$Í3Ë.€°\26‚˜ù§›o5f`ŒÔc\4òái\2\24e¦±Y$w¹Ã¢&Á,H\2‹vt]\11å\19‡Ç\23OTægÀ1à\26™„¹1ux\24Ú§Â-ÎÁ\17e¼Ÿ\30%BÙúÉÚB\6ÓÓ\12á{\1½“\0016*\29O%þçÎ\"©žGñ<.…òyHùžG¥®þ<éÖ»x¾ë™\18\127ÿVÎÿ-&\11\21ÊÀÌýàù)s{!önàA”™Œ@v7ð\17\240îtÈÛ·\13\19Ì”³µë^\14¦{\"<8\18ÑîêÞÓ¿¢ìCmé\29‡ÞÓªpïÆn\23D;&7íêÛƒ…Õ×,Õ¾iOFš¤,ÆþÎïQôqšÐ«iõ]s¯\9d\9\3êWÑ—ðGZÑ©ä\1=e\19½#ÌÆàQ\2íëŽvÀÅ˜\0306ÕÛô.E^xY\0134>-s#ª™\21²$ˆàÍt{¤8m@Š²S”].\17ÍxzU\21¼\\/]‚.7HØ½d”j™ð¾óô†.CChýÍ.ôEï©xO\127W¤íiZ¯ðC Š[ßCßÛ@´¯¯\\\20N\19 Nö_Eÿ%÷¤!Ô«\"Ó³Æéñ\16\18h?\4á4,N²Â!'¥©HôýP:±%¢PÕ«¿ô!\11•½ŠKÙÛŒI\
C‹ øÈc­}\0R2°\25/ŸeÔ\30ÔýôÒ©XJÌïÏl_\0038\9‰•Ó—)†Í\26—\15\1µ,I±œ.'\7'ô\30à\28\30ÇÍ\22e0Je®Éã±\8\18Ÿ\29rã7á‘\18ö9Z˜‘p…Œu\127©3}¨3„\13«ù]/\8k\12Y^ÊÓ|0H€ì¿‡©ü5éïß\15ÂàÎ)|ßê=Ü¢\15å¥o¶6Êß:Ç\9í¥‡Uº`7„ÊÞóXƒjdI\24?B’î%2 \14ö²\24ÀlÖ¹3I¤HC@Gt»9!Á8…‹\17k\0045kŽ\28ë!´A•Ô§¿Ôš^ŽšõÖ^Gë\29ž\0179LQÔþŠÀåò°|{×D\23¿ßÑ\"ÄÇ^}\7§‡\31¤;£\27'#\3zïFÇJ¹Ù#\15Ø{¸/k’ŒÇô¨„AÕÁn–ÃKM<La­þð\24¾ì\15³\31»{ýæ< \19õŒÎ\27Nû²Lëûý›QÄHÑà¢\25õï7M/\127¿\25\11fg‹tp»Þe×Ëš–Hüã\17éWñ\21·‡_-Û\17È:\5N\30Y~y‹B\5_í,UúŠû\15d4\29ì;±4Ê¬Yèéœp\5nÈ¢Ê|g)0góYÔ_â\11½k\23>³Ð\17øRª\8h\22ÑY|U}ñÅ¾EÎ\"Ý\16ÒÑ×À\30ÿb\23JS¿nŒÑ\23\21)å•_lˆ¯D\14x \0\30öµ ÷\2×fE\22\7›gñÒâk\9¢_\127-ÿP\13~\7ý\11‰¿ü\"\27J*@iªøz÷\1%-@9â×ÛÛa\2\29ø†ùEkàÄì\4x[*±2ÐWÌÐûš/§â\11¾Ò\11\27/6ÀQ\7\19¢•\0038ÒÿDý\3ºêÐV\12\20°\7x¾7x±`\0\11\11±\2ad€÷ º\14Õ'ÉQL>\8ùD?\24®\19=°\23š\6.äÀÿˆëäá\1i&Ã\3áax H\12ž[\0Kãœƒ!îº†Ð\\\7Ué¢\28P`\7ä#‹{\18w£qÕ\16ò\1\30ˆÉÐ³ÿ\21SïÅÐ7Ý\11Èn\30ú\
Ò6T\3åÄýä \0309TªIÃ(s$“:ä \14‰‹-‡v§°?¨9>/´‰¼p\17Ñ7K8¦€³a\7\0195høAÈ[`Ã+}\7•ËÁmgëT.†é¦V;LPjÀÔŠØ\1¢I‹Š\
|D”»i˜\16ØmŸ-žJèÄPEô¡$RxôºÒd—ó0—ê«Ã¬|7Ìn§Á#ï¡™£=³i\26/\0315ê <±’Ô\14ÃÁÊD\31\127\24\12ó\11èŒÆ\21cà\6\2ì(sÑ\27òÎP%‡6AÌˆz\9T²)(u_E3¤\28\30Vd\5Œª\16¬h\29\11a¼üò‘!ÉLu'“oèƒM )Yä¶:Ù‰&¦ñrähf¨\24ÄïQ‰ëÒ+IÛîÕÍàÅ$ms)¥ê=\27\16#°|âD\11\29ª…A_êÑ\21\15å\29ÂTeP¨\29–T\26ïâY\18T„\4« ’ZöâZ¢ƒzë°.®L¶¼‹Ë\22Ô\30ä\13ªœCö\26gP‹\28òRYŠ­sÿ\1>E¾XY\18\26­hPˆ\17ÉÕ<ã¬s½09 Îve‹%¦67ë¹–°jÑ »¢\24«€+Y5Œ(²oV¥øCÄ\22\27x\0039\24·Ðô\2ÁJ\7¶¿\12tøOó3\\QK‰ÅþÈ¯úˆe\1\4V\17¼p\23¹í¥Ób¯\26÷\3ªß\16‡\7\3\\iØ!Æ\16Ón\8øGø2ÔÓ£AUÐm\31×uÃ^î^Q\14{ˆå\"Æ€0Oã‡\27n/Ý†òtÿxÛ6ÄIÅ –6œ’’›ŒqøSRíŸÆÌ\
Ì·W[T/\4å¢~)\30¾Z/bË\23Üîõ(^\"@Üv¿ B¤ïŠ—‚nóBÄ}iÕ’\18Y±~A\26ë×\23I é/ê®_#™Æ©xyFý\26¡d¤DJzÍ:RñRÂzA[^±èê×‚höZâÆ\13IÏ“oq\\\8’\14ÞýZ‹\23|„ì´‹26¼LéKRübÏtB–\127ùÚ‹\23ú\9\14Xþë€\0“ô\24+á„\30Q{øýB–\26\3‘\18\8Õ2ˆ\30½Ž=Ž+àqž€Ëêê\21N\16Ž-Â³[6\28ð‹×u™\4²æõû¿â62JÕØ~\8\30\23„€Œmý é\
^\13€57¶ã±mÈ\8\30\11í1d‹£†\16ÂžX(â\"’ãRÒ¼\6ÌBÖ¥§³TAê5\26Ì\17¾F©\30 áÖèblãèHƒ:….’dÛãþ”\25Ü‹±\1¢æ‘-G\3ÐL•®\4k! ·Á:>.Ô\5:M·Ù9Ædlãž„=º½o‘Öî¡oŸ`\15¥F\24^í0u$bdÊ±{\\\22w\26%à„\11\6Ž„£WÖ£\23>\0Eñ1´Ÿ±‹\3ôRBá)O\"¤4—R'iPÓF–ç¨\30\25Ð#¹rlz\22ÇøE3†G$„dÃ\11\25ëa´ÒaB­lÆAV1j£—M\3\25\15„Œ2z-3JO…Ðq8£ \23ÙXÉÌcè)#«mD2¹ž7è'H™¸ëÙ!Bué?\2o–éIn\3<uw¦†sã\28\"ç0›\18í@÷fÂ!Ž\23 ¨Ëçèü‹]u\19Ë\
\15Ç{:FÝ¿ß\15\0273yLÏˆ°\5Ç’±\
ƒj\12µ³\25“ª\7žá\12t\24ÿ¦üô¦\19ìVöÑg1.Íƒ¶5ËƒN.H\20@¯•qCMMãš[‚»ëyá™´`lÀç\7YìÈ2Ï†°”i–7L¸\21”ÇÅµ¹¤g@ïˆGu®q©hÏMiƒ€Ü\27\0163éñ¶!r˜Æ»Rµ]Ú¨ð>†ZFìf\1µg(5•¹\20o\14£šÚ\24š\26Ð³}è\0163¢7JñÐœ­2æ\1‰À9TQ\19ÐÏÿL6GóÄxÅS@\4‘1ŽlZ\22k•ßæùý«9¦¸†‡!E1!¬w¹¾\12±Öá¢‰{¨r$éÖŽ\22Tn[+®ÄYšì…‘ZkC ­£$¬\13t\22ÚÍIQD?Ôá\17ç‡ÉáãúÞ–¶˜\19\26:Þ¤U#T-\24eb\15ãÝeð¦1\24\18”HdôXˆq(w×>hy\4œ…4(ŒNâV€D\30\23\18-óë#ÐÍ°7Ñ±q÷@\21\31»‹B\15×õ~Dmv\31–NHsô\20s \11\26À†Wº´CÇ,ñ‡í#m1G‡M:êµ\11\4«%]–>\30´\17Õ¡b\\Ngølc\0ý»ðI$€AKÃJeD/Ø\25˜\18a­DbKŠPãiŸ\25×ÁÎÕ'ñÁCÉ£–\17>$Òñíí4(ÎÊ‘F š£|Âå®º\6JF…~.ÒbjT\21\4Œ\23QþýY?ôf´º@.Ü\9öÄ,ã€p<P®&oèq?ìY@P’žz\25¬~Æ#¡*\21¢•¤å\13âÁÄLåF\2ù™Ö[–9i?7˜þ²<Ã\1\27ð %\17'c£>†\7êT}é†ºOq<F©ˆBÑ¸ÝrÜÞ“–BÔA)‡à4Ü\11Åé\14µžn\16þ\9µgzx\23PLÞýOqë?5üÆ½Õˆ=7è^5Ù¸.$î©kØsS§É\
A¬ò©ƒN¨\4MM—\28¤.›,£@èNºÃv˜¬^ü\20Œ§®B;¡ˆh’|aòˆkB[šÊž¶T½‰{XËÔ{LWN\0083,œI5Ž¢\7ÇÜ¶\12u¿\0005 EO1Ó -ÖC\16Bó,Ãb5<\2öL¢¨~Šsøœuc\0073¤W¸\25iÇJi<´½ú´.åið:>ã?­ûDÇÊ—÷<“·„·\9ñaBð Ÿ7ùÎT)“Ø=¦L³\19ô+“Ä0Ž®\22CT“\8Ê&ÑìuÒÆ{RG›&X4â\6«mb\0ïº)‰8ãiÂ´°¡\12¥©ÊD\12ûä]¹\"ÊØ†g‰˜SO­ <…½è¤‰è45‡9Ü¥Ö;YV\3šdPnoõ½Ÿ‡~íjH\16g%ô–9¬gHÊ4k¤:!GNKÉ~€÷i'† \4_ò¼žê—G¤YÂ·œäE@·‘\
9Nø\8Àå¸ÄÀ†]Ã¤\"3©ÈL!?Mkˆ¤ÓêÊ¯§Øaˆž“×ètðµ\4Œ¡tƒ \3!™ÐŸ°\2˜6õéI=y \28³ã\1›Ð\9\19Öëå8\7ÈCý),\5&4•÷ná‘Æ¶\5\1\23:\14ÚžM’U­v[szÒ6… <]\6‹SÜ \8ß\17\15Gš®\27©@ß¶ÏÓøIò\27áxÒ<Óé³\11Í\9o˜Boa\6¨io!Û„ìh\1Nî\5¿„ˆ\30Ú­{n>iz²\7²ð½qxöƒé<\26bÑcg4öirv\\\16‡¶Z8á¤\19”*´ëB#i\\*\31&Þï\1¥34P­gº®¥¦Ó»Fƒ¬ù´\29§\"‚vÈ«Áö\19\0K˜ÞŸAv§7º½H²)ô¼azK<\26Q2…RC9yÒ\
pÓß&mÊŠ€Ò\0ŸTŒ¢8\3\8ï\30#õûÍ\2a=£9xÃ\30R\7p¯\1’wª±mÄ«(,,=™ž\2\"$\1S@o‹(âÇÚ~4†5\20%\3Yrn›g\6öè³ÂÍ\16¶ú¬e9ÐK®ÙwCBÏ\
gÏ\12ëÅd)¢\6hDCÂ¬oûj„ªl Ó‹xeÂ\4Î—`\15ª\17Pç{1‡\9\1279CÙçG1×\15Ær–£Ìî¾9®En(eåÜÑõ¹Sƒ\4B‚„Lý¬8\15X¨3Œ/g/èu§#à\27˜ÃŠƒ\28›P¡eîâù\18Å²ÞçîR”g/MMÁú\"\6ú>Cßçú‰\\\8Lú\21úg¨:²÷\28rÿ\28¶z\30)Ñ\14\15wl”Ç*€ÐIg­2ç!L¹çå1\15Íö4\31s6Ç¹\30yá\28jÀ<Ä4R™#SMºf²ÑLªˆ·2s=\31\17N£ËÔÎÅœâ”v®5j˜\19ì\16XÑØ9\30J\1Ùl$õ$ø\6E˜µ\3›5\26(g%ç\25Ù˜X˜5`é ,q‘'\"ç²«{Ïˆ¼s)›!s\16S<ÌÄŠ4@iR:´›ðîÌ\31\0079óÚ¬B%jÜv¼ÖÐ€\18\29!‡×KúYÂÇ¬ÇÅú\28G1 ’î±Ÿ\24›4h.ÝNóvÉŠóÖü~¯\22\4a\15š\1-@˜š¯§/Í\12Ç&ü\26‹#¹fª\25â\4Ø˜Â#\8Þ¬²îxÒÉÛü¦ÔwÐ>T7²Ý@\23Ïü&-`t¨2Ï>£\0@Èq£\20\1ÆÊäßI·\15ˆ<\"Dš3l3,Î\6ô1@lÃû\20¨÷hÈG\12/½Ùå­/Êý¡IL\13Óó!x\20ü4®L0¬ä\3@£Qv\13˜\9V•(R\24à\16;¡\8!\
ÉÃ\0\0ë+µPÉ\"5-Ûè9\25\0276™ “hØùjv\4:áh\4DR÷Nt(Žeò²2!™¥\18\17'iâ\26°\0118\20)¬®Òç{t!³G\23i®:\30ªñIe0i!ið0á\14û÷@›‰¼ÊKaÒéÊ6EØçEŠÅ\20×»\0’l\9¸U¨x ¸V&Rc•\27+³Jì±ÔI^šÔÁãuÓ‰¤}WxØ¢©ÓÀ2ikÅ¶×$È<\
\22¸“y²§Á©\11#»tYl“`Óî9iÔIgºÛáÈKBÒíI²gËªlÀCÌ]\127+<\19ÎBç>ÐãBÛ…,Í\27×9\16ý/{Bú\
)(yï\9¬i\20ÁÌtï\17+‘ö»\15SI2É1I¤¾‡°\0081Ñ6\7Í1$Ça\14¯/5“wJÈ2\9²–¼¨I°ê44\29“:x³‡Û\27èÄv\11c§Û… \21\17¼’Bg­îÏÏ“¢ä\21¬·Äi¸ä³4øZ\0tÊÂ\0039B·\23Õ¿\28ˆê\5÷N/¥Óuî‘\\&qÇ¼cH>íb¨ª\17šž¼]H*ÞžÙû8g0,G WíImÕ\8hM\
åÓøC àŸ<ELža$hhò1fbyàŠåšì[Š›è›\7bI‰0-nLÜÊ€Iª™®—‹x”\5“²`Z<NLñf1\5í¤\6·‘„Î¹ÝJ»²)ª‹ì‘¨3†J}µjS\21üô8£’C{¹©3‰à\16æZ>M¸FBèpŠûÓt­Ëê:\127\14Ì\8HÎ¦ð!h¥ëÔÙ@gFz:Xõîs\21Ñ\25[Œh\7Zñ;ÅÕ¨P}•ÎX\127Ü¿¢çfoÏ’CLÑž1CPÂ€Í1¥†¯\11‘¶ñz¾½\"§áòÏáíÖHäR½\30ž¤‹¼§ËŒÉ[ˆeÕ¯#\7ruïj8IÓ\18ÝMŒÖ\30â\22)Ø‚”©¾¼ÚAƒL\7½Ž³*\29®h˜\3?¯]“]¯”\26qzS›n,ë·ô55ÿ’Ubïkã€Ÿdö\22Y¸\27ò\3£Å³ž\127\127P«Dñ¶))Œ%u\3jÐ´ÜÚ\2…ƒ5³”ÐÞ¥¾¿\
\0#²Üßu¡\22\2ëZ®GŒË§w\21\11jïò@ä\1\0145,„\5IòËVu‘\26\18±E´r¼n\8Èòˆ7.Ä³Ÿ–\0275?Ÿ\
­Ký4\23Bß¢Ý‹/z‰î\9ï¡ÊK_ÑkÜ´ªéÑÔ„o‚“¬\\äÞõÀn\8ÈD,\26\8\20qz\0231Q±,¤…=¾@}Ü=\4©Ë,¾?\0j ³ølpQa\\âên™\26”ÿe¢a°^÷Ú2i¯ºL\
£Ë¤†¶\\¯\12\23•ÃAÄ^\15\127u!O\1—É«ÑEMsA:´’8x_|fø×\8ÊAtë\3f\3ÞVî</aMºøz^\\!S’jv—/³–rì{6ÜM\26P\3\12Ð\\ØãGÄ†j™7—\5^V\"iw*÷!â‚ØL{ã]á’4{¡Øä\24Ñ/#F\0068m‘t\27l\127ò\"jQˆcÿ.±Íë†26,ó\23×<†.’2:—¢ÝŠœ\11z,`Fª_ä\15‹ªé¢jº °ùªsbSöŠÀvyr@×w^K(­K\24†.ÍÿÑaû[¹¡q…`µ”Š\
·xtâ­‹¯G–:w_†õ-K\28ˆ¦@œ=\15ûQÚà%æ’‡0=Z²Å)ïˆÝ…±Œ\\Ú9Z˜›5roÎ€æa\0161\2\25ñ%{ˆ\24Žº\11-æ´\11ù­ë*ÉÂQÐ¼3Y¶ÑÑgÖ#\8„\127.h‰–¸©’\8¡þËE*—ÿÿ\\Ï¥¯É\18\22GKÜÏ¥\11[8©‘Ë\23t[ß\29ÕË>|\4ì\2’P\11Í%¬!\23Mz\9Ù5`ÅãvÝë°Ö\\vÍ5\23-0I\27‰N”\9CÞ†8xqÙ¸\28††¹åâ\18>Âry‘‡.Õá7\25\22µÛålkë†„/Þæ-gl›36á\25—^Kè¶Kõ\15Î?M±¼K<QÂì¢uéQGê\127\22kË”£\4\12UÀM'­«zÃMQ¤T–\\ãMkØ\1a]Ã\\nUˆ\\ãì”\16†Ú÷ùp»µ•r‘’ôk[Á8WeË\21ÕpUL\\ã#\6ƒ8æ·^Uý\0000ªAß\\4k‡V]\1\19\17\26Mƒ²R6a¾\27\23m\17F××.&‚œˆi«\23kÕãú*Ö¡f·Ý\\\13«’Mµ\"Ùøù€% \2_ |å‹È—Â=™Ç’\0Ê­§ö³\8mè#<ì1u¢œDÝI\14\15\15Ã'•h¨Àò†¥\19û2€µˆsqÄPêõfF¶Ï\13öÞ¬KKøâ¨,Ì…\15’=Ä!{½J-\1ïÊÈìH \29«€I4ˆ>ñ„ê_ÂçÖK…[×&&\1ß\31ª8¬\18\7üÒ%ˆ\2E®HK’‡6 ë˜LÞ\31‰Ž\8{\7ÔväÂû…¿/ôcJšŒÇ6SKm¡YgŽB×ÕwöÂ(,_™]\12%´hõe2~Öäêƒ r%#ô€Fßü C!`Ã®9l­Ãë#¦5,ã„£É\7—\2‚\5m¹¾›±6¬‹\8$m^ªHë›ŸUû8‚[\17zX¹RMX“W+YÒ„…|—µú\26·$+:ˆ\27Åµ\2Ya…Æ-Éz©‰~¿O‹Q\12]oÎº«úF\31¡¹T\127LåÔ8UÇuåµ\30±¦\15Äáõ¿’‹Øß¿ž¬B•¿™›ßï&V²\7¶\4ý¯ø¿\3qäÿŽ®¸ù¶3£;æöS£+Å2´ t;rçÖó\20´,D\3Hx|Ñ ‡™Rn5N)%ò\25b¶\20¹öÀ¿ˆ—WWþ\20º“þ*Rz`If\8uåSN2äHÇž×Ý…»\15÷\24î9Ü)à\22!{‘+`kõR2b6Ü^\29ä‹:äëÒ ^GDuŽ\29•ënÞHê*«Ù‹‚ŒÄ\4+‚^åG¨ÉÙë‚\28O\5s¼ »Ðn\24D;‡qT\14Q)«\9¢3zÙ“£·]{­«îºÙÜ€E¿çS¹k\24EÂŸ»°ïÍÔ³÷sç›ºü\31Ý\"\
zE\30¶Lî4á&ÙL©ñjHKå!à\24p2¥ü\27´˜2\127\4LÂÍº7-S©Âs¬*žæÄ]#ý¹Ž±ô½mœü‚\"O-D³´.Cëòÿ¿ÇÎÈ}¹×Æ=«\23Ju2Ã\29æM¡,>‘m¸ë|š~py\\–b\17v\8{ª\29FŸÇ‚v†vðÜ™Ähµ\2o5Üpv5_—áF^p\11h\9ÒZö£Nèg\7*ãp™â\20ç³&)ŒØuOžÎ—þêÅ€xb™ã}SÉ\2Ëa\4A‚±Óƒ¶^dµÈ\0287å„”\22Hê\16+“æ\17ýÞ4®õ‘}›ý‚†\1‡\1¨\0079\0307e/Úl741Ç\21Y \22àô(\5Ö4yÄE\18—ø|í€\25Ò“çrkhõìÆ&šZS;Õ@¥¨ŒøWd5KœÊòÂÝHÀÂÒËJÛ4oñ¾¥ÌR{€¶ž\25Q\19r\8bY+’´G 80°>ÍÏÆôf™9¢\28¯êrh­YF!\28\\ì‹ûqQ=\13$Ô~0/JY´˜Q€WÅÖ\\µFÍ\16ñœ\21/r†GgÖøÐ\15\14ä‚\28ƒ2C†»Ö\6PH÷òVd\21Þ\28\31i(³û`‹\13\2úÃ0D\19B\13&d\28ˆð\26„ÁVÍC\2ó‰[9¾·ã˜—›3u]\\çP™í7Œ¾\11è´nq\11“ãNDãu7¿¯'¿­iµ\8\7\9h´j´B¦$0N\3}Úëb\
S®ÇåeÏ† jƒâtÒGJH„Ycã\"ÿwç&>LpZÔÙöVr^Õ¾\29VÚQúÀB¨éNÞ½Èô)}r`¼&Ï\18\17\9dˆˆYá._›â¸ß\27ª?ª;5\30a\24™q»\5dò3§ë\127ö}\14Rg*\3²¿\25}D|h0§½Á—ë‚BÉ£Ü\11t©P*²#a±¹à>ùôýF>YÎ±'ª\127Šü~øZ0¿\27\6Á/fi’€cÒ\23·\28`MŒóõQ zñ©=C}½¢\21Í\6þ—ô;©¨ÖÁ~ó\127÷\28z®È0®\4ŸÖèG¦ºéÂ9P0$/Ç3‚«\9\127ÆÈ÷\19\27ÊçT\18_·qŽ{rQ\29mú‰SM_‚œ¹¸¡.V›ç®[Ø_\1ábÀW\20 ûÅíç*6¦nÓ\8kóË<\16É-Ž^·ëª|+Û\25·¶á[;³C«ð-f\15ÊhçzKêo\21!Å\19oô\9¥­[0SÜ²·MÖ¹5Àh\19;Ö Ýbò)Ü ¶›·ê[\27\7P\27Ô€r1\26f’{±•ðÈÍ¯\18Ü6Ïlu“¬\6Ý#\8&P¾Ð\30hˆ\4cÀ9 ûüz\7dulŸCµ\18Q=Hß\21›&â´£+í_\21¼qëzºé“VÆ\3Þ8™LÝ~»¾RæS\3³xäºusi\0\\ck\16Ý½µÚduåæ»1ºÃÀ×ˆ-ŒÎ\22öYT\13++·¯BÙ¬ý§Ø¾\6ˆÍÖØº\27jÏ¦!\14‘»\0131?\15€·!ž­0]ƒ­\28\12\25¥,¤õz\17xv¹\
,ûÚnq=/¢\17\26vùº²Òå0\5s\3Z¹\22¸»å¤hzXÖ’p!›\11ró\11C·­tYy!¿…=%e¼’€\0045¼­Ù^‡#¯Ý¡wÅSÔ&¿ƒ>ZlX\
BSÛ\7\3+ríHuÎ$ØrFhqSDM\31\17³\22žŸ¯\31\23ê¬9Œÿ„>ÀÞ|\9i^Eîm¼V™Öz–t•\26!\
f[Øà…@Ü…ou9Œ_\20†–æ}öÓ24ìÚâ<WÏ)ôe\14ñ/\23áÈ\
ÑÄ`-¶‹_\19”Ü\6ãb“A½AK¿õö`‰îh4f\20{N”É\12ô£K·¸:\15;§\20mTìÛÂ6+|èd$ÉÑ>¿\14à\3I\22A£/]kdGØ\8ß\25>è<\21å#\18\30÷ˆ:¢/\0187*\14mcÔqLÑ—ÃE;žæÓª›\1|ë~»‡Ãîç\22\23ú\4I9½4ýË¼Ô[|²+lË5Ø\0223\9å6¹à5ññhØq\15»\28Wf…ïª«\12U\22ß\28ÉMƒ\27f.\20Q˜ãél©‰n(v\26ßmjvª2ŽØ$•š.\14»y_DYÇgÀ§I‘Šu+šû½;Ò\30ÞÈãñ¶»¡d\27.ú\30‹x\17;_(ÅtNÞÝÕqÑ—-ßS3\27ï9j¹‘\20¢i\127vn\14ªJØ$”\14øøö\17ÐŒÞœ¶¦{Qõ|8ƒó›a˜á<\23ªÆ\0119³\6àT[ÜÐéS¸ÛÊ„þ„\"ç¤Ö©µÇ^³*3 \20èÙ\28žÔ¹f“Ò1p\
èr\3:ìa\5¹%ÇÅ\3dš“®yŒ\19dÃ¾#ÿï\15=ñÀ¸¿|9|Ú\9lŽ%šs\3|#—â”Ã(ý\1´7(=½\"xžMÌ¢\\´ä\7©\31ƒ<Ë#\"8ˆ2ßæG7.O\31\17ÎÅâ¶_lv¹–”¶¶Iªë!Á\24ÞØõ«+¨Ze1¸%×7ÍIˆè\28ËzíÆ\11M\0176y«ºi^'´ç\23‡yUb\18eÓ17Íd¼Æ€Ï\7Ú­a\26j›à‘C³­×’\\ãxi[c\30Bõ¯Å±5WE$ªBJ6ì\29A1ðk|¤ƒ@\0075îž‰ò¼\"P´Ì\4ú$¨ÞÖlÁ7`ñÅ\6\31³\13›¬\0\31r«Ú—ÎÊ'\4›ïÜ67]ÿ\17X\6\30ËØ\20\8­›öá8µ7Ü4‹ÙâBe+m­šÛ¶·n\23?åñÅƒ¸xqkÐÔGßp„< \30\"b¾²0íñÚ`\15_\30¯Ð¬é¨á\30H‹¦ð±ƒ÷JÖß¨G{\\-Mß;\27Ž\27Œ\4”\"ÐÝæÅ‘Sµw!n€ºˆc#8ÓûEç÷°¤Žð-š£¼\25h\8:¤ãˆt9]éÂÎ\0151.º\20\27h\31b‰kDêíÅ\24«f]\5ŒÊã¹\
hû´ð˜ëmÐì¯(\\®ø\31v\19ïîŠ}‰´‹\11\0188\6b'ïh<uwD\
\23(ÈÂîAˆ©®3†\8\8’¶«ù\7z9ˆ9$¤¸³Š\27´èo\30Ü ¢î\
e#¨\
h\27\30×lŒèŽˆ¸áVç\16Ì@L¤oIÞŸQÄ{\12ôû7º\28’t`(G\29øñŸ_kãp\\÷¨´Ï\21§–@âÓrÕœošo\17ù^uja$Œü–\127\11e;ì¹.\"\19+æ¨\31èévT2ÉÃ\26\14×È!¸\29é\17›û`n·&>ï¶\29J\21ÇÊÚ?<¿Ãí|{/¾\5‹\16JóO‰Í\25\27§\2)\23T>A1P\17óT\0088Û\28ÒÎyÉ¹gP¡³\13wLÊé·~€ÁM\16ÓhÆyQ\6ï2ã›\27R)Ç@S4É\\sú\8²Æ{Kñ5’^qÎÑ\0269B ë‰éx;\0070k~r’JŽM\0Éâiáö¾Œå¶÷^\2šý‹ñ\11òã küæL3Ò¬ŽíúªØM™v«Ã¶^S–¾\15ŸdSÞHÎ`KW\27€®² Pqe¿©äí§gœÑa´ˆÚÂúkSÇÙ®G%È¥×3QrW\18š½½iº_GAn„Þƒî.~b¼µÙåº{«){q)¦=ÞËän\15«’ El|±º\28ø474B8\8“eÔÁJ÷ëð°ÜQrž­ÉÑxPuý<5\21hBl¢\28BÕ\1ÔW!°(€w¸R6+†¾SxO!\27Šdp=úæý/\4¯´^ªÐ­ÕÅîC,`¤Gúj,A™9pºðBj\31;áùCbo öÏb\15»–=ìZhý\3á`/évç\1åÞU$câÙ˜\16Rüe\15ÿ Ø¯sƒ\6\19zÀEô\11÷«4“Æ\4¤Ö“éÀ\14 G øâ \2ì{bàbúù(ü\16o\31u¥m\8Ÿ]½¾‚½ûŒ\5ÑÁ\21ø\17p \12_ÕÑ;\7Lm -bv3+Àî>I\20\26\18§\29{w}Â%p¤¸|\14¥†ýÐí=t°]\3\23\6EË8\22ü^‡êè¡äîÙa#q\7|F€“6î¾H¥œA“\27<H\15û\16¶\28ñe”É´ý—1ý\18A9BhÝ !\17îq³(\31îå\16Õ \16Åëo…Qñy!†Fs\23'.\20¶=4³ÝùØãsh¤Bh¢’ÅiYÁ)\22Õp¶&<=YÃ386ñE\29…­Þ_`A/ßãÙÅ„\2!Ž‰’£ã§\6öXæ\26ì\13òåžüt\6»éa‡–Qçô\17\16éwËe 3U.P\2ø\19¤p¿d7}ƒêªß\29ž\11ÌkW–Û/¥Ç\24D‹}ñ(q÷«jxêå´\9”ãË•Rû\15OxÜò@§\8ßô\17SûŸ×­\2Z\"Ñ´]‘{ø\18> /LŠ:¾\31ªm\7k)>`t•\19ä\"³1„)`ìð8Í–ú¼«ôˆÜÓü»k-+\
ÈEYl²K\22Ä~\11Q\"ÌBúH¿¸/³r±ß!í‹¸‹u\18˜¢Îe\29\28ª¼x\"\2Ú“Iy\13´ZŸÇ_{¾ÞìÝ.Þ+\28#ß»g\13Ö\23\15Ž\15éH,‚ó\6Ô¾OÇóBÑAõœý¿/ÄùážïtåÔJ_ÞüŠ\1ÿýÙÃû?úÁ\0086¾[ Ð-¾L%ën\3±ÒêMŠ²ù)Â=NFw¥Ï=\12Þ&ÓŒRµ=\14J÷xÏ³_'¢‰üXÜ\30úÖhl‰Ð0˜\127T‹]K9ëõpxWFÝ]9ûE\0.^¶_Ç›OS!kí×7\21öë˜Ó·8±„”W\2\29Ùz÷w6î0ùñ0\4±ÃvVJ¸{­\28\
t×C_ \28zf=e\18nWÈ\31¡G \"æi¯\28>ïÐ÷Ë¾(Pú\15ïº€\12\6Ãü\22:Š»\31\12Û¯\23™»Ÿ’ÙãåÐî×f\8ÖFˆà· †(¾³[ïa*Tî~b·ò«µd>â|Ò[ùˆqõ\28MðG­†öê@Ø\18:Äñ1<’zjj°wñõ\14çÙ+/c\20ÉbEŸ*¯xÌy*)„ÕR\
\31ëgW\"‰Ý­(B/ßŸÛÜß¾ûÛß©·uHtû»Z]eˆ#åþ/a\22\5\8®é•l|ªI\17ao®Õ*‰\18f)\21ò£t\11)‚ñD\23õ¬sOïíÊ\18F¬nÑË”\\äe¤ÁŠcÍÎb>nmq”÷â¸7Pþ#> [ÄWö?‹Ãs\31ÁGæ“ØòQ\28a\11zXÕáeâñˆ#™Ãw<F\30‚7Å\18_\"Î\29OÏúD²u\179ü¼Ìá‡e\14¿\26\3„¶\2Ø\1‡_‘¡ü8?‡ôº\9¼%;ª\23…Ž\29­mØ;‡ìøðÌ\9X‘Ô‹ cÔâéð^ëð}œ!×cêcôK7G<:£¨ñ0æ$—ù'-Lé¡å²ž# «àˆÏ¢wÙCë¤ãúèè1iÂrx;x„ù‘,óÕåøøÀ1+e\30~‚à¨â¤¢\9Ñ\27a=°’áå¢))¾\7q¤\24X¿rþ\23ä·yž…æÐ¤fèý\8Á.ŠD~{¥@I\29L\"Ÿ\21&sFß\"‡bû\17¦{¶Z3ûãFÓ4+ò%]¶[,”CÓðCS\7Ê×j\0^ÊvAì»zÂ´0\8\15cÖˆì'¡6eõ#\31Ç\26¦âÇÚ 5\28¹q­\0íœûüÐ€èÐ>èˆ»¥#î–â»QÎuŽ«vZ\8\0258ÊÍÌÐ×d£âÄû¾\30›\31•%úf´vf~²eº\16íh|esÄqœÙ£‰~\21àð)\13.6‚yìú\20µ(\31¢®hÅõ‚ÿ¸Þs\28ÿ5É[™#ÞÂ\8¿-Í©Ž¯kÝ¤#G<‹9vm¢\15Š+i‰šðq}èíð»1\16™1ŽÝ3?\24å!a<*¯p}qyz—á\13Nw!bmÍj\29\8}å±o\8dG|›™ÒÂ†Ž@º\2MdwÄ·¸ h\8¶Tÿ6¥f\16Gc^âŽøVÀá·ÜŽ0+94>;láé\31*,Å-4ºòŒ?% Ð\23`g\27W–\"\15ÅOU\6 ’îyÙŸƒVâã\16Ë?hÑ\
B5êP\
Î6>\5!\26\"q¶Lõ\28µÃ&ƒ´ü:ã\19ëfÜaû$;\4QÕ9P”’ý©¡À©8\127S\31°£g\7{=;ß»Õ§Â8šå6V\
‘ñ¨\19nGlz\3\21·MD[»ìÑ\29È¼\12JñÉÑéí¼á*^ÀŽ]û`P|çüôýàyC_>¿Š³fT†š6ÄÃ’óú›\28f\27°\
†F†\17ß2À\1½:\7¿3…>›\20î.L\29C|Àëôt\29·Õ\13[ó\21\16\18v\0141®C|–ž\18\24Ýsˆ¯Ú0‘‹ã¡¬zj }\"«žñï.1XÉq‚âž‹ÇD§¯àÎ¸C>=H<¥•¤ržJgLã‘êŒgÐ§¦=åIoü¼Ðé¹w–å‘»ög@ON\13ZŒÝ\13µ'~™–%¥±8’Ùy}šé¼lgÎ\27Éà\0157rÈ¡ëSóeXîn\28+÷|\23êøÎ¡º¶\7\8êú¦\12•\31h³ªøc\0/ŸÀõTÄóÜúÊñí\11QY0\\êŒ\1M–ð_\22ïëŽˆ\28‡8¿\6þ1…¬óŒ«ÆSR}û§-þéÊâŸò«øçkÀ1 Bþã¿\1ý¹\21\127ü{ŠºøÓÍñÅÎ?šÕýa\"þx\4úG\15JGñ'lWËwñ†Ó¾ë»¬è}¯\1pÓ·Ÿ¢R6H:—â-å\127+¥¾åAï`Aoxé[Žù–c\"àš¦\15ƒÌwÿ÷mà\7G|__\7(Þ~\28€\"å\4o¹â[&÷ž´\15~û4ìí‡wÞñu\29ã\22ãXTï¹|NÀú¹à‰~¿ƒÏ¼ã3üïø\0Ý;ndß\26¦¾\27Ô§·läÝ¬\20\18Faïø°áû\22NM\127ßÙG£o©þ[\19\0 ÖÈÀÝÜ^.“\31\2O||zó\29ëü\29ïÎÞq®ø\1Ž7\9ïø‚w<½\18:(Ðw|\0ó½[ŸF\127{TûŽ\15£¿›\127øù†ê_øØ¿]ño'Y½ý;ð[Š\127—ø\24BýïZüËZªþ=Š\127ë\127a\3¿\127™/-¶^Àøì\22!à)èÛ€\6Ä—}$xA{\24x\23i§M)ƒ©™!\26\18Ÿ„\0]'‚†37·8aÊøâ\11\
ø*KqE¯bhS\23¡Qj\8\27 \0250KtÁþG˜Èu\3rŽ\2V¿˜Ú‚äð¿\127ã«ÏOY]þïÏÃøì—º\3—ÛåUX$Uî¢ïÙ>4\26Úip½µ\22œ›0 Ãá\9¹þ(Ñ»DQeOÔQ\12ò\0319Ä–éÓ0`\21eVA0âSýŽuYê£¼o§à\27é´ô\0085¬\15\12eãø\29\5(-(úûýpÍX\5À\0061Aƒõ]éŽùúŽùúö\19†\"È¥\127ˆ”#(GL\21\25­ï\6ÂZ«„‘m4ÀÍ$4½S\22Ÿ‡ÅÅ×aÐø¼Þm¼åŒ€ÉV!\31FòÉw³\6ûu\30¿\14ÀR©}\26:yb¢#’¥Ç-Zœ|;ê}Û\16]ôUKá×þluÚ¢ÙÁh/‹‹îò:0é¿ú4\9ýýÖŽÓ|«Aë•!\30ˆAúÊ{t8÷IÂÆ›^9\29ßÙÿ52L3\17±§\\×§oöÈêµX„;×ß¹AŽ\11cFKª”UÂ—/\20YUåÌá“Îð.—÷jJ4=«\31<Â¿›5Ç³XORµ Y\29nm½EÚz\7Z#n¸«ã—°&–æJÚiÒnmþU\22h÷ãÀâkÜü—\19KÙ¯ìñ}¥@±øÎX}\
L”rÆ¢@;üýqUþ¸\8\127B\25\
4]\8A÷÷ÇÅØ„ß‘û‰Ï\29€ÊËã\18û‰Uû\19äò\12‰\21úÓ7Q`ãC³\27ÞGÄt\17$yøéÑ¼.‚Ÿ\30Í\27˜Xá¦]ôø-ë@\22sÓ­¥ÝïÏ+VÈ\22\1³1.éŸXÒ?c4,Þw\16áÊþ™üäB hàT®¶ ¨Î\4GäG\5(0E×Ã\4Nc\29¥0°ªÞ\24×ŸX?qÅ¨ÇªµF¶L¿\15Hã×5EŠH\29\6«—Ã–±f£7Ùuù“Ã€óú;¿èž’¥‰:ÏÃ¿\27Ý„õ¤é…±´\127â\11ÀaD™®(O\20M;ä\11Ùéìç—¢\2¿ò`ð\24Mýo#k¹¢—ÈT®M\12Y\14\9)¾P\27Ñõv\13W<vð,¿‰Ì·#Òœ‘·zGÐ•.´xFr‹\21\16´ógÓf\11TÆ\0\\KþçZòš=ÙÜ`ˆ¿?ñ”J\28ûüGêùsvuÀ|ƒd‹mHyZây­Éx*\15Š-õ¿ªû\127F4™Â",
  ["length"]=29397,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=4693,
 },
 ["version"]="1.001",
}