return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["characters"]="abcdeghijklnoprstuvwxy",
  ["compression"]="zlib",
  ["data"]="xÚMŒÑ\13Ã \12DWñ\2\30ŠĞSì\6\5„¡-Û\23B\20ñsïÙ:ÛWÎ\
ò\23Œv(›¸›c\17«c/xÄH4qj\19ãFâÆ[›\24ó\27HWt5`¦Ñ\17\0>ñ{Ä(¸Ì» pÑÅ#\5Åë\
d:£±\11\\r\127‘#·áºx£ÏÒøŠ\26\31ífïı\1}\26Pò",
  ["length"]=225,
  ["n"]=26,
 },
 ["metadata"]={
  ["mnemonic"]="ca",
  ["source"]="hyph-ca",
  ["texcomment"]="% Catalan hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: cahyph.tex (2003-09-08)\
% Author: GonÃ§al Badenes <g.badenes at ieee.org>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
% Hyphenation patterns for Catalan.\
% This is version 1.11\
% Compiled by GonÃ§al Badenes and Francina Turon,\
%       December 1991-January 1995.\
%\
% Copyright (C) 1991-2003 GonÃ§al Badenes\
%\
% -----------------------------------------------------------------\
% IMPORTANT NOTICE:\
%\
% This program can be redistributed and/or modified under the terms\
% of the LaTeX Project Public License Distributed from CTAN\
% archives in directory macros/latex/base/lppl.txt; either\
% version 1 of the License, or any later version.\
% -----------------------------------------------------------------\
%\
%%% ====================================================================\
%%%  @TeX-hyphen-file{\
%%%     author          = \"GonÃ§al Badenes\",\
%%%     version         = \"1.11\",\
%%%     date            = \"15 July 2003\",\
%%%     time            = \"15:08:12 CET\",\
%%%     filename        = \"cahyph.tex\",\
%%%     email           = \"g.badenes@ieee.org\",\
%%%     codetable       = \"UTF-8\",\
%%%     keywords        = \"TeX, hyphen, catalan\",\
%%%     supported       = \"yes\",\
%%%     abstract        = \"Catalan hyphenation patterns\",\
%%%     docstring       = \"This file contains the hyphenation patterns\
%%%                        for the catalan language\",\
%%%  }\
%%% ====================================================================\
%\
% NOTICE: Version 1.11 is identical to version 1.10 (issued on January 17,\
%         1995) except for the updated copyright notice above.\
%\
% The macros used were created for ghyph31.tex by Bernd Raichle (see the\
% German hyphenation pattern files for further details)\
%\
% This patterns have been created using standard, conservative\
% hyphenation rules for catalan. The results have refined running them\
% through patgen. In that way, the number of hits has been increased.\
%\
% These rules produce no wrong patterns (Results checked against the\
% ``Diccionari Ortogr\\`afic i de Pron\\'uncia'', Enciclop\\`edia\
% Catalana. The percentage of valid hyphen misses is lower than 1%\
%\
% Some of the patterns below represent combinations that never\
% happen in Catalan. We have tried to keep them to a minimum.\
%\
% *** IMPORTANT ***\
% \\lefthyphenmin and \\righthyphenmin should be set to 2 and 2\
% respectively. If you set them below these values incorrect breaks\
% will happen (specially at the beginning of foreign words and words\
% which begin with some prefixes).\
% *** IMPORTANT ***\
%\
% Please report any problem you might have to the authors!!!\
%\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
% \\message{Catalan Hyphenation Patterns `cahyphen' Version 1.11 <2003/07/15>}\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijlmnopqrstuvxyzÃ Ã§Ã¨Ã©Ã­Ã¯Ã²Ã³ÃºÃ¼",
  ["compression"]="zlib",
  ["data"]="xÚ5˜AâJ\19„¯â\19´ÔæDP.\23…ÀUØ.Äã4Ş=¿\5BÂ;Ë»¾ØŸ\17á\127A¦'2¾Š\4ìî™ù=\29«ß“·W´W²W©~iÎ4gš3Í™Ö˜Ö˜Ö˜Ö¤êĞ˜ÖšÖšÖšÖš¯5-˜\22L\11¦\5Ó‚igÓÎ¦M;›v6íbÚÅ´‹i\23Ó.¦]M»šv5íjÚÕ´›i7Ón¦İL»™Ö™ÖùêĞ™Ö™Ö™–Õ!›–£½LË¦İíÕ›·7¾7oozoÚ`Ú`Ú`Ú`Ú`ÚhÚhÚhÚhÚhÚÃ´‡i\15Ó\30¦=L{šö4íiÚÓ´§i/Ó^¦½L{™ö2íô÷\31Ê\27eAYQ&”\25åk\31+,\14\22\7‹ƒÅÁâ`q°üı›P(\5\5F«+ëÄj¶\6'58©¡Á¼Á¸ÁI\13,-,-,-,-,-,-,-,\1–\0K€%À\18`\9°\4Y6ûúà;Ãw†ï\12ß\25¾3|gø.°\\`¹Àrå\2Ë\5–\11,WX®°\\a¹Âr…å\
Ë\21–\27,7Xn°Ü`¹Árƒå\6K\7K\7K\7K\7K\7K\7K\7K†%Ã’aÉ°dX2,\25–;ŞV\15_\15_\15_\15_\15_\15_\15ß\0Ë\0Ë\0Ë\0Ë\0Ë\0Ë\0Ë\8Ë\8Ë\8Ë\8Ë\8Ë\8Ë\8Ë\3–\7,\15X\30°<`yÀò€å\9Ë\19–',OX°<ayÂò‚å\5Ë\11–\23,/X^°¼Ìr¸Ö|¢j>Sµ=UP\18¯q‡rzâô„)jbå´ç´ç´ç´ç\20O#ëÈ:²¬#ëÈ:²¬#ëÈ6œ6œ6œ6œ6œ¶<¹åÉ-OnyrË“[²-Ù–lK¶%\27È\6²l \27È\6²l \27È\6²™l&›Éf²™l&›Éf²™l&;r:r:r:r:rÚÕÿ\28Y=kdM¬…ß\5\31„ZB­‡¡ÖãPë¨õHÔ|(N\2N\2N\2N\2N\2N\2Nÿ\7z\1½€^@/ \23Ğ\11à]î”à”à”à”à”à”à”à”à”à”à”à”à”à”Ğ\8h\0044\2\26\1€F@# ÕJ­VjµR«•Z­Ôj¥V+µJh•Ğ*¡UB«„V\9­\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18‚\18²\18²\18²\18²\18²\18²\18²\18²\18²\18²\18²\18²\18²\18²\18F\1£€QÀ(`\0200\
\24\5Ø-ÈŸŸÖŞj‹Úª6©Íjßêø{´—·Wª¼]{»öv\29í:Úu´ëd×É®“]\23».v]ìúøkQVŞ(\11ÊŠ2¡Ì(8şïƒ²Ù¡fö0{˜=Ì\30f\15³‡ÙÃìa0G˜#Ì\17æ\8s„9Â\28a0'˜\19Ì\9æ\4s‚9Áœ`N0'˜\11Ì\5æ\2s¹À\\`.0\23˜\11Ì\127ÿÙ»µâQ\18ŠMPmôÆèÑ\27£7Go\22Œ\22Œ\22Œ\22\22VŒVŒVŒVV&Œ&Œ&Œ&&fŒfŒfŒff¾\24}1úbôåèËÑ\7£\15F\31Œ>xç¨oÖ…ueXgÖ/j¬ş6Ğ\27è\13ôFz#½‘ŞHo¤7Ò›¾ñX\31Y=kb-V\11õB½Ô‘5±\22ûÖAyR”'åIyR”'åIER‘T$\21IER‘T$\21IER‰T\"•H%R‰T\"•èOd\19©Bª*¤\
©Bª*ô\23²…\20Ş;\31\18koµEmU›Ôfµ/?\14\2E@\17P\4\20\1E@©ùĞ0Á+Á+Á+Á+Á+Á+Á+Á+Á+Á+Á+Á+Á+!*!*!*!*!*!*!*!*!*!*!*!*!*!*!)!)!)!)!)!)!)!)!)!)!)!)!)!)¡(¡(¡(¡(¡(¡(¡(¡(¡(¡(¡(¡(¡(¡(Á~,à\6aójI­ \21ÍŠfE3Ü-l\5?:ˆ¿…¿…¿…¿…¿…¿…¿…¿…/Â\23á‹ğEø\"|\17¾\8_„/ÂWá«ğUø*|\21¾\
_…¯ÂWá“ğIø$|\18>\9Ÿ„OÂ'á“ğYø,|\22>\11Ÿ…ÏÂgá³ğYøWøWøWøWøWøWøWøWøWøGøGøGøG7Œú{ïËŞ×½O{Ÿ÷®Ÿ:³èÌ¢3‹Î,û™e?³ìg–ıÌ²ŸYö3Ë~&×ıhİMënZwÓºÛ¾î¶¯»íënûºÛ¾î¶¯»íënZwÓº›Öİ´î¶¯»íënûºÛ¾î¶¯»íënûº›Öİ¸îÏ\25Û¢zÖÄ\
½P/Ô\1 Ú”ûıp»\31ûÃSAÙ2l‹Úª6©Íj_C'·f[Ô&µYí[\5¬\16°AÀ\2\1ùwhwhwhwh\7\6\23x\\ài‡\5u§çNÏ;=wzîÊûÛe\21Ç¡½Õf6K£á.Ã]†»\12w\26ì—Äpó?øQÎ\30÷ö^ö\14ßx”\15=î=í½ìİ~‡ÜàB¬‰µ°ş\28»1Ú‡Zıœ|İ±\14V#ª;ÖÙª¯¯V¯Çº·–êë•­c5©!Ñğİ7Bö˜ ÷78£éN­QËl~`Ã-ÑdnG¤İWûËî¹Ø8\31q€\14Ìş`ÿLûÉi¨Gk\3½½×Î½¯íì¡Ô'Ô\19\14µ¦í†¢\3ÆşØÙŸCİ¥*×CDñV:_ Ú÷g\2î(w¶Od´âc÷kiÖª¾`'ß·©oªÎnöñõ;8Sªƒ\127æêĞù\22\5ÿ“ÕW‡Á÷ÕÑşhÅv>E\19ªÆ\15‡cPëÕ\30l¾s•?Ø÷jÕş)‹·™X‡\
&—ØZÖÌÚ÷lœÛgWÅpè*|¢Ïª;Ø\27K‡\0307z<øÊ¿eÔÁª}0ö7\25“G³\4{Çÿ\3F\11Ê/",
  ["length"]=5195,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=869,
 },
 ["version"]="1.001",
}