return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="sl",
  ["source"]="hyph-sl",
  ["texcomment"]="% Slovenian hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: slhyph.tex (2007-01-29)\
% Author: MatjaÅ¾ VreÄko <matjaz at mg-soft.si>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
% This is `slhyph.tex' as of 15. 4. 97.\
%\
% Copyright (C) 1990 MatjaÅ¾ VreÄko, TeXCeX (SLO)\
%               [slovenian hyphenation patterns]\
%\
% This program can be redistributed and/or modified under the terms\
% of the LaTeX Project Public License Distributed from CTAN\
% archives in directory macros/latex/base/lppl.txt; either\
% version 1 of the License, or any later version.\
%\
% This file contains slovene hyphen patterns with ÄÅ¡Å¾\
%\
% Generation of hyphen patterns for TeX\
%\
%          MatjaÅ¾ VreÄko, TeXCeH (SLO), 1990\
%   Email: matjaz@mg-soft.si\
%\
% Changes:\
%  1990       First version of `hyphen.si' (MatjaÅ¾ VreÄko, TeXCeX)\
%\
% Some cosmetic changes done later on, but none of these apply any more;\
% the patterns are still the same as they were originally:\
%\
%  1994-05-17 Use of code page 852 in patterns (Leon Å½lajpah)\
%  1995-04-06 Release of `sihyph21.tex'\
%  1995-06-20 Added \\slovenehyphenmins\
%             Release of `sihyph22.tex'\
%  1997-15-04 Some changes concerning \"c, \"s, \"z and ...\
%             Release of `sihyph23.tex'\
%  2007-01-20 `sihyph23.tex' renamed to `slhyph.tex'\
%             (sl is the proper language code for Slovenian)\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnopqrstuvwxyzÄÅ¡Å¾",
  ["compression"]="zlib",
  ["data"]="xÚ%˜]–ã,¯…§Â\8²–\29ìÓÓqb’à\31ğ‡±ë-æĞƒ¨‰ÔUg^çÙä\"[ °\16BH\"—áì’¹Œ¾ß·h.n¾îÂî4\23¿7@\1âÍÛQ¤ó\0252ÂÚ¢\29»PéÙñÉ–\\?ş\31ŒİÙYŒİ[a¶ærÆÒ-\31Â„²øÒ›¡\25øİÌpën´n}Š#Œ»\25îİİÓú÷\23€5¶‹\25ú1Ş cŸ–Ë‡\12•D\4Œİ‘˜ê\26àa†G÷dìÑdºO~/3Ø×j†W·úŠ\17&-ß\6}11<un\22áë©{øŠQø\26*:¡GÆÔ{}>]ã®ÎY¾›‹X‡\20†<5ùı\27Ğ\25#\12vŞ¥\13\27h\16b×BƒñĞR\21òbM\27\24\11UÉĞ\21Y€•b{“’\27Ã\27\27i\18óS?~ÉvÉ\00941iKé`¨ûo¨\24+Âi´üşş1ÃŞ½\127ªMÕ‘ulf¿ÙJÀÁ\"ö Û\0302Ä!MOƒg¼\127¤Ùùş­_„\127wY«\21\22/ÕJ¶x¶\\®:\17P|»øåCò‡œš¦³²å\26¥Dé¢¶\"REÔMn\20ïÜ¤%K¾\127eÛĞßp‘Û\16®ÿşZ¨=\12f¹\11\5æÆéßœ=Íó¾y:ÍÄ'v\26.æÖMn1·ëäÖÚÎúd†±¸\13Æâò ‚ÊÂ\\Q‚Vco,Ïä`n\17‘±¿¿$\"&\22ŒRóvMÃ\13N\26öÚÆ´\16WÌ-9[\31â?$i{ÿ:MÁ\22·Ô¿\127ÇAòw\1ß‚,\127t³¯xT<…é[ƒÒ\
Ù²M{gÿ÷×ÅÜñh„ÜgsoæÁÜç&¶æŞÍ‘¡9Wqv ûrÌb+\0\22ø÷—»'|š\127\127±\23–œj\127Vs1öß_ì“\25ìV·×‘ fÜjûƒ»8\7íQÂF\29ÉXdäHÆ±?ãdÆÖ™~ìÜ‚õGgW\31*©X®^sŸ‚—\25}Ç.ìè\3\31[ß…\8‹\0164\18Hædj„Jš:\9fÓRğàÍX\15n¬\00776KdÂ•ã\27¯a¸\27Å©\1­*İ>Ü\4\9\28šxîÆ—/Õñ¥’éóÁ5Dl=¶‘v¼}dÄÛ(ñ±}˜1v¸\2x2$b‹TÛ—†bF\\6qc»x÷©Ñ] Ã\0309‡1»yï\25$„\28s\20\30«\6¥Ïõ¬\6*­q„K‡•\29>\13ôÄPúw~,í8†Ñ8Îjt\31â?$ŠèNªÇÑib®ü™‘ã‡¤J8J§s=ÕëÏ´#\30¹v|\0247v\\s§`ìd\3°7÷!Isâm\23©÷›)ç‡\20f6L³XÂ\17}\0îá„Y›B,§ïˆÉÎ÷[\17iÙœ/\29s8lÇY»¹_‡E$'qir?\29>é\26®¦‹Õ, ª˜\22¡’ã0ÜÆ±\"BÁÓ¥¡W.‚vE“+=5(%ÓC-/ˆê&µ\14€­í\29—Õu{ş ¿|ÈëC¤\16‡êìû‡\21ß?\29ÉÔqÀÖefØìƒF\21hÌ{º>KS)Æı¦åO\18Š\8òğ\20÷eÜW¯Ëà¾:\29¡ıÊjêÈì7ƒ„\2Wº‘}_‹\29Qµ´OqÈ%À/½Ÿ¢Xû&Ş^y$#ñô¹]ÄYâ*²\14A¬U\11(ZƒÄ:±ªqJ®œÃ®\26\\\12§HÔ<\6ó ü>\\¿LÙ<\30ŠG\15ß—…{úà„\30±?°éƒ xˆÃ\5x0/w§3\15\12Ò>q²§ëıÓA–NAn˜ğ §ï3—şÉ\25?¹_E“³yòÕ«¦—ÜÿåHb4\9\30/Êƒ—U\0x±ò‹€\27ÔÔu{ñaó:Ìëè\31Õx.”çBy.‘·÷Æ¿¿CEWÑ\27Ï•H\31ÖQ;g¢3\26ëÇ¨\22›ö¸´Çƒ­\127¾hèÇwµ´ğ¸®G'ogtôs÷\17¿\24_·ˆ²S\5\"\\ô±+_¯\29¥€GõF\7ßúàÌÕÛ z\3ÎF'ìNMvd…³XYÚD-¹ñ#¶ù¤=°§İ²æŞ»”!ôŒb)Îåwm\24!\30«øÜm’À&ñM\127v“Tú_1”\127hŒŸ ‡ÂÍŠCF¨È¬ÒÇ±vpwnmÒüCì£j€{Lİ0“o&eˆI\25bª\25bÂ\19•\"*Ñ&\3L/35lŞN\30ñ”dlKC³`\17¬\2’Ğ\20«(ÊÅ)VCX\7®²â¤Ì4a‚)\13 Tù»™Ø}_\5Ê\23&v=Éõ&UmÓÑ\18~0íhß¿âc\8 ˜©ô§òß,Õg”bçLÊ¤»šf\14fÆôsœ-ĞÍÌˆıùşqPİ,f`ŠvŞ/†²xÈfŞ\17\5l€Ål4\9\19TˆL@EòÆ¼wYŸÀ¿Îœ­\5\0063×ô@aî7³\12\0281ØŸåbÚE¶]¤àRm» æ‚s.D] ÷[èÔ\24z\8fyV\127¤ı2KËn\22ßïß‹i”YìBxÀÿ–éB{’ä©JfA\16ì\2Œ¹È|ı$Q\26ÔY-:«…³Z°\12éø£Ô&ĞWõ\8\22v·ÔRg©¥\14ŒSPê\4rÕ®Víj­»ZÙÕêê£cå©Á™«—4ğ0ª+ÆŠ[EVX\9\29ÔG\12Ï‚Õ¬5É¯±\127ÿ`ëµR\29ß\4»@Š­(¶ò¤\8j2ÿ[WRc¿&àSµ– \12C­\19 ${°\0319#19mõHèM\0244ŞOÃ¬\17^\25\1Êã¡2e\21q¯‡&îjŸ×\0029‹ëÅR›ûÅ\14ƒL\17dŠ j \
5P…\26¨BPm¸­\9£Ş? Z\7‹_\7<!8\0135Á½Ô,b*ë!ó!x2“ø\21ÊF4O5Uz\4¼£\0138\1p7\11«·\30YP[\
Daª²ÄÔñ\7N>ÔÒ(ØH²±\9ØcA4eè€¡ƒê\31Ë¼Œ\14¹j\14:1N5Q\"è\6N\"|wÿÓ.q‘PlÕ3‰Äñh±_ÄH<PÉ~z¦\18• \0042j\21b\23Èå‰öV˜w7‘\2ÙUô0ï\9&†xX\28»ñ\20\6ÊÈ¡R·Ğã2D•mZ\15©f-­\7?b\127ÔšX*\18û£§X‹„şˆ9¢ÑiÖ\3WèÄÈŒHòÒ\13'í¥\127ê4£]Pb!_1¼ò\11üP¸\6¸ØFÀFñÑÆn46]g\27·ox8^Lvtu\11U\2é6ª„‰ª^\"†ïâN™\11(yG™?6Ò„Ñz\7c½ƒ\17+GN˜R=êíÇ\14Ú\19s+ó²\6î‰\25\26-\9¯X\4–±›Ô|\26=ñYP!OV*m\16+øû‡hÅÒjB›\4§´`Şç‰×nrî÷]k6\18-\15™\13·m6íis²ÚæòuQ;“5·#nÔJÙ\26Æ´_İ\30Íæ»\18%ôº-±˜\8´q\20)úÇB\"¢JÿJ:İAF\0232\
dÏ£¡\16SÊØ\20\15¶ê¦\27†Ú¨š\23ó¿£5¼òêeKƒ3\20““^ú‰ÇqQOfJ<gñ?M,Ë§§;œt‡“¶™j8K8[b¼\17ğ4Ş\8÷W†\16•Oƒ\27ŒÌÑ?*\20İ\"a:D=Ä\28Ü\26œW±öQ,JÇY½R_:jÌD¨±’.yRM8i\"Ö'J\7\26\29×\19¢Ó\19.\21ƒ¦M‚Y°\8V\1_`K^®}İ\\ä‘bµvÂ+SS÷¸\11dµ„Õ’¥öMYA%á_UÔiÒõl'“j•‘¾»¡.ˆõ\
O‹$ŸHø„ŞÅ;\22kvŞoûıbööîÍç¯¥\1\
QW¥&ÈKœÙ\15³³·êŒFÿ\12|¤ç##lgŸ%ƒd­·¤cÖ2œ`\12fÁw\21Ux6û\6\27×AÈö)/víJéùªò|·ÙIJ~¨É7FåÿZ;Ióf\1…ÁNæ†™\6\22&„í‡½E³Ÿ”\15æıÓÊ\5ô\127ÌåCæ\15\9\12¹vW\7¥óĞ}yP\14™å>\25÷É<ø£š£!vâ³†b\0013d§ÿ~²ra®¹\16T]”kJÌµn´ùZ«ªÌÙöÜ£\28ª$^ÊY©*+%R\2dÎì\0ûL\18c|\23d“Ù…Í*8\14bîB‡^]ìk£¥\
ğ@¿CŞ} İ1ö+¤ƒxy Õ\3\30øßA<ØÜ¡\127+\0Îútá·ò\11ü\16¸õXE3R\5”?’$$}N5|pP‡\\íÀd×vF\21\28îÈ2Ğ§\29ÿuN\18‹&RQœ²á©+¨ÇéYÓèYÓèÉ»Ø¥Úñš2šSOååCV\17/ÀŒ\16,G)y²©“M^\25ãôc\127\14¦9½Úıû—p ÉØ\19?§5\11V\1\"jr¬ÿŠ:q¨ëÏvC\25»ñl\19²r·ã­ŠÂXv*\0243“e3O‡“$s¶\4\27¾+\\l\"³†¹Œ´6\13QT|\13æ+¶æ?ôl¾Yç›Æ7\26}cêïæË4¥\29Lé‡à.¦\12İ1ƒW®R\25ô‡\3\28U€\5›]Ë\13×.2\\©±«4T\19\
ı‡)W6_0\3Q$xÃë3fMx!nCü¢ÇÃSA±ş\1Iw\18°Ü•œƒ\13HŞ¼2<ëèO¸®è¿\28!‚)F;$ñ”d0>5›4¨6\7ÊG‡$qÙ\
/&v_\26½\13ŠŞ\6\0Ó•9‹2'Ì)z\28•Ot\21UñRô\127]íüŠxA\21+­˜PônÄÅ\30Uoıß\5\22\6N¬`OÂA¹\1­¬şğ\18Îš\"#V¿ãEq«x¯X¯ş¯Œ\0r¶ï_2àåßß?æòş\17üş1\127t\15ÿ¨>ıCŒø\127é˜ím",
  ["length"]=6052,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=1068,
 },
 ["version"]="1.001",
}