return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["characters"]="abdeikmnoprstyÃ³Å¥",
  ["compression"]="zlib",
  ["data"]="xÚKÉ/>ºT!7U·äğfİ”D8«R!/U7%_·¸$±D7;Q77S¡8µ@·$5W7©(\17\0Y$\20Ô",
  ["length"]=54,
  ["n"]=5,
 },
 ["metadata"]={
  ["mnemonic"]="sk",
  ["source"]="hyph-sk",
  ["texcomment"]="% Slovak hyphenation patterns (Jana Chlebikova, 1992)\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: skhyphen.tex (yyyy-mm-dd), skhyphen.ex (yy-mm-dd)\
% Author: Jana ChlebÃ­kovÃ¡ <chlebikj at dcs.fmph.uniba.sk>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
% Slovak hyphenation (version 2.0) 24.4.1992\
% Autor: Jana ChlebÃ­kovÃ¡, department of Informatics Education,\
%         Comenius University, 842 15 Bratislava, Slovakia\
%         <chlebikj@dcs.fmph.uniba.sk>\
%\
% This is free software; you can redistribute it and/or modify\
% it under the terms of the GNU General Public License as published by\
% the Free Software Foundation; either version 2 of the License, or\
% (at your option) any later version.\
%\
% This file is distributed in the hope that it will be useful,\
% but WITHOUT ANY WARRANTY; without even the implied warranty of\
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\
% GNU General Public License for more details.\
%\
% You should have received a copy of the GNU General Public License\
% along with this program; if not, write to the Free Software\
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA\
%%% --------------------------------------------------------------------\
% \\message {Loading SK hyphenation patterns: Jana Chlebikova, 1992}\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnoprstuvwxyzÃ¡Ã¤Ã©Ã­Ã³Ã´ÃºÃ½ÄÄÄ¾ÅˆÅ•Å¡Å¥Å¾",
  ["compression"]="zlib",
  ["data"]="xÚe›M’ã8’…¯¢\19¤Y(¨è¹\14ER\"\5\18¤\1\16;ƒ'¨MZ¬ê\0002\27-r‘«ªUš•6\
İkü=wPÑ=‹„?€øùàø%CY¾lî\23ù÷¿/›FÌÏ—M'æ×Ëf\20ó—üûûes\22óûeó.æ\31y¾-åßı\"A#ÿÎ›QşUÛvSo\23ù÷¸m¶û—=‚\
Áç\15„5å\7Â\3‚#‚–™¶4'\4\14AÏ¬¬e@à\17<ş@8!\8\8\"\19/\8\19å\21áŒàß\8¾#Xø„5\6Ñ\
x\21ğ*âUÀ«ˆW\1¯\2^¥d\21È*U «HV¬\2YE²\
d\21È*U$«@V‘¬\2Y\5²\
d\21Èª\23E!YedŸ?€&aÅ\16pbj|Ğ\28\24\30\25¶šw«öÄĞ1ìµˆV90ô\12+fb\24\24F}p¡I\26¹ÒÌ\12ÿÍğ;ÃE\31k½D§EB\13ô\26ä5Ákp×Ä®A]\3º\6s­È5ˆk\0×à­‰[ƒ¶\6lMÖ\26¨5Hk€Öä¬Y“²\6d­(uöâ\7½øA/~¨\23?èÅ\15õâ\7½øA/~Ğ‹\31æÅ\15zñƒ^ü \23?€õ­ŒE*Âø**\0134ÛóK\18\12\3CÏşı \127?èß\15ú÷CıûAÿ~¨\127?èß\15úôãÅÀÕ§\31Ö“\3:r@?\14ìÆ\1½8°\19\7ôá€.\28Ğƒƒvà\0ş\3ğ\15 ?Ğ§\7\16\30\0x ß\1x\7Ğ\29\0w Û\1h\7’\29\0v\0×áE)Hu0¨# €:\18ê\8¨#¡€:\2ê\8¨£B\29\1u\4Ô\17PGB\29\1u\4Ô‘PG@\29\1u\4Ô‘PG@\29\9u\4Ô\17PÇ\23¥ ÔÑ Z@µ€j\9Õ\2ª%T\11¨\22P- Z…j\1Õ\2ª\5TK¨\22P- ZBµ€j\1Õ\2ª%T\11¨–P- Z@µ/JA¨6o4ŠU)Xeh•ÂU†W)`¥ˆ•BV\25³RĞJQ+…­\12·RàJ‘+ƒ®\20»RğJÑ+ƒ¯\20¿²\14TÚ\5˜\127[ªÕ«ûÒÚ•\19:rB7NìÄ\9]8±\3'àŸ\0\127\2úIÁOÀ>\1ú\4ä\19OÀ=\1öDÔ\19@OÀ<\1òDÄ\19\0OÄ;\1î\4´\0196 \19<}zQ\30\2\12Ï\1Ï\1Ï\17Ï\1Ï\17Ï\1Ï\1Ï\1Ï)\3\3\3#\3\3#\3\3\3#\3#\3\3\3\3{Q\30â9Ãë×\3¯'^\15¼x=ğzàõÀë\21¯\7^\15¼\30x=ñzàõÀë‰×\3¯\7^\15¼x=ğzâõÀë\1Õ¿(\5¡ú¼MŞ¸MŞ¸MŞt›¼q›¼é6yã6yã6yã6y³mòÆmòÆmòÆmò¦‡Í›á›áM7Ã\0277Ã\0277Ã\0277Ã›n†7n†7İ\12oÜ\12oÜ\12o/†§›áÍx\7à\14 \29\8;€u ê\0Ò\1 \0038\7Å\28@9\0r\0ã@Ä\1„\3\0\7ò\13À\27@7\0n Û\0´d\3À\6p\13/JAªÁ < < <¡< <¡< < < ¼By@y@y@yBy@y@yBy@y@y@yBy@yBy@yL<‰çç_”‡xŞğ\30\127€OÂŠ!\8ÅÔ\26ù 90<2l5ïVí‰¡cØk\17­r`è\25\2WÌÄ00ŒúàB“4r¥™\25.š¤u\17—\22\9\19p'ĞN„À:\17u\2é\4Ğ\9œ“bN œ\0009q\"â\4Â\9€\19ù&àM ›\0007‘m\2ÚD²\9`\19Ü9Á\19\8§\23å!ßdx\1x\1xx\1xx\1x\1x\1xAñ\2ğ\2ğ\2ğ\2ñ\2ğ\2ğ\2ñ\2ğ\2ğ\2ğ\2ñ\2ğ\2ñ\2ğ\2ğ\2ğ\2ğÂ‹ò\16/\24^\4^\4^$^\4^$^\4^\4^\4^T¼\8¼\8¼\8¼H¼\8¼\8¼H¼\8¼\8¼\8¼H¼\8¼H¼\8¼\8¨ø¢\20„Šy\
^8\5/œ‚\23‚\23NÁ‹NÁ\11§à…SğÂ)x±)xá\20¼p\
^8\5/:\5/œ‚\23NÁ‹NÁ\11§à…SğÂ)xÑ)xá\20¼è\20¼p\
^àK\9¿3\\ô±Ö«Óñbì\9è\9ä‰à\9Ü‰Ø\9Ô\9Ğ\9ÌI‘\19ˆ\19€\19x\19q\19h\19`\19Y\19P\19H\19@\0199\0190\19)\19 \19\24\19\16\19\8Ó‹ò/e×^éÚ+]{U×^éÚ«ºöJ×^éÚ+]{5×^éÚ+]{¥k¯êÚ+]{¥k¯êÚ+]{¥k¯tíU]{¥k¯êÚ+]{¥k¯tí•®½¾\24ªºöjì3ĞgÏ\4ŸÁ=\19{\6õ\12è\25Ì³\"Ï \1<ƒw&î\12Ú\25°3Yg Î \1:“s\6æLÊ\253\24g Î œ_”‡|³á-À[€·\16o\1ŞB¼\5x\11ğ\22à-Š·\0o\1Ş\2¼…x\11ğ\22à-Ä[€·\0o\1ŞB¼\5x\11ñ\22à-€Z^”‚PK\30oØ\15Ø\15=±\31<±\31zb?xb?xb?xb?ìÄ~ğÄ~ğÄ~ğÄ~è‰ıà‰ıà‰ıĞ\19ûÁ\19ûÁ\19ûÁ\19û¡'öƒ'öCOì\7Oì\7Oì‡Ø\15;±\31ùÄ®Õ!µº Ö×Ú÷:×ú\29•~·×ü?¥ôŸ|‘„\0074¦ïvæQÆµníAùrÿµ•pÜnš—û…á/„šğ\23ÂóvÓ!>¾”\8\26\4\29\2I;#íÌ’g$Yü¬¤à;¿£Ì;k{G\"Şş$è^6ûmÿºß¼ÂÈpÀÀßŒ;˜Ï›ÚşU\\KsÙ0U¬$\7)Œ°Ö\8³>şT\27^{‹J7\25÷j¤&Ú™E—Íş5n+†iS½:\9\5\"€G,ŠÿĞ\4gq'¹ÒvŞÈ\3\1ò´ÌN;Y<™7õkU´…ä«µ³0øÜÃ²02\30bÑ)\
v\7æ¸©µ\23µ¶\01430ÍkdV³¨ÑÒ\2(¢–ŞÌ\12“„ó6l^\15Ö'Øƒ\26\7£ş:°n\26©ü(TG˜ğZ©‘X«ø-H÷\26M0Ã¶‡\9š(Õí5ŠÆZí\13ÌC\
§fPãÕ`PZu[«=“‰ -L*X¹\
©V…x5§õY¤Í\9o]Rë‰}?ÉDÙöØ´\29\24Š'œvÄYGœN>ÚÅ’—Ó6uÄå™@Që\3gÑl\7MÔD5IÍ¼qB$SÑm£à9¢ô\24¸\13&ùÖK\4I\3f;CÉ\11ƒ¤\3“\14ÔÈú:\24óÀ…2¼NÌ0i™‰ù¦mÄó smÈŞ\26\8=Ğc\8e\21\13Š8¨Ó\7N\3z³H%ğá\0\31¦\127­?o%ŒTï‰ä‰äe‚´\12{†Âà·Gé#\"úx–ĞÉ\"CØ2ô\12\3C<|*\13MjĞ^Ú\30\25ö\12=C)!;\23<=é\2što`ßMp\24'\29FK¿AHŸ*X\29ÑI§æ¤#5©7&´-ûóÄ¦Âv/M\4íS`o\16F\9İ¶–Ç±e\4öCÆ^úPZ\8\28\8©]ú„Ê5\13óQ\13êOÒ“ÀÎA\11~Ğ†uƒ‰…î\28Q\26ê\25\14\12%…Î‹lT\26 '¢y\"Ò\1‘­K„½Œ…NÓX°›Qêw›ûß±HRÅı\"E*f©<¡!.\22hO\29\24âéã*³‰fP3m\30\23,\0285\1†Kìqa}‰Ï’ÎÙds6qÎ&l \18)t4`[<ãbNº¸\18·‰²HºO¬Fú’-:Œ²“>s²\12ølíÍ˜\1*°ñÒ85\30&hbĞ£gV‚™µ\\L$M_,\
[,E­¦Uƒº^\23LE–ˆÌÖqÙÕ…øB2f3Ë³#|!¥˜¦ı\\´cK1\23âÉÛ¶FL¬òS$ÚÏ›ZñÙ‡däòüÎÅÿÃı]½/;HñùCÏ»Ï\27¤\30¢…\127ª[=\13‹½\30“\16IEÎ\30Š\26ë\5GhQçÃ“ƒ¶—ÙT8&\21¡\24x‚‹ğÄUåTÈ|èU¥§°rs\22\11ÏoŠ>\11¯\0072zS¡5…ªä\25Û­ÄUvDS9\21:É5©Ç\1\\XŸE\5\6*±®ôä\22=å\12¢rZ2eu›ÂQ,5bS¨\11qì\3·\19¤ˆx&ápF\19Y\28y\1QeIm\22ê²:»\12\"æg\15N¦pD³ÒUx\21ê\24¨\3ø\14ÙC\7ÖY¯¢À’P}ÌB\
\30…ş¨G¾Õó]ºèì„/ô€–\20;ÏµÅ–ÓC\15~ë!”û¢¼^\7²Ê…ŠvÎ‹õòZµpİ¤7¬6ÏE•\24©şk\4\13`[ÔZNÜ¹‚YYş\3Ä“šÊ©XÂC°\27Ãª,Í½Î*\6M\17ú!?›¬R£w:»M%­Ş&õ ëÏAIÇœ¦QÍú\20ƒ,G47.µxÇnÈ(\3Qz\21ê¾!Ü\0:% L¹À’\11,šM—“—Q\18\23ñt¥Çä4-z;Hµ\12JæÅQ©3lZ÷\3aÔ]`BczÇbbÌOáƒ —\27WÔf“\\‰\27ú«àif‹1\22â)l¢±\16:ì1*Ğ=Uu\22.‹\4\1?ñ\30\19\11ÛœbvYÌã‚iÀ·†Èsa¿qc\17×c†“eU²]´9M\
ĞÎ›B\14ËëN\16ï—Ä“L¦\13V\"\21‘¨¸×\12%\14>å³çª¦‚gúZJ›ğùh\\3ªÆ*Hp\127eR7æ´º?åõ\6Ñ>…\30‹ê\3\21³\
Î[tQw5$é6bŠi³úÚD±¨Ä\5·àY×c½ıÈÊeáUøœâ™’÷µ9\9j’ùtÔ¤/Â2\9E¯G¡\29ä\11ç6Ï¾\"Ÿ`”É\20|àÖ#¦À!ñe×å¾¿\20s^(²y\11‡MBİİ¿îïÊjÛì\17'\0047GîŠÜ¿PÒ­{\22uÿ_òê…¹ŠE‰AÔHÊSQat:ñ\8ÉsÇzÇÙóEç\3n¸Uë1·>Ğ\18Cöiõ¡3QÇE§ v\23ûF>\0118\3umÏÅºZmÈ\
ÿô%#¹Õ\\\0011ê8f÷\127¾eõ³\29Ÿz8g=\14kê?OùsU—¬šÓšö{-¼Vsÿõ¬¦j¿TÙA§L’ éÉ‘2FZ)R†H™!e„”\9R\6H¹ıôl>åÖıê\8ÿÅ\17ş‹#üê\8ÿt„_\29áWGøÕ\17~u„_\29áWGø/ğ_\28á\11u‹ˆ”‘Ò“(=RæI+NÊ4)Ã¤Ì’2JÊ$)ƒ¤'Çê\17N0´®‚­›Dë”hİò­êg\22\23\19h]S~çb¹<Z·òh=WÅÖ‡Üúğl}x¶>äÖ‡µõ!·>äÖ‡Üú[\31rëCn}x¶><[Ÿt\8B\30‚ğ\28‚ğ\28‚‡ ¬C\16ò\16„<\4!\15AÈC\16ò\16„<\4á9\4á9\0041·\30Ÿ­Çgë1·\30×Öcn=æÖcn=æÖcn=æÖã³õøl}Áh¼›mĞ¶*4½äÑ×LY4fË\28?™X‹d±ÖF­’œ†\30/ÏI·<'İ²Îµ%Ïµ%Ïµ%O±%Ï¬å9³–çÌÂ[\21¶ñM¿Åk® ªxÏ¢ÉâœÅ¸ªûexJTl•¼páæ\
}®Ğç\
}®Ğ¯\21úg…şK…ş?*tˆÉíÎ*rÅS®xÊ\21OkÅÓ³âéKÅÓ—Šc®0æ\
c®0æ\
ãZa|V\24¿T\24¿T¸›ì6·Ç]\17Ÿ1%<1ìå:CËP.zš˜heÉ©±L¾¨Í:Ëá-®1Í5Y,h˜cÅ²ƒİáf©\0282Î0ú|f¸è\3Åğòâ.'öÂïW[Ô`jo/'²\9¨¨sÂG\0227\19ƒYŸ-q &³ù[¼kìT‘K?·¨Í>r­ßÊm³\13c¶ü„÷­lD\29©4\21ßj4uZUÜºU%S‰e\\Õ5øl·m%â!S“ºUß\127.Ğ©“›t¿*\20œF\25ß¾*B7š½ÿ%\"TÈ\4ÑÅ4ªÄG®¾™Dc\
£ôyóm_V[÷Ú–¾†î}³ÅÊöM?îÌ´ÈÕ,;\13÷\22«Íæ§Îì`v2\27Í&³³Ù\5¶³f`÷9¡Í‚Y»­æ\24Ù@7NjXm_¶|\8;å\4}ÒÔ|2¶¥’Œ­uw|Üš]¶uN\17×C†R\\5Ãµûí²\21T÷K`J)\26°(Aá²˜²ˆYœ)üÈ>WŒàn(O\"»àšÙ\3l•,]àÓÀ·ê\\/V/Õ¸ª¸ª´*8§zOZÃç2hQUqUóª\22ª&H£û§lŸÒ=åhrF/Ê¯‘ı×Hû5â¾Fş£\2%ì¾4İ}i»ûÒâ¸«Z\19Ú…s­}®K~&şöùQ¦¦ïÌ·u³;¨9ÒpyÔM,å¥“É¸§o¡–]gv„íğé\23CYw³UÕ·\
D\1âzÜ\7\29oUÏ´Hµûü±\29(4¢X%Ò‘ÂD§Æ©\25\25j]¹\"¼Yd‘ºf•÷_”‰½‚\29Ì\6³3í™á¬u-Vå\01364³µE5fÁ¼aÜ{Ë\31Î¶:êy<íÊŞ„¼Ô™ª³h³è²pYLY¬\21¥,Îfçœ€V›¾qØ„D}g-‡±ßº\29lBê±ìuí\30Ë¡ä\0\31›BºĞúFı¨BênÇ^'\22E›…£\8\13[\19áue¶áş7×TzFæ,ßÙb\27Î{uHû^\19±’òã^y*£'€\
Ô~jj›ÏªºUM«Š«:¯ŠeáüÒ,3\0317ËïÊT²\31\20Šì†æñ‡NZ7F}\0202eL‰O\\èlì]8'í¡\11sgI\"b\22¬)s×ìJY\28ıı\18ú¡o\"·ÓÏ\27^Ëae=Î¬\127(í8ªÆU¡Àp¿ôùiO_iÊ¬Ï‚­ß¡©—nSÕ­jZ\21{¥R‹Ø&<4á¼»ÿ-ÀC×à„c¢J–î\0Ó¬Ê­jÌB³\13æ9ªûo\19$õùÔP•VuÎbÎBNèa¬­öP:ã\9¥¹ë\\å\
ø×o¾ä¾*f¯¦¢©é\13‰Ö…oâ7MšrÒT|3õøs•\\Ç\26±²\26§fP3ªa]÷K¶a¬u.û’\29…I–%f›ô\1½D«5¿=ä™c’å8«¹ÿ¶’g³šPîğ7\25µ¾4\17,‹)$-*\22ls´3[“«ÃûãÂÜz‹\0\
¶9ß¨+å8\31_Ï¸d‰l4¥S3¨É.¢êVåVõÌ7­*®*©²Gšş\22wi\12LPÿ4–í-í\18£ç-Íı·ÚY3é_²²šMõf\7³ŞlÎ‰|²L\9Ü™ysB ùµ8è«tkb\0171î;ÎÈqÏ\12£ío°‹&k”ôb˜XsrŠ©ÔÔj\14jÚüÌDGóÖípÿ”øı—¦³½z´ºF+7®éC‘Õd6jAæ\24İ+6©™Õ€“_İ$&5÷jğ\31%`1Íh±®!˜Íˆõ6\13Ãì\14gF—E´\28¡4{¿˜àõbÕ÷ËüŒv9ï/\19çœÀæ\7moÀ°Â\16†|›v}éUÈ\29\20é±èË}\22u\22³\9iÖ\20®ó\20£ZÖ‡£¢\12Y(\31”_“ş@c2wË´¦¥Ñ­2«ÜÎ\27d\
q\9šä\11ÄY³ÍMEêMuMZÕã–eN\27O\16üäiâó–ÕÅ”\5Ç\26÷2f1›0@Qê\8\17\29‡l.ä¨R!ŞªM•Š2[İ6odá\21j½šĞ¨å†5İÿWî“İ²\23\15O½çaM‹:(85©\\ \26±ÛcµL:í§Q/SÓXëv3qm\5\21­%àï1\0209Ç¤Ekt\19àªÑQ<\5¤¦´YtkÒÅœE¡5`=¹QŞ­©gméui\6\19c¯âq+³8³\
¥|k¥İ=\19t\25MzÛ™F£î­ß½$/\20ê°|GÃ“±Ø÷X\18L´ì¶z'[…S¾ÁQ\12YŒYLYÄ,R\22ç,xìPÍY,FÀëÌ”+~\27v²y:¦h\11;y\29m³ –5ô&%wü«[7i|—ÎšAgÁˆc1•«\26ç,u$R?¶¨ú¼™àD\8ãbİ‚Š«š­á´;jF´ÙYI\26\29 ÍWÌ»ÀÖçw\0272\17.‹)‹˜Åœ…º†ç¯/\19‚Ş\28`'µsWú2D]!\20ş¼*\14nÀ±>æblT.ä{³•Úú)Ú5eUY—\19\6\19ã3÷8e\17uGcd²fdò—íSNO‰qÕ·Uw«²Ä:£ÛŠX¬v]Ø\"š­ÚƒÙvíeVYëŠœÜs¦±N™³›•İÚ•!×^Ù,\11zÍ€5 •‡w¢)tæå.\3êù\15ÛšÍ`\1İ\127™è\12§3ŒÎ0$C\22\2Dòn\0218{î\127«4È\14Ó¾/¿=u÷Eª­#u¤³tÚ‘ ïöæ4õ\25£“F'ø%»Å¼\18Æb¡¯Ã(·F^Cd\29éöCQg¡\30 \28²˜²\8YÄ,´\17¨eMºåvÎYH?ğ\7ö±?ïVÑ>Ó¦§D\31—Î\13\\N¢‚\\>vO5ñ¹\28ÂISå¢3\6Qñ\\è}-Ş\127s4aùE\16bÈ\"ç˜Íò®\20äõÛ®L\5¿‘Í]YÑ¹\0203Eİğ«Û,\0119\127'Ìš>à²®Z\196â#†}M±o\12²«HpÿgG¹×\20¬u¤U\26åìD\\Å;\7\7ñZ£-\28;¸²PøF3´¹>\19Î\
:\14j&K4\26-\0265ª½yÇ|Ä\21Z@:>K–5iVëĞb©°‹¾½-²Ñí5Z©a_–’}Xô¥ƒ\15M85ƒšIMP\19Õ\16lÑw¥dãK™\27å¤C«Î,Óu‚/ã[\21Éi\30ÌÎ´­æâ5t±\11¨Mï<¹í\19£}\18±‰nÓ|WöN^uûMyNc\17œÙ¸‘v{Ù`ašÚ«•\23CØQÍıwMûnÉï\17ÙÆöuîŠæµÜº/±q‹?½3.‹•ÊäÌe½Ü±aå\295\6|¹¥\24ıB{–«\13süjÿY\27qıpv0òú\0043—ŒÍ\29rÃºÍç\15îj½\28Ø\24¿¾ñjï\23ïV5šD&y\11ÿCm(\7¹´ç\19\5ş.å-•¿}a¬kÕÈi\2+—_š°‘3ã¼\13÷¿¦¼T}Ş\0u(úN®¹bCé+9H¡\0267\3çÀop\15(\15j†Í$›Îq\7…„ûOôèˆ¯\0020s\25êFškù\18A\19ÕÌ\27¾'Yjgö,‹Z,»#f¤ñì•Ø¦VÃ²âÉEã#\27ğgÍ|ÿm¹e¿€\13ò\26\3ójµI·Ôh6‚Â\12j\22š³&¾36kKÕ\27¸'\19r\9…`mH\16Ï<•ì\21”óıÒ¯*™*³ËÂfwjê†ƒ•dÙ?c\28:§^ƒùüØğE\17C„ø@#9Ñ\11\7\7&³– ·tš¨åî¿1.|eÜ›ÕŒ¡K]µÑ·ÆºWñ7F\1¯jÄ£7Šw¶1—}wÈBS\26{PË”\26\0İEşˆ\13ïš#\
\15|e‚Á\4ÒOH·âX>¥¼ßúræ/[d|Å\7OmÉ÷_3şœØÓÑ\19fR’eC•ÔèóFn¿j±Ö(0EtÚéI¦Ğö<h)¾ÁÅ·‰\22ñ\14¾…\13£ø~Ú†N^²5i¬Ïü+âáş3ÀÊÚ\31'¿á}œ#E1j\
ŞqhšI\13\11ºûßj1ïä<1™LÜ\127W¦ÎÉå´\127f-ù;6Ú€ì~Ö„Ì.-!\16nc/êù5/éõÆŞÕù¦>{³ÙÒ¬\22Æ°£0‡=ÊäÁjˆ²(5>4½\26vaê\26¶1™Ñ\14NcÂk\26¿\7à\27d½Ê&KaóÏ\12\27ıdÀ%Á/\0]¥‚µâ»j³ò&8\17LÕe~*ç(Ô\22ß1Th“\16Î2i\15 >o¦º5­û’˜Ûì\0309\9û„¶ù;?<gŒ³å\18zÙa·3®ÏIº&Mw&1‘ß×˜¾Úç'\13—½Æ¢l\4ƒé1®²næ/E´ø³¨bôêŠ3\7›şæç\13œ\"d‡˜(ÜˆŒú[5l‘ª°dğé£ój±h*-)wbŸ´\7e0Á]ët²„_– Şp²î‚ÆÎu“…9AÈB™å(ç¨ù¦ï(\30×2²&YÄrAÙåŸWêï9ÿ3ŞÿW<üW\\.\24ø#V‰Õ\2ë6ü„ã‹¸ÛØW\29~À‰ú@ö\13OÑÁwI\15\3üÄn.OYôYHÎ³ÜIøú\14õy“\20Şdå¶#—\24ü\17²Üä@ü\4\20adÊªÅ\4‡I–J+\23ğ\1õÀÁVŞöw¼>r¶ŸXåRÔgµâ­vU˜„‹¬æ†÷‘¥\24Ş#&8\5­‡\27Äpo£}\\J¨ \15d-´\13Æa™\11İ;%\1‹YÌY³±~üó~ÉªÄ\6\29€ä$şVÍoø;–\4qBŞğJá\24N\12‘’pF®³œ‘0L\24\16 ×9J { ¥æ˜\8ÄÆz>\0284bæ_\9¯*ğ»\20•ü\14EÕ¡Hzë\25Mÿòï\26\15ö8àkâY„ÌŠJ\1ìáã‚Ö€~F\7Ï‹\4s\0l3f€Ï@™{Fî™\25\23fZ˜ké\0252óã&á²GP¿y†!nÒG$£à‚Î-\1´]ìùsço›ÿ‘‹¾„u±0|Ü¾mğsûTˆ=Y¢Oßøëš\"˜´X7\"ø3\27±øõÎ,6ÔúÛ·\4ƒíä\7\127†\22ŠˆŒ\17•Ú/­¿qÿ\25Ÿ1|i\18\2dÁoMäÂ-VnD¡{=o‡Íñ}À\31U$2lz9™_İıçĞ•øÉ43\0286®ï^›­Oÿ\7¸'ğl",
  ["length"]=19364,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=2467,
 },
 ["version"]="1.001",
}