return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="da",
  ["source"]="hyph-da",
  ["texcomment"]="% Danish hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: dkcommon.tex (yyyy-mm-dd), dkspecial.tex (yyyy-mm-dd)\
% Author: Frank Jensen <frank.jensen at hugin.com>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
% This file contains the hyphenation patterns for Danish.\
%\
%% Copyright 1994 Frank Jensen (Frank.Jensen@hugin.com)\
%\
% This work may be distributed and/or modified under the\
% conditions of the LaTeX Project Public License, either version 1.3\
% of this license or (at your option) any later version.\
% The latest version of this license is in\
%   http://www.latex-project.org/lppl.txt\
% and version 1.3 or later is part of all distributions of LaTeX\
% version 2003/12/01 or later.\
%\
% Changes:\
% - 2011-01-11 - remove support for OT1 encoding\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnopqrstuvwxyzÃ¥Ã¦Ã¸",
  ["compression"]="zlib",
  ["data"]="xÚ-˜İ•Ã,\14†[¡‚œãcØ~œ1vˆ1x\1{×_?35Ì}\26Ûçeö\"²\16B\8¡?ò˜üh\30S\0267Á¡šÇÓ»8é34`°­˜ÇìË\24ø„iMÙ™Ç‹10_~æ›¼m\16ó>\0.oÍãÈ -D&ïÙ\0213=]ôfœµ™iü2ÓÜ7qÓ¼šiğ Ë\
°Ë\16Í´Œ,Xl\9\"W3ÙÕ/‚ÁL«\11I°\6„­-ˆ|#ñe¦Pd¿Íä¶\9dóÂ´!»M\3:\0X\0219®âviœ\25K\"L§Æ\8Üí1±Cš4HvÓ\17ÆtŠÄ\18Ç\
w k<‚0†CA~A_3Lå©±\14Utº\"É\5±J¯Êé‡¾[İ\0042BÇz\8m¾Cæ†6\13‚Ò·Ÿ²õƒ\15\0131-;éÀµ0Fawéh—û\25“yÂ\30Œ}ÎŒ¼á\0307€4àfË)Bµ‚H\24Á<ƒC“çğfÉ Á˜íZ€#§zfÇY†g±ÌWó¬\14f©ı\28¸Ì'F\31Ÿ\8=m•JO÷\31xoó¼]5ökø2Ã—7_lÌ9¿^^\15ó\21l6_ÛhÜ×mÆy2v\30±Üì¦Ô&3O¶šyxò›­\25fop–\25\30o£ß\25\20ç±)Ã\18VÍ¡ı<°|`„'\0123“\1§šƒ‹PŞÌˆ\3|Ø\17Ã\25Ç9ƒäƒ-ó\5ù`T|kÆÍ¶xL9Î%,\0292îUğ4sEEA.c\30êÆF¶î\2š;µ]u\23ÔQçĞõÍ\13g™e\25°\19İ`<ŸÉ\11ñ·ñ„€ñ:=Ø*l3~˜¢ñ“Åe\25'Í\28Â\26àÉÌ³ğ|\5ã±X\1bŠ\14£3c‰ÎÅ\17š\\œ ÚztD\9?r6¿°Û¸\20a’¹ˆ{ˆ\15g\0{³Ğ¾g·a“\26D\19 \26Ë˜\13\20X~s8ôè·Ê­è#%7É\"¬ààpD\29§‹ıP@Ö\12q’ü(ùÑo¬Óz\5%»…]sÈ\18MŠ85Fİ%ˆ¨T\26ñ;iÊ''©6a ëS\18ÊÂ$ÏôPõ.£ıÈ%û!ëäÜ´?‚Lwh(\11•nx[dy L/“á\3q³• öåu‰\30D\15Oèx“/\25—„EBËX…vó–s\23~êÖ\
Š\19È\2\8m~Ã¯½ÂÙí-,\11Óª&«5\25LËGVş”µ.Ùş’J×èË\"\
Ëİ\127Í°Lf™,±µL+ş°\16/Ë@Ä/PüÛ\
Ä\1ÒÂoåG\\,/&_\"x6K.ƒO|”i\23b`Q^°¸Ä\"÷]¤õ\"u\23‡¦\0¶\30–\19\26®»ÜfX'³r©Í¬l¾jsìeWçÓŒÜU%C\31¬³\11\12+?Ô ¯Á²\"ëŒ[ßLoLE~8Òš%#ïf•q×ñ`E1k\29Ø­ö\28€P[=£×dáªQ3cîL‡\8¤?²ÆÚ=\30š¤p U\7Zu U\7ZeúµYiwÎf=“\3»Øí†á&á¼¦‡yù\25ë¾¼²ÙË7ó\
Ö\11ÀüB\127óÊx\0rIö5Âp&+@]|]Ùš€Şa|\26NŒë\6\18b ­˜0+’¥¢@‚è‹@{˜ ú\23\20•l\22\\à÷†‹8\4 cÃTAÛ†M\17\30¨Nğlª\127a³Më\8C&/°ˆoS‡½ óï\14£è,±Ñ…Y³Ò„°cN‹w\0ús7!- ˜\16ÈaC²\21™©\17\3ğ%1çY\0é.oÂ±\0@«\28ÅCT4sÔÊ0\30Ú×\29\"JõQš\23)®º\8VdÔP¹÷@éVQI$/2@ë@–\20qä\"ƒ.24ªÔCT)E(…\1Dñ\19T\26ƒâæMË`Şª\27H}Ïè÷&&‘ L—\30æÍ¼•šŞ²Î;î>Îîïkg-gUñPNlA“q˜ÍM§°\11ìi6¥- \
û†Ç4 …{2\27÷¸q¹\2¢\18„\27í\15P\29\9iõ4›M7’°&ù5™­—ŞqËD\0238^¹1&ëŞf«ª\9›Z\8PdÈé·Ş<9>€>4oœ”\11$…™­És7™I°\"œ\0123lgÇÄ|e\1Î\19§§!qs\\Ğu\6·ëß`7äïf\"ñ\30ÿzÁêL”?ÇY'ã8\15ø<Á\19Iì&’¸©û\
Y¦Š@ÕÔ‰ˆÅÄ\5‡ê\0163Ça¥gŒX*\6Kf‘o&1“DØ\17Obò\13\27\17\16UƒğÚ\27,šèpØ˜-¥5*İ³’\\@\25¹´ú0Ñ\30•™ÂˆoõÜ{ì\21œÛ’@<*b©E¨\23ê”iãˆ\127Å6j#ü+*GGUø¨|\12 \25î“Ù1Å>rk;ñ¿+ÀvrİN®ÛÕŠìÁìD£ÙÙ\15’ú\29OÆ?wQÑ~'çí;Õ\12Œ´¹vÂùw\29eW\14Ü\7zÍ]½&@+h8Á\
\24¿ªÜ´÷\3íj…v…ÎŞıa—'ìÊ}\0‰h\18Ñ´ğ”Ê'ÂN•Şq§\15KlšpÊ®×$Î•HV6Í&é‚¹#<Npë´œ¼Iô&\0)œ<§°\127\31L\8BöK¤5ø±h\20oıƒ\13Ñ‹IV©>©$$ÚÕDñOºæÔƒ$é¢“.š§I\0178‘CgÁ\
©\7³šÕ¤ù\\PÒ\29`\\2N“”GxËh\9ÖÈÂ1BrJ$I\23NŸ‰\27\
ï\0j\11\19ÇÒ&vl”š:Úş9EîàÖö”?‚5ÿ˜<N&[:šüTÊÈ\24ŒËã&ò¬œ\12¬\2ÔóL?š\23’!5m`\20ä¼yUL\2±lv/~\18\16şU1b¦+Ï#™?Ë\28YFÈzÊd¥©<ô=IÜY/—ìè”†¼³‡^s9o\9B!Ë‰²ü'\31c\20(\2\4~>°…Íåaè\5È*²${—®÷¨„*¸v¸uX:\28ÿ¦›`ĞªÀ³Îq‡´\19ı\0E:\20ş(v(~n&«GËÔ—,óçn‹:<òæ:&·¾ÌA›\29ÍA\\ÙÃ\1271¡\4r°ùáõĞ:äò\7}\18,\11,\24m8°ÊAËL7x(\11\9–\14a\29w~ÉğRãÙwHudR”XzX–ñ8¡)Ì_pq\9‡C¿£ÚCÃf\14Rép°×I?Ü‰å\15âÊ\29÷hş}Ò1\21rG™\\¨Byü\21b§ØŞ›\23…N¡÷\30™£E6ô—Ñ”şø¥¿L•BR<Í\12¤Š£Â\4I\6ndOÍó0)\4L\25è\9\
ñRôº)ABèİH\25Å*½\20•j\2ıË5h2\29\29\"@^TäE€`Ê¦K(r¨B<\21’\14\
í\26%S²N€ÇÀu\8\16RM‘FÀ¬î§\12Uò¸Î‚ã2ië†UJµ¬×{¶ôb\4<5fÆ5òJÑ•\23J\18®[\20xE\1\7A9»P(/¥é‚ÔP‡\14³(Uè\13;™«Ğc‘qx‘é\\—ô '\23åärãHUm=úí¦N¼\0284>\12\13d\17‘[¯\28¯Ò¯Öùæ‰õ«¥dam<\6\3Š€¹a[¹İJ\30¯êŞàä½©DKgT¹m@ÇNˆï\19Îí\1ÏFõ\4\"Cï%ŒBS…ndF\9æà5fŞ¾5jaÔ\4ŠZR°­‰ÈÁ‚È­4–ğĞO\1ö‡áºvØhŒk§4Q’”¤NT¼\24›\19*¶*LFœ—m\8\
‘K^\31¬ä\1_{‡_i2Õ$«œ“\23Ù‘&…ğ\3or\9úG‡³è^Z4§‰”úàè\19åÑ?µ“d\13^6\16²dæ.\31“ªÚŒ•jSûÓ¦ÒxTUQÔ$cÕ›ç\28ÎÁ~\6\13…Ôr£^\"Ù·§A\7º~}h6¨c+Ì~K\16h\24@Ë\14ªÿ\23lãÖşÕFd\16$=¡+ƒSõf£î‡%½´Ø¦\127\127\26nßHù\8m\\@Ãï[Ö»¹e=\2\5\3°Ø]\11\14Ó\8n0\2Ôà’¸:E‚+k\12•ÔZÕ_F­ª·mÚ\5”\19³\13¨;g\29‘s7=\20xê\29æäa\0=šS\127³òñ9_Ğ½9û\31jçª\23'\31Ìq:bÿ\28\0259¼êTk×!+iÉ\4X%g:õÇÔÉ;\25ìß¬@éSátÚ¢GÀ9(‡Ÿú7è¬NsU2ñZÁN”\
\4é©è<õH=›\20lİ‘O¦¯‰·/a‡á‰»Ù\\\\\15µêRc½òQw|á\12\23yù\
½ƒƒ‘€¹xÇ\\¸õ\21­¹TÁ.G4\\‘l û´—\\æ¢_ªˆ—¬x)\127\\ºE:Ó›r{;2êM/}ë?‰Û‘ËîMÅ—q\6Õ}‚^L‰è¨·òÚ4A9ºÕMİª†·ìrc–M¨ÆU i\25)\8È]ı£–äQ?ß£y|~(m|~/ıC9¶Ï¯ş}ûü˜gùüòàsOpôƒÁÌµ}¾‰Ê\25\18àW\127d€\
\
/‚Å}~õGAÓ„“8Ş÷©\19>ß¼³µ|a†ŸUÅàÙ\12¦Ç-Dz\0061­bZ?¿ƒà7O%\9\12#\12ãö\7¾é ÓêS_Kó*=Q„Æ\17ŞoZAIØÅ»3¤}`œº˜1\1HøŸŸ§q\9\14Ú\12(”óÃÇKÜñù™Í!;\21§å¥//ıX¥ïÈq\127ˆˆ¢C; yª|¾gÑ¿É\8VjÒ*\0I\18Yµv¨]Ã*5*\18’ğ_òÙçw3\28\31«(º¥{C\17rpë¶iİ6­ï|vÛ\11¥S”‰iJ¹¸o]1\19œ¾èó3~\9xÀJh|~z«¦\15ş\15\13\7úüà\0\0ü‹³ğ¼á“†YÓ¸ÉçG™\3éÿ_!§ÒhŸş>â  Š¹jF%X°i‘\18\"^Äûòó+\29~‡· ¼\28\24\5wiğ›\20\23|ÈJâ*}^;ı–äERÓÅ„ä}Så\0Â\8F.'\
hÉwQn„LÃ\3©ı\15\14Ó\2ş",
  ["length"]=6152,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=1144,
 },
 ["version"]="1.001",
}