return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="la",
  ["source"]="hyph-la",
  ["texcomment"]="% Latin hyphenation patterns\
% \
% (more info about the licence to be added later)\
% \
% This file is part of hyph-utf8 package and resulted from\
% semi-manual conversions of hyphenation patterns into UTF-8 in June 2008.\
%\
% Source: lahyph.tex (2007-09-03)\
% Author: Claudio Beccari <claudio.beccari at polito.it>\
%\
% The above mentioned file should become obsolete,\
% and the author of the original file should preferaby modify this file instead.\
%\
% Modificatios were needed in order to support native UTF-8 engines,\
% but functionality (hopefully) didn't change in any way, at least not intentionally.\
% This file is no longer stand-alone; at least for 8-bit engines\
% you probably want to use loadhyph-foo.tex (which will load this file) instead.\
%\
% Modifications were done by Jonathan Kew, Mojca Miklavec & Arthur Reutenauer\
% with help & support from:\
% - Karl Berry, who gave us free hands and all resources\
% - Taco Hoekwater, with useful macros\
% - Hans Hagen, who did the unicodifisation of patterns already long before\
%               and helped with testing, suggestions and bug reports\
% - Norbert Preining, who tested & integrated patterns into TeX Live\
%\
% However, the \"copyright/copyleft\" owner of patterns remains the original author.\
%\
% The copyright statement of this file is thus:\
%\
%    Do with this file whatever needs to be done in future for the sake of\
%    \"a better world\" as long as you respect the copyright of original file.\
%    If you're the original author of patterns or taking over a new revolution,\
%    plese remove all of the TUG comments & credits that we added here -\
%    you are the Queen / the King, we are only the servants.\
%\
% If you want to change this file, rather than uploading directly to CTAN,\
% we would be grateful if you could send it to us (http://tug.org/tex-hyphen)\
% or ask for credentials for SVN repository and commit it yourself;\
% we will then upload the whole \"package\" to CTAN.\
%\
% Before a new \"pattern-revolution\" starts,\
% please try to follow some guidelines if possible:\
%\
% - \\lccode is *forbidden*, and I really mean it\
% - all the patterns should be in UTF-8\
% - the only \"allowed\" TeX commands in this file are: \\patterns, \\hyphenation,\
%   and if you really cannot do without, also \\input and \\message\
% - in particular, please no \\catcode or \\lccode changes,\
%   they belong to loadhyph-foo.tex,\
%   and no \\lefthyphenmin and \\righthyphenmin,\
%   they have no influence here and belong elsewhere\
% - \\begingroup and/or \\endinput is not needed\
% - feel free to do whatever you want inside comments\
%\
% We know that TeX is extremely powerful, but give a stupid parser\
% at least a chance to read your patterns.\
%\
% For more unformation see\
%\
%    http://tug.org/tex-hyphen\
%\
%------------------------------------------------------------------------------\
%\
%                  ********** lahyph.tex *************\
%\
% Copyright 1999- 2001 Claudio Beccari\
%                [latin hyphenation patterns]\
%\
% -----------------------------------------------------------------\
% IMPORTANT NOTICE:\
%\
% This program can be redistributed and/or modified under the terms\
% of the LaTeX Project Public License Distributed from CTAN\
% archives in directory macros/latex/base/lppl.txt; either\
% version 1 of the License, or any later version.\
% -----------------------------------------------------------------\
%\
% Patterns for the latin language mainly in modern spelling\
% (u when u is needed and v when v is needed); medieval spelling\
% with the ligatures \\ae and \\oe  and the (uncial) lowercase `v'\
% written as a `u' is also supported; apparently there is no conflict\
% between the patterns of modern  Latin and those of medieval Latin.\
%\
% Support for font encoding T1 with a 256-character set.\
%\
% Prepared by  Claudio Beccari\
%              Politecnico di Torino\
%              Torino, Italy\
%              e-mail beccari@polito.it\
%\
% 1999/03/10 Integration of `lahyph7.tex' and `lahyph8.tex' into\
% one file `lahyph.tex' supporting fonts in OT1 and T1 encoding by\
% Bernd Raichle using the macro code from `dehypht.tex' (this code\
% is Copyright 1993,1994,1998,1999 Bernd Raichle/DANTE e.V.).\
%\
% 2010/05/31 Removal of OT1 support\
% 2010/06/01 Removal of pattern 2'2 (probably a leftover from Italian)\
%\
% \\versionnumber{3.2}   \\versiondate{2010/06/01}\
%\
% Information after \\endinput.\
%\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
%\
% \\message{Latin Hyphenation Patterns `lahyph' Version 3.2 <2010/06/01>}\
%\
%\
% ",
 },
 ["patterns"]={
  ["characters"]="abcdefghijklmnopqrstuvxzÃ¦Å“",
  ["compression"]="zlib",
  ["data"]="xÚ5”á±Ú0\16„[Q\5±¨ÈØ²QĞÌ˜7¯ôF2é+»lòãNàİ[}\2Ä´äë¥¥iñWµ\\,{šÖ\26ëÈ†gkÏ>×g[ÍÏËZ½¤©ä/H\29Ãi:—Xæúo\29iz\14fş\127\17\9CQ&®[±)]Îü¬+\23/#ış5§??ç„ˆ…­°u¶‘–2/lm¤Âgµc¯Ns§¹ÓÜ)Œ~\25i¾¦|eméš\27VC9^\3ãúB=QSš×”×5­ù–Ñà[á[\29õÀ{xWøVø×o\20ü[Ê\27ë@YÚhÙ`ÙŞ(È{Êûv&í\21òé\29\18&\14\22¦=\29´\28†ÕQ°\29H9rÀzKùv¢0yÃÛ\31i¾§|¿§;1g\0126œ¬\1½!¬í©]ö\12oC|ƒ³Ñs4œ£!§=PØ¢a‹F\31¶iÈ…ÅX\0083Ø\12c†\17ƒİ`7Øğ-Íxä°8ösìç8£c'‡İ1îÔ1î\24sŒù39¾aûtz±£#Ê¿Pˆ;Ó™o(ŒŸ\24=ù\30c'àNXO|Ğ'O\127òø'\6\30\3‡†#\0\17€\8@\4‚ãH¤\28H\
€\4Ò\2ƒ\1 \31‰ŒÀæÔ@Ö3ó×wŞØ!?_W¶•mcÛÙ\0146\\\6tcs¶“íÁö™{±!øÉŸó\11ÉxÀ0f1ŠI\8z\1ğ…£¾xD¦1ŒYŒb\00838şNoØŞ´½ßiÆgõ\5õ‹+TĞ\127O¸\
ƒ7cğfŒÊÆë1x\31 \20\
…B¡P(T\
•B¥P)T\
B§Ğ)t\
Â 0(\12\
ƒÂ °äöÙKÑRµt-À¥ÈRd)²\20Yª,U–*K•¥ÊÒeé²tYº,]–!ËeÈ2d\25²,øËúàšpM¸&\\\19®\9×„kÂ5ášpM¸&\\\19®\9×„kÂ5ášpM¸&\\\19®\9×„kÂ5áºp]¸.\\\23®\11×…ëÂuáºp]¸.\\\23®\11×…ëÂuáºp]¸.\\\23®\11×…ëÂuáºpC¸!Ü\16n\0087„\27Â\13á†pC¸!Ü\16n\0087„\27Â\13á†pC¸!Ü\16n\0087„\27Â\13á†più\11‚2\24H",
  ["length"]=1756,
  ["minhyphenmax"]=1,
  ["minhyphenmin"]=1,
  ["n"]=335,
 },
 ["version"]="1.001",
}