/* This file is generated by "mtxrun --script "mtx-wtoc.lua" from the metapost cweb files. */


# ifndef MPMATH_H
# define MPMATH_H 1

# include "mp.h"

math_data *mp_initialize_scaled_math (MP mp);

# endif

