/* This file is generated by "mtxrun --script "mtx-wtoc.lua" from the metapost cweb files. */


# ifndef MPMATHBINARY_H
# define MPMATHBINARY_H 1

# include "mp.h"

math_data *mp_initialize_binary_math (MP mp);

# endif

