/* This file is generated by "mtxrun --script "mtx-wtoc.lua" from the metapost cweb files. */


# ifndef MPMATHDOUBLE_H
# define MPMATHDOUBLE_H 1

# include "mp.h"

math_data *mp_initialize_double_math (MP mp);

# endif

