.TH "mtx-interface" "1" "01-01-2020" "version 0.13" "ConTeXt Interface Related Goodies"
.SH NAME
 mtx-interface - ConTeXt Interface Related Goodies
.SH SYNOPSIS
.B mtxrun --script interface [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt Interface Related Goodies
.SH OPTIONS
.TP
.B --interfaces
generate context mkii interface files
.TP
.B --context
equals --interfaces --messages --languages
.TP
.B --scite
generate scite interface
.TP
.B --bbedit
generate bbedit interface files
.TP
.B --jedit
generate jedit interface files
.TP
.B --textpad
generate textpad interface files
.TP
.B --text
create text files for commands and environments
.TP
.B --raw
report commands to the console
.TP
.B --check
generate check file
.TP
.B --meaning
report the mening of commands
.TP
.B --toutf
replace named characters by utf
.TP
.B --preprocess
preprocess mkvi files to tex files [force,suffix]
.TP
.B --suffix
use given suffix for output files
.TP
.B --force
force action even when in doubt
.TP
.B --pattern
a pattern for meaning lookups
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
