.TH "mtx-fonts" "1" "01-01-2020" "version 1.00" "ConTeXt Font Database Management"
.SH NAME
 mtx-fonts - ConTeXt Font Database Management
.SH SYNOPSIS
.B mtxrun --script fonts [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt Font Database Management
.SH OPTIONS
.TP
.B --convert
save open type font in raw table
.TP
.B --unpack
save a tma file in a more readable format
.TP
.B --reload
generate new font database (use --force when in doubt)
.TP
.B --reload
--simple:generate luatex-fonts-names.lua (not for context!)
.TP
.B --list
--name: list installed fonts, filter by name [--pattern]
.TP
.B --list
--spec: list installed fonts, filter by spec [--filter]
.TP
.B --list
--file: list installed fonts, filter by file [--pattern]
.TP
.B --pattern=str
filter files using pattern
.TP
.B --filter=list
key-value pairs
.TP
.B --all
show all found instances (combined with other flags)
.TP
.B --info
give more details
.TP
.B --trackers=list
enable trackers
.TP
.B --statistics
some info about the database
.TP
.B --names
use name instead of unicodes
.TP
.B --cache=str
use specific cache (otl or otf)
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
