.TH "mtx-unicode" "1" "01-01-2020" "version 1.02" "Checker for char-dat.lua"
.SH NAME
 mtx-unicode - Checker for char-dat.lua
.SH SYNOPSIS
.B mtxrun --script unicode [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B Checker for char-dat.lua
.SH OPTIONS
.TP
.B --whatever
do whatever
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
