.TH "mtx-fonts" "1" "01-01-2013" "version 0.21" "ConTeXt Font Database Management" 
.PP
.SH "NAME" 
.PP
.SH "SYNOPSIS" 
.PP
.SH \fBmtxrun --script fonts\fP [ \fIOPTIONS\fP ... ] [ \fIFILENAMES\fP ] 
.PP
.SH "DESCRIPTION"\nConTeXt Font Database Management\n 
.SH "OPTIONS"
.TP
.B --save
save open type font in raw table
.TP
.B --unpack
save a tma file in a more readale format
.TP
.B --reload
generate new font database (use --force when in doubt)
.TP
.B --reload
--simple:generate luatex-fonts-names.lua (not for context!)
.TP
.B --list
--name: list installed fonts, filter by name [--pattern]
.TP
.B --list
--spec: list installed fonts, filter by spec [--filter]
.TP
.B --list
--file: list installed fonts, filter by file [--pattern]
.TP
.B --pattern=str
filter files using pattern
.TP
.B --filter=list
key-value pairs
.TP
.B --all
show all found instances (combined with other flags)
.TP
.B --info
give more details
.TP
.B --track=list
enable trackers
.TP
.B --statistics
some info about the database
.SH "AUTHOR"
More information about ConTeXt and the tools that come with it can be found at:

maillist : ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context
webpage  : http://www.pragma-ade.nl / http://tex.aanhet.net
wiki     : http://contextgarden.net
