.TH "mtx-pdf" "1" "01-01-2020" "version 0.10" "ConTeXt PDF Helpers"
.SH NAME
 mtx-pdf - ConTeXt PDF Helpers
.SH SYNOPSIS
.B mtxrun --script pdf [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt PDF Helpers
.SH OPTIONS
.TP
.B --info
show some info about the given file
.TP
.B --metadata
show metadata xml blob
.TP
.B --pretty
replace newlines in metadata
.TP
.B --fonts
show used fonts (--detail)
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
