.TH "mtx-scite" "1" "01-01-2013" "version 1.00" "Scite Helper Script" 
.SH "NAME" 
.PP
.SH "SYNOPSIS" 
.PP
.SH \fBmtxrun --script scite\fP [ \fIOPTIONS\fP ... ] [ \fIFILENAMES\fP ] 
.SH "DESCRIPTION"\nScite Helper Script\n 
.SH "OPTIONS"
.TP
.B --words
convert spell-*.txt into spell-*.lua
.SH "AUTHOR"
More information about ConTeXt and the tools that come with it can be found at:

maillist : ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context
webpage  : http://www.pragma-ade.nl / http://tex.aanhet.net
wiki     : http://contextgarden.net
