.TH "mtx-tools" "1" "01-01-2020" "version 1.01" "Some File Related Goodies"
.SH NAME
 mtx-tools - Some File Related Goodies
.SH SYNOPSIS
.B mtxrun --script tools [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B Some File Related Goodies
.SH OPTIONS
.TP
.B --disarmutfbomb
remove utf bomb if present
.TP
.B --force
remove indeed
.TP
.B --dirtoxml
glob directory into xml
.TP
.B --pattern
glob pattern (default: *)
.TP
.B --url
url attribute (no processing)
.TP
.B --root
the root of the globbed path (default: .)
.TP
.B --output
output filename (console by default)
.TP
.B --recurse
recurse into subdirecories
.TP
.B --stripname
take pathpart of given pattern
.TP
.B --longname
set name attributes to full path name
.TP
.B --downcase
lowercase names
.TP
.B --showstring
show unicode characters in given string
.TP
.B --showfile
show unicode characters in given file
.TP
.B --pattern
glob pattern (default: *)
.TP
.B --recurse
recurse into subdirecories
.TP
.B --force
downcase indeed
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
