.TH "mtx-chars" "1" "01-01-2020" "version 0.10" "MkII Character Table Generators"
.SH NAME
 mtx-chars - MkII Character Table Generators
.SH SYNOPSIS
.B mtxrun --script chars [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B MkII Character Table Generators
.SH OPTIONS
.TP
.B --xtx
generate xetx-*.tex (used by xetex)
.TP
.B --pdf
generate pdfr-def.tex (used by pdftex)
.TP
.B --entities
generate entities table
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
