.TH "mtx-colors" "1" "01-01-2020" "version 0.10" "ConTeXt Color Management"
.SH NAME
 mtx-colors - ConTeXt Color Management
.SH SYNOPSIS
.B mtxrun --script colors [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt Color Management
.SH OPTIONS
.TP
.B --table
show icc table
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
