.TH "mtx-rsync" "1" "01-01-2020" "version 0.10" "Rsync Helpers"
.SH NAME
 mtx-rsync - Rsync Helpers
.SH SYNOPSIS
.B mtxrun --script rsync [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B Rsync Helpers
.SH OPTIONS
.TP
.B --job
use given file as specification
.TP
.B --dryrun
show what would happen
.TP
.B --force
force run
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
