.TH "mtx-evohome" "1" "01-01-2020" "version 1.00" "Evohome Fetcher"
.SH NAME
 mtx-evohome - Evohome Fetcher
.SH SYNOPSIS
.B mtxrun --script evohome [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B Evohome Fetcher
.SH OPTIONS
.TP
.B --collect
collect data from device
.TP
.B --update
update data from device
.TP
.B --presets
file with authenciation data
.TP
.B --auto
fetch temperature data every hour
.TP
.B --port
server port when running the service, default: 8068
.TP
.B --host
server host when running the service, default: localhost
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
