.TH "mtx-timing" "1" "01-01-2013" "version 0.10" "ConTeXt Timing Tools" 
.PP
.SH "NAME" 
.PP
.SH "SYNOPSIS" 
.PP
.SH \fBmtxrun --script timing\fP [ \fIOPTIONS\fP ... ] [ \fIFILENAMES\fP ] 
.PP
.SH "DESCRIPTION"\nConTeXt Timing Tools\n 
.SH "OPTIONS"
.TP
.B --xhtml
make xhtml file
.TP
.B --launch
launch after conversion
.TP
.B --remove
remove after launching
.SH "AUTHOR"
More information about ConTeXt and the tools that come with it can be found at:

maillist : ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context
webpage  : http://www.pragma-ade.nl / http://tex.aanhet.net
wiki     : http://contextgarden.net
