.TH "mtx-patterns" "1" "01-01-2020" "version 0.20" "ConTeXt Pattern File Management"
.SH NAME
 mtx-patterns - ConTeXt Pattern File Management
.SH SYNOPSIS
.B mtxrun --script patterns [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt Pattern File Management
.SH OPTIONS
.TP
.B --convert
generate context language files (mnemonic driven, if not given then all)
.TP
.B --check
check pattern file (or those used by context when no file given)
.TP
.B --path
source path where hyph-foo.tex files are stored
.TP
.B --destination
destination path
.TP
.B --specification
additional patterns: e.g.: =cy,hyph-cy,welsh
.TP
.B --compress
compress data
.TP
.B --words
update words in given file
.TP
.B --hyphenate
show hypephenated words
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
