.TH "mtx-timing" "1" "01-01-2020" "version 0.10" "ConTeXt Timing Tools"
.SH NAME
 mtx-timing - ConTeXt Timing Tools
.SH SYNOPSIS
.B mtxrun --script timing [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt Timing Tools
.SH OPTIONS
.TP
.B --xhtml
make xhtml file
.TP
.B --launch
launch after conversion
.TP
.B --remove
remove after launching
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
