.TH "mtx-unzip" "1" "01-01-2020" "version 0.10" "Simple Unzipper"
.SH NAME
 mtx-unzip - Simple Unzipper
.SH SYNOPSIS
.B mtxrun --script unzip [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B Simple Unzipper
.SH OPTIONS
.TP
.B --list
list files in archive
.TP
.B --extract
extract files [--silent --steps]
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
