.TH "mtx-metapost" "1" "01-01-2020" "version 0.10" "MetaPost to PDF processor"
.SH NAME
 mtx-metapost - MetaPost to PDF processor
.SH SYNOPSIS
.B mtxrun --script metapost [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B MetaPost to PDF processor
.SH OPTIONS
.TP
.B --rawmp
raw metapost run
.TP
.B --metafun
use metafun instead of plain
.TP
.B --latex
force --tex=latex
.TP
.B --texexec
force texexec usage (mkii)
.TP
.B --split
split single result file into pages
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
