.TH "mtx-modules" "1" "01-01-2020" "version 1.00" "ConTeXt Module Documentation Generators"
.SH NAME
 mtx-modules - ConTeXt Module Documentation Generators
.SH SYNOPSIS
.B mtxrun --script modules [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt Module Documentation Generators
.SH OPTIONS
.TP
.B --convert
convert source files (tex, mkii, mkiv, mp, etc.) to 'ted' files
.TP
.B --process
process source files (tex, mkii, mkiv, mp, etc.) to 'pdf' files
.TP
.B --prep
use original name with suffix 'prep' appended
.TP
.B --direct
use old method instead of extra
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
