.TH "mtx-profile" "1" "01-01-2020" "version 1.00" "ConTeXt MkIV LuaTeX Profiler"
.SH NAME
 mtx-profile - ConTeXt MkIV LuaTeX Profiler
.SH SYNOPSIS
.B mtxrun --script profile [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B ConTeXt MkIV LuaTeX Profiler
.SH OPTIONS
.TP
.B --analyze
analyze lua calls
.TP
.B --trace
analyze tex calls
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
