.TH "mtxrun" "1" "01-01-2013" "version 1.31" "ConTeXt TDS Runner Tool" 
.SH "NAME" 
.PP
.SH "SYNOPSIS" 
.PP
.SH \fBmtxrun\fP [ \fIOPTIONS\fP ... ] [ \fIFILENAMES\fP ] 
.SH "DESCRIPTION"\nConTeXt TDS Runner Tool\n 
.SH "OPTIONS"
.TP
.B --script
run an mtx script (lua prefered method) (--noquotes), no script gives list
.TP
.B --execute
run a script or program (texmfstart method) (--noquotes)
.TP
.B --resolve
resolve prefixed arguments
.TP
.B --ctxlua
run internally (using preloaded libs)
.TP
.B --internal
run script using built in libraries (same as --ctxlua)
.TP
.B --locate
locate given filename in database (default) or system (--first --all --detail)
.TP
.B --autotree
use texmf tree cf. env texmfstart_tree or texmfstarttree
.TP
.B --tree=pathtotree
use given texmf tree (default file: setuptex.tmf)
.TP
.B --environment=name
use given (tmf) environment file
.TP
.B --path=runpath
go to given path before execution
.TP
.B --ifchanged=filename
only execute when given file has changed (md checksum)
.TP
.B --iftouched=old,new
only execute when given file has changed (time stamp)
.TP
.B --makestubs
create stubs for (context related) scripts
.TP
.B --removestubs
remove stubs (context related) scripts
.TP
.B --stubpath=binpath
paths where stubs wil be written
.TP
.B --windows
create windows (mswin) stubs
.TP
.B --unix
create unix (linux) stubs
.TP
.B --verbose
give a bit more info
.TP
.B --trackers=list
enable given trackers
.TP
.B --progname=str
format or backend
.TP
.B --edit
launch editor with found file
.TP
.B --launch
launch files like manuals, assumes os support (--all)
.TP
.B --timedrun
run a script an time its run
.TP
.B --autogenerate
regenerate databases if needed (handy when used to run context in an editor)
.TP
.B --usekpse
use kpse as fallback (when no mkiv and cache installed, often slower)
.TP
.B --forcekpse
force using kpse (handy when no mkiv and cache installed but less functionality)
.TP
.B --prefixes
show supported prefixes
.TP
.B --generate
generate file database
.TP
.B --variables
show configuration variables
.TP
.B --configurations
show configuration order
.TP
.B --directives
show (known) directives
.TP
.B --trackers
show (known) trackers
.TP
.B --experiments
show (known) experiments
.TP
.B --expand-braces
expand complex variable
.TP
.B --expand-path
expand variable (resolve paths)
.TP
.B --expand-var
expand variable (resolve references)
.TP
.B --show-path
show path expansion of ...
.TP
.B --var-value
report value of variable
.TP
.B --find-file
report file location
.TP
.B --find-path
report path of file
.TP
.B --pattern=string
filter variables
.SH "AUTHOR"
More information about ConTeXt and the tools that come with it can be found at:

maillist : ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context
webpage  : http://www.pragma-ade.nl / http://tex.aanhet.net
wiki     : http://contextgarden.net
