return {
 ["comment"]="% generated by mtxrun --script pattern --convert",
 ["exceptions"]={
  ["n"]=0,
 },
 ["metadata"]={
  ["mnemonic"]="eo",
  ["source"]="hyph-eo",
  ["texcomment"]="% \n% \\begingroup\n% \\def\\adj#1{#1a. #1aj. #1ajn. #1an. #1e.}\n% \\edef\\nom#1{\\adj{#1} #1o. #1oj. #1ojn. #1on.}\n% \\def\\ver#1{#1as. #1i. #1is. #1os. #1u. #1us.}",
 },
 ["patterns"]={
  ["characters"]="abdefgijklmnoprstuvŝ",
  ["data"]="a1 e1 i1 o1 u1 2aj. 2ajn. 2an. 2as. en. is. 2oj. 2ojn. 2on. 2os. 2us. a3a e3a i3a o3a u3a a3e e3e i3e o3e u3e a3i e3i i3i o3i u3i a3o e3o i3o o3o u3o a3u e3u i3u o3u u3u e2sper 2jn. 2lp. 2lt. 2nk. 2ns. 2nt. 2st. .bl4 .br4 .dr4 .dl4 .fl4 .fr4 .gl4 .gn4 .gr4 .kl4 .kn4 .kr4 .kv4 .pl4 .pr4 .ps4 .pt4 .sf4 .sk4 .skl4 .skr4 .skv4 .sl4 .sm4 .sn4 .sp4 .spl4 .spr4 .st4 .str4 .sv4 .ŝl4 .ŝm4 .ŝn4 .ŝp4 .ŝr4 .ŝpr4 .ŝt4 .ŝtr4 .ŝv4 .tr4 .vr4",
  ["lefthyphenmin"]=1,
  ["length"]=438,
  ["n"]=91,
  ["righthyphenmax"]=1,
 },
 ["version"]="1.001",
}