.TH "texshow" "1" "Jul 2006" "ConTeXt" "CONTEXT" 
.PP 
.SH "NAME" 
texshow \- ConTeXt command and parameter reference
.PP 
.SH "SYNOPSIS" 
\fBtexshow\fP [ \fIOPTION\fP ] [ \fICOMMAND\fP ] 
[ \fILANGUAGE\fP ]
.PP 
.SH "DESCRIPTION" 
.PP 
\fBtexshow\fP uses \fBperl\fP(1) and PerlTk (see \fBTk\fP(3pm)) to
show a overview of the commands and parameters of those\&.  In the Tk
window you can search for a command and by switching the interface,
you can see the equivalent in another interface language\&.
.PP 
\fICOMMAND\fP is a \fBConTeXt\fP command to search for in the
database\&.  Note that Plain TeX commands are not (yet) in this database
although they can be used in \fBConTeXt\fP source files\&.
.PP 
\fILANGUAGE\fP can be one of \fBcz\fP (Czech), \fBde\fP
(German), \fBen\fP (US-English) or \fBnl\fP (Dutch)\&.  The default
language is English\&.
.PP 
You can also set the interface language with the
\fB--interface\fP switch\&.
.PP 
.SH "BINDINGS" 
.PP
Most keyboard events are bound to the search widget, with the
exception of \fB<Page Up>\fP (aka \fB<Prior>\fP) and \fB<Page Down>\fP
(aka \fB<Next>\fP).  \fB<Control-q>\fP, \fB<Control-x>\fP, and
\fB<Alt-F4>\fP quit the application\&.
.PP 
.SH "OPTIONS" 
.PP 
.IP "\fB--help\fP" 
Print a brief syntax summary 
.IP "\fB--interface=\fP\fILANGUAGE\fP" 
Primary interface language\&.
See DESCRIPTION for \fILANGUAGE\fP options\&. 
.PP 
.SH "FILES" 
.PP 
.IP "\fITEXMF/tex/context/interface/cont-\fIXX\fP\&.xml\fP" 
The database
file\&.  At this writing, \fIXX\fP can be one of \fBcz\fP (Czech),
\fBde\fP (German), \fBen\fP (English), \fBfr\fP (French),  
\fBit\fP (Italian), \fBnl\fP (Dutch), or \fBro\fP (Romanian)\&. 
Which file is used is determined by the
\fILANGUAGE\fP specified on the command line\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBtexexec\fP(1), \fBpdfetex\fP(1), \fBpdftex\fP(1)\&.
.PP 
Web page: <http://www\&.pragma-ade\&.com/>
.PP 
.SH "AUTHOR" 
.PP 
This version of \fBtexshow\fP was written by Taco Hoekwater
<taco@elvenkind\&.com>\&.
.PP 
This manpage was written by Tobias Burnus
<burnus@gmx\&.de> and C\&.M\&. Connelly
<c@eskimo\&.com>\&.
.PP 
\fBtexshow\fP is part of \fBConTeXt\fP and is available
from <http://www\&.pragma-ade\&.com/pragma-ade/>\&.
.PP 
